<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class AdvertisementsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('advertisements')->delete();
        
        \DB::table('advertisements')->insert(array (
            0 => 
            array (
                'id' => 1000000,
                'store_id' => 45,
                'module_id' => 4,
                'module_type' => 'food',
                'add_type' => 'store_promotion',
                'title' => 'Big Flavors, Big Deals',
                'description' => 'Hungry Puppets has it all at 30% off. Don\'t miss out on these tasty savings!',
                'start_date' => '2024-11-17',
                'end_date' => '2025-04-30',
                'pause_note' => NULL,
                'cancellation_note' => NULL,
                'cover_image' => '2024-11-03-6726f7a108bfe.webp',
                'profile_image' => '2024-11-17-6739a54f9b438.png',
                'video_attachment' => NULL,
                'priority' => NULL,
                'is_rating_active' => 1,
                'is_review_active' => 1,
                'is_paid' => 1,
                'is_updated' => 0,
                'created_by_id' => 1,
                'created_by_type' => 'App\\Models\\Admin',
                'status' => 'approved',
                'created_at' => '2024-08-08 05:36:45',
                'updated_at' => '2024-11-17 14:11:59',
            ),
            1 => 
            array (
                'id' => 1000001,
                'store_id' => 47,
                'module_id' => 4,
                'module_type' => 'food',
                'add_type' => 'store_promotion',
                'title' => 'Tap Into Mexican Flavors',
                'description' => 'From burritos to nachos, get your favorite Mexican dishes with just one tap.',
                'start_date' => '2024-11-03',
                'end_date' => '2025-04-30',
                'pause_note' => NULL,
                'cancellation_note' => NULL,
                'cover_image' => '2024-11-03-6726fa1b5fb87.webp',
                'profile_image' => '2024-11-03-67275f5f5abd0.webp',
                'video_attachment' => NULL,
                'priority' => NULL,
                'is_rating_active' => 1,
                'is_review_active' => 1,
                'is_paid' => 1,
                'is_updated' => 0,
                'created_by_id' => 1,
                'created_by_type' => 'App\\Models\\Admin',
                'status' => 'approved',
                'created_at' => '2024-08-08 05:39:01',
                'updated_at' => '2024-11-03 17:32:47',
            ),
            2 => 
            array (
                'id' => 1000002,
                'store_id' => 48,
                'module_id' => 4,
                'module_type' => 'food',
                'add_type' => 'video_promotion',
                'title' => '50% Off Burger Feast',
                'description' => 'Satisfy your burger cravings with a massive 50% off on all combo meals today!',
                'start_date' => '2024-11-03',
                'end_date' => '2025-05-31',
                'pause_note' => NULL,
                'cancellation_note' => NULL,
                'cover_image' => NULL,
                'profile_image' => NULL,
                'video_attachment' => '2024-11-03-6726ee30c42c3.mp4',
                'priority' => NULL,
                'is_rating_active' => 0,
                'is_review_active' => 0,
                'is_paid' => 1,
                'is_updated' => 0,
                'created_by_id' => 1,
                'created_by_type' => 'App\\Models\\Admin',
                'status' => 'approved',
                'created_at' => '2024-08-08 05:40:28',
                'updated_at' => '2024-11-03 09:29:52',
            ),
            3 => 
            array (
                'id' => 1000003,
                'store_id' => 46,
                'module_id' => 4,
                'module_type' => 'food',
                'add_type' => 'video_promotion',
                'title' => 'Asian Delights for You',
                'description' => 'Order $100+ worth of Asian cuisine, to get a free delivery treat!',
                'start_date' => '2024-11-03',
                'end_date' => '2025-05-07',
                'pause_note' => NULL,
                'cancellation_note' => NULL,
                'cover_image' => NULL,
                'profile_image' => NULL,
                'video_attachment' => '2024-11-03-6726f2e829e85.mp4',
                'priority' => NULL,
                'is_rating_active' => 0,
                'is_review_active' => 0,
                'is_paid' => 1,
                'is_updated' => 0,
                'created_by_id' => 1,
                'created_by_type' => 'App\\Models\\Admin',
                'status' => 'approved',
                'created_at' => '2024-08-08 05:43:08',
                'updated_at' => '2024-11-03 09:50:00',
            ),
            4 => 
            array (
                'id' => 1000004,
                'store_id' => 1,
                'module_id' => 1,
                'module_type' => 'grocery',
                'add_type' => 'store_promotion',
                'title' => 'Get 50% Off Everything!',
                'description' => 'Dive into our biggest sale of the year! Enjoy a massive 50% off on all products storewide. Whether you\'re shopping for the latest trends or stocking up on essentials, now’s the perfect time to grab unbeatable deals. Hurry—this offer won\'t last long! Shop now and save big!',
                'start_date' => '2024-08-08',
                'end_date' => '2024-08-18',
                'pause_note' => NULL,
                'cancellation_note' => NULL,
                'cover_image' => '2024-08-08-66b45c37d4761.png',
                'profile_image' => '2024-08-08-66b45c37ddd15.png',
                'video_attachment' => NULL,
                'priority' => NULL,
                'is_rating_active' => 1,
                'is_review_active' => 1,
                'is_paid' => 1,
                'is_updated' => 0,
                'created_by_id' => 1,
                'created_by_type' => 'App\\Models\\Admin',
                'status' => 'approved',
                'created_at' => '2024-08-08 05:48:39',
                'updated_at' => '2024-08-08 05:48:40',
            ),
            5 => 
            array (
                'id' => 1000005,
                'store_id' => 1,
                'module_id' => 1,
                'module_type' => 'grocery',
                'add_type' => 'video_promotion',
                'title' => 'Half Off, Full Clean',
                'description' => 'Grab cleaning essentials at half the price and make your home shine!',
                'start_date' => '2024-10-24',
                'end_date' => '2025-03-08',
                'pause_note' => NULL,
                'cancellation_note' => NULL,
                'cover_image' => NULL,
                'profile_image' => NULL,
                'video_attachment' => '2024-10-24-6719debdeac0d.mp4',
                'priority' => NULL,
                'is_rating_active' => 0,
                'is_review_active' => 0,
                'is_paid' => 1,
                'is_updated' => 0,
                'created_by_id' => 1,
                'created_by_type' => 'App\\Models\\Admin',
                'status' => 'approved',
                'created_at' => '2024-08-08 05:50:21',
                'updated_at' => '2024-10-24 11:44:29',
            ),
            6 => 
            array (
                'id' => 1000006,
                'store_id' => 9,
                'module_id' => 1,
                'module_type' => 'grocery',
                'add_type' => 'store_promotion',
                'title' => 'Fresh Picks, Zero Fees!',
                'description' => 'Enjoy free delivery on all your favorite fruits and vegetables.',
                'start_date' => '2024-11-17',
                'end_date' => '2025-05-10',
                'pause_note' => NULL,
                'cancellation_note' => NULL,
                'cover_image' => '2024-10-24-6719d729f07f5.webp',
                'profile_image' => '2024-11-17-6739a7de85168.png',
                'video_attachment' => NULL,
                'priority' => NULL,
                'is_rating_active' => 1,
                'is_review_active' => 1,
                'is_paid' => 1,
                'is_updated' => 0,
                'created_by_id' => 1,
                'created_by_type' => 'App\\Models\\Admin',
                'status' => 'approved',
                'created_at' => '2024-08-08 05:53:11',
                'updated_at' => '2024-11-17 14:22:54',
            ),
            7 => 
            array (
                'id' => 1000007,
                'store_id' => 12,
                'module_id' => 1,
                'module_type' => 'grocery',
                'add_type' => 'store_promotion',
                'title' => 'Refresh Your Workspace',
                'description' => 'Save $50 on our best-selling air fresheners.',
                'start_date' => '2024-11-17',
                'end_date' => '2025-04-30',
                'pause_note' => NULL,
                'cancellation_note' => NULL,
                'cover_image' => '2024-10-24-6719d739bf289.webp',
                'profile_image' => '2024-11-17-6739a7637e9f8.png',
                'video_attachment' => NULL,
                'priority' => NULL,
                'is_rating_active' => 1,
                'is_review_active' => 1,
                'is_paid' => 1,
                'is_updated' => 0,
                'created_by_id' => 1,
                'created_by_type' => 'App\\Models\\Admin',
                'status' => 'approved',
                'created_at' => '2024-08-08 05:54:55',
                'updated_at' => '2024-11-17 14:20:51',
            ),
            8 => 
            array (
                'id' => 1000008,
                'store_id' => 4,
                'module_id' => 2,
                'module_type' => 'pharmacy',
                'add_type' => 'store_promotion',
                'title' => 'Premium Medicine',
                'description' => 'Discover top-quality medications delivered straight to your door at no extra charge! Our extensive selection of trusted, high-quality medicines is now available with free delivery, ensuring you get the care you need with the convenience you deserve. Order now and enjoy peace of mind knowing that your health is in good hands—delivered promptly and reliably. Your well-being, our priority!',
                'start_date' => '2024-11-17',
                'end_date' => '2025-04-05',
                'pause_note' => NULL,
                'cancellation_note' => NULL,
                'cover_image' => '2024-11-04-6728b6815f0be.webp',
                'profile_image' => '2024-11-05-6729d0a169f7d.webp',
                'video_attachment' => NULL,
                'priority' => NULL,
                'is_rating_active' => 1,
                'is_review_active' => 1,
                'is_paid' => 1,
                'is_updated' => 0,
                'created_by_id' => 1,
                'created_by_type' => 'App\\Models\\Admin',
                'status' => 'approved',
                'created_at' => '2024-08-08 05:58:12',
                'updated_at' => '2024-11-17 10:20:44',
            ),
            9 => 
            array (
                'id' => 1000009,
                'store_id' => 15,
                'module_id' => 2,
                'module_type' => 'pharmacy',
                'add_type' => 'store_promotion',
                'title' => 'Expert Medical Services: Your Health, Our Priority!',
                'description' => 'Experience top-notch medical care with our comprehensive range of services designed to meet all your health needs. From routine check-ups to specialized treatments, our team of dedicated professionals is here to provide personalized care and support. Book your appointment today and take the first step toward better health with confidence and convenience. Your wellness journey starts here!',
                'start_date' => '2024-11-17',
                'end_date' => '2025-05-10',
                'pause_note' => NULL,
                'cancellation_note' => NULL,
                'cover_image' => '2024-11-04-6728b6939ab78.webp',
                'profile_image' => '2024-11-05-6729d0b815b99.webp',
                'video_attachment' => NULL,
                'priority' => NULL,
                'is_rating_active' => 1,
                'is_review_active' => 1,
                'is_paid' => 1,
                'is_updated' => 0,
                'created_by_id' => 1,
                'created_by_type' => 'App\\Models\\Admin',
                'status' => 'approved',
                'created_at' => '2024-08-08 06:01:05',
                'updated_at' => '2024-11-17 10:17:46',
            ),
            10 => 
            array (
                'id' => 1000010,
                'store_id' => 4,
                'module_id' => 2,
                'module_type' => 'pharmacy',
                'add_type' => 'video_promotion',
                'title' => 'The Scent of Safety',
                'description' => 'Enjoy germ-free hands with a variety of fragrant hand sanitizers.',
                'start_date' => '2024-11-05',
                'end_date' => '2025-04-30',
                'pause_note' => NULL,
                'cancellation_note' => NULL,
                'cover_image' => NULL,
                'profile_image' => NULL,
                'video_attachment' => '2024-11-04-6728b83c60e36.mp4',
                'priority' => NULL,
                'is_rating_active' => 0,
                'is_review_active' => 0,
                'is_paid' => 1,
                'is_updated' => 0,
                'created_by_id' => 1,
                'created_by_type' => 'App\\Models\\Admin',
                'status' => 'approved',
                'created_at' => '2024-08-08 06:03:03',
                'updated_at' => '2024-11-05 13:59:43',
            ),
            11 => 
            array (
                'id' => 1000011,
                'store_id' => 21,
                'module_id' => 3,
                'module_type' => 'ecommerce',
                'add_type' => 'video_promotion',
                'title' => 'Bags That Define You',
                'description' => 'Exclusive 40% off on bags you’ll love.',
                'start_date' => '2024-11-17',
                'end_date' => '2025-05-07',
                'pause_note' => NULL,
                'cancellation_note' => NULL,
                'cover_image' => NULL,
                'profile_image' => NULL,
                'video_attachment' => '2024-10-28-671f6c0dbde7d.mp4',
                'priority' => NULL,
                'is_rating_active' => 0,
                'is_review_active' => 0,
                'is_paid' => 1,
                'is_updated' => 0,
                'created_by_id' => 1,
                'created_by_type' => 'App\\Models\\Admin',
                'status' => 'approved',
                'created_at' => '2024-08-08 06:09:37',
                'updated_at' => '2024-11-17 11:29:29',
            ),
            12 => 
            array (
                'id' => 1000012,
                'store_id' => 26,
                'module_id' => 3,
                'module_type' => 'ecommerce',
                'add_type' => 'store_promotion',
                'title' => 'Cook Like a Pro!',
                'description' => 'Upgrade your kitchen with our selection of top-quality appliances.',
                'start_date' => '2024-11-17',
                'end_date' => '2025-04-30',
                'pause_note' => NULL,
                'cancellation_note' => NULL,
                'cover_image' => '2024-10-28-671f6e06e8b4b.webp',
                'profile_image' => '2024-11-17-67397cf228ebc.png',
                'video_attachment' => NULL,
                'priority' => NULL,
                'is_rating_active' => 1,
                'is_review_active' => 1,
                'is_paid' => 1,
                'is_updated' => 0,
                'created_by_id' => 1,
                'created_by_type' => 'App\\Models\\Admin',
                'status' => 'approved',
                'created_at' => '2024-08-08 06:14:28',
                'updated_at' => '2024-11-17 11:19:46',
            ),
            13 => 
            array (
                'id' => 1000014,
                'store_id' => 24,
                'module_id' => 3,
                'module_type' => 'ecommerce',
                'add_type' => 'store_promotion',
                'title' => 'Save $30 On First Tick!',
                'description' => NULL,
                'start_date' => '2024-11-17',
                'end_date' => '2025-11-08',
                'pause_note' => NULL,
                'cancellation_note' => NULL,
                'cover_image' => '2024-10-29-6720a56d7c2ed.webp',
                'profile_image' => '2024-11-17-67397ca8272da.png',
                'video_attachment' => NULL,
                'priority' => NULL,
                'is_rating_active' => 1,
                'is_review_active' => 1,
                'is_paid' => 1,
                'is_updated' => 0,
                'created_by_id' => 1,
                'created_by_type' => 'App\\Models\\Admin',
                'status' => 'approved',
                'created_at' => '2024-10-29 15:05:49',
                'updated_at' => '2024-11-17 11:18:32',
            ),
            14 => 
            array (
                'id' => 1000015,
                'store_id' => 1,
                'module_id' => 8,
                'module_type' => 'service',
                'add_type' => 'store_promotion',
                'title' => 'Don’t Just Scroll, Save!',
                'description' => 'Don’t Just Scroll, Save! Don’t Just Scroll, Save!Don’t Just Scroll, Save!Don’t Just Scroll, Save!Don’t Just Scroll, Save!Don’t Just Scroll, Save!Don’t Just Scroll, Save!Don’t Just Scroll, Save!Don’t Just Scroll, Save!Don’t Just Scroll, Save!',
                'start_date' => '2025-09-09',
                'end_date' => '2025-10-31',
                'pause_note' => NULL,
                'cancellation_note' => NULL,
                'cover_image' => '2025-09-09-68bfc5a8eded5.png',
                'profile_image' => '2025-09-09-68bfc5a8f3616.png',
                'video_attachment' => NULL,
                'priority' => 3,
                'is_rating_active' => 1,
                'is_review_active' => 1,
                'is_paid' => 1,
                'is_updated' => 0,
                'created_by_id' => 1,
                'created_by_type' => 'App\\Models\\Admin',
                'status' => 'approved',
                'created_at' => '2025-09-09 12:14:01',
                'updated_at' => '2025-09-18 11:14:10',
            ),
            15 => 
            array (
                'id' => 1000016,
                'store_id' => 1,
                'module_id' => 8,
                'module_type' => 'service',
                'add_type' => 'video_promotion',
                'title' => 'Test',
                'description' => '321321321',
                'start_date' => '2025-09-18',
                'end_date' => '2025-09-28',
                'pause_note' => NULL,
                'cancellation_note' => NULL,
                'cover_image' => NULL,
                'profile_image' => NULL,
                'video_attachment' => '2025-09-18-68cb95013f595.mp4',
                'priority' => 2,
                'is_rating_active' => 0,
                'is_review_active' => 0,
                'is_paid' => 1,
                'is_updated' => 0,
                'created_by_id' => 1,
                'created_by_type' => 'App\\Models\\Admin',
                'status' => 'approved',
                'created_at' => '2025-09-18 11:13:37',
                'updated_at' => '2025-09-18 11:14:10',
            ),
            16 => 
            array (
                'id' => 1000017,
                'store_id' => 1,
                'module_id' => 8,
                'module_type' => 'service',
                'add_type' => 'video_promotion',
                'title' => 'Test',
                'description' => '321321321',
                'start_date' => '2025-09-18',
                'end_date' => '2025-09-28',
                'pause_note' => 'sergerytw',
                'cancellation_note' => NULL,
                'cover_image' => NULL,
                'profile_image' => NULL,
                'video_attachment' => '2025-09-18-68cb952264b07.mp4',
                'priority' => 1,
                'is_rating_active' => 0,
                'is_review_active' => 0,
                'is_paid' => 1,
                'is_updated' => 0,
                'created_by_id' => 1,
                'created_by_type' => 'App\\Models\\Admin',
                'status' => 'paused',
                'created_at' => '2025-09-18 11:14:10',
                'updated_at' => '2025-09-18 11:15:08',
            ),
            17 => 
            array (
                'id' => 1000018,
                'store_id' => 1,
                'module_id' => 8,
                'module_type' => 'service',
                'add_type' => 'store_promotion',
                'title' => 'Pp',
                'description' => 'Tt',
                'start_date' => '2025-09-21',
                'end_date' => '2025-10-10',
                'pause_note' => NULL,
                'cancellation_note' => NULL,
                'cover_image' => '2025-09-21-68cfc01a98d13.png',
                'profile_image' => '2025-09-21-68cfc01a9b91b.png',
                'video_attachment' => NULL,
                'priority' => NULL,
                'is_rating_active' => 1,
                'is_review_active' => 1,
                'is_paid' => 0,
                'is_updated' => 0,
                'created_by_id' => 1,
                'created_by_type' => 'Modules\\Service\\Entities\\ProviderManagement\\Provider',
                'status' => 'pending',
                'created_at' => '2025-09-21 15:06:34',
                'updated_at' => '2025-09-21 15:06:34',
            ),
            18 => 
            array (
                'id' => 1000019,
                'store_id' => 8,
                'module_id' => 8,
                'module_type' => 'service',
                'add_type' => 'store_promotion',
                'title' => '53464',
                'description' => '65756',
                'start_date' => '2025-09-24',
                'end_date' => '2025-10-04',
                'pause_note' => NULL,
                'cancellation_note' => NULL,
                'cover_image' => '2025-09-24-68d3c7c654ec4.jpeg',
                'profile_image' => '2025-09-24-68d3c7c65923e.jpeg',
                'video_attachment' => NULL,
                'priority' => NULL,
                'is_rating_active' => 1,
                'is_review_active' => 1,
                'is_paid' => 0,
                'is_updated' => 0,
                'created_by_id' => 8,
                'created_by_type' => 'Modules\\Service\\Entities\\ProviderManagement\\Provider',
                'status' => 'pending',
                'created_at' => '2025-09-24 16:28:22',
                'updated_at' => '2025-09-24 16:28:22',
            ),
            19 => 
            array (
                'id' => 1000020,
                'store_id' => 1,
                'module_id' => 8,
                'module_type' => 'service',
                'add_type' => 'store_promotion',
                'title' => 'Pp',
                'description' => 'Xx',
                'start_date' => '2025-09-25',
                'end_date' => '2025-09-30',
                'pause_note' => NULL,
                'cancellation_note' => NULL,
                'cover_image' => '2025-09-25-68d4cf200bddf.jpg',
                'profile_image' => '2025-09-25-68d4cf203078b.jpg',
                'video_attachment' => NULL,
                'priority' => NULL,
                'is_rating_active' => 1,
                'is_review_active' => 1,
                'is_paid' => 0,
                'is_updated' => 0,
                'created_by_id' => 1,
                'created_by_type' => 'Modules\\Service\\Entities\\ProviderManagement\\Provider',
                'status' => 'pending',
                'created_at' => '2025-09-25 11:12:00',
                'updated_at' => '2025-09-25 11:12:00',
            ),
            20 => 
            array (
                'id' => 1000021,
                'store_id' => 1,
                'module_id' => 8,
                'module_type' => 'service',
                'add_type' => 'store_promotion',
                'title' => 'Hxhxxu',
                'description' => 'Fuf',
                'start_date' => '2025-09-25',
                'end_date' => '2025-09-30',
                'pause_note' => NULL,
                'cancellation_note' => NULL,
                'cover_image' => '2025-09-25-68d4cf7637884.jpg',
                'profile_image' => '2025-09-25-68d4cf763ab02.jpg',
                'video_attachment' => NULL,
                'priority' => NULL,
                'is_rating_active' => 1,
                'is_review_active' => 1,
                'is_paid' => 0,
                'is_updated' => 0,
                'created_by_id' => 1,
                'created_by_type' => 'Modules\\Service\\Entities\\ProviderManagement\\Provider',
                'status' => 'pending',
                'created_at' => '2025-09-25 11:13:26',
                'updated_at' => '2025-09-25 11:13:26',
            ),
            21 => 
            array (
                'id' => 1000022,
                'store_id' => 1,
                'module_id' => 8,
                'module_type' => 'service',
                'add_type' => 'store_promotion',
                'title' => 'Uvuvugi',
                'description' => 'Uvuv',
                'start_date' => '2025-09-25',
                'end_date' => '2025-09-30',
                'pause_note' => NULL,
                'cancellation_note' => NULL,
                'cover_image' => '2025-09-25-68d4cfc0b1c41.jpg',
                'profile_image' => '2025-09-25-68d4cfc0b47f9.jpg',
                'video_attachment' => NULL,
                'priority' => NULL,
                'is_rating_active' => 1,
                'is_review_active' => 1,
                'is_paid' => 0,
                'is_updated' => 0,
                'created_by_id' => 1,
                'created_by_type' => 'Modules\\Service\\Entities\\ProviderManagement\\Provider',
                'status' => 'pending',
                'created_at' => '2025-09-25 11:14:40',
                'updated_at' => '2025-09-25 11:14:40',
            ),
            22 => 
            array (
                'id' => 1000023,
                'store_id' => 7,
                'module_id' => 8,
                'module_type' => 'service',
                'add_type' => 'store_promotion',
                'title' => '76578568',
                'description' => '68585685',
                'start_date' => '2025-09-28',
                'end_date' => '2025-10-08',
                'pause_note' => NULL,
                'cancellation_note' => NULL,
                'cover_image' => '2025-09-28-68d8be1ccfc71.jpg',
                'profile_image' => '2025-09-28-68d8be1cd2e44.jpg',
                'video_attachment' => NULL,
                'priority' => NULL,
                'is_rating_active' => 1,
                'is_review_active' => 1,
                'is_paid' => 0,
                'is_updated' => 0,
                'created_by_id' => 7,
                'created_by_type' => 'Modules\\Service\\Entities\\ProviderManagement\\Provider',
                'status' => 'pending',
                'created_at' => '2025-09-28 10:48:28',
                'updated_at' => '2025-09-28 10:48:28',
            ),
            23 => 
            array (
                'id' => 1000024,
                'store_id' => 7,
                'module_id' => 8,
                'module_type' => 'service',
                'add_type' => 'store_promotion',
                'title' => 'oipiup',
                'description' => 'Uiopuip',
                'start_date' => '2025-09-28',
                'end_date' => '2025-09-30',
                'pause_note' => NULL,
                'cancellation_note' => NULL,
                'cover_image' => '2025-09-28-68d8c337bb8ab.jpg',
                'profile_image' => '2025-09-28-68d8c337bdf25.jpg',
                'video_attachment' => NULL,
                'priority' => NULL,
                'is_rating_active' => 0,
                'is_review_active' => 1,
                'is_paid' => 0,
                'is_updated' => 0,
                'created_by_id' => 7,
                'created_by_type' => 'Modules\\Service\\Entities\\ProviderManagement\\Provider',
                'status' => 'pending',
                'created_at' => '2025-09-28 11:10:15',
                'updated_at' => '2025-09-28 11:10:15',
            ),
            24 => 
            array (
                'id' => 1000025,
                'store_id' => 1,
                'module_id' => 8,
                'module_type' => 'service',
                'add_type' => 'store_promotion',
                'title' => 'Testtttttt',
                'description' => 'Hxhcy',
                'start_date' => '2025-10-09',
                'end_date' => '2025-10-31',
                'pause_note' => NULL,
                'cancellation_note' => NULL,
                'cover_image' => '2025-10-09-68e75baf2bea3.jpg',
                'profile_image' => '2025-10-09-68e75baf2f42b.jpg',
                'video_attachment' => NULL,
                'priority' => NULL,
                'is_rating_active' => 1,
                'is_review_active' => 1,
                'is_paid' => 0,
                'is_updated' => 0,
                'created_by_id' => 1,
                'created_by_type' => 'Modules\\Service\\Entities\\ProviderManagement\\Provider',
                'status' => 'pending',
                'created_at' => '2025-10-09 12:52:31',
                'updated_at' => '2025-10-09 12:52:31',
            ),
        ));
        
        
    }
}