<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class BannersTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('banners')->delete();
        
        \DB::table('banners')->insert(array (
            0 => 
            array (
                'id' => 2,
                'title' => 'Offer Banner',
                'type' => 'store_wise',
                'time_period' => NULL,
                'start_date' => NULL,
                'end_date' => NULL,
                'total_redirection' => '0.00',
                'image' => '2024-10-24-6719c8e24d74a.png',
                'status' => 1,
                'data' => '1',
                'created_at' => '2022-03-16 16:56:57',
                'updated_at' => '2024-10-24 10:11:14',
                'zone_id' => 1,
                'module_id' => 1,
                'featured' => 1,
                'default_link' => NULL,
                'created_by' => 'admin',
            ),
            1 => 
            array (
                'id' => 7,
                'title' => 'Offer Banner',
                'type' => 'store_wise',
                'time_period' => NULL,
                'start_date' => NULL,
                'end_date' => NULL,
                'total_redirection' => '0.00',
                'image' => '2024-10-22-6717655483273.png',
                'status' => 1,
                'data' => '1',
                'created_at' => '2022-03-22 14:07:55',
                'updated_at' => '2024-10-22 14:41:56',
                'zone_id' => 1,
                'module_id' => 1,
                'featured' => 0,
                'default_link' => NULL,
                'created_by' => 'admin',
            ),
            2 => 
            array (
                'id' => 11,
                'title' => 'Offer Banner',
                'type' => 'store_wise',
                'time_period' => NULL,
                'start_date' => NULL,
                'end_date' => NULL,
                'total_redirection' => '0.00',
                'image' => '2024-10-22-671765659e629.png',
                'status' => 1,
                'data' => '1',
                'created_at' => '2022-03-23 15:30:52',
                'updated_at' => '2024-10-22 14:42:13',
                'zone_id' => 1,
                'module_id' => 1,
                'featured' => 1,
                'default_link' => NULL,
                'created_by' => 'admin',
            ),
            3 => 
            array (
                'id' => 14,
                'title' => 'Cafe Monarch',
                'type' => 'store_wise',
                'time_period' => NULL,
                'start_date' => NULL,
                'end_date' => NULL,
                'total_redirection' => '0.00',
                'image' => '2024-10-31-672369f71b702.png',
                'status' => 1,
                'data' => '45',
                'created_at' => '2023-10-19 11:27:39',
                'updated_at' => '2024-10-31 17:28:55',
                'zone_id' => 1,
                'module_id' => 4,
                'featured' => 1,
                'default_link' => NULL,
                'created_by' => 'admin',
            ),
            4 => 
            array (
                'id' => 15,
                'title' => 'Hungry Puppets',
                'type' => 'store_wise',
                'time_period' => NULL,
                'start_date' => NULL,
                'end_date' => NULL,
                'total_redirection' => '0.00',
                'image' => '2024-10-31-6723715c9a756.png',
                'status' => 1,
                'data' => '46',
                'created_at' => '2023-10-19 11:28:19',
                'updated_at' => '2024-10-31 18:00:28',
                'zone_id' => 1,
                'module_id' => 4,
                'featured' => 0,
                'default_link' => NULL,
                'created_by' => 'admin',
            ),
            5 => 
            array (
                'id' => 16,
                'title' => 'Cheesy Restaurant',
                'type' => 'store_wise',
                'time_period' => NULL,
                'start_date' => NULL,
                'end_date' => NULL,
                'total_redirection' => '0.00',
                'image' => '2024-10-31-6723719262405.png',
                'status' => 0,
                'data' => '47',
                'created_at' => '2023-10-19 11:28:52',
                'updated_at' => '2024-10-31 18:02:50',
                'zone_id' => 1,
                'module_id' => 4,
                'featured' => 0,
                'default_link' => NULL,
                'created_by' => 'admin',
            ),
            6 => 
            array (
                'id' => 17,
                'title' => 'All Your Healthcare Needs in One Place!',
                'type' => 'store_wise',
                'time_period' => NULL,
                'start_date' => NULL,
                'end_date' => NULL,
                'total_redirection' => '0.00',
                'image' => '2024-11-05-6729d4e1334aa.png',
                'status' => 1,
                'data' => '17',
                'created_at' => '2023-10-19 12:07:21',
                'updated_at' => '2024-11-05 14:18:41',
                'zone_id' => 1,
                'module_id' => 2,
                'featured' => 1,
                'default_link' => NULL,
                'created_by' => 'admin',
            ),
            7 => 
            array (
                'id' => 18,
                'title' => 'Daily Vitamins, Daily Savings!',
                'type' => 'store_wise',
                'time_period' => NULL,
                'start_date' => NULL,
                'end_date' => NULL,
                'total_redirection' => '0.00',
                'image' => '2024-11-04-6728a2f493128.png',
                'status' => 1,
                'data' => '4',
                'created_at' => '2023-10-19 12:07:53',
                'updated_at' => '2024-11-04 16:33:24',
                'zone_id' => 1,
                'module_id' => 2,
                'featured' => 0,
                'default_link' => NULL,
                'created_by' => 'admin',
            ),
            8 => 
            array (
                'id' => 19,
                'title' => 'Daily Care',
                'type' => 'store_wise',
                'time_period' => NULL,
                'start_date' => NULL,
                'end_date' => NULL,
                'total_redirection' => '0.00',
                'image' => '2023-10-19-6530c7d2ac84d.png',
                'status' => 0,
                'data' => '6',
                'created_at' => '2023-10-19 12:08:18',
                'updated_at' => '2024-11-04 16:28:19',
                'zone_id' => 1,
                'module_id' => 2,
                'featured' => 0,
                'default_link' => NULL,
                'created_by' => 'admin',
            ),
            9 => 
            array (
                'id' => 20,
                'title' => 'KR Fashion',
                'type' => 'store_wise',
                'time_period' => NULL,
                'start_date' => NULL,
                'end_date' => NULL,
                'total_redirection' => '0.00',
                'image' => '2024-10-28-671f710c0304e.png',
                'status' => 1,
                'data' => '21',
                'created_at' => '2023-10-19 12:56:48',
                'updated_at' => '2024-10-28 17:10:04',
                'zone_id' => 1,
                'module_id' => 3,
                'featured' => 1,
                'default_link' => NULL,
                'created_by' => 'admin',
            ),
            10 => 
            array (
                'id' => 21,
                'title' => 'Bicycle',
                'type' => 'store_wise',
                'time_period' => NULL,
                'start_date' => NULL,
                'end_date' => NULL,
                'total_redirection' => '0.00',
                'image' => '2024-10-28-671f5e92f022d.png',
                'status' => 1,
                'data' => '22',
                'created_at' => '2023-10-19 12:57:24',
                'updated_at' => '2024-10-28 15:51:14',
                'zone_id' => 1,
                'module_id' => 3,
                'featured' => 0,
                'default_link' => NULL,
                'created_by' => 'admin',
            ),
            11 => 
            array (
                'id' => 22,
                'title' => 'Organic market',
                'type' => 'store_wise',
                'time_period' => NULL,
                'start_date' => NULL,
                'end_date' => NULL,
                'total_redirection' => '0.00',
                'image' => '2024-10-28-671f450724492.png',
                'status' => 0,
                'data' => '26',
                'created_at' => '2023-10-19 12:58:20',
                'updated_at' => '2024-10-29 14:29:41',
                'zone_id' => 1,
                'module_id' => 3,
                'featured' => 0,
                'default_link' => NULL,
                'created_by' => 'admin',
            ),
            12 => 
            array (
                'id' => 23,
                'title' => 'Banner 1',
                'type' => 'store_wise',
                'time_period' => NULL,
                'start_date' => NULL,
                'end_date' => NULL,
                'total_redirection' => '0.00',
                'image' => '2023-10-19-6530fa57587a8.png',
                'status' => 1,
                'data' => '34',
                'created_at' => '2023-10-19 15:43:51',
                'updated_at' => '2023-10-19 15:43:51',
                'zone_id' => 1,
                'module_id' => 1,
                'featured' => 0,
                'default_link' => NULL,
                'created_by' => 'store',
            ),
            13 => 
            array (
                'id' => 24,
                'title' => 'Banner 2',
                'type' => 'store_wise',
                'time_period' => NULL,
                'start_date' => NULL,
                'end_date' => NULL,
                'total_redirection' => '0.00',
                'image' => '2023-10-19-6530fa69572fe.png',
                'status' => 1,
                'data' => '34',
                'created_at' => '2023-10-19 15:44:09',
                'updated_at' => '2023-10-19 15:44:09',
                'zone_id' => 1,
                'module_id' => 1,
                'featured' => 0,
                'default_link' => NULL,
                'created_by' => 'store',
            ),
            14 => 
            array (
                'id' => 25,
                'title' => 'Banner 1',
                'type' => 'store_wise',
                'time_period' => NULL,
                'start_date' => NULL,
                'end_date' => NULL,
                'total_redirection' => '0.00',
                'image' => '2023-10-19-6530fafc594bc.png',
                'status' => 1,
                'data' => '33',
                'created_at' => '2023-10-19 15:46:36',
                'updated_at' => '2023-10-19 15:46:36',
                'zone_id' => 1,
                'module_id' => 1,
                'featured' => 0,
                'default_link' => NULL,
                'created_by' => 'store',
            ),
            15 => 
            array (
                'id' => 26,
                'title' => 'Banner 2',
                'type' => 'store_wise',
                'time_period' => NULL,
                'start_date' => NULL,
                'end_date' => NULL,
                'total_redirection' => '0.00',
                'image' => '2023-10-19-6530fb1a165d3.png',
                'status' => 1,
                'data' => '33',
                'created_at' => '2023-10-19 15:47:06',
                'updated_at' => '2023-10-19 15:47:06',
                'zone_id' => 1,
                'module_id' => 1,
                'featured' => 0,
                'default_link' => NULL,
                'created_by' => 'store',
            ),
            16 => 
            array (
                'id' => 27,
                'title' => 'Banner 1',
                'type' => 'store_wise',
                'time_period' => NULL,
                'start_date' => NULL,
                'end_date' => NULL,
                'total_redirection' => '0.00',
                'image' => '2023-10-19-6530fb55f0168.png',
                'status' => 1,
                'data' => '1',
                'created_at' => '2023-10-19 15:48:05',
                'updated_at' => '2023-10-19 15:48:05',
                'zone_id' => 1,
                'module_id' => 1,
                'featured' => 0,
                'default_link' => NULL,
                'created_by' => 'store',
            ),
            17 => 
            array (
                'id' => 28,
                'title' => 'Banner 2',
                'type' => 'store_wise',
                'time_period' => NULL,
                'start_date' => NULL,
                'end_date' => NULL,
                'total_redirection' => '0.00',
                'image' => '2023-10-19-6530fb77505ff.png',
                'status' => 1,
                'data' => '1',
                'created_at' => '2023-10-19 15:48:39',
                'updated_at' => '2023-10-19 15:48:39',
                'zone_id' => 1,
                'module_id' => 1,
                'featured' => 0,
                'default_link' => NULL,
                'created_by' => 'store',
            ),
            18 => 
            array (
                'id' => 29,
                'title' => 'Banner 1',
                'type' => 'store_wise',
                'time_period' => NULL,
                'start_date' => NULL,
                'end_date' => NULL,
                'total_redirection' => '0.00',
                'image' => '2023-10-19-6530fbffa24c5.png',
                'status' => 1,
                'data' => '44',
                'created_at' => '2023-10-19 15:50:55',
                'updated_at' => '2023-10-19 15:50:55',
                'zone_id' => 1,
                'module_id' => 2,
                'featured' => 0,
                'default_link' => NULL,
                'created_by' => 'store',
            ),
            19 => 
            array (
                'id' => 30,
                'title' => 'Banner 2',
                'type' => 'store_wise',
                'time_period' => NULL,
                'start_date' => NULL,
                'end_date' => NULL,
                'total_redirection' => '0.00',
                'image' => '2023-10-19-6530fc0d54a82.png',
                'status' => 1,
                'data' => '44',
                'created_at' => '2023-10-19 15:51:09',
                'updated_at' => '2023-10-19 15:51:09',
                'zone_id' => 1,
                'module_id' => 2,
                'featured' => 0,
                'default_link' => NULL,
                'created_by' => 'store',
            ),
            20 => 
            array (
                'id' => 31,
                'title' => 'Banner',
                'type' => 'store_wise',
                'time_period' => NULL,
                'start_date' => NULL,
                'end_date' => NULL,
                'total_redirection' => '0.00',
                'image' => '2023-10-19-6530fc363ad89.png',
                'status' => 1,
                'data' => '2',
                'created_at' => '2023-10-19 15:51:50',
                'updated_at' => '2023-10-19 15:51:50',
                'zone_id' => 1,
                'module_id' => 2,
                'featured' => 0,
                'default_link' => NULL,
                'created_by' => 'store',
            ),
            21 => 
            array (
                'id' => 32,
                'title' => 'Banner 2',
                'type' => 'store_wise',
                'time_period' => NULL,
                'start_date' => NULL,
                'end_date' => NULL,
                'total_redirection' => '0.00',
                'image' => '2023-10-19-6530fc44c9d0d.png',
                'status' => 1,
                'data' => '2',
                'created_at' => '2023-10-19 15:52:04',
                'updated_at' => '2023-10-19 15:52:04',
                'zone_id' => 1,
                'module_id' => 2,
                'featured' => 0,
                'default_link' => NULL,
                'created_by' => 'store',
            ),
            22 => 
            array (
                'id' => 34,
                'title' => 'vvv',
                'type' => 'store_wise',
                'time_period' => NULL,
                'start_date' => NULL,
                'end_date' => NULL,
                'total_redirection' => '0.00',
                'image' => '2023-10-19-6530fc8004fcf.png',
                'status' => 1,
                'data' => '4',
                'created_at' => '2023-10-19 15:53:04',
                'updated_at' => '2023-10-19 15:53:04',
                'zone_id' => 1,
                'module_id' => 2,
                'featured' => 0,
                'default_link' => NULL,
                'created_by' => 'store',
            ),
            23 => 
            array (
                'id' => 35,
                'title' => 'VVVfff',
                'type' => 'store_wise',
                'time_period' => NULL,
                'start_date' => NULL,
                'end_date' => NULL,
                'total_redirection' => '0.00',
                'image' => '2023-10-19-6530fc8e4f53b.png',
                'status' => 1,
                'data' => '4',
                'created_at' => '2023-10-19 15:53:18',
                'updated_at' => '2023-10-19 15:53:18',
                'zone_id' => 1,
                'module_id' => 2,
                'featured' => 0,
                'default_link' => NULL,
                'created_by' => 'store',
            ),
            24 => 
            array (
                'id' => 36,
                'title' => 'Banner1',
                'type' => 'store_wise',
                'time_period' => NULL,
                'start_date' => NULL,
                'end_date' => NULL,
                'total_redirection' => '0.00',
                'image' => '2023-10-19-6530fd3305686.png',
                'status' => 1,
                'data' => '37',
                'created_at' => '2023-10-19 15:56:03',
                'updated_at' => '2023-10-19 15:56:03',
                'zone_id' => 2,
                'module_id' => 3,
                'featured' => 0,
                'default_link' => NULL,
                'created_by' => 'store',
            ),
            25 => 
            array (
                'id' => 37,
                'title' => 'Banner 2',
                'type' => 'store_wise',
                'time_period' => NULL,
                'start_date' => NULL,
                'end_date' => NULL,
                'total_redirection' => '0.00',
                'image' => '2023-10-19-6530fd3f0e004.png',
                'status' => 1,
                'data' => '37',
                'created_at' => '2023-10-19 15:56:15',
                'updated_at' => '2023-10-19 15:56:15',
                'zone_id' => 2,
                'module_id' => 3,
                'featured' => 0,
                'default_link' => NULL,
                'created_by' => 'store',
            ),
            26 => 
            array (
                'id' => 38,
                'title' => 'AAA',
                'type' => 'store_wise',
                'time_period' => NULL,
                'start_date' => NULL,
                'end_date' => NULL,
                'total_redirection' => '0.00',
                'image' => '2023-10-19-6530fd769ee1b.png',
                'status' => 1,
                'data' => '26',
                'created_at' => '2023-10-19 15:57:10',
                'updated_at' => '2023-10-19 15:57:10',
                'zone_id' => 1,
                'module_id' => 3,
                'featured' => 0,
                'default_link' => NULL,
                'created_by' => 'store',
            ),
            27 => 
            array (
                'id' => 39,
                'title' => 'DD',
                'type' => 'store_wise',
                'time_period' => NULL,
                'start_date' => NULL,
                'end_date' => NULL,
                'total_redirection' => '0.00',
                'image' => '2023-10-19-6530fd819674f.png',
                'status' => 1,
                'data' => '26',
                'created_at' => '2023-10-19 15:57:21',
                'updated_at' => '2023-10-19 15:57:21',
                'zone_id' => 1,
                'module_id' => 3,
                'featured' => 0,
                'default_link' => NULL,
                'created_by' => 'store',
            ),
            28 => 
            array (
                'id' => 40,
                'title' => 'AAA',
                'type' => 'store_wise',
                'time_period' => NULL,
                'start_date' => NULL,
                'end_date' => NULL,
                'total_redirection' => '0.00',
                'image' => '2023-10-19-6530fdc479945.png',
                'status' => 1,
                'data' => '21',
                'created_at' => '2023-10-19 15:58:28',
                'updated_at' => '2023-10-19 15:58:28',
                'zone_id' => 1,
                'module_id' => 3,
                'featured' => 0,
                'default_link' => NULL,
                'created_by' => 'store',
            ),
            29 => 
            array (
                'id' => 41,
                'title' => 'CCCC',
                'type' => 'store_wise',
                'time_period' => NULL,
                'start_date' => NULL,
                'end_date' => NULL,
                'total_redirection' => '0.00',
                'image' => '2023-10-19-6530fdd47f22d.png',
                'status' => 1,
                'data' => '21',
                'created_at' => '2023-10-19 15:58:44',
                'updated_at' => '2023-10-19 15:58:44',
                'zone_id' => 1,
                'module_id' => 3,
                'featured' => 0,
                'default_link' => NULL,
                'created_by' => 'store',
            ),
            30 => 
            array (
                'id' => 42,
                'title' => 'Bann',
                'type' => 'store_wise',
                'time_period' => NULL,
                'start_date' => NULL,
                'end_date' => NULL,
                'total_redirection' => '0.00',
                'image' => '2023-10-19-6530fe1ecdb9d.png',
                'status' => 1,
                'data' => '46',
                'created_at' => '2023-10-19 15:59:58',
                'updated_at' => '2023-10-19 15:59:58',
                'zone_id' => 1,
                'module_id' => 4,
                'featured' => 0,
                'default_link' => NULL,
                'created_by' => 'store',
            ),
            31 => 
            array (
                'id' => 43,
                'title' => 'Baddddd',
                'type' => 'store_wise',
                'time_period' => NULL,
                'start_date' => NULL,
                'end_date' => NULL,
                'total_redirection' => '0.00',
                'image' => '2023-10-19-6530fe2bc50bb.png',
                'status' => 1,
                'data' => '46',
                'created_at' => '2023-10-19 16:00:11',
                'updated_at' => '2023-10-19 16:00:11',
                'zone_id' => 1,
                'module_id' => 4,
                'featured' => 0,
                'default_link' => NULL,
                'created_by' => 'store',
            ),
            32 => 
            array (
                'id' => 44,
                'title' => 'Offer Banner',
                'type' => 'default',
                'time_period' => NULL,
                'start_date' => NULL,
                'end_date' => NULL,
                'total_redirection' => '0.00',
                'image' => '2024-10-22-6717658a6cad9.png',
                'status' => 1,
                'data' => '',
                'created_at' => '2024-10-22 14:42:50',
                'updated_at' => '2024-10-22 14:42:50',
                'zone_id' => 1,
                'module_id' => 1,
                'featured' => 0,
                'default_link' => NULL,
                'created_by' => 'admin',
            ),
            33 => 
            array (
                'id' => 46,
                'title' => 'New Car Rent for today',
                'type' => 'store_wise',
                'time_period' => NULL,
                'start_date' => NULL,
                'end_date' => NULL,
                'total_redirection' => '0.00',
                'image' => '2025-02-05-67a3431e76e6a.png',
                'status' => 1,
                'data' => '60',
                'created_at' => '2025-02-05 16:21:19',
                'updated_at' => '2025-02-05 16:53:18',
                'zone_id' => 1,
                'module_id' => 6,
                'featured' => 1,
                'default_link' => NULL,
                'created_by' => 'admin',
            ),
            34 => 
            array (
                'id' => 47,
                'title' => 'Rent your dream car',
                'type' => 'default',
                'time_period' => NULL,
                'start_date' => NULL,
                'end_date' => NULL,
                'total_redirection' => '0.00',
                'image' => '2025-02-08-67a6ccaa19cdc.png',
                'status' => 1,
                'data' => '',
                'created_at' => '2025-02-05 16:24:24',
                'updated_at' => '2025-02-08 09:16:58',
                'zone_id' => 1,
                'module_id' => 6,
                'featured' => 0,
                'default_link' => 'https://codecanyon.net/item/6ammart-multivendor-food-grocery-ecommerce-parcel-pharmacy-delivery-app-with-admin-website/36772112?s_rank=16',
                'created_by' => 'admin',
            ),
            35 => 
            array (
                'id' => 48,
                'title' => 'Get the best car',
                'type' => 'default',
                'time_period' => NULL,
                'start_date' => NULL,
                'end_date' => NULL,
                'total_redirection' => '0.00',
                'image' => '2025-02-08-67a6ccb81b00e.png',
                'status' => 1,
                'data' => '',
                'created_at' => '2025-02-05 16:25:53',
                'updated_at' => '2025-02-08 09:17:12',
                'zone_id' => 1,
                'module_id' => 6,
                'featured' => 1,
                'default_link' => 'https://codecanyon.net/item/6ammart-multivendor-food-grocery-ecommerce-parcel-pharmacy-delivery-app-with-admin-website/36772112?s_rank=16',
                'created_by' => 'admin',
            ),
            36 => 
            array (
                'id' => 49,
                'title' => 'Luxury Car for rent',
                'type' => 'store_wise',
                'time_period' => NULL,
                'start_date' => NULL,
                'end_date' => NULL,
                'total_redirection' => '0.00',
                'image' => '2025-02-08-67a6ccc9968d5.png',
                'status' => 1,
                'data' => '60',
                'created_at' => '2025-02-05 16:26:16',
                'updated_at' => '2025-02-08 09:17:29',
                'zone_id' => 1,
                'module_id' => 6,
                'featured' => 0,
                'default_link' => 'https://codecanyon.net/item/6ammart-multivendor-food-grocery-ecommerce-parcel-pharmacy-delivery-app-with-admin-website/36772112?s_rank=16',
                'created_by' => 'admin',
            ),
            37 => 
            array (
                'id' => 50,
                'title' => 'Repair Service',
                'type' => 'category',
                'time_period' => NULL,
                'start_date' => NULL,
                'end_date' => NULL,
                'total_redirection' => '0.00',
                'image' => '2025-09-09-68bfc30ecb8f3.png',
                'status' => 1,
                'data' => '1',
                'created_at' => '2025-09-09 11:33:07',
                'updated_at' => '2025-09-09 12:02:54',
                'zone_id' => 1,
                'module_id' => 8,
                'featured' => 0,
                'default_link' => NULL,
                'created_by' => 'admin',
            ),
            38 => 
            array (
                'id' => 51,
                'title' => 'Fan service',
                'type' => 'category',
                'time_period' => NULL,
                'start_date' => NULL,
                'end_date' => NULL,
                'total_redirection' => '0.00',
                'image' => '2025-09-09-68bfbc4930809.png',
                'status' => 1,
                'data' => '3',
                'created_at' => '2025-09-09 11:34:01',
                'updated_at' => '2025-09-09 11:34:01',
                'zone_id' => 1,
                'module_id' => 8,
                'featured' => 0,
                'default_link' => NULL,
                'created_by' => 'admin',
            ),
            39 => 
            array (
                'id' => 52,
                'title' => 'Plumbing Repair Services Offer',
                'type' => 'category',
                'time_period' => NULL,
                'start_date' => NULL,
                'end_date' => NULL,
                'total_redirection' => '0.00',
                'image' => '2025-09-09-68bfc3c69542f.png',
                'status' => 1,
                'data' => '3',
                'created_at' => '2025-09-09 11:34:16',
                'updated_at' => '2025-09-09 12:05:58',
                'zone_id' => 1,
                'module_id' => 8,
                'featured' => 0,
                'default_link' => NULL,
                'created_by' => 'admin',
            ),
            40 => 
            array (
                'id' => 53,
                'title' => 'Cleanning',
                'type' => 'service',
                'time_period' => NULL,
                'start_date' => NULL,
                'end_date' => NULL,
                'total_redirection' => '0.00',
                'image' => '2025-09-09-68bfbca6a2f15.png',
                'status' => 1,
                'data' => '4',
                'created_at' => '2025-09-09 11:35:34',
                'updated_at' => '2025-09-09 11:35:34',
                'zone_id' => 1,
                'module_id' => 8,
                'featured' => 0,
                'default_link' => NULL,
                'created_by' => 'admin',
            ),
            41 => 
            array (
                'id' => 55,
                'title' => 'AC Service',
                'type' => 'category',
                'time_period' => NULL,
                'start_date' => NULL,
                'end_date' => NULL,
                'total_redirection' => '0.00',
                'image' => '2025-09-10-68c158281fbfc.png',
                'status' => 1,
                'data' => '1',
                'created_at' => '2025-09-10 16:51:20',
                'updated_at' => '2025-09-10 16:51:20',
                'zone_id' => 1,
                'module_id' => 8,
                'featured' => 0,
                'default_link' => NULL,
                'created_by' => 'admin',
            ),
            42 => 
            array (
                'id' => 56,
                'title' => 'Test  service banner',
                'type' => 'service',
                'time_period' => NULL,
                'start_date' => NULL,
                'end_date' => NULL,
                'total_redirection' => '0.00',
                'image' => '2025-09-16-68c9356ac081f.png',
                'status' => 1,
                'data' => '5',
                'created_at' => '2025-09-16 16:01:14',
                'updated_at' => '2025-09-16 16:01:28',
                'zone_id' => 1,
                'module_id' => 8,
                'featured' => 0,
                'default_link' => NULL,
                'created_by' => 'admin',
            ),
            43 => 
            array (
                'id' => 57,
                'title' => 'Car service',
                'type' => 'default',
                'time_period' => 'period',
                'start_date' => '2025-09-16 00:00:00',
                'end_date' => '2026-08-08 00:00:00',
                'total_redirection' => '5.00',
                'image' => '2025-09-16-68c946340dd51.png',
                'status' => 1,
                'data' => '',
                'created_at' => '2025-09-16 17:12:52',
                'updated_at' => '2025-10-12 09:49:21',
                'zone_id' => NULL,
                'module_id' => 7,
                'featured' => 0,
                'default_link' => 'https://6amtech.com',
                'created_by' => 'admin',
            ),
            44 => 
            array (
                'id' => 58,
                'title' => 'banner 1',
                'type' => 'redirect_link',
                'time_period' => NULL,
                'start_date' => NULL,
                'end_date' => NULL,
                'total_redirection' => '0.00',
                'image' => '2025-09-17-68ca5f558a72a.png',
                'status' => 1,
                'data' => '0',
                'created_at' => '2025-09-17 13:12:21',
                'updated_at' => '2025-09-17 13:12:21',
                'zone_id' => 1,
                'module_id' => 8,
                'featured' => 0,
                'default_link' => 'https://6amtech.com',
                'created_by' => 'admin',
            ),
            45 => 
            array (
                'id' => 59,
                'title' => 'ergyteryhtr',
                'type' => 'category',
                'time_period' => NULL,
                'start_date' => NULL,
                'end_date' => NULL,
                'total_redirection' => '0.00',
                'image' => '2025-10-06-68e39198329e7.png',
                'status' => 1,
                'data' => '13',
                'created_at' => '2025-10-06 15:53:28',
                'updated_at' => '2025-10-06 15:53:28',
                'zone_id' => 1,
                'module_id' => 8,
                'featured' => 0,
                'default_link' => NULL,
                'created_by' => 'admin',
            ),
        ));
        
        
    }
}