<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class CashBackHistoriesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('cash_back_histories')->delete();
        
        \DB::table('cash_back_histories')->insert(array (
            0 => 
            array (
                'id' => 1,
                'cash_back_id' => 4,
                'order_id' => NULL,
                'user_id' => 26,
                'cashback_type' => 'percentage',
                'calculated_amount' => 386.93,
                'cashback_amount' => 10.0,
                'min_purchase' => 100.0,
                'max_discount' => 1000.0,
                'created_at' => '2025-02-06 15:10:03',
                'updated_at' => '2025-02-06 15:10:03',
                'trip_id' => 100000,
            ),
            1 => 
            array (
                'id' => 2,
                'cash_back_id' => 4,
                'order_id' => NULL,
                'user_id' => 26,
                'cashback_type' => 'percentage',
                'calculated_amount' => 886.73,
                'cashback_amount' => 10.0,
                'min_purchase' => 100.0,
                'max_discount' => 1000.0,
                'created_at' => '2025-02-06 15:14:10',
                'updated_at' => '2025-02-06 15:14:10',
                'trip_id' => 100001,
            ),
            2 => 
            array (
                'id' => 3,
                'cash_back_id' => 6,
                'order_id' => NULL,
                'user_id' => 26,
                'cashback_type' => 'amount',
                'calculated_amount' => 100.0,
                'cashback_amount' => 100.0,
                'min_purchase' => 200.0,
                'max_discount' => 0.0,
                'created_at' => '2025-02-06 16:18:00',
                'updated_at' => '2025-02-06 16:18:00',
                'trip_id' => 100003,
            ),
            3 => 
            array (
                'id' => 4,
                'cash_back_id' => 4,
                'order_id' => NULL,
                'user_id' => 26,
                'cashback_type' => 'percentage',
                'calculated_amount' => 1000.0,
                'cashback_amount' => 10.0,
                'min_purchase' => 100.0,
                'max_discount' => 1000.0,
                'created_at' => '2025-02-06 16:22:37',
                'updated_at' => '2025-02-06 16:22:37',
                'trip_id' => 100005,
            ),
            4 => 
            array (
                'id' => 5,
                'cash_back_id' => 4,
                'order_id' => NULL,
                'user_id' => 26,
                'cashback_type' => 'percentage',
                'calculated_amount' => 529.0,
                'cashback_amount' => 10.0,
                'min_purchase' => 100.0,
                'max_discount' => 1000.0,
                'created_at' => '2025-02-06 16:23:27',
                'updated_at' => '2025-02-06 16:23:27',
                'trip_id' => 100006,
            ),
            5 => 
            array (
                'id' => 6,
                'cash_back_id' => 4,
                'order_id' => NULL,
                'user_id' => 26,
                'cashback_type' => 'percentage',
                'calculated_amount' => 577.46,
                'cashback_amount' => 10.0,
                'min_purchase' => 100.0,
                'max_discount' => 1000.0,
                'created_at' => '2025-02-06 16:24:15',
                'updated_at' => '2025-02-06 16:24:15',
                'trip_id' => 100007,
            ),
            6 => 
            array (
                'id' => 7,
                'cash_back_id' => 4,
                'order_id' => NULL,
                'user_id' => 26,
                'cashback_type' => 'percentage',
                'calculated_amount' => 737.9,
                'cashback_amount' => 10.0,
                'min_purchase' => 100.0,
                'max_discount' => 1000.0,
                'created_at' => '2025-02-06 16:24:48',
                'updated_at' => '2025-02-06 16:24:48',
                'trip_id' => 100008,
            ),
            7 => 
            array (
                'id' => 8,
                'cash_back_id' => 4,
                'order_id' => NULL,
                'user_id' => 26,
                'cashback_type' => 'percentage',
                'calculated_amount' => 1000.0,
                'cashback_amount' => 10.0,
                'min_purchase' => 100.0,
                'max_discount' => 1000.0,
                'created_at' => '2025-02-06 16:26:26',
                'updated_at' => '2025-02-06 16:26:26',
                'trip_id' => 100010,
            ),
            8 => 
            array (
                'id' => 9,
                'cash_back_id' => 4,
                'order_id' => NULL,
                'user_id' => 26,
                'cashback_type' => 'percentage',
                'calculated_amount' => 368.77,
                'cashback_amount' => 10.0,
                'min_purchase' => 100.0,
                'max_discount' => 1000.0,
                'created_at' => '2025-02-06 16:27:02',
                'updated_at' => '2025-02-06 16:27:02',
                'trip_id' => 100011,
            ),
            9 => 
            array (
                'id' => 10,
                'cash_back_id' => 4,
                'order_id' => NULL,
                'user_id' => 26,
                'cashback_type' => 'percentage',
                'calculated_amount' => 370.78,
                'cashback_amount' => 10.0,
                'min_purchase' => 100.0,
                'max_discount' => 1000.0,
                'created_at' => '2025-02-06 16:27:38',
                'updated_at' => '2025-02-06 16:27:38',
                'trip_id' => 100012,
            ),
            10 => 
            array (
                'id' => 11,
                'cash_back_id' => 4,
                'order_id' => NULL,
                'user_id' => 26,
                'cashback_type' => 'percentage',
                'calculated_amount' => 1000.0,
                'cashback_amount' => 10.0,
                'min_purchase' => 100.0,
                'max_discount' => 1000.0,
                'created_at' => '2025-02-06 16:28:31',
                'updated_at' => '2025-02-06 16:28:31',
                'trip_id' => 100013,
            ),
            11 => 
            array (
                'id' => 12,
                'cash_back_id' => 3,
                'order_id' => NULL,
                'user_id' => 26,
                'cashback_type' => 'amount',
                'calculated_amount' => 20.0,
                'cashback_amount' => 20.0,
                'min_purchase' => 100.0,
                'max_discount' => 0.0,
                'created_at' => '2025-02-06 16:29:45',
                'updated_at' => '2025-02-06 16:29:45',
                'trip_id' => 100014,
            ),
            12 => 
            array (
                'id' => 13,
                'cash_back_id' => 3,
                'order_id' => NULL,
                'user_id' => 26,
                'cashback_type' => 'amount',
                'calculated_amount' => 20.0,
                'cashback_amount' => 20.0,
                'min_purchase' => 100.0,
                'max_discount' => 0.0,
                'created_at' => '2025-02-06 16:31:33',
                'updated_at' => '2025-02-06 16:31:33',
                'trip_id' => 100015,
            ),
            13 => 
            array (
                'id' => 14,
                'cash_back_id' => 3,
                'order_id' => NULL,
                'user_id' => 26,
                'cashback_type' => 'amount',
                'calculated_amount' => 20.0,
                'cashback_amount' => 20.0,
                'min_purchase' => 100.0,
                'max_discount' => 0.0,
                'created_at' => '2025-02-06 16:35:33',
                'updated_at' => '2025-02-06 16:35:33',
                'trip_id' => 100018,
            ),
            14 => 
            array (
                'id' => 15,
                'cash_back_id' => 3,
                'order_id' => NULL,
                'user_id' => 26,
                'cashback_type' => 'amount',
                'calculated_amount' => 20.0,
                'cashback_amount' => 20.0,
                'min_purchase' => 100.0,
                'max_discount' => 0.0,
                'created_at' => '2025-02-06 16:37:13',
                'updated_at' => '2025-02-06 16:37:13',
                'trip_id' => 100019,
            ),
            15 => 
            array (
                'id' => 16,
                'cash_back_id' => 3,
                'order_id' => NULL,
                'user_id' => 26,
                'cashback_type' => 'amount',
                'calculated_amount' => 20.0,
                'cashback_amount' => 20.0,
                'min_purchase' => 100.0,
                'max_discount' => 0.0,
                'created_at' => '2025-02-06 16:38:00',
                'updated_at' => '2025-02-06 16:38:00',
                'trip_id' => 100020,
            ),
            16 => 
            array (
                'id' => 17,
                'cash_back_id' => 5,
                'order_id' => NULL,
                'user_id' => 26,
                'cashback_type' => 'amount',
                'calculated_amount' => 15.0,
                'cashback_amount' => 15.0,
                'min_purchase' => 100.0,
                'max_discount' => 0.0,
                'created_at' => '2025-02-06 16:39:09',
                'updated_at' => '2025-02-06 16:39:09',
                'trip_id' => 100021,
            ),
            17 => 
            array (
                'id' => 18,
                'cash_back_id' => 7,
                'order_id' => NULL,
                'user_id' => 26,
                'cashback_type' => 'amount',
                'calculated_amount' => 10.0,
                'cashback_amount' => 10.0,
                'min_purchase' => 100.0,
                'max_discount' => 0.0,
                'created_at' => '2025-02-06 16:49:25',
                'updated_at' => '2025-02-06 16:49:25',
                'trip_id' => 100022,
            ),
            18 => 
            array (
                'id' => 19,
                'cash_back_id' => 7,
                'order_id' => NULL,
                'user_id' => 26,
                'cashback_type' => 'amount',
                'calculated_amount' => 10.0,
                'cashback_amount' => 10.0,
                'min_purchase' => 100.0,
                'max_discount' => 0.0,
                'created_at' => '2025-02-06 16:50:47',
                'updated_at' => '2025-02-06 16:50:47',
                'trip_id' => 100023,
            ),
            19 => 
            array (
                'id' => 20,
                'cash_back_id' => 7,
                'order_id' => NULL,
                'user_id' => 26,
                'cashback_type' => 'amount',
                'calculated_amount' => 10.0,
                'cashback_amount' => 10.0,
                'min_purchase' => 100.0,
                'max_discount' => 0.0,
                'created_at' => '2025-02-06 16:52:34',
                'updated_at' => '2025-02-06 16:52:34',
                'trip_id' => 100024,
            ),
            20 => 
            array (
                'id' => 21,
                'cash_back_id' => 7,
                'order_id' => NULL,
                'user_id' => 26,
                'cashback_type' => 'amount',
                'calculated_amount' => 10.0,
                'cashback_amount' => 10.0,
                'min_purchase' => 100.0,
                'max_discount' => 0.0,
                'created_at' => '2025-02-06 17:01:47',
                'updated_at' => '2025-02-06 17:01:47',
                'trip_id' => 100025,
            ),
            21 => 
            array (
                'id' => 22,
                'cash_back_id' => 7,
                'order_id' => NULL,
                'user_id' => 26,
                'cashback_type' => 'amount',
                'calculated_amount' => 10.0,
                'cashback_amount' => 10.0,
                'min_purchase' => 100.0,
                'max_discount' => 0.0,
                'created_at' => '2025-02-06 17:05:38',
                'updated_at' => '2025-02-06 17:05:38',
                'trip_id' => 100026,
            ),
            22 => 
            array (
                'id' => 23,
                'cash_back_id' => 4,
                'order_id' => NULL,
                'user_id' => 28,
                'cashback_type' => 'percentage',
                'calculated_amount' => 305.86,
                'cashback_amount' => 10.0,
                'min_purchase' => 100.0,
                'max_discount' => 1000.0,
                'created_at' => '2025-02-06 17:18:05',
                'updated_at' => '2025-02-06 17:18:05',
                'trip_id' => 100030,
            ),
            23 => 
            array (
                'id' => 24,
                'cash_back_id' => 3,
                'order_id' => NULL,
                'user_id' => 28,
                'cashback_type' => 'amount',
                'calculated_amount' => 20.0,
                'cashback_amount' => 20.0,
                'min_purchase' => 100.0,
                'max_discount' => 0.0,
                'created_at' => '2025-02-06 17:22:15',
                'updated_at' => '2025-02-06 17:22:15',
                'trip_id' => 100031,
            ),
            24 => 
            array (
                'id' => 25,
                'cash_back_id' => 4,
                'order_id' => NULL,
                'user_id' => 21,
                'cashback_type' => 'percentage',
                'calculated_amount' => 788.0,
                'cashback_amount' => 10.0,
                'min_purchase' => 100.0,
                'max_discount' => 1000.0,
                'created_at' => '2025-02-06 17:26:06',
                'updated_at' => '2025-02-06 17:26:06',
                'trip_id' => 100032,
            ),
            25 => 
            array (
                'id' => 26,
                'cash_back_id' => 3,
                'order_id' => NULL,
                'user_id' => 21,
                'cashback_type' => 'amount',
                'calculated_amount' => 20.0,
                'cashback_amount' => 20.0,
                'min_purchase' => 100.0,
                'max_discount' => 0.0,
                'created_at' => '2025-02-06 17:43:43',
                'updated_at' => '2025-02-06 17:43:43',
                'trip_id' => 100033,
            ),
            26 => 
            array (
                'id' => 27,
                'cash_back_id' => 4,
                'order_id' => NULL,
                'user_id' => 21,
                'cashback_type' => 'percentage',
                'calculated_amount' => 364.67,
                'cashback_amount' => 10.0,
                'min_purchase' => 100.0,
                'max_discount' => 1000.0,
                'created_at' => '2025-02-06 17:53:56',
                'updated_at' => '2025-02-06 17:53:56',
                'trip_id' => 100034,
            ),
            27 => 
            array (
                'id' => 28,
                'cash_back_id' => 6,
                'order_id' => NULL,
                'user_id' => 8,
                'cashback_type' => 'amount',
                'calculated_amount' => 100.0,
                'cashback_amount' => 100.0,
                'min_purchase' => 200.0,
                'max_discount' => 0.0,
                'created_at' => '2025-02-08 12:48:15',
                'updated_at' => '2025-02-08 12:48:15',
                'trip_id' => 100037,
            ),
            28 => 
            array (
                'id' => 29,
                'cash_back_id' => 4,
                'order_id' => NULL,
                'user_id' => 28,
                'cashback_type' => 'percentage',
                'calculated_amount' => 249.0,
                'cashback_amount' => 10.0,
                'min_purchase' => 100.0,
                'max_discount' => 1000.0,
                'created_at' => '2025-02-08 13:06:59',
                'updated_at' => '2025-02-08 13:06:59',
                'trip_id' => 100040,
            ),
            29 => 
            array (
                'id' => 30,
                'cash_back_id' => 4,
                'order_id' => NULL,
                'user_id' => 28,
                'cashback_type' => 'percentage',
                'calculated_amount' => 886.51,
                'cashback_amount' => 10.0,
                'min_purchase' => 100.0,
                'max_discount' => 1000.0,
                'created_at' => '2025-02-08 13:09:18',
                'updated_at' => '2025-02-08 13:09:18',
                'trip_id' => 100041,
            ),
            30 => 
            array (
                'id' => 31,
                'cash_back_id' => 1,
                'order_id' => 100102,
                'user_id' => 8,
                'cashback_type' => 'percentage',
                'calculated_amount' => 55.05,
                'cashback_amount' => 10.0,
                'min_purchase' => 500.0,
                'max_discount' => 100.0,
                'created_at' => '2025-04-20 18:13:58',
                'updated_at' => '2025-04-20 18:13:58',
                'trip_id' => NULL,
            ),
            31 => 
            array (
                'id' => 32,
                'cash_back_id' => 1,
                'order_id' => 100103,
                'user_id' => 8,
                'cashback_type' => 'percentage',
                'calculated_amount' => 80.5,
                'cashback_amount' => 10.0,
                'min_purchase' => 500.0,
                'max_discount' => 100.0,
                'created_at' => '2025-04-20 18:14:55',
                'updated_at' => '2025-04-20 18:14:55',
                'trip_id' => NULL,
            ),
            32 => 
            array (
                'id' => 33,
                'cash_back_id' => 4,
                'order_id' => 100104,
                'user_id' => 8,
                'cashback_type' => 'percentage',
                'calculated_amount' => 67.83,
                'cashback_amount' => 10.0,
                'min_purchase' => 100.0,
                'max_discount' => 1000.0,
                'created_at' => '2025-04-20 18:15:58',
                'updated_at' => '2025-04-20 18:15:58',
                'trip_id' => NULL,
            ),
            33 => 
            array (
                'id' => 34,
                'cash_back_id' => 4,
                'order_id' => 100105,
                'user_id' => 8,
                'cashback_type' => 'percentage',
                'calculated_amount' => 96.25,
                'cashback_amount' => 10.0,
                'min_purchase' => 100.0,
                'max_discount' => 1000.0,
                'created_at' => '2025-04-20 18:18:10',
                'updated_at' => '2025-04-20 18:18:10',
                'trip_id' => NULL,
            ),
            34 => 
            array (
                'id' => 35,
                'cash_back_id' => 4,
                'order_id' => 100106,
                'user_id' => 8,
                'cashback_type' => 'percentage',
                'calculated_amount' => 121.88,
                'cashback_amount' => 10.0,
                'min_purchase' => 100.0,
                'max_discount' => 1000.0,
                'created_at' => '2025-04-20 18:18:58',
                'updated_at' => '2025-04-20 18:18:58',
                'trip_id' => NULL,
            ),
            35 => 
            array (
                'id' => 36,
                'cash_back_id' => 6,
                'order_id' => 100107,
                'user_id' => 30,
                'cashback_type' => 'amount',
                'calculated_amount' => 100.0,
                'cashback_amount' => 100.0,
                'min_purchase' => 200.0,
                'max_discount' => 0.0,
                'created_at' => '2025-09-09 14:26:32',
                'updated_at' => '2025-09-09 14:26:32',
                'trip_id' => NULL,
            ),
            36 => 
            array (
                'id' => 37,
                'cash_back_id' => 2,
                'order_id' => 100108,
                'user_id' => 8,
                'cashback_type' => 'amount',
                'calculated_amount' => 20.0,
                'cashback_amount' => 20.0,
                'min_purchase' => 100.0,
                'max_discount' => 0.0,
                'created_at' => '2025-09-12 00:26:24',
                'updated_at' => '2025-09-12 00:26:24',
                'trip_id' => NULL,
            ),
            37 => 
            array (
                'id' => 38,
                'cash_back_id' => 4,
                'order_id' => 100109,
                'user_id' => 8,
                'cashback_type' => 'percentage',
                'calculated_amount' => 152.9,
                'cashback_amount' => 10.0,
                'min_purchase' => 100.0,
                'max_discount' => 1000.0,
                'created_at' => '2025-09-18 21:04:55',
                'updated_at' => '2025-09-18 21:04:55',
                'trip_id' => NULL,
            ),
            38 => 
            array (
                'id' => 39,
                'cash_back_id' => 4,
                'order_id' => 100111,
                'user_id' => 8,
                'cashback_type' => 'percentage',
                'calculated_amount' => 30.9,
                'cashback_amount' => 10.0,
                'min_purchase' => 100.0,
                'max_discount' => 1000.0,
                'created_at' => '2025-09-18 21:23:29',
                'updated_at' => '2025-09-18 21:23:29',
                'trip_id' => NULL,
            ),
            39 => 
            array (
                'id' => 40,
                'cash_back_id' => 4,
                'order_id' => 100112,
                'user_id' => 8,
                'cashback_type' => 'percentage',
                'calculated_amount' => 98.81,
                'cashback_amount' => 10.0,
                'min_purchase' => 100.0,
                'max_discount' => 1000.0,
                'created_at' => '2025-09-25 21:04:44',
                'updated_at' => '2025-09-25 21:04:44',
                'trip_id' => NULL,
            ),
            40 => 
            array (
                'id' => 41,
                'cash_back_id' => 4,
                'order_id' => 100113,
                'user_id' => 8,
                'cashback_type' => 'percentage',
                'calculated_amount' => 21.84,
                'cashback_amount' => 10.0,
                'min_purchase' => 100.0,
                'max_discount' => 1000.0,
                'created_at' => '2025-10-01 00:27:51',
                'updated_at' => '2025-10-01 00:27:51',
                'trip_id' => NULL,
            ),
            41 => 
            array (
                'id' => 42,
                'cash_back_id' => 1,
                'order_id' => 100114,
                'user_id' => 33,
                'cashback_type' => 'percentage',
                'calculated_amount' => 100.0,
                'cashback_amount' => 10.0,
                'min_purchase' => 500.0,
                'max_discount' => 100.0,
                'created_at' => '2025-10-07 13:34:30',
                'updated_at' => '2025-10-07 13:34:30',
                'trip_id' => NULL,
            ),
            42 => 
            array (
                'id' => 43,
                'cash_back_id' => 6,
                'order_id' => 100115,
                'user_id' => 33,
                'cashback_type' => 'amount',
                'calculated_amount' => 100.0,
                'cashback_amount' => 100.0,
                'min_purchase' => 200.0,
                'max_discount' => 0.0,
                'created_at' => '2025-10-12 15:42:50',
                'updated_at' => '2025-10-12 15:42:50',
                'trip_id' => NULL,
            ),
            43 => 
            array (
                'id' => 44,
                'cash_back_id' => 1,
                'order_id' => 100116,
                'user_id' => 33,
                'cashback_type' => 'percentage',
                'calculated_amount' => 65.87,
                'cashback_amount' => 10.0,
                'min_purchase' => 500.0,
                'max_discount' => 100.0,
                'created_at' => '2025-10-12 15:49:28',
                'updated_at' => '2025-10-12 15:49:28',
                'trip_id' => NULL,
            ),
            44 => 
            array (
                'id' => 45,
                'cash_back_id' => 4,
                'order_id' => 100117,
                'user_id' => 33,
                'cashback_type' => 'percentage',
                'calculated_amount' => 65.87,
                'cashback_amount' => 10.0,
                'min_purchase' => 100.0,
                'max_discount' => 1000.0,
                'created_at' => '2025-10-12 16:09:51',
                'updated_at' => '2025-10-12 16:09:51',
                'trip_id' => NULL,
            ),
            45 => 
            array (
                'id' => 46,
                'cash_back_id' => 6,
                'order_id' => 100118,
                'user_id' => 21,
                'cashback_type' => 'amount',
                'calculated_amount' => 100.0,
                'cashback_amount' => 100.0,
                'min_purchase' => 200.0,
                'max_discount' => 0.0,
                'created_at' => '2025-10-12 16:17:43',
                'updated_at' => '2025-10-12 16:17:43',
                'trip_id' => NULL,
            ),
            46 => 
            array (
                'id' => 47,
                'cash_back_id' => 1,
                'order_id' => 100119,
                'user_id' => 21,
                'cashback_type' => 'percentage',
                'calculated_amount' => 65.87,
                'cashback_amount' => 10.0,
                'min_purchase' => 500.0,
                'max_discount' => 100.0,
                'created_at' => '2025-10-12 16:20:50',
                'updated_at' => '2025-10-12 16:20:50',
                'trip_id' => NULL,
            ),
            47 => 
            array (
                'id' => 48,
                'cash_back_id' => 1,
                'order_id' => 100120,
                'user_id' => 21,
                'cashback_type' => 'percentage',
                'calculated_amount' => 65.87,
                'cashback_amount' => 10.0,
                'min_purchase' => 500.0,
                'max_discount' => 100.0,
                'created_at' => '2025-10-12 16:27:31',
                'updated_at' => '2025-10-12 16:27:31',
                'trip_id' => NULL,
            ),
            48 => 
            array (
                'id' => 49,
                'cash_back_id' => 4,
                'order_id' => 100121,
                'user_id' => 21,
                'cashback_type' => 'percentage',
                'calculated_amount' => 67.77,
                'cashback_amount' => 10.0,
                'min_purchase' => 100.0,
                'max_discount' => 1000.0,
                'created_at' => '2025-10-12 16:31:26',
                'updated_at' => '2025-10-12 16:31:26',
                'trip_id' => NULL,
            ),
            49 => 
            array (
                'id' => 50,
                'cash_back_id' => 4,
                'order_id' => 100122,
                'user_id' => 21,
                'cashback_type' => 'percentage',
                'calculated_amount' => 65.87,
                'cashback_amount' => 10.0,
                'min_purchase' => 100.0,
                'max_discount' => 1000.0,
                'created_at' => '2025-10-12 16:39:45',
                'updated_at' => '2025-10-12 16:39:45',
                'trip_id' => NULL,
            ),
            50 => 
            array (
                'id' => 51,
                'cash_back_id' => 4,
                'order_id' => 100123,
                'user_id' => 21,
                'cashback_type' => 'percentage',
                'calculated_amount' => 65.87,
                'cashback_amount' => 10.0,
                'min_purchase' => 100.0,
                'max_discount' => 1000.0,
                'created_at' => '2025-10-12 17:27:51',
                'updated_at' => '2025-10-12 17:27:51',
                'trip_id' => NULL,
            ),
            51 => 
            array (
                'id' => 52,
                'cash_back_id' => 4,
                'order_id' => 100124,
                'user_id' => 21,
                'cashback_type' => 'percentage',
                'calculated_amount' => 65.87,
                'cashback_amount' => 10.0,
                'min_purchase' => 100.0,
                'max_discount' => 1000.0,
                'created_at' => '2025-10-12 17:32:09',
                'updated_at' => '2025-10-12 17:32:09',
                'trip_id' => NULL,
            ),
            52 => 
            array (
                'id' => 53,
                'cash_back_id' => 4,
                'order_id' => 100125,
                'user_id' => 21,
                'cashback_type' => 'percentage',
                'calculated_amount' => 65.87,
                'cashback_amount' => 10.0,
                'min_purchase' => 100.0,
                'max_discount' => 1000.0,
                'created_at' => '2025-10-12 17:34:46',
                'updated_at' => '2025-10-12 17:34:46',
                'trip_id' => NULL,
            ),
            53 => 
            array (
                'id' => 54,
                'cash_back_id' => 4,
                'order_id' => 100126,
                'user_id' => 33,
                'cashback_type' => 'percentage',
                'calculated_amount' => 78.98,
                'cashback_amount' => 10.0,
                'min_purchase' => 100.0,
                'max_discount' => 1000.0,
                'created_at' => '2025-10-13 12:19:31',
                'updated_at' => '2025-10-13 12:19:31',
                'trip_id' => NULL,
            ),
            54 => 
            array (
                'id' => 55,
                'cash_back_id' => 4,
                'order_id' => 100127,
                'user_id' => 33,
                'cashback_type' => 'percentage',
                'calculated_amount' => 65.87,
                'cashback_amount' => 10.0,
                'min_purchase' => 100.0,
                'max_discount' => 1000.0,
                'created_at' => '2025-10-13 12:27:36',
                'updated_at' => '2025-10-13 12:27:36',
                'trip_id' => NULL,
            ),
        ));
        
        
    }
}