<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class CategoriesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('categories')->delete();
        
        \DB::table('categories')->insert(array (
            0 => 
            array (
                'id' => 1,
                'name' => 'Baby Care',
                'image' => '2024-10-24-6719c7280b472.png',
                'parent_id' => 0,
                'position' => 0,
                'status' => 1,
                'created_at' => '2022-03-16 13:39:39',
                'updated_at' => '2024-10-24 13:44:21',
                'priority' => 2,
                'module_id' => 1,
                'slug' => 'baby-care1',
                'featured' => 0,
            ),
            1 => 
            array (
                'id' => 2,
                'name' => 'Personal Care',
                'image' => '2024-10-24-6719c71a0338d.png',
                'parent_id' => 0,
                'position' => 0,
                'status' => 1,
                'created_at' => '2022-03-16 13:40:42',
                'updated_at' => '2024-10-24 13:44:16',
                'priority' => 2,
                'module_id' => 1,
                'slug' => 'seafood2',
                'featured' => 0,
            ),
            2 => 
            array (
                'id' => 3,
                'name' => 'Health',
                'image' => '2024-10-24-6719c85be3d9f.png',
                'parent_id' => 0,
                'position' => 0,
                'status' => 1,
                'created_at' => '2022-03-16 13:41:29',
                'updated_at' => '2024-10-24 13:44:12',
                'priority' => 2,
                'module_id' => 1,
                'slug' => 'meat3',
                'featured' => 0,
            ),
            3 => 
            array (
                'id' => 4,
                'name' => 'Snacks',
                'image' => '2024-10-23-6718f254cb596.png',
                'parent_id' => 0,
                'position' => 0,
                'status' => 1,
                'created_at' => '2022-03-16 13:42:11',
                'updated_at' => '2024-10-24 13:44:08',
                'priority' => 2,
                'module_id' => 1,
                'slug' => 'snacks4',
                'featured' => 0,
            ),
            4 => 
            array (
                'id' => 5,
                'name' => 'Pantry',
                'image' => '2024-10-23-6718f227a2627.png',
                'parent_id' => 0,
                'position' => 0,
                'status' => 1,
                'created_at' => '2022-03-16 13:42:53',
                'updated_at' => '2024-10-24 13:44:04',
                'priority' => 2,
                'module_id' => 1,
                'slug' => 'pantry5',
                'featured' => 0,
            ),
            5 => 
            array (
                'id' => 6,
                'name' => 'Frozen',
                'image' => '2024-11-17-6739638489261.png',
                'parent_id' => 0,
                'position' => 0,
                'status' => 1,
                'created_at' => '2022-03-16 13:43:42',
                'updated_at' => '2024-11-17 09:31:16',
                'priority' => 2,
                'module_id' => 1,
                'slug' => 'frozen6',
                'featured' => 0,
            ),
            6 => 
            array (
                'id' => 7,
                'name' => 'Beverages',
                'image' => '2024-10-23-6718f14c85661.png',
                'parent_id' => 0,
                'position' => 0,
                'status' => 1,
                'created_at' => '2022-03-16 13:44:19',
                'updated_at' => '2024-10-24 13:43:56',
                'priority' => 2,
                'module_id' => 1,
                'slug' => 'beverages7',
                'featured' => 0,
            ),
            7 => 
            array (
                'id' => 8,
                'name' => 'Bakery',
                'image' => '2024-10-23-6718f13f3d508.png',
                'parent_id' => 0,
                'position' => 0,
                'status' => 1,
                'created_at' => '2022-03-16 13:44:57',
                'updated_at' => '2024-10-24 13:43:52',
                'priority' => 2,
                'module_id' => 1,
                'slug' => 'bakery8',
                'featured' => 0,
            ),
            8 => 
            array (
                'id' => 9,
                'name' => 'Seafood',
                'image' => '2024-10-23-6718f130ce658.png',
                'parent_id' => 0,
                'position' => 0,
                'status' => 1,
                'created_at' => '2022-03-16 13:46:52',
                'updated_at' => '2024-10-24 13:43:48',
                'priority' => 2,
                'module_id' => 1,
                'slug' => 'fresh-produce9',
                'featured' => 0,
            ),
            9 => 
            array (
                'id' => 10,
                'name' => 'Meat',
                'image' => '2024-10-23-6718f120700a2.png',
                'parent_id' => 0,
                'position' => 0,
                'status' => 1,
                'created_at' => '2022-03-16 13:47:36',
                'updated_at' => '2024-10-24 13:43:45',
                'priority' => 2,
                'module_id' => 1,
                'slug' => 'meat10',
                'featured' => 0,
            ),
            10 => 
            array (
                'id' => 11,
                'name' => 'Dairy & Eggs',
                'image' => '2024-10-23-6718f111d1be2.png',
                'parent_id' => 0,
                'position' => 0,
                'status' => 1,
                'created_at' => '2022-03-16 13:48:19',
                'updated_at' => '2024-10-24 13:42:59',
                'priority' => 2,
                'module_id' => 1,
                'slug' => 'dairy-eggs11',
                'featured' => 0,
            ),
            11 => 
            array (
                'id' => 12,
                'name' => 'Fresh Produce',
                'image' => '2024-10-23-6718e9fc41a6a.png',
                'parent_id' => 0,
                'position' => 0,
                'status' => 1,
                'created_at' => '2022-03-16 13:49:48',
                'updated_at' => '2024-10-24 13:42:52',
                'priority' => 2,
                'module_id' => 1,
                'slug' => 'home-and-kitchen-appliance12',
                'featured' => 0,
            ),
            12 => 
            array (
                'id' => 13,
                'name' => 'Eye Care',
                'image' => '2024-11-05-67299fc32b966.png',
                'parent_id' => 0,
                'position' => 0,
                'status' => 1,
                'created_at' => '2022-03-16 17:15:48',
                'updated_at' => '2024-11-05 10:32:03',
                'priority' => 0,
                'module_id' => 2,
                'slug' => 'eye-care13',
                'featured' => 0,
            ),
            13 => 
            array (
                'id' => 14,
                'name' => 'Women\'s Care',
                'image' => '2024-11-05-67299fb5a481c.png',
                'parent_id' => 0,
                'position' => 0,
                'status' => 1,
                'created_at' => '2022-03-16 17:16:36',
                'updated_at' => '2024-11-05 10:31:49',
                'priority' => 0,
                'module_id' => 2,
                'slug' => 'womens-care14',
                'featured' => 0,
            ),
            14 => 
            array (
                'id' => 16,
                'name' => 'Vaccine',
                'image' => '2024-11-05-67299fa8a23da.png',
                'parent_id' => 0,
                'position' => 0,
                'status' => 1,
                'created_at' => '2022-03-16 17:18:14',
                'updated_at' => '2024-11-05 10:31:36',
                'priority' => 0,
                'module_id' => 2,
                'slug' => 'vaccine16',
                'featured' => 0,
            ),
            15 => 
            array (
                'id' => 17,
                'name' => 'Oral Care',
                'image' => '2024-11-05-67299f9c2efb0.png',
                'parent_id' => 0,
                'position' => 0,
                'status' => 1,
                'created_at' => '2022-03-16 17:18:54',
                'updated_at' => '2024-11-05 10:31:24',
                'priority' => 0,
                'module_id' => 2,
                'slug' => 'oral-care17',
                'featured' => 0,
            ),
            16 => 
            array (
                'id' => 18,
                'name' => 'Skin Care',
                'image' => '2024-11-05-67299f8fa18d7.png',
                'parent_id' => 0,
                'position' => 0,
                'status' => 1,
                'created_at' => '2022-03-16 17:19:48',
                'updated_at' => '2024-11-05 10:31:11',
                'priority' => 0,
                'module_id' => 2,
                'slug' => 'skin-care18',
                'featured' => 0,
            ),
            17 => 
            array (
                'id' => 19,
                'name' => 'Devices',
                'image' => '2024-11-05-67299f80d099b.png',
                'parent_id' => 0,
                'position' => 0,
                'status' => 1,
                'created_at' => '2022-03-16 17:20:19',
                'updated_at' => '2024-11-05 10:30:56',
                'priority' => 0,
                'module_id' => 2,
                'slug' => 'devices19',
                'featured' => 0,
            ),
            18 => 
            array (
                'id' => 20,
                'name' => 'Baby Care',
                'image' => '2024-11-05-67299f730c2a3.png',
                'parent_id' => 0,
                'position' => 0,
                'status' => 1,
                'created_at' => '2022-03-16 17:20:44',
                'updated_at' => '2024-11-05 10:30:43',
                'priority' => 0,
                'module_id' => 2,
                'slug' => 'baby-care20',
                'featured' => 0,
            ),
            19 => 
            array (
                'id' => 21,
                'name' => 'First Aid',
                'image' => '2024-11-05-67299f64d4393.png',
                'parent_id' => 0,
                'position' => 0,
                'status' => 1,
                'created_at' => '2022-03-16 17:24:08',
                'updated_at' => '2024-11-05 10:30:28',
                'priority' => 0,
                'module_id' => 2,
                'slug' => 'first-aid21',
                'featured' => 0,
            ),
            20 => 
            array (
                'id' => 22,
                'name' => 'Supplements',
                'image' => '2024-11-05-67299f557d546.png',
                'parent_id' => 0,
                'position' => 0,
                'status' => 1,
                'created_at' => '2022-03-16 17:25:42',
                'updated_at' => '2024-11-05 10:30:13',
                'priority' => 0,
                'module_id' => 2,
                'slug' => 'supplements22',
                'featured' => 0,
            ),
            21 => 
            array (
                'id' => 23,
                'name' => 'Vitamins',
                'image' => '2024-11-05-67299f45971f4.png',
                'parent_id' => 0,
                'position' => 0,
                'status' => 1,
                'created_at' => '2022-03-16 17:26:08',
                'updated_at' => '2024-11-05 10:29:57',
                'priority' => 0,
                'module_id' => 2,
                'slug' => 'vitamins23',
                'featured' => 0,
            ),
            22 => 
            array (
                'id' => 25,
                'name' => 'Eyewear',
                'image' => '2024-10-28-671f7edf905b2.png',
                'parent_id' => 0,
                'position' => 0,
                'status' => 1,
                'created_at' => '2022-03-22 12:31:22',
                'updated_at' => '2024-10-28 18:09:03',
                'priority' => 0,
                'module_id' => 3,
                'slug' => 'eyewear25',
                'featured' => 0,
            ),
            23 => 
            array (
                'id' => 26,
                'name' => 'Watches',
                'image' => '2024-10-28-671f7ed3b3f67.png',
                'parent_id' => 0,
                'position' => 0,
                'status' => 1,
                'created_at' => '2022-03-22 12:31:29',
                'updated_at' => '2024-10-28 18:08:51',
                'priority' => 0,
                'module_id' => 3,
                'slug' => 'watches26',
                'featured' => 0,
            ),
            24 => 
            array (
                'id' => 27,
                'name' => 'Electronics',
                'image' => '2024-10-28-671f7ec58767d.png',
                'parent_id' => 0,
                'position' => 0,
                'status' => 1,
                'created_at' => '2022-03-22 12:32:19',
                'updated_at' => '2024-10-28 18:08:37',
                'priority' => 0,
                'module_id' => 3,
                'slug' => 'electronics27',
                'featured' => 0,
            ),
            25 => 
            array (
                'id' => 28,
                'name' => 'Gifts',
                'image' => '2024-10-28-671f7eb803c75.png',
                'parent_id' => 0,
                'position' => 0,
                'status' => 1,
                'created_at' => '2022-03-22 12:32:50',
                'updated_at' => '2024-10-28 18:08:24',
                'priority' => 0,
                'module_id' => 3,
                'slug' => 'gifts28',
                'featured' => 0,
            ),
            26 => 
            array (
                'id' => 30,
                'name' => 'Luggage',
                'image' => '2024-10-28-671f7ea9c2846.png',
                'parent_id' => 0,
                'position' => 0,
                'status' => 1,
                'created_at' => '2022-03-22 12:33:52',
                'updated_at' => '2024-10-28 18:08:09',
                'priority' => 0,
                'module_id' => 3,
                'slug' => 'luggage30',
                'featured' => 0,
            ),
            27 => 
            array (
                'id' => 31,
                'name' => 'Jewelry',
                'image' => '2024-10-28-671f7e95647f7.png',
                'parent_id' => 0,
                'position' => 0,
                'status' => 1,
                'created_at' => '2022-03-22 12:34:44',
                'updated_at' => '2024-10-28 18:07:49',
                'priority' => 0,
                'module_id' => 3,
                'slug' => 'jewelry31',
                'featured' => 0,
            ),
            28 => 
            array (
                'id' => 32,
                'name' => 'Sports',
                'image' => '2024-10-28-671f7e854c4a8.png',
                'parent_id' => 0,
                'position' => 0,
                'status' => 1,
                'created_at' => '2022-03-22 12:34:45',
                'updated_at' => '2024-10-28 18:07:33',
                'priority' => 0,
                'module_id' => 3,
                'slug' => 'sports32',
                'featured' => 0,
            ),
            29 => 
            array (
                'id' => 33,
                'name' => 'Kitchen',
                'image' => '2024-10-28-671f7e7727295.png',
                'parent_id' => 0,
                'position' => 0,
                'status' => 1,
                'created_at' => '2022-03-22 12:35:16',
                'updated_at' => '2024-10-28 18:07:19',
                'priority' => 0,
                'module_id' => 3,
                'slug' => 'kitchen33',
                'featured' => 0,
            ),
            30 => 
            array (
                'id' => 34,
                'name' => 'Pet Supplies',
                'image' => '2024-10-28-671f7e63b3cf4.png',
                'parent_id' => 0,
                'position' => 0,
                'status' => 1,
                'created_at' => '2022-03-22 12:35:22',
                'updated_at' => '2024-10-28 18:06:59',
                'priority' => 0,
                'module_id' => 3,
                'slug' => 'pet-supplies34',
                'featured' => 0,
            ),
            31 => 
            array (
                'id' => 35,
                'name' => 'Beauty',
                'image' => '2024-10-28-671f7e5274e56.png',
                'parent_id' => 0,
                'position' => 0,
                'status' => 1,
                'created_at' => '2022-03-22 12:35:53',
                'updated_at' => '2024-10-28 18:06:42',
                'priority' => 0,
                'module_id' => 3,
                'slug' => 'beauty35',
                'featured' => 0,
            ),
            32 => 
            array (
                'id' => 36,
                'name' => 'Health',
                'image' => '2024-10-28-671f7e41753eb.png',
                'parent_id' => 0,
                'position' => 0,
                'status' => 1,
                'created_at' => '2022-03-22 12:36:02',
                'updated_at' => '2024-10-28 18:06:25',
                'priority' => 0,
                'module_id' => 3,
                'slug' => 'health36',
                'featured' => 0,
            ),
            33 => 
            array (
                'id' => 37,
                'name' => 'Kids\' Fashion',
                'image' => '2024-10-28-671f7e3447ed1.png',
                'parent_id' => 0,
                'position' => 0,
                'status' => 1,
                'created_at' => '2022-03-22 12:36:31',
                'updated_at' => '2024-10-28 18:06:12',
                'priority' => 0,
                'module_id' => 3,
                'slug' => 'kids-fashion37',
                'featured' => 0,
            ),
            34 => 
            array (
                'id' => 38,
                'name' => 'Women’s Trend',
                'image' => '2024-10-28-671f7e1adb6a9.png',
                'parent_id' => 0,
                'position' => 0,
                'status' => 1,
                'created_at' => '2022-03-22 12:36:39',
                'updated_at' => '2024-10-28 18:05:46',
                'priority' => 0,
                'module_id' => 3,
                'slug' => 'womens-trend38',
                'featured' => 1,
            ),
            35 => 
            array (
                'id' => 39,
                'name' => 'Men’s Fashion',
                'image' => '2024-10-28-671f7dfb5378a.png',
                'parent_id' => 0,
                'position' => 0,
                'status' => 1,
                'created_at' => '2022-03-22 12:37:16',
                'updated_at' => '2024-10-28 18:05:15',
                'priority' => 0,
                'module_id' => 3,
                'slug' => 'mens-fashion39',
                'featured' => 1,
            ),
            36 => 
            array (
                'id' => 40,
                'name' => 'Men\'s Footwear',
                'image' => 'def.png',
                'parent_id' => 39,
                'position' => 1,
                'status' => 1,
                'created_at' => '2022-03-22 13:23:51',
                'updated_at' => '2024-10-28 17:24:24',
                'priority' => 0,
                'module_id' => 3,
                'slug' => 'mens-footwear40',
                'featured' => 0,
            ),
            37 => 
            array (
                'id' => 45,
                'name' => 'Men\'s Clothing',
                'image' => 'def.png',
                'parent_id' => 39,
                'position' => 1,
                'status' => 1,
                'created_at' => '2022-03-22 13:26:42',
                'updated_at' => '2024-10-28 17:24:03',
                'priority' => 0,
                'module_id' => 3,
                'slug' => 'mens-clothing45',
                'featured' => 0,
            ),
            38 => 
            array (
                'id' => 46,
                'name' => 'Crab',
                'image' => 'def.png',
                'parent_id' => 9,
                'position' => 1,
                'status' => 1,
                'created_at' => '2022-03-22 13:27:01',
                'updated_at' => '2024-10-27 09:46:14',
                'priority' => 0,
                'module_id' => 1,
                'slug' => 'crab46',
                'featured' => 0,
            ),
            39 => 
            array (
                'id' => 47,
                'name' => 'Shrimp',
                'image' => 'def.png',
                'parent_id' => 9,
                'position' => 1,
                'status' => 1,
                'created_at' => '2022-03-22 13:27:26',
                'updated_at' => '2024-10-27 09:46:00',
                'priority' => 0,
                'module_id' => 1,
                'slug' => 'shrimp47',
                'featured' => 0,
            ),
            40 => 
            array (
                'id' => 48,
                'name' => 'Fresh Fish',
                'image' => 'def.png',
                'parent_id' => 9,
                'position' => 1,
                'status' => 1,
                'created_at' => '2022-03-22 13:27:46',
                'updated_at' => '2024-10-27 09:45:46',
                'priority' => 0,
                'module_id' => 1,
                'slug' => 'fresh-fish48',
                'featured' => 0,
            ),
            41 => 
            array (
                'id' => 49,
                'name' => 'Vegan',
                'image' => 'def.png',
                'parent_id' => 3,
                'position' => 1,
                'status' => 1,
                'created_at' => '2022-03-22 13:28:04',
                'updated_at' => '2024-10-27 09:54:17',
                'priority' => 0,
                'module_id' => 1,
                'slug' => 'vegan49',
                'featured' => 0,
            ),
            42 => 
            array (
                'id' => 50,
                'name' => 'Gluten-Free',
                'image' => 'def.png',
                'parent_id' => 3,
                'position' => 1,
                'status' => 1,
                'created_at' => '2022-03-22 13:28:18',
                'updated_at' => '2024-10-27 09:53:57',
                'priority' => 0,
                'module_id' => 1,
                'slug' => 'gluten-free50',
                'featured' => 0,
            ),
            43 => 
            array (
                'id' => 51,
                'name' => 'Organic Foods',
                'image' => 'def.png',
                'parent_id' => 3,
                'position' => 1,
                'status' => 1,
                'created_at' => '2022-03-22 13:28:28',
                'updated_at' => '2024-10-27 09:53:35',
                'priority' => 0,
                'module_id' => 1,
                'slug' => 'organic-foods51',
                'featured' => 0,
            ),
            44 => 
            array (
                'id' => 52,
                'name' => 'Rice',
                'image' => 'def.png',
                'parent_id' => 5,
                'position' => 1,
                'status' => 1,
                'created_at' => '2022-03-22 13:28:49',
                'updated_at' => '2022-03-22 13:28:49',
                'priority' => 0,
                'module_id' => 1,
                'slug' => NULL,
                'featured' => 0,
            ),
            45 => 
            array (
                'id' => 53,
                'name' => 'Pasta',
                'image' => 'def.png',
                'parent_id' => 5,
                'position' => 1,
                'status' => 1,
                'created_at' => '2022-03-22 13:29:08',
                'updated_at' => '2024-10-27 09:51:42',
                'priority' => 0,
                'module_id' => 1,
                'slug' => 'pasta53',
                'featured' => 0,
            ),
            46 => 
            array (
                'id' => 54,
                'name' => 'Flour',
                'image' => 'def.png',
                'parent_id' => 5,
                'position' => 1,
                'status' => 1,
                'created_at' => '2022-03-22 13:30:08',
                'updated_at' => '2024-10-27 09:52:01',
                'priority' => 0,
                'module_id' => 1,
                'slug' => 'flour54',
                'featured' => 0,
            ),
            47 => 
            array (
                'id' => 59,
                'name' => 'Processed Meat',
                'image' => 'def.png',
                'parent_id' => 10,
                'position' => 1,
                'status' => 1,
                'created_at' => '2022-03-22 13:31:55',
                'updated_at' => '2024-10-27 09:45:29',
                'priority' => 0,
                'module_id' => 1,
                'slug' => 'processed-meat59',
                'featured' => 0,
            ),
            48 => 
            array (
                'id' => 60,
                'name' => 'Lamb',
                'image' => 'def.png',
                'parent_id' => 10,
                'position' => 1,
                'status' => 1,
                'created_at' => '2022-03-22 13:32:07',
                'updated_at' => '2024-10-27 09:45:14',
                'priority' => 0,
                'module_id' => 1,
                'slug' => 'lamb60',
                'featured' => 0,
            ),
            49 => 
            array (
                'id' => 61,
                'name' => 'Beef',
                'image' => 'def.png',
                'parent_id' => 10,
                'position' => 1,
                'status' => 1,
                'created_at' => '2022-03-22 13:32:17',
                'updated_at' => '2024-10-27 09:44:59',
                'priority' => 0,
                'module_id' => 1,
                'slug' => 'beef61',
                'featured' => 0,
            ),
            50 => 
            array (
                'id' => 62,
                'name' => 'Chicken',
                'image' => 'def.png',
                'parent_id' => 10,
                'position' => 1,
                'status' => 1,
                'created_at' => '2022-03-22 13:32:29',
                'updated_at' => '2024-10-27 09:44:42',
                'priority' => 0,
                'module_id' => 1,
                'slug' => 'chicken62',
                'featured' => 0,
            ),
            51 => 
            array (
                'id' => 63,
                'name' => 'Wipes',
                'image' => 'def.png',
                'parent_id' => 1,
                'position' => 1,
                'status' => 1,
                'created_at' => '2022-03-22 13:33:02',
                'updated_at' => '2024-10-27 09:58:46',
                'priority' => 0,
                'module_id' => 1,
                'slug' => 'wipes63',
                'featured' => 0,
            ),
            52 => 
            array (
                'id' => 64,
                'name' => 'Baby Food',
                'image' => 'def.png',
                'parent_id' => 1,
                'position' => 1,
                'status' => 1,
                'created_at' => '2022-03-22 13:33:18',
                'updated_at' => '2024-10-27 09:58:24',
                'priority' => 0,
                'module_id' => 1,
                'slug' => 'baby-food64',
                'featured' => 0,
            ),
            53 => 
            array (
                'id' => 65,
                'name' => 'Diapers',
                'image' => 'def.png',
                'parent_id' => 1,
                'position' => 1,
                'status' => 1,
                'created_at' => '2022-03-22 13:33:28',
                'updated_at' => '2024-10-27 09:58:04',
                'priority' => 0,
                'module_id' => 1,
                'slug' => 'diapers65',
                'featured' => 0,
            ),
            54 => 
            array (
                'id' => 70,
                'name' => 'Burger',
                'image' => '2024-11-03-67270e7994d53.png',
                'parent_id' => 0,
                'position' => 0,
                'status' => 1,
                'created_at' => '2021-08-20 20:37:02',
                'updated_at' => '2024-11-03 11:47:37',
                'priority' => 0,
                'module_id' => 4,
                'slug' => 'burger70',
                'featured' => 0,
            ),
            55 => 
            array (
                'id' => 71,
                'name' => 'Biriyani',
                'image' => '2024-11-03-67270e54ea7f5.png',
                'parent_id' => 0,
                'position' => 0,
                'status' => 1,
                'created_at' => '2021-08-20 20:39:41',
                'updated_at' => '2024-11-03 11:47:00',
                'priority' => 0,
                'module_id' => 4,
                'slug' => 'biriyani71',
                'featured' => 0,
            ),
            56 => 
            array (
                'id' => 72,
                'name' => 'Asian',
                'image' => '2024-11-03-67270e3258336.png',
                'parent_id' => 0,
                'position' => 0,
                'status' => 1,
                'created_at' => '2021-08-20 20:39:55',
                'updated_at' => '2024-11-03 11:46:26',
                'priority' => 0,
                'module_id' => 4,
                'slug' => 'asian72',
                'featured' => 0,
            ),
            57 => 
            array (
                'id' => 73,
                'name' => 'Cake',
                'image' => '2024-11-03-67270ef5be976.png',
                'parent_id' => 0,
                'position' => 0,
                'status' => 1,
                'created_at' => '2021-08-20 20:40:11',
                'updated_at' => '2024-11-03 11:49:41',
                'priority' => 0,
                'module_id' => 4,
                'slug' => 'cake73',
                'featured' => 0,
            ),
            58 => 
            array (
                'id' => 74,
                'name' => 'Drinks',
                'image' => '2024-11-03-67270e0e949f0.png',
                'parent_id' => 0,
                'position' => 0,
                'status' => 1,
                'created_at' => '2021-08-20 20:40:30',
                'updated_at' => '2024-11-03 11:51:03',
                'priority' => 0,
                'module_id' => 4,
                'slug' => 'coffee-drinks74',
                'featured' => 0,
            ),
            59 => 
            array (
                'id' => 75,
                'name' => 'Chinese',
                'image' => '2024-11-03-67270dfc5251e.png',
                'parent_id' => 0,
                'position' => 0,
                'status' => 1,
                'created_at' => '2021-08-20 20:41:31',
                'updated_at' => '2024-11-03 11:45:32',
                'priority' => 0,
                'module_id' => 4,
                'slug' => 'chinese75',
                'featured' => 0,
            ),
            60 => 
            array (
                'id' => 76,
                'name' => 'Fast Food',
                'image' => '2021-08-20-611fbf30f1a68.png',
                'parent_id' => 0,
                'position' => 0,
                'status' => 0,
                'created_at' => '2021-08-20 20:41:52',
                'updated_at' => '2024-11-03 11:48:41',
                'priority' => 0,
                'module_id' => 4,
                'slug' => NULL,
                'featured' => 0,
            ),
            61 => 
            array (
                'id' => 77,
                'name' => 'Kabab',
                'image' => '2024-11-03-67270de473797.png',
                'parent_id' => 0,
                'position' => 0,
                'status' => 1,
                'created_at' => '2021-08-20 20:42:17',
                'updated_at' => '2024-11-03 11:50:35',
                'priority' => 0,
                'module_id' => 4,
                'slug' => 'kabab-more77',
                'featured' => 0,
            ),
            62 => 
            array (
                'id' => 78,
                'name' => 'Indian',
                'image' => '2024-11-03-67270eaa6b327.png',
                'parent_id' => 0,
                'position' => 0,
                'status' => 1,
                'created_at' => '2021-08-20 20:42:50',
                'updated_at' => '2024-11-03 11:48:26',
                'priority' => 0,
                'module_id' => 4,
                'slug' => 'indian78',
                'featured' => 0,
            ),
            63 => 
            array (
                'id' => 79,
                'name' => 'Noodles',
                'image' => '2024-11-03-67270e21114aa.png',
                'parent_id' => 0,
                'position' => 0,
                'status' => 1,
                'created_at' => '2021-08-20 20:43:03',
                'updated_at' => '2024-11-03 11:46:09',
                'priority' => 0,
                'module_id' => 4,
                'slug' => 'noodles79',
                'featured' => 0,
            ),
            64 => 
            array (
                'id' => 80,
                'name' => 'Mexican',
                'image' => '2024-11-03-67270dc8346d4.png',
                'parent_id' => 0,
                'position' => 0,
                'status' => 1,
                'created_at' => '2021-08-20 20:43:34',
                'updated_at' => '2024-11-03 11:50:49',
                'priority' => 0,
                'module_id' => 4,
                'slug' => 'mexican-food80',
                'featured' => 0,
            ),
            65 => 
            array (
                'id' => 81,
                'name' => 'Pasta',
                'image' => '2024-11-03-67270d9ecd692.png',
                'parent_id' => 0,
                'position' => 0,
                'status' => 1,
                'created_at' => '2021-08-20 20:43:47',
                'updated_at' => '2024-11-03 11:43:58',
                'priority' => 0,
                'module_id' => 4,
                'slug' => 'pasta81',
                'featured' => 0,
            ),
            66 => 
            array (
                'id' => 82,
                'name' => 'Pizza',
                'image' => '2024-11-03-67270d8902b23.png',
                'parent_id' => 0,
                'position' => 0,
                'status' => 1,
                'created_at' => '2021-08-20 20:44:00',
                'updated_at' => '2024-11-03 11:43:37',
                'priority' => 0,
                'module_id' => 4,
                'slug' => 'pizza82',
                'featured' => 0,
            ),
            67 => 
            array (
                'id' => 83,
                'name' => 'Snacks',
                'image' => '2021-08-20-611fbfbc0e2ed.png',
                'parent_id' => 0,
                'position' => 0,
                'status' => 0,
                'created_at' => '2021-08-20 20:44:12',
                'updated_at' => '2024-11-03 11:48:33',
                'priority' => 0,
                'module_id' => 4,
                'slug' => NULL,
                'featured' => 0,
            ),
            68 => 
            array (
                'id' => 84,
                'name' => 'Thai',
                'image' => '2024-11-03-67270d6d3c394.png',
                'parent_id' => 0,
                'position' => 0,
                'status' => 1,
                'created_at' => '2021-08-20 20:44:22',
                'updated_at' => '2024-11-03 11:43:09',
                'priority' => 0,
                'module_id' => 4,
                'slug' => 'thai84',
                'featured' => 0,
            ),
            69 => 
            array (
                'id' => 85,
                'name' => 'Varieties',
                'image' => '2021-08-20-611fbfd13f7db.png',
                'parent_id' => 0,
                'position' => 0,
                'status' => 0,
                'created_at' => '2021-08-20 20:44:33',
                'updated_at' => '2024-11-03 11:48:30',
                'priority' => 0,
                'module_id' => 4,
                'slug' => NULL,
                'featured' => 0,
            ),
            70 => 
            array (
                'id' => 86,
                'name' => 'Kubie Burger',
                'image' => 'def.png',
                'parent_id' => 70,
                'position' => 1,
                'status' => 1,
                'created_at' => '2021-08-20 20:46:55',
                'updated_at' => '2021-08-20 20:46:55',
                'priority' => 0,
                'module_id' => 4,
                'slug' => NULL,
                'featured' => 0,
            ),
            71 => 
            array (
                'id' => 87,
                'name' => 'Steamed Cheese',
                'image' => 'def.png',
                'parent_id' => 70,
                'position' => 1,
                'status' => 1,
                'created_at' => '2021-08-20 20:47:28',
                'updated_at' => '2021-08-20 20:47:28',
                'priority' => 0,
                'module_id' => 4,
                'slug' => NULL,
                'featured' => 0,
            ),
            72 => 
            array (
                'id' => 88,
                'name' => 'Theta Burger',
                'image' => 'def.png',
                'parent_id' => 70,
                'position' => 1,
                'status' => 1,
                'created_at' => '2021-08-20 20:47:40',
                'updated_at' => '2021-08-20 20:47:40',
                'priority' => 0,
                'module_id' => 4,
                'slug' => NULL,
                'featured' => 0,
            ),
            73 => 
            array (
                'id' => 89,
                'name' => 'Nutburger',
                'image' => 'def.png',
                'parent_id' => 70,
                'position' => 1,
                'status' => 1,
                'created_at' => '2021-08-20 20:47:51',
                'updated_at' => '2021-08-20 20:47:51',
                'priority' => 0,
                'module_id' => 4,
                'slug' => NULL,
                'featured' => 0,
            ),
            74 => 
            array (
                'id' => 90,
                'name' => 'Pimento Cheese',
                'image' => 'def.png',
                'parent_id' => 70,
                'position' => 1,
                'status' => 1,
                'created_at' => '2021-08-20 20:48:13',
                'updated_at' => '2021-08-20 20:48:13',
                'priority' => 0,
                'module_id' => 4,
                'slug' => NULL,
                'featured' => 0,
            ),
            75 => 
            array (
                'id' => 91,
                'name' => 'Pound Cake',
                'image' => 'def.png',
                'parent_id' => 73,
                'position' => 1,
                'status' => 1,
                'created_at' => '2021-08-20 20:54:43',
                'updated_at' => '2021-08-20 20:54:43',
                'priority' => 0,
                'module_id' => 4,
                'slug' => NULL,
                'featured' => 0,
            ),
            76 => 
            array (
                'id' => 92,
                'name' => 'Yellow Butter',
                'image' => 'def.png',
                'parent_id' => 73,
                'position' => 1,
                'status' => 1,
                'created_at' => '2021-08-20 20:54:52',
                'updated_at' => '2021-08-20 20:54:52',
                'priority' => 0,
                'module_id' => 4,
                'slug' => NULL,
                'featured' => 0,
            ),
            77 => 
            array (
                'id' => 93,
                'name' => 'Red Velvet',
                'image' => 'def.png',
                'parent_id' => 73,
                'position' => 1,
                'status' => 1,
                'created_at' => '2021-08-20 20:55:03',
                'updated_at' => '2021-08-20 20:55:03',
                'priority' => 0,
                'module_id' => 4,
                'slug' => NULL,
                'featured' => 0,
            ),
            78 => 
            array (
                'id' => 94,
                'name' => 'Black Coffee',
                'image' => 'def.png',
                'parent_id' => 74,
                'position' => 1,
                'status' => 1,
                'created_at' => '2021-08-20 20:55:42',
                'updated_at' => '2021-08-20 20:55:42',
                'priority' => 0,
                'module_id' => 4,
                'slug' => NULL,
                'featured' => 0,
            ),
            79 => 
            array (
                'id' => 95,
                'name' => 'Robusta',
                'image' => 'def.png',
                'parent_id' => 74,
                'position' => 1,
                'status' => 1,
                'created_at' => '2021-08-20 20:55:50',
                'updated_at' => '2021-08-20 20:55:50',
                'priority' => 0,
                'module_id' => 4,
                'slug' => NULL,
                'featured' => 0,
            ),
            80 => 
            array (
                'id' => 96,
                'name' => 'Cappuccino',
                'image' => 'def.png',
                'parent_id' => 74,
                'position' => 1,
                'status' => 1,
                'created_at' => '2021-08-20 20:56:01',
                'updated_at' => '2021-08-20 20:56:01',
                'priority' => 0,
                'module_id' => 4,
                'slug' => NULL,
                'featured' => 0,
            ),
            81 => 
            array (
                'id' => 97,
                'name' => 'Macchiato',
                'image' => 'def.png',
                'parent_id' => 74,
                'position' => 1,
                'status' => 1,
                'created_at' => '2021-08-20 20:56:08',
                'updated_at' => '2021-08-20 20:56:08',
                'priority' => 0,
                'module_id' => 4,
                'slug' => NULL,
                'featured' => 0,
            ),
            82 => 
            array (
                'id' => 98,
                'name' => 'Soft Drinks',
                'image' => 'def.png',
                'parent_id' => 74,
                'position' => 1,
                'status' => 1,
                'created_at' => '2021-08-20 20:56:20',
                'updated_at' => '2021-08-20 20:56:20',
                'priority' => 0,
                'module_id' => 4,
                'slug' => NULL,
                'featured' => 0,
            ),
            83 => 
            array (
                'id' => 101,
                'name' => 'Household',
                'image' => '2024-10-24-6719c752f13f3.png',
                'parent_id' => 0,
                'position' => 0,
                'status' => 1,
                'created_at' => '2024-10-24 09:13:35',
                'updated_at' => '2024-10-24 13:44:27',
                'priority' => 1,
                'module_id' => 1,
                'slug' => 'household',
                'featured' => 0,
            ),
            84 => 
            array (
                'id' => 102,
                'name' => 'Cooking',
                'image' => '2024-11-17-673963a555240.png',
                'parent_id' => 0,
                'position' => 0,
                'status' => 1,
                'created_at' => '2024-10-24 09:15:11',
                'updated_at' => '2024-11-17 09:31:49',
                'priority' => 1,
                'module_id' => 1,
                'slug' => 'cooking',
                'featured' => 0,
            ),
            85 => 
            array (
                'id' => 103,
                'name' => 'Fruits',
                'image' => 'def.png',
                'parent_id' => 12,
                'position' => 1,
                'status' => 1,
                'created_at' => '2024-10-27 09:42:22',
                'updated_at' => '2024-10-27 09:42:22',
                'priority' => 0,
                'module_id' => 1,
                'slug' => 'fruits',
                'featured' => 0,
            ),
            86 => 
            array (
                'id' => 104,
                'name' => 'Vegetables',
                'image' => 'def.png',
                'parent_id' => 12,
                'position' => 1,
                'status' => 1,
                'created_at' => '2024-10-27 09:42:30',
                'updated_at' => '2024-10-27 09:42:30',
                'priority' => 0,
                'module_id' => 1,
                'slug' => 'vegetables',
                'featured' => 0,
            ),
            87 => 
            array (
                'id' => 105,
                'name' => 'Herbs',
                'image' => 'def.png',
                'parent_id' => 12,
                'position' => 1,
                'status' => 1,
                'created_at' => '2024-10-27 09:42:37',
                'updated_at' => '2024-10-27 09:42:37',
                'priority' => 0,
                'module_id' => 1,
                'slug' => 'herbs',
                'featured' => 0,
            ),
            88 => 
            array (
                'id' => 106,
                'name' => 'Milk',
                'image' => 'def.png',
                'parent_id' => 11,
                'position' => 1,
                'status' => 1,
                'created_at' => '2024-10-27 09:42:49',
                'updated_at' => '2024-10-27 09:42:49',
                'priority' => 0,
                'module_id' => 1,
                'slug' => 'milk',
                'featured' => 0,
            ),
            89 => 
            array (
                'id' => 107,
                'name' => 'Cheese',
                'image' => 'def.png',
                'parent_id' => 11,
                'position' => 1,
                'status' => 1,
                'created_at' => '2024-10-27 09:42:56',
                'updated_at' => '2024-10-27 09:42:56',
                'priority' => 0,
                'module_id' => 1,
                'slug' => 'cheese',
                'featured' => 0,
            ),
            90 => 
            array (
                'id' => 108,
                'name' => 'Eggs',
                'image' => 'def.png',
                'parent_id' => 11,
                'position' => 1,
                'status' => 1,
                'created_at' => '2024-10-27 09:43:02',
                'updated_at' => '2024-10-27 09:43:47',
                'priority' => 0,
                'module_id' => 1,
                'slug' => 'yogurt',
                'featured' => 0,
            ),
            91 => 
            array (
                'id' => 109,
                'name' => 'Butter',
                'image' => 'def.png',
                'parent_id' => 11,
                'position' => 1,
                'status' => 1,
                'created_at' => '2024-10-27 09:43:22',
                'updated_at' => '2024-10-27 09:43:22',
                'priority' => 0,
                'module_id' => 1,
                'slug' => 'butter',
                'featured' => 0,
            ),
            92 => 
            array (
                'id' => 110,
                'name' => 'Frozen Seafood',
                'image' => 'def.png',
                'parent_id' => 9,
                'position' => 1,
                'status' => 1,
                'created_at' => '2024-10-27 09:46:39',
                'updated_at' => '2024-10-27 09:46:39',
                'priority' => 0,
                'module_id' => 1,
                'slug' => 'frozen-seafood',
                'featured' => 0,
            ),
            93 => 
            array (
                'id' => 111,
                'name' => 'Bread',
                'image' => 'def.png',
                'parent_id' => 8,
                'position' => 1,
                'status' => 1,
                'created_at' => '2024-10-27 09:47:51',
                'updated_at' => '2024-10-27 09:47:51',
                'priority' => 0,
                'module_id' => 1,
                'slug' => 'bread',
                'featured' => 0,
            ),
            94 => 
            array (
                'id' => 112,
                'name' => 'Rolls',
                'image' => 'def.png',
                'parent_id' => 8,
                'position' => 1,
                'status' => 1,
                'created_at' => '2024-10-27 09:48:04',
                'updated_at' => '2024-10-27 09:48:04',
                'priority' => 0,
                'module_id' => 1,
                'slug' => 'rolls',
                'featured' => 0,
            ),
            95 => 
            array (
                'id' => 113,
                'name' => 'Cakes',
                'image' => 'def.png',
                'parent_id' => 8,
                'position' => 1,
                'status' => 1,
                'created_at' => '2024-10-27 09:48:14',
                'updated_at' => '2024-10-27 09:48:14',
                'priority' => 0,
                'module_id' => 1,
                'slug' => 'cakes',
                'featured' => 0,
            ),
            96 => 
            array (
                'id' => 114,
                'name' => 'Cookies',
                'image' => 'def.png',
                'parent_id' => 8,
                'position' => 1,
                'status' => 1,
                'created_at' => '2024-10-27 09:48:23',
                'updated_at' => '2024-10-27 09:48:23',
                'priority' => 0,
                'module_id' => 1,
                'slug' => 'cookies',
                'featured' => 0,
            ),
            97 => 
            array (
                'id' => 115,
                'name' => 'Water',
                'image' => 'def.png',
                'parent_id' => 7,
                'position' => 1,
                'status' => 1,
                'created_at' => '2024-10-27 09:48:59',
                'updated_at' => '2024-10-27 09:48:59',
                'priority' => 0,
                'module_id' => 1,
                'slug' => 'water',
                'featured' => 0,
            ),
            98 => 
            array (
                'id' => 116,
                'name' => 'Soft Drinks',
                'image' => 'def.png',
                'parent_id' => 7,
                'position' => 1,
                'status' => 1,
                'created_at' => '2024-10-27 09:49:07',
                'updated_at' => '2024-10-27 09:49:07',
                'priority' => 0,
                'module_id' => 1,
                'slug' => 'soft-drinks',
                'featured' => 0,
            ),
            99 => 
            array (
                'id' => 117,
                'name' => 'Juices',
                'image' => 'def.png',
                'parent_id' => 7,
                'position' => 1,
                'status' => 1,
                'created_at' => '2024-10-27 09:49:18',
                'updated_at' => '2024-10-27 09:49:18',
                'priority' => 0,
                'module_id' => 1,
                'slug' => 'juices',
                'featured' => 0,
            ),
            100 => 
            array (
                'id' => 118,
                'name' => 'Tea',
                'image' => 'def.png',
                'parent_id' => 7,
                'position' => 1,
                'status' => 1,
                'created_at' => '2024-10-27 09:49:26',
                'updated_at' => '2024-10-27 09:49:26',
                'priority' => 0,
                'module_id' => 1,
                'slug' => 'tea',
                'featured' => 0,
            ),
            101 => 
            array (
                'id' => 119,
                'name' => 'Coffee',
                'image' => 'def.png',
                'parent_id' => 7,
                'position' => 1,
                'status' => 1,
                'created_at' => '2024-10-27 09:49:34',
                'updated_at' => '2024-10-27 09:49:34',
                'priority' => 0,
                'module_id' => 1,
                'slug' => 'coffee',
                'featured' => 0,
            ),
            102 => 
            array (
                'id' => 120,
                'name' => 'Frozen Meals',
                'image' => 'def.png',
                'parent_id' => 6,
                'position' => 1,
                'status' => 1,
                'created_at' => '2024-10-27 09:50:15',
                'updated_at' => '2024-10-27 09:50:15',
                'priority' => 0,
                'module_id' => 1,
                'slug' => 'frozen-meals',
                'featured' => 0,
            ),
            103 => 
            array (
                'id' => 121,
                'name' => 'Vegetables',
                'image' => 'def.png',
                'parent_id' => 6,
                'position' => 1,
                'status' => 1,
                'created_at' => '2024-10-27 09:50:28',
                'updated_at' => '2024-10-27 09:50:28',
                'priority' => 0,
                'module_id' => 1,
                'slug' => 'vegetables-2',
                'featured' => 0,
            ),
            104 => 
            array (
                'id' => 122,
                'name' => 'Ice Cream',
                'image' => 'def.png',
                'parent_id' => 6,
                'position' => 1,
                'status' => 1,
                'created_at' => '2024-10-27 09:50:36',
                'updated_at' => '2024-10-27 09:50:36',
                'priority' => 0,
                'module_id' => 1,
                'slug' => 'ice-cream',
                'featured' => 0,
            ),
            105 => 
            array (
                'id' => 123,
                'name' => 'Sugar',
                'image' => 'def.png',
                'parent_id' => 5,
                'position' => 1,
                'status' => 1,
                'created_at' => '2024-10-27 09:52:24',
                'updated_at' => '2024-10-27 09:52:24',
                'priority' => 0,
                'module_id' => 1,
                'slug' => 'sugar',
                'featured' => 0,
            ),
            106 => 
            array (
                'id' => 124,
                'name' => 'Canned Goods',
                'image' => 'def.png',
                'parent_id' => 5,
                'position' => 1,
                'status' => 1,
                'created_at' => '2024-10-27 09:52:32',
                'updated_at' => '2024-10-27 09:52:32',
                'priority' => 0,
                'module_id' => 1,
                'slug' => 'canned-goods',
                'featured' => 0,
            ),
            107 => 
            array (
                'id' => 125,
                'name' => 'Chips',
                'image' => 'def.png',
                'parent_id' => 4,
                'position' => 1,
                'status' => 1,
                'created_at' => '2024-10-27 09:52:45',
                'updated_at' => '2024-10-27 09:52:45',
                'priority' => 0,
                'module_id' => 1,
                'slug' => 'chips',
                'featured' => 0,
            ),
            108 => 
            array (
                'id' => 126,
                'name' => 'Chocolates',
                'image' => 'def.png',
                'parent_id' => 4,
                'position' => 1,
                'status' => 1,
                'created_at' => '2024-10-27 09:52:55',
                'updated_at' => '2024-10-27 09:52:55',
                'priority' => 0,
                'module_id' => 1,
                'slug' => 'chocolates',
                'featured' => 0,
            ),
            109 => 
            array (
                'id' => 127,
                'name' => 'Biscuits',
                'image' => 'def.png',
                'parent_id' => 4,
                'position' => 1,
                'status' => 1,
                'created_at' => '2024-10-27 09:53:03',
                'updated_at' => '2024-10-27 09:53:03',
                'priority' => 0,
                'module_id' => 1,
                'slug' => 'biscuits',
                'featured' => 0,
            ),
            110 => 
            array (
                'id' => 128,
                'name' => 'Nuts',
                'image' => 'def.png',
                'parent_id' => 4,
                'position' => 1,
                'status' => 1,
                'created_at' => '2024-10-27 09:53:11',
                'updated_at' => '2024-10-27 09:53:11',
                'priority' => 0,
                'module_id' => 1,
                'slug' => 'nuts',
                'featured' => 0,
            ),
            111 => 
            array (
                'id' => 129,
                'name' => 'Spices',
                'image' => '2024-10-27-671db9d3a2ba4.png',
                'parent_id' => 0,
                'position' => 0,
                'status' => 1,
                'created_at' => '2024-10-27 09:56:03',
                'updated_at' => '2024-10-27 09:56:03',
                'priority' => 0,
                'module_id' => 1,
                'slug' => 'spices',
                'featured' => 0,
            ),
            112 => 
            array (
                'id' => 130,
                'name' => 'Sauces',
                'image' => 'def.png',
                'parent_id' => 129,
                'position' => 1,
                'status' => 1,
                'created_at' => '2024-10-27 09:56:33',
                'updated_at' => '2024-10-27 09:56:33',
                'priority' => 0,
                'module_id' => 1,
                'slug' => 'sauces',
                'featured' => 0,
            ),
            113 => 
            array (
                'id' => 131,
                'name' => 'Spices',
                'image' => 'def.png',
                'parent_id' => 129,
                'position' => 1,
                'status' => 1,
                'created_at' => '2024-10-27 09:56:42',
                'updated_at' => '2024-10-27 09:56:42',
                'priority' => 0,
                'module_id' => 1,
                'slug' => 'spices-2',
                'featured' => 0,
            ),
            114 => 
            array (
                'id' => 132,
                'name' => 'Seasonings',
                'image' => 'def.png',
                'parent_id' => 129,
                'position' => 1,
                'status' => 1,
                'created_at' => '2024-10-27 09:56:49',
                'updated_at' => '2024-10-27 09:56:49',
                'priority' => 0,
                'module_id' => 1,
                'slug' => 'seasonings',
                'featured' => 0,
            ),
            115 => 
            array (
                'id' => 133,
                'name' => 'Shampoo',
                'image' => 'def.png',
                'parent_id' => 2,
                'position' => 1,
                'status' => 1,
                'created_at' => '2024-10-27 09:57:09',
                'updated_at' => '2024-10-27 09:57:09',
                'priority' => 0,
                'module_id' => 1,
                'slug' => 'shampoo',
                'featured' => 0,
            ),
            116 => 
            array (
                'id' => 134,
                'name' => 'Soap',
                'image' => 'def.png',
                'parent_id' => 2,
                'position' => 1,
                'status' => 1,
                'created_at' => '2024-10-27 09:57:18',
                'updated_at' => '2024-10-27 09:57:18',
                'priority' => 0,
                'module_id' => 1,
                'slug' => 'soap',
                'featured' => 0,
            ),
            117 => 
            array (
                'id' => 135,
                'name' => 'Skincare',
                'image' => 'def.png',
                'parent_id' => 2,
                'position' => 1,
                'status' => 1,
                'created_at' => '2024-10-27 09:57:28',
                'updated_at' => '2024-10-27 09:57:28',
                'priority' => 0,
                'module_id' => 1,
                'slug' => 'skincare',
                'featured' => 0,
            ),
            118 => 
            array (
                'id' => 136,
                'name' => 'Oral Care',
                'image' => 'def.png',
                'parent_id' => 2,
                'position' => 1,
                'status' => 1,
                'created_at' => '2024-10-27 09:57:36',
                'updated_at' => '2024-10-27 09:57:36',
                'priority' => 0,
                'module_id' => 1,
                'slug' => 'oral-care',
                'featured' => 0,
            ),
            119 => 
            array (
                'id' => 137,
                'name' => 'Cleaning',
                'image' => 'def.png',
                'parent_id' => 101,
                'position' => 1,
                'status' => 1,
                'created_at' => '2024-10-27 09:59:47',
                'updated_at' => '2024-10-27 09:59:47',
                'priority' => 0,
                'module_id' => 1,
                'slug' => 'cleaning',
                'featured' => 0,
            ),
            120 => 
            array (
                'id' => 138,
                'name' => 'Detergents',
                'image' => 'def.png',
                'parent_id' => 101,
                'position' => 1,
                'status' => 1,
                'created_at' => '2024-10-27 09:59:55',
                'updated_at' => '2024-10-27 09:59:55',
                'priority' => 0,
                'module_id' => 1,
                'slug' => 'detergents',
                'featured' => 0,
            ),
            121 => 
            array (
                'id' => 139,
                'name' => 'Paper Product',
                'image' => 'def.png',
                'parent_id' => 101,
                'position' => 1,
                'status' => 1,
                'created_at' => '2024-10-27 10:00:11',
                'updated_at' => '2024-10-27 10:00:11',
                'priority' => 0,
                'module_id' => 1,
                'slug' => 'paper-product',
                'featured' => 0,
            ),
            122 => 
            array (
                'id' => 140,
                'name' => 'Oils',
                'image' => 'def.png',
                'parent_id' => 102,
                'position' => 1,
                'status' => 1,
                'created_at' => '2024-10-27 10:00:21',
                'updated_at' => '2024-10-27 10:00:21',
                'priority' => 0,
                'module_id' => 1,
                'slug' => 'oils',
                'featured' => 0,
            ),
            123 => 
            array (
                'id' => 141,
                'name' => 'Vinegar',
                'image' => 'def.png',
                'parent_id' => 102,
                'position' => 1,
                'status' => 1,
                'created_at' => '2024-10-27 10:00:28',
                'updated_at' => '2024-10-27 10:00:28',
                'priority' => 0,
                'module_id' => 1,
                'slug' => 'vinegar',
                'featured' => 0,
            ),
            124 => 
            array (
                'id' => 142,
                'name' => 'Ghee',
                'image' => 'def.png',
                'parent_id' => 102,
                'position' => 1,
                'status' => 1,
                'created_at' => '2024-10-27 10:00:35',
                'updated_at' => '2024-10-27 10:00:35',
                'priority' => 0,
                'module_id' => 1,
                'slug' => 'ghee',
                'featured' => 0,
            ),
            125 => 
            array (
                'id' => 143,
                'name' => 'Cooking Sauces',
                'image' => 'def.png',
                'parent_id' => 102,
                'position' => 1,
                'status' => 1,
                'created_at' => '2024-10-27 10:00:42',
                'updated_at' => '2024-10-27 10:00:42',
                'priority' => 0,
                'module_id' => 1,
                'slug' => 'cooking-sauces',
                'featured' => 0,
            ),
            126 => 
            array (
                'id' => 144,
                'name' => 'Clothing',
                'image' => 'def.png',
                'parent_id' => 38,
                'position' => 1,
                'status' => 1,
                'created_at' => '2024-10-28 17:25:15',
                'updated_at' => '2024-10-28 17:25:15',
                'priority' => 0,
                'module_id' => 3,
                'slug' => 'clothing',
                'featured' => 0,
            ),
            127 => 
            array (
                'id' => 145,
                'name' => 'Footwear',
                'image' => 'def.png',
                'parent_id' => 38,
                'position' => 1,
                'status' => 1,
                'created_at' => '2024-10-28 17:25:22',
                'updated_at' => '2024-10-28 17:25:22',
                'priority' => 0,
                'module_id' => 3,
                'slug' => 'footwear',
                'featured' => 0,
            ),
            128 => 
            array (
                'id' => 146,
                'name' => 'Women\'s bag',
                'image' => 'def.png',
                'parent_id' => 38,
                'position' => 1,
                'status' => 1,
                'created_at' => '2024-10-28 17:25:30',
                'updated_at' => '2024-10-28 17:25:30',
                'priority' => 0,
                'module_id' => 3,
                'slug' => 'womens-bag',
                'featured' => 0,
            ),
            129 => 
            array (
                'id' => 147,
                'name' => 'Boy\'s Clothing',
                'image' => 'def.png',
                'parent_id' => 37,
                'position' => 1,
                'status' => 1,
                'created_at' => '2024-10-28 17:25:40',
                'updated_at' => '2024-10-28 17:25:40',
                'priority' => 0,
                'module_id' => 3,
                'slug' => 'boys-clothing',
                'featured' => 0,
            ),
            130 => 
            array (
                'id' => 148,
                'name' => 'Girl\'s Clothing',
                'image' => 'def.png',
                'parent_id' => 37,
                'position' => 1,
                'status' => 1,
                'created_at' => '2024-10-28 17:25:50',
                'updated_at' => '2024-10-28 17:25:50',
                'priority' => 0,
                'module_id' => 3,
                'slug' => 'girls-clothing',
                'featured' => 0,
            ),
            131 => 
            array (
                'id' => 149,
                'name' => 'OTC Medicine',
                'image' => '2024-11-05-67299f356d5ab.png',
                'parent_id' => 0,
                'position' => 0,
                'status' => 1,
                'created_at' => '2024-11-05 09:45:18',
                'updated_at' => '2024-11-05 10:29:41',
                'priority' => 0,
                'module_id' => 2,
                'slug' => 'prescriptions',
                'featured' => 0,
            ),
            132 => 
            array (
                'id' => 150,
                'name' => 'Prescriptions',
                'image' => '2024-11-05-672994fce8507.png',
                'parent_id' => 0,
                'position' => 0,
                'status' => 0,
                'created_at' => '2024-11-05 09:46:04',
                'updated_at' => '2024-11-05 09:50:49',
                'priority' => 0,
                'module_id' => 2,
                'slug' => 'prescriptions-2',
                'featured' => 0,
            ),
        ));
        
        
    }
}