<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class CouponsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('coupons')->delete();
        
        \DB::table('coupons')->insert(array (
            0 => 
            array (
                'id' => 1,
            'title' => 'Super offer (30%)',
                'code' => '10',
                'start_date' => '2022-03-23',
                'expire_date' => '2022-03-24',
                'min_purchase' => '0.00',
                'max_discount' => '0.00',
                'discount' => '30.00',
                'discount_type' => 'percent',
                'coupon_type' => 'store_wise',
                'limit' => 2,
                'status' => 1,
                'created_at' => '2022-03-23 15:31:25',
                'updated_at' => '2025-10-09 17:22:10',
                'data' => '["1"]',
                'total_uses' => 0,
                'module_id' => 1,
                'created_by' => 'admin',
                'customer_id' => '["all"]',
                'slug' => NULL,
                'store_id' => NULL,
            ),
            1 => 
            array (
                'id' => 2,
                'title' => 'Festival Offer',
                'code' => 'fest',
                'start_date' => '2022-10-01',
                'expire_date' => '2026-10-29',
                'min_purchase' => '100.00',
                'max_discount' => '300.00',
                'discount' => '25.00',
                'discount_type' => 'percent',
                'coupon_type' => 'default',
                'limit' => 1,
                'status' => 1,
                'created_at' => '2022-09-29 12:19:17',
                'updated_at' => '2025-10-09 17:23:03',
                'data' => '""',
                'total_uses' => 0,
                'module_id' => 1,
                'created_by' => 'admin',
                'customer_id' => '["all"]',
                'slug' => NULL,
                'store_id' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'title' => 'Bogo Offer',
                'code' => 'bogo',
                'start_date' => '2022-10-10',
                'expire_date' => '2025-01-22',
                'min_purchase' => '100.00',
                'max_discount' => '10000.00',
                'discount' => '50.00',
                'discount_type' => 'percent',
                'coupon_type' => 'zone_wise',
                'limit' => 3,
                'status' => 1,
                'created_at' => '2022-09-29 12:20:39',
                'updated_at' => '2022-09-29 12:20:39',
                'data' => '["1"]',
                'total_uses' => 0,
                'module_id' => 4,
                'created_by' => 'admin',
                'customer_id' => '["all"]',
                'slug' => NULL,
                'store_id' => NULL,
            ),
            3 => 
            array (
                'id' => 4,
                'title' => 'Free delivery',
                'code' => 'freedv',
                'start_date' => '2022-10-05',
                'expire_date' => '2023-11-30',
                'min_purchase' => '75.00',
                'max_discount' => '0.00',
                'discount' => '0.00',
                'discount_type' => '',
                'coupon_type' => 'free_delivery',
                'limit' => 10,
                'status' => 1,
                'created_at' => '2022-09-29 16:04:00',
                'updated_at' => '2022-09-29 16:04:00',
                'data' => '""',
                'total_uses' => 0,
                'module_id' => 2,
                'created_by' => 'admin',
                'customer_id' => '["all"]',
                'slug' => NULL,
                'store_id' => NULL,
            ),
            4 => 
            array (
                'id' => 5,
                'title' => 'Welcome offer',
                'code' => 'welcome',
                'start_date' => '2022-09-30',
                'expire_date' => '2027-12-30',
                'min_purchase' => '100.00',
                'max_discount' => '1000.00',
                'discount' => '50.00',
                'discount_type' => 'percent',
                'coupon_type' => 'first_order',
                'limit' => 1,
                'status' => 1,
                'created_at' => '2022-09-29 16:05:59',
                'updated_at' => '2022-09-29 16:05:59',
                'data' => '""',
                'total_uses' => 0,
                'module_id' => 3,
                'created_by' => 'admin',
                'customer_id' => '["all"]',
                'slug' => NULL,
                'store_id' => NULL,
            ),
            5 => 
            array (
                'id' => 6,
                'title' => 'Save 15% on Your First Ride – Book Now!',
                'code' => 'FirstTrip15',
                'start_date' => '2025-02-05',
                'expire_date' => '2029-08-30',
                'min_purchase' => '100.00',
                'max_discount' => '1000.00',
                'discount' => '15.00',
                'discount_type' => 'percent',
                'coupon_type' => 'first_order',
                'limit' => 1,
                'status' => 1,
                'created_at' => '2025-02-05 16:00:03',
                'updated_at' => '2025-02-06 17:18:05',
                'data' => '""',
                'total_uses' => 5,
                'module_id' => 6,
                'created_by' => 'admin',
                'customer_id' => '["all"]',
                'slug' => NULL,
                'store_id' => NULL,
            ),
            6 => 
            array (
                'id' => 7,
                'title' => 'Get 10% Off on Your Next Taxi Rental!',
                'code' => 'Trip10',
                'start_date' => '2025-02-05',
                'expire_date' => '2029-12-21',
                'min_purchase' => '100.00',
                'max_discount' => '1000.00',
                'discount' => '10.00',
                'discount_type' => 'percent',
                'coupon_type' => 'default',
                'limit' => 2,
                'status' => 1,
                'created_at' => '2025-02-05 16:03:43',
                'updated_at' => '2025-02-08 12:54:40',
                'data' => '""',
                'total_uses' => 1,
                'module_id' => 6,
                'created_by' => 'admin',
                'customer_id' => '["all"]',
                'slug' => NULL,
                'store_id' => NULL,
            ),
            7 => 
            array (
                'id' => 8,
                'title' => 'Limited Time Offer: 20% Off on All Rentals!',
                'code' => 'Limited20',
                'start_date' => '2025-02-05',
                'expire_date' => '2029-12-05',
                'min_purchase' => '100.00',
                'max_discount' => '1000.00',
                'discount' => '20.00',
                'discount_type' => 'percent',
                'coupon_type' => 'default',
                'limit' => 5,
                'status' => 1,
                'created_at' => '2025-02-05 16:06:01',
                'updated_at' => '2025-02-06 16:26:26',
                'data' => '""',
                'total_uses' => 1,
                'module_id' => 6,
                'created_by' => 'admin',
                'customer_id' => '["all"]',
                'slug' => NULL,
                'store_id' => NULL,
            ),
            8 => 
            array (
                'id' => 9,
                'title' => 'Weekend Special: 30% Off All Bookings!',
                'code' => 'Weekend',
                'start_date' => '2025-02-05',
                'expire_date' => '2029-12-27',
                'min_purchase' => '100.00',
                'max_discount' => '0.00',
                'discount' => '30.00',
                'discount_type' => 'amount',
                'coupon_type' => 'default',
                'limit' => 1,
                'status' => 1,
                'created_at' => '2025-02-05 16:07:50',
                'updated_at' => '2025-09-16 17:39:23',
                'data' => '""',
                'total_uses' => 2,
                'module_id' => 6,
                'created_by' => 'admin',
                'customer_id' => '["all"]',
                'slug' => NULL,
                'store_id' => NULL,
            ),
        ));
        
        
    }
}