<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class ExpensesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('expenses')->delete();
        
        \DB::table('expenses')->insert(array (
            0 => 
            array (
                'id' => 1,
                'type' => 'add_fund_bonus',
                'amount' => '19.000',
                'order_id' => NULL,
                'created_at' => '2023-08-22 11:22:33',
                'updated_at' => '2023-08-22 11:22:33',
                'description' => '',
                'created_by' => 'admin',
                'store_id' => NULL,
                'delivery_man_id' => NULL,
                'user_id' => 5,
                'trip_id' => NULL,
            ),
            1 => 
            array (
                'id' => 2,
                'type' => 'add_fund_bonus',
                'amount' => '20.000',
                'order_id' => NULL,
                'created_at' => '2023-08-22 11:50:11',
                'updated_at' => '2023-08-22 11:50:11',
                'description' => '',
                'created_by' => 'admin',
                'store_id' => NULL,
                'delivery_man_id' => NULL,
                'user_id' => 5,
                'trip_id' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'type' => 'discount_on_product',
                'amount' => '40.500',
                'order_id' => 100089,
                'created_at' => '2023-11-27 12:35:04',
                'updated_at' => '2023-11-27 12:35:04',
                'description' => '',
                'created_by' => 'vendor',
                'store_id' => 2,
                'delivery_man_id' => NULL,
                'user_id' => NULL,
                'trip_id' => NULL,
            ),
            3 => 
            array (
                'id' => 4,
                'type' => 'discount_on_product',
                'amount' => '4.500',
                'order_id' => 100089,
                'created_at' => '2023-11-27 12:35:04',
                'updated_at' => '2023-11-27 12:35:04',
                'description' => '',
                'created_by' => 'admin',
                'store_id' => NULL,
                'delivery_man_id' => NULL,
                'user_id' => NULL,
                'trip_id' => NULL,
            ),
            4 => 
            array (
                'id' => 5,
                'type' => 'add_fund_bonus',
                'amount' => '300.000',
                'order_id' => NULL,
                'created_at' => '2024-01-02 16:52:29',
                'updated_at' => '2024-01-02 16:52:29',
                'description' => '',
                'created_by' => 'admin',
                'store_id' => NULL,
                'delivery_man_id' => NULL,
                'user_id' => 8,
                'trip_id' => NULL,
            ),
            5 => 
            array (
                'id' => 6,
                'type' => 'discount_on_product',
                'amount' => '19.440',
                'order_id' => 100099,
                'created_at' => '2024-01-02 16:59:09',
                'updated_at' => '2024-01-02 16:59:09',
                'description' => '',
                'created_by' => 'vendor',
                'store_id' => 11,
                'delivery_man_id' => NULL,
                'user_id' => NULL,
                'trip_id' => NULL,
            ),
            6 => 
            array (
                'id' => 7,
                'type' => 'discount_on_product',
                'amount' => '2.160',
                'order_id' => 100099,
                'created_at' => '2024-01-02 16:59:09',
                'updated_at' => '2024-01-02 16:59:09',
                'description' => '',
                'created_by' => 'admin',
                'store_id' => NULL,
                'delivery_man_id' => NULL,
                'user_id' => NULL,
                'trip_id' => NULL,
            ),
            7 => 
            array (
                'id' => 8,
                'type' => 'free_delivery',
                'amount' => '500.000',
                'order_id' => 100100,
                'created_at' => '2024-01-02 17:24:06',
                'updated_at' => '2024-01-02 17:24:06',
                'description' => '',
                'created_by' => 'admin',
                'store_id' => NULL,
                'delivery_man_id' => NULL,
                'user_id' => NULL,
                'trip_id' => NULL,
            ),
            8 => 
            array (
                'id' => 9,
                'type' => 'discount_on_product',
                'amount' => '90.000',
                'order_id' => 100100,
                'created_at' => '2024-01-02 17:24:06',
                'updated_at' => '2024-01-02 17:24:06',
                'description' => '',
                'created_by' => 'vendor',
                'store_id' => 4,
                'delivery_man_id' => NULL,
                'user_id' => NULL,
                'trip_id' => NULL,
            ),
            9 => 
            array (
                'id' => 10,
                'type' => 'discount_on_product',
                'amount' => '10.000',
                'order_id' => 100100,
                'created_at' => '2024-01-02 17:24:06',
                'updated_at' => '2024-01-02 17:24:06',
                'description' => '',
                'created_by' => 'admin',
                'store_id' => NULL,
                'delivery_man_id' => NULL,
                'user_id' => NULL,
                'trip_id' => NULL,
            ),
            10 => 
            array (
                'id' => 11,
                'type' => 'CashBack',
                'amount' => '737.900',
                'order_id' => NULL,
                'created_at' => '2025-02-06 16:40:51',
                'updated_at' => '2025-02-06 16:40:51',
                'description' => '',
                'created_by' => 'admin',
                'store_id' => NULL,
                'delivery_man_id' => NULL,
                'user_id' => NULL,
                'trip_id' => 100008,
            ),
            11 => 
            array (
                'id' => 12,
                'type' => 'discount_on_trip',
                'amount' => '60.000',
                'order_id' => NULL,
                'created_at' => '2025-02-06 16:40:52',
                'updated_at' => '2025-02-06 16:40:52',
                'description' => '',
                'created_by' => 'vendor',
                'store_id' => 66,
                'delivery_man_id' => NULL,
                'user_id' => NULL,
                'trip_id' => 100008,
            ),
            12 => 
            array (
                'id' => 13,
                'type' => 'CashBack',
                'amount' => '10.000',
                'order_id' => NULL,
                'created_at' => '2025-02-06 16:57:59',
                'updated_at' => '2025-02-06 16:57:59',
                'description' => '',
                'created_by' => 'admin',
                'store_id' => NULL,
                'delivery_man_id' => NULL,
                'user_id' => NULL,
                'trip_id' => 100024,
            ),
            13 => 
            array (
                'id' => 14,
                'type' => 'discount_on_trip',
                'amount' => '337.500',
                'order_id' => NULL,
                'created_at' => '2025-02-06 16:58:00',
                'updated_at' => '2025-02-06 16:58:00',
                'description' => '',
                'created_by' => 'vendor',
                'store_id' => 64,
                'delivery_man_id' => NULL,
                'user_id' => NULL,
                'trip_id' => 100024,
            ),
            14 => 
            array (
                'id' => 15,
                'type' => 'discount_on_trip',
                'amount' => '37.500',
                'order_id' => NULL,
                'created_at' => '2025-02-06 16:58:00',
                'updated_at' => '2025-02-06 16:58:00',
                'description' => '',
                'created_by' => 'admin',
                'store_id' => NULL,
                'delivery_man_id' => NULL,
                'user_id' => NULL,
                'trip_id' => 100024,
            ),
            15 => 
            array (
                'id' => 16,
                'type' => 'coupon_discount',
                'amount' => '500.000',
                'order_id' => NULL,
                'created_at' => '2025-02-06 16:58:19',
                'updated_at' => '2025-02-06 16:58:19',
                'description' => '',
                'created_by' => 'admin',
                'store_id' => NULL,
                'delivery_man_id' => NULL,
                'user_id' => NULL,
                'trip_id' => 100015,
            ),
            16 => 
            array (
                'id' => 17,
                'type' => 'CashBack',
                'amount' => '20.000',
                'order_id' => NULL,
                'created_at' => '2025-02-06 16:58:19',
                'updated_at' => '2025-02-06 16:58:19',
                'description' => '',
                'created_by' => 'admin',
                'store_id' => NULL,
                'delivery_man_id' => NULL,
                'user_id' => NULL,
                'trip_id' => 100015,
            ),
            17 => 
            array (
                'id' => 18,
                'type' => 'discount_on_trip',
                'amount' => '4892.562',
                'order_id' => NULL,
                'created_at' => '2025-02-06 16:58:19',
                'updated_at' => '2025-02-06 16:58:19',
                'description' => '',
                'created_by' => 'vendor',
                'store_id' => 64,
                'delivery_man_id' => NULL,
                'user_id' => NULL,
                'trip_id' => 100015,
            ),
            18 => 
            array (
                'id' => 19,
                'type' => 'discount_on_trip',
                'amount' => '543.618',
                'order_id' => NULL,
                'created_at' => '2025-02-06 16:58:19',
                'updated_at' => '2025-02-06 16:58:19',
                'description' => '',
                'created_by' => 'admin',
                'store_id' => NULL,
                'delivery_man_id' => NULL,
                'user_id' => NULL,
                'trip_id' => 100015,
            ),
            19 => 
            array (
                'id' => 20,
                'type' => 'CashBack',
                'amount' => '10.000',
                'order_id' => NULL,
                'created_at' => '2025-02-06 17:04:22',
                'updated_at' => '2025-02-06 17:04:22',
                'description' => '',
                'created_by' => 'admin',
                'store_id' => NULL,
                'delivery_man_id' => NULL,
                'user_id' => NULL,
                'trip_id' => 100025,
            ),
            20 => 
            array (
                'id' => 21,
                'type' => 'discount_on_trip',
                'amount' => '50.000',
                'order_id' => NULL,
                'created_at' => '2025-02-06 17:04:22',
                'updated_at' => '2025-02-06 17:04:22',
                'description' => '',
                'created_by' => 'vendor',
                'store_id' => 66,
                'delivery_man_id' => NULL,
                'user_id' => NULL,
                'trip_id' => 100025,
            ),
            21 => 
            array (
                'id' => 22,
                'type' => 'coupon_discount',
                'amount' => '537.986',
                'order_id' => NULL,
                'created_at' => '2025-02-06 17:19:00',
                'updated_at' => '2025-02-06 17:19:00',
                'description' => '',
                'created_by' => 'admin',
                'store_id' => NULL,
                'delivery_man_id' => NULL,
                'user_id' => NULL,
                'trip_id' => 100030,
            ),
            22 => 
            array (
                'id' => 23,
                'type' => 'CashBack',
                'amount' => '305.860',
                'order_id' => NULL,
                'created_at' => '2025-02-06 17:19:00',
                'updated_at' => '2025-02-06 17:19:00',
                'description' => '',
                'created_by' => 'admin',
                'store_id' => NULL,
                'delivery_man_id' => NULL,
                'user_id' => NULL,
                'trip_id' => 100030,
            ),
            23 => 
            array (
                'id' => 24,
                'type' => 'discount_on_trip',
                'amount' => '3227.922',
                'order_id' => NULL,
                'created_at' => '2025-02-06 17:19:00',
                'updated_at' => '2025-02-06 17:19:00',
                'description' => '',
                'created_by' => 'vendor',
                'store_id' => 64,
                'delivery_man_id' => NULL,
                'user_id' => NULL,
                'trip_id' => 100030,
            ),
            24 => 
            array (
                'id' => 25,
                'type' => 'discount_on_trip',
                'amount' => '358.658',
                'order_id' => NULL,
                'created_at' => '2025-02-06 17:19:00',
                'updated_at' => '2025-02-06 17:19:00',
                'description' => '',
                'created_by' => 'admin',
                'store_id' => NULL,
                'delivery_man_id' => NULL,
                'user_id' => NULL,
                'trip_id' => 100030,
            ),
            25 => 
            array (
                'id' => 26,
                'type' => 'CashBack',
                'amount' => '20.000',
                'order_id' => NULL,
                'created_at' => '2025-02-06 17:23:07',
                'updated_at' => '2025-02-06 17:23:07',
                'description' => '',
                'created_by' => 'admin',
                'store_id' => NULL,
                'delivery_man_id' => NULL,
                'user_id' => NULL,
                'trip_id' => 100031,
            ),
            26 => 
            array (
                'id' => 27,
                'type' => 'discount_on_trip',
                'amount' => '17.064',
                'order_id' => NULL,
                'created_at' => '2025-02-06 17:23:07',
                'updated_at' => '2025-02-06 17:23:07',
                'description' => '',
                'created_by' => 'vendor',
                'store_id' => 60,
                'delivery_man_id' => NULL,
                'user_id' => NULL,
                'trip_id' => 100031,
            ),
            27 => 
            array (
                'id' => 28,
                'type' => 'discount_on_trip',
                'amount' => '1.896',
                'order_id' => NULL,
                'created_at' => '2025-02-06 17:23:07',
                'updated_at' => '2025-02-06 17:23:07',
                'description' => '',
                'created_by' => 'admin',
                'store_id' => NULL,
                'delivery_man_id' => NULL,
                'user_id' => NULL,
                'trip_id' => 100031,
            ),
            28 => 
            array (
                'id' => 29,
                'type' => 'CashBack',
                'amount' => '788.000',
                'order_id' => NULL,
                'created_at' => '2025-02-06 17:38:57',
                'updated_at' => '2025-02-06 17:38:57',
                'description' => '',
                'created_by' => 'admin',
                'store_id' => NULL,
                'delivery_man_id' => NULL,
                'user_id' => NULL,
                'trip_id' => 100032,
            ),
            29 => 
            array (
                'id' => 30,
                'type' => 'discount_on_trip',
                'amount' => '90.000',
                'order_id' => NULL,
                'created_at' => '2025-02-06 17:38:58',
                'updated_at' => '2025-02-06 17:38:58',
                'description' => '',
                'created_by' => 'vendor',
                'store_id' => 66,
                'delivery_man_id' => NULL,
                'user_id' => NULL,
                'trip_id' => 100032,
            ),
            30 => 
            array (
                'id' => 31,
                'type' => 'CashBack',
                'amount' => '364.670',
                'order_id' => NULL,
                'created_at' => '2025-02-06 17:54:38',
                'updated_at' => '2025-02-06 17:54:38',
                'description' => '',
                'created_by' => 'admin',
                'store_id' => NULL,
                'delivery_man_id' => NULL,
                'user_id' => NULL,
                'trip_id' => 100034,
            ),
            31 => 
            array (
                'id' => 32,
                'type' => 'discount_on_trip',
                'amount' => '3273.057',
                'order_id' => NULL,
                'created_at' => '2025-02-06 17:54:39',
                'updated_at' => '2025-02-06 17:54:39',
                'description' => '',
                'created_by' => 'vendor',
                'store_id' => 64,
                'delivery_man_id' => NULL,
                'user_id' => NULL,
                'trip_id' => 100034,
            ),
            32 => 
            array (
                'id' => 33,
                'type' => 'discount_on_trip',
                'amount' => '363.673',
                'order_id' => NULL,
                'created_at' => '2025-02-06 17:54:39',
                'updated_at' => '2025-02-06 17:54:39',
                'description' => '',
                'created_by' => 'admin',
                'store_id' => NULL,
                'delivery_man_id' => NULL,
                'user_id' => NULL,
                'trip_id' => 100034,
            ),
            33 => 
            array (
                'id' => 34,
                'type' => 'CashBack',
                'amount' => '100.000',
                'order_id' => NULL,
                'created_at' => '2025-02-08 12:49:31',
                'updated_at' => '2025-02-08 12:49:31',
                'description' => '',
                'created_by' => 'admin',
                'store_id' => NULL,
                'delivery_man_id' => NULL,
                'user_id' => NULL,
                'trip_id' => 100037,
            ),
            34 => 
            array (
                'id' => 35,
                'type' => 'discount_on_trip',
                'amount' => '25.000',
                'order_id' => NULL,
                'created_at' => '2025-02-08 12:49:31',
                'updated_at' => '2025-02-08 12:49:31',
                'description' => '',
                'created_by' => 'vendor',
                'store_id' => 67,
                'delivery_man_id' => NULL,
                'user_id' => NULL,
                'trip_id' => 100037,
            ),
            35 => 
            array (
                'id' => 36,
                'type' => 'CashBack',
                'amount' => '55.050',
                'order_id' => 100102,
                'created_at' => '2025-04-20 18:14:43',
                'updated_at' => '2025-04-20 18:14:43',
                'description' => '',
                'created_by' => 'admin',
                'store_id' => NULL,
                'delivery_man_id' => NULL,
                'user_id' => NULL,
                'trip_id' => NULL,
            ),
            36 => 
            array (
                'id' => 37,
                'type' => 'discount_on_product',
                'amount' => '4.500',
                'order_id' => 100102,
                'created_at' => '2025-04-20 18:14:43',
                'updated_at' => '2025-04-20 18:14:43',
                'description' => '',
                'created_by' => 'admin',
                'store_id' => NULL,
                'delivery_man_id' => NULL,
                'user_id' => NULL,
                'trip_id' => NULL,
            ),
            37 => 
            array (
                'id' => 38,
                'type' => 'CashBack',
                'amount' => '80.500',
                'order_id' => 100103,
                'created_at' => '2025-04-20 18:15:14',
                'updated_at' => '2025-04-20 18:15:14',
                'description' => '',
                'created_by' => 'admin',
                'store_id' => NULL,
                'delivery_man_id' => NULL,
                'user_id' => NULL,
                'trip_id' => NULL,
            ),
            38 => 
            array (
                'id' => 39,
                'type' => 'CashBack',
                'amount' => '67.830',
                'order_id' => 100104,
                'created_at' => '2025-04-20 18:16:07',
                'updated_at' => '2025-04-20 18:16:07',
                'description' => '',
                'created_by' => 'admin',
                'store_id' => NULL,
                'delivery_man_id' => NULL,
                'user_id' => NULL,
                'trip_id' => NULL,
            ),
            39 => 
            array (
                'id' => 40,
                'type' => 'discount_on_product',
                'amount' => '0.621',
                'order_id' => 100104,
                'created_at' => '2025-04-20 18:16:07',
                'updated_at' => '2025-04-20 18:16:07',
                'description' => '',
                'created_by' => 'vendor',
                'store_id' => 1,
                'delivery_man_id' => NULL,
                'user_id' => NULL,
                'trip_id' => NULL,
            ),
            40 => 
            array (
                'id' => 41,
                'type' => 'discount_on_product',
                'amount' => '0.069',
                'order_id' => 100104,
                'created_at' => '2025-04-20 18:16:07',
                'updated_at' => '2025-04-20 18:16:07',
                'description' => '',
                'created_by' => 'admin',
                'store_id' => NULL,
                'delivery_man_id' => NULL,
                'user_id' => NULL,
                'trip_id' => NULL,
            ),
            41 => 
            array (
                'id' => 42,
                'type' => 'CashBack',
                'amount' => '96.250',
                'order_id' => 100105,
                'created_at' => '2025-04-20 18:18:29',
                'updated_at' => '2025-04-20 18:18:29',
                'description' => '',
                'created_by' => 'admin',
                'store_id' => NULL,
                'delivery_man_id' => NULL,
                'user_id' => NULL,
                'trip_id' => NULL,
            ),
            42 => 
            array (
                'id' => 43,
                'type' => 'discount_on_product',
                'amount' => '117.500',
                'order_id' => 100105,
                'created_at' => '2025-04-20 18:18:29',
                'updated_at' => '2025-04-20 18:18:29',
                'description' => '',
                'created_by' => 'admin',
                'store_id' => NULL,
                'delivery_man_id' => NULL,
                'user_id' => NULL,
                'trip_id' => NULL,
            ),
            43 => 
            array (
                'id' => 44,
                'type' => 'CashBack',
                'amount' => '121.880',
                'order_id' => 100106,
                'created_at' => '2025-04-20 18:19:22',
                'updated_at' => '2025-04-20 18:19:22',
                'description' => '',
                'created_by' => 'admin',
                'store_id' => NULL,
                'delivery_man_id' => NULL,
                'user_id' => NULL,
                'trip_id' => NULL,
            ),
            44 => 
            array (
                'id' => 45,
                'type' => 'discount_on_product',
                'amount' => '116.250',
                'order_id' => 100106,
                'created_at' => '2025-04-20 18:19:23',
                'updated_at' => '2025-04-20 18:19:23',
                'description' => '',
                'created_by' => 'admin',
                'store_id' => NULL,
                'delivery_man_id' => NULL,
                'user_id' => NULL,
                'trip_id' => NULL,
            ),
            45 => 
            array (
                'id' => 46,
                'type' => 'discount_on_product',
                'amount' => '504.000',
                'order_id' => 100101,
                'created_at' => '2025-09-08 06:00:42',
                'updated_at' => '2025-09-08 06:00:42',
                'description' => '',
                'created_by' => 'vendor',
                'store_id' => 38,
                'delivery_man_id' => NULL,
                'user_id' => NULL,
                'trip_id' => NULL,
            ),
            46 => 
            array (
                'id' => 47,
                'type' => 'discount_on_product',
                'amount' => '56.000',
                'order_id' => 100101,
                'created_at' => '2025-09-08 06:00:42',
                'updated_at' => '2025-09-08 06:00:42',
                'description' => '',
                'created_by' => 'admin',
                'store_id' => NULL,
                'delivery_man_id' => NULL,
                'user_id' => NULL,
                'trip_id' => NULL,
            ),
            47 => 
            array (
                'id' => 48,
                'type' => 'add_fund_bonus',
                'amount' => '200.000',
                'order_id' => NULL,
                'created_at' => '2025-09-15 17:29:54',
                'updated_at' => '2025-09-15 17:29:54',
                'description' => '',
                'created_by' => 'admin',
                'store_id' => NULL,
                'delivery_man_id' => NULL,
                'user_id' => 33,
                'trip_id' => NULL,
            ),
            48 => 
            array (
                'id' => 49,
                'type' => 'add_fund_bonus',
                'amount' => '10.000',
                'order_id' => NULL,
                'created_at' => '2025-10-05 11:41:50',
                'updated_at' => '2025-10-05 11:41:50',
                'description' => '',
                'created_by' => 'admin',
                'store_id' => NULL,
                'delivery_man_id' => NULL,
                'user_id' => 32,
                'trip_id' => NULL,
            ),
            49 => 
            array (
                'id' => 50,
                'type' => 'CashBack',
                'amount' => '100.000',
                'order_id' => 100114,
                'created_at' => '2025-10-12 10:17:31',
                'updated_at' => '2025-10-12 10:17:31',
                'description' => '',
                'created_by' => 'admin',
                'store_id' => NULL,
                'delivery_man_id' => NULL,
                'user_id' => NULL,
                'trip_id' => NULL,
            ),
            50 => 
            array (
                'id' => 51,
                'type' => 'discount_on_product',
                'amount' => '374.250',
                'order_id' => 100114,
                'created_at' => '2025-10-12 10:17:32',
                'updated_at' => '2025-10-12 10:17:32',
                'description' => '',
                'created_by' => 'admin',
                'store_id' => NULL,
                'delivery_man_id' => NULL,
                'user_id' => NULL,
                'trip_id' => NULL,
            ),
            51 => 
            array (
                'id' => 52,
                'type' => 'CashBack',
                'amount' => '65.870',
                'order_id' => 100116,
                'created_at' => '2025-10-12 15:59:10',
                'updated_at' => '2025-10-12 15:59:10',
                'description' => '',
                'created_by' => 'admin',
                'store_id' => NULL,
                'delivery_man_id' => NULL,
                'user_id' => NULL,
                'trip_id' => NULL,
            ),
            52 => 
            array (
                'id' => 53,
                'type' => 'discount_on_product',
                'amount' => '2.070',
                'order_id' => 100116,
                'created_at' => '2025-10-12 15:59:10',
                'updated_at' => '2025-10-12 15:59:10',
                'description' => '',
                'created_by' => 'vendor',
                'store_id' => 5,
                'delivery_man_id' => NULL,
                'user_id' => NULL,
                'trip_id' => NULL,
            ),
            53 => 
            array (
                'id' => 54,
                'type' => 'discount_on_product',
                'amount' => '0.230',
                'order_id' => 100116,
                'created_at' => '2025-10-12 15:59:10',
                'updated_at' => '2025-10-12 15:59:10',
                'description' => '',
                'created_by' => 'admin',
                'store_id' => NULL,
                'delivery_man_id' => NULL,
                'user_id' => NULL,
                'trip_id' => NULL,
            ),
            54 => 
            array (
                'id' => 55,
                'type' => 'CashBack',
                'amount' => '65.870',
                'order_id' => 100117,
                'created_at' => '2025-10-12 16:13:30',
                'updated_at' => '2025-10-12 16:13:30',
                'description' => '',
                'created_by' => 'admin',
                'store_id' => NULL,
                'delivery_man_id' => NULL,
                'user_id' => NULL,
                'trip_id' => NULL,
            ),
            55 => 
            array (
                'id' => 56,
                'type' => 'discount_on_product',
                'amount' => '2.070',
                'order_id' => 100117,
                'created_at' => '2025-10-12 16:13:30',
                'updated_at' => '2025-10-12 16:13:30',
                'description' => '',
                'created_by' => 'vendor',
                'store_id' => 5,
                'delivery_man_id' => NULL,
                'user_id' => NULL,
                'trip_id' => NULL,
            ),
            56 => 
            array (
                'id' => 57,
                'type' => 'discount_on_product',
                'amount' => '0.230',
                'order_id' => 100117,
                'created_at' => '2025-10-12 16:13:30',
                'updated_at' => '2025-10-12 16:13:30',
                'description' => '',
                'created_by' => 'admin',
                'store_id' => NULL,
                'delivery_man_id' => NULL,
                'user_id' => NULL,
                'trip_id' => NULL,
            ),
            57 => 
            array (
                'id' => 58,
                'type' => 'CashBack',
                'amount' => '65.870',
                'order_id' => 100125,
                'created_at' => '2025-10-12 18:06:21',
                'updated_at' => '2025-10-12 18:06:21',
                'description' => '',
                'created_by' => 'admin',
                'store_id' => NULL,
                'delivery_man_id' => NULL,
                'user_id' => NULL,
                'trip_id' => NULL,
            ),
            58 => 
            array (
                'id' => 59,
                'type' => 'discount_on_product',
                'amount' => '2.070',
                'order_id' => 100125,
                'created_at' => '2025-10-12 18:06:21',
                'updated_at' => '2025-10-12 18:06:21',
                'description' => '',
                'created_by' => 'vendor',
                'store_id' => 5,
                'delivery_man_id' => NULL,
                'user_id' => NULL,
                'trip_id' => NULL,
            ),
            59 => 
            array (
                'id' => 60,
                'type' => 'discount_on_product',
                'amount' => '0.230',
                'order_id' => 100125,
                'created_at' => '2025-10-12 18:06:21',
                'updated_at' => '2025-10-12 18:06:21',
                'description' => '',
                'created_by' => 'admin',
                'store_id' => NULL,
                'delivery_man_id' => NULL,
                'user_id' => NULL,
                'trip_id' => NULL,
            ),
        ));
        
        
    }
}