<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class FlashSaleItemsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('flash_sale_items')->delete();
        
        \DB::table('flash_sale_items')->insert(array (
            0 => 
            array (
                'id' => 1,
                'flash_sale_id' => 1,
                'item_id' => 5,
                'stock' => 20,
                'sold' => 4,
                'available_stock' => 16,
                'discount_type' => 'percent',
                'discount' => 20.0,
                'discount_amount' => 0.6,
                'price' => 2.4,
                'status' => 1,
                'created_at' => '2023-10-19 13:18:56',
                'updated_at' => '2023-10-19 16:55:46',
            ),
            1 => 
            array (
                'id' => 3,
                'flash_sale_id' => 1,
                'item_id' => 22,
                'stock' => 10,
                'sold' => 0,
                'available_stock' => 10,
                'discount_type' => 'percent',
                'discount' => 20.0,
                'discount_amount' => 100.0,
                'price' => 400.0,
                'status' => 1,
                'created_at' => '2023-10-19 13:19:32',
                'updated_at' => '2023-10-19 13:19:32',
            ),
            2 => 
            array (
                'id' => 4,
                'flash_sale_id' => 1,
                'item_id' => 29,
                'stock' => 30,
                'sold' => 0,
                'available_stock' => 30,
                'discount_type' => 'amount',
                'discount' => 20.0,
                'discount_amount' => 20.0,
                'price' => 980.0,
                'status' => 1,
                'created_at' => '2023-10-19 13:19:46',
                'updated_at' => '2023-10-19 13:19:46',
            ),
            3 => 
            array (
                'id' => 5,
                'flash_sale_id' => 1,
                'item_id' => 38,
                'stock' => 30,
                'sold' => 0,
                'available_stock' => 30,
                'discount_type' => 'percent',
                'discount' => 30.0,
                'discount_amount' => 90.0,
                'price' => 210.0,
                'status' => 1,
                'created_at' => '2023-10-19 13:20:10',
                'updated_at' => '2023-10-19 13:20:10',
            ),
            4 => 
            array (
                'id' => 6,
                'flash_sale_id' => 1,
                'item_id' => 90,
                'stock' => 30,
                'sold' => 0,
                'available_stock' => 30,
                'discount_type' => 'percent',
                'discount' => 10.0,
                'discount_amount' => 20.0,
                'price' => 180.0,
                'status' => 1,
                'created_at' => '2023-10-19 13:20:27',
                'updated_at' => '2023-10-19 13:20:27',
            ),
            5 => 
            array (
                'id' => 7,
                'flash_sale_id' => 1,
                'item_id' => 150,
                'stock' => 30,
                'sold' => 0,
                'available_stock' => 30,
                'discount_type' => 'percent',
                'discount' => 5.0,
                'discount_amount' => 4.0,
                'price' => 76.0,
                'status' => 1,
                'created_at' => '2023-10-19 13:20:46',
                'updated_at' => '2023-10-19 13:20:46',
            ),
            6 => 
            array (
                'id' => 8,
                'flash_sale_id' => 1,
                'item_id' => 146,
                'stock' => 50,
                'sold' => 0,
                'available_stock' => 50,
                'discount_type' => 'percent',
                'discount' => 20.0,
                'discount_amount' => 60.0,
                'price' => 240.0,
                'status' => 1,
                'created_at' => '2023-10-19 13:21:04',
                'updated_at' => '2023-10-19 13:21:04',
            ),
            7 => 
            array (
                'id' => 9,
                'flash_sale_id' => 1,
                'item_id' => 144,
                'stock' => 200,
                'sold' => 0,
                'available_stock' => 200,
                'discount_type' => 'percent',
                'discount' => 20.0,
                'discount_amount' => 40.0,
                'price' => 160.0,
                'status' => 1,
                'created_at' => '2023-10-19 13:21:26',
                'updated_at' => '2023-10-19 13:21:26',
            ),
            8 => 
            array (
                'id' => 10,
                'flash_sale_id' => 1,
                'item_id' => 110,
                'stock' => 30,
                'sold' => 0,
                'available_stock' => 30,
                'discount_type' => 'percent',
                'discount' => 20.0,
                'discount_amount' => 60.0,
                'price' => 240.0,
                'status' => 1,
                'created_at' => '2023-10-19 13:21:39',
                'updated_at' => '2023-10-19 13:21:39',
            ),
            9 => 
            array (
                'id' => 11,
                'flash_sale_id' => 1,
                'item_id' => 112,
                'stock' => 10,
                'sold' => 0,
                'available_stock' => 10,
                'discount_type' => 'percent',
                'discount' => 10.0,
                'discount_amount' => 15.6,
                'price' => 140.4,
                'status' => 1,
                'created_at' => '2023-10-19 13:21:50',
                'updated_at' => '2023-10-19 13:21:50',
            ),
            10 => 
            array (
                'id' => 12,
                'flash_sale_id' => 2,
                'item_id' => 33,
                'stock' => 100,
                'sold' => 0,
                'available_stock' => 100,
                'discount_type' => 'percent',
                'discount' => 10.0,
                'discount_amount' => 10.0,
                'price' => 90.0,
                'status' => 1,
                'created_at' => '2023-10-19 13:25:13',
                'updated_at' => '2023-10-19 13:25:13',
            ),
            11 => 
            array (
                'id' => 13,
                'flash_sale_id' => 2,
                'item_id' => 36,
                'stock' => 20,
                'sold' => 0,
                'available_stock' => 20,
                'discount_type' => 'percent',
                'discount' => 20.0,
                'discount_amount' => 11.8,
                'price' => 47.2,
                'status' => 1,
                'created_at' => '2023-10-19 13:25:26',
                'updated_at' => '2023-10-19 13:25:26',
            ),
            12 => 
            array (
                'id' => 14,
                'flash_sale_id' => 2,
                'item_id' => 39,
                'stock' => 100,
                'sold' => 0,
                'available_stock' => 100,
                'discount_type' => 'percent',
                'discount' => 20.0,
                'discount_amount' => 24.0,
                'price' => 96.0,
                'status' => 1,
                'created_at' => '2023-10-19 13:25:38',
                'updated_at' => '2023-10-19 13:25:38',
            ),
            13 => 
            array (
                'id' => 15,
                'flash_sale_id' => 2,
                'item_id' => 43,
                'stock' => 100,
                'sold' => 0,
                'available_stock' => 100,
                'discount_type' => 'percent',
                'discount' => 20.0,
                'discount_amount' => 6.0,
                'price' => 24.0,
                'status' => 1,
                'created_at' => '2023-10-19 13:25:50',
                'updated_at' => '2023-10-19 13:25:50',
            ),
            14 => 
            array (
                'id' => 16,
                'flash_sale_id' => 2,
                'item_id' => 45,
                'stock' => 10,
                'sold' => 1,
                'available_stock' => 9,
                'discount_type' => 'percent',
                'discount' => 20.0,
                'discount_amount' => 6.0,
                'price' => 24.0,
                'status' => 1,
                'created_at' => '2023-10-19 13:26:07',
                'updated_at' => '2023-10-19 14:25:04',
            ),
            15 => 
            array (
                'id' => 17,
                'flash_sale_id' => 2,
                'item_id' => 53,
                'stock' => 100,
                'sold' => 0,
                'available_stock' => 100,
                'discount_type' => 'percent',
                'discount' => 20.0,
                'discount_amount' => 20.0,
                'price' => 80.0,
                'status' => 1,
                'created_at' => '2023-10-19 13:26:25',
                'updated_at' => '2023-10-19 13:26:25',
            ),
            16 => 
            array (
                'id' => 18,
                'flash_sale_id' => 2,
                'item_id' => 58,
                'stock' => 150,
                'sold' => 0,
                'available_stock' => 150,
                'discount_type' => 'percent',
                'discount' => 20.0,
                'discount_amount' => 20.0,
                'price' => 80.0,
                'status' => 1,
                'created_at' => '2023-10-19 13:26:41',
                'updated_at' => '2023-10-19 13:26:41',
            ),
            17 => 
            array (
                'id' => 19,
                'flash_sale_id' => 2,
                'item_id' => 67,
                'stock' => 100,
                'sold' => 0,
                'available_stock' => 100,
                'discount_type' => 'amount',
                'discount' => 10.0,
                'discount_amount' => 10.0,
                'price' => 140.0,
                'status' => 1,
                'created_at' => '2023-10-19 13:27:04',
                'updated_at' => '2023-10-19 13:27:04',
            ),
            18 => 
            array (
                'id' => 20,
                'flash_sale_id' => 2,
                'item_id' => 78,
                'stock' => 70,
                'sold' => 0,
                'available_stock' => 70,
                'discount_type' => 'percent',
                'discount' => 15.0,
                'discount_amount' => 30.0,
                'price' => 170.0,
                'status' => 1,
                'created_at' => '2023-10-19 13:27:25',
                'updated_at' => '2023-10-19 13:27:25',
            ),
        ));
        
        
    }
}