<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class NotificationSettingsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('notification_settings')->delete();
        
        \DB::table('notification_settings')->insert(array (
            0 => 
            array (
                'id' => 1,
                'title' => 'forget_password',
                'sub_title' => 'Sent_notification_on_forget_password',
                'key' => 'forget_password',
                'type' => 'admin',
                'mail_status' => 'active',
                'sms_status' => 'active',
                'push_notification_status' => 'disable',
                'created_at' => '2024-09-24 10:20:37',
                'updated_at' => '2024-09-24 10:20:37',
                'module_type' => 'all',
            ),
            1 => 
            array (
                'id' => 2,
                'title' => 'deliveryman_self_registration',
                'sub_title' => 'Sent_notification_on_deliveryman_self_registration',
                'key' => 'deliveryman_self_registration',
                'type' => 'admin',
                'mail_status' => 'active',
                'sms_status' => 'disable',
                'push_notification_status' => 'disable',
                'created_at' => '2024-09-24 10:20:37',
                'updated_at' => '2024-09-24 10:20:37',
                'module_type' => 'all',
            ),
            2 => 
            array (
                'id' => 3,
                'title' => 'store_self_registration',
                'sub_title' => 'Sent_notification_on_store_self_registration',
                'key' => 'store_self_registration',
                'type' => 'admin',
                'mail_status' => 'active',
                'sms_status' => 'disable',
                'push_notification_status' => 'disable',
                'created_at' => '2024-09-24 10:20:37',
                'updated_at' => '2024-09-24 10:20:37',
                'module_type' => 'all',
            ),
            3 => 
            array (
                'id' => 4,
                'title' => 'campaign_join_request',
                'sub_title' => 'Sent_notification_on_campaign_join_request',
                'key' => 'campaign_join_request',
                'type' => 'admin',
                'mail_status' => 'active',
                'sms_status' => 'disable',
                'push_notification_status' => 'disable',
                'created_at' => '2024-09-24 10:20:37',
                'updated_at' => '2024-09-24 10:20:37',
                'module_type' => 'all',
            ),
            4 => 
            array (
                'id' => 5,
                'title' => 'withdraw_request',
                'sub_title' => 'Sent_notification_on_withdraw_request',
                'key' => 'withdraw_request',
                'type' => 'admin',
                'mail_status' => 'active',
                'sms_status' => 'disable',
                'push_notification_status' => 'disable',
                'created_at' => '2024-09-24 10:20:37',
                'updated_at' => '2024-09-24 10:20:37',
                'module_type' => 'all',
            ),
            5 => 
            array (
                'id' => 6,
                'title' => 'order_refund_request',
                'sub_title' => 'Sent_notification_on_order_refund_request',
                'key' => 'order_refund_request',
                'type' => 'admin',
                'mail_status' => 'active',
                'sms_status' => 'disable',
                'push_notification_status' => 'disable',
                'created_at' => '2024-09-24 10:20:37',
                'updated_at' => '2024-09-24 10:20:37',
                'module_type' => 'all',
            ),
            6 => 
            array (
                'id' => 7,
                'title' => 'advertisement_add',
                'sub_title' => 'Sent_notification_on_advertisement_add',
                'key' => 'advertisement_add',
                'type' => 'admin',
                'mail_status' => 'active',
                'sms_status' => 'disable',
                'push_notification_status' => 'disable',
                'created_at' => '2024-09-24 10:20:37',
                'updated_at' => '2024-09-24 10:20:37',
                'module_type' => 'all',
            ),
            7 => 
            array (
                'id' => 8,
                'title' => 'advertisement_update',
                'sub_title' => 'Sent_notification_on_advertisement_update',
                'key' => 'advertisement_update',
                'type' => 'admin',
                'mail_status' => 'active',
                'sms_status' => 'disable',
                'push_notification_status' => 'disable',
                'created_at' => '2024-09-24 10:20:37',
                'updated_at' => '2024-09-24 10:20:37',
                'module_type' => 'all',
            ),
            8 => 
            array (
                'id' => 9,
                'title' => 'deliveryman_registration',
                'sub_title' => 'Sent_notification_on_deliveryman_registration',
                'key' => 'deliveryman_registration',
                'type' => 'deliveryman',
                'mail_status' => 'active',
                'sms_status' => 'disable',
                'push_notification_status' => 'disable',
                'created_at' => '2024-09-24 10:20:37',
                'updated_at' => '2024-09-24 10:20:37',
                'module_type' => 'all',
            ),
            9 => 
            array (
                'id' => 10,
                'title' => 'deliveryman_registration_approval',
                'sub_title' => 'Sent_notification_on_deliveryman_registration_approval',
                'key' => 'deliveryman_registration_approval',
                'type' => 'deliveryman',
                'mail_status' => 'active',
                'sms_status' => 'disable',
                'push_notification_status' => 'disable',
                'created_at' => '2024-09-24 10:20:37',
                'updated_at' => '2024-09-24 10:20:37',
                'module_type' => 'all',
            ),
            10 => 
            array (
                'id' => 11,
                'title' => 'deliveryman_registration_deny',
                'sub_title' => 'Sent_notification_on_deliveryman_registration_deny',
                'key' => 'deliveryman_registration_deny',
                'type' => 'deliveryman',
                'mail_status' => 'active',
                'sms_status' => 'disable',
                'push_notification_status' => 'disable',
                'created_at' => '2024-09-24 10:20:37',
                'updated_at' => '2024-09-24 10:20:37',
                'module_type' => 'all',
            ),
            11 => 
            array (
                'id' => 12,
                'title' => 'deliveryman_account_block',
                'sub_title' => 'Sent_notification_on_deliveryman_account_block',
                'key' => 'deliveryman_account_block',
                'type' => 'deliveryman',
                'mail_status' => 'active',
                'sms_status' => 'disable',
                'push_notification_status' => 'active',
                'created_at' => '2024-09-24 10:20:37',
                'updated_at' => '2024-09-24 10:20:37',
                'module_type' => 'all',
            ),
            12 => 
            array (
                'id' => 13,
                'title' => 'deliveryman_account_unblock',
                'sub_title' => 'Sent_notification_on_deliveryman_account_unblock',
                'key' => 'deliveryman_account_unblock',
                'type' => 'deliveryman',
                'mail_status' => 'active',
                'sms_status' => 'disable',
                'push_notification_status' => 'active',
                'created_at' => '2024-09-24 10:20:37',
                'updated_at' => '2024-09-24 10:20:37',
                'module_type' => 'all',
            ),
            13 => 
            array (
                'id' => 14,
                'title' => 'deliveryman_forget_password',
                'sub_title' => 'Sent_notification_on_deliveryman_forget_password',
                'key' => 'deliveryman_forget_password',
                'type' => 'deliveryman',
                'mail_status' => 'active',
                'sms_status' => 'active',
                'push_notification_status' => 'disable',
                'created_at' => '2024-09-24 10:20:37',
                'updated_at' => '2024-09-24 10:20:37',
                'module_type' => 'all',
            ),
            14 => 
            array (
                'id' => 15,
                'title' => 'deliveryman_collect_cash',
                'sub_title' => 'Sent_notification_on_deliveryman_collect_cash',
                'key' => 'deliveryman_collect_cash',
                'type' => 'deliveryman',
                'mail_status' => 'active',
                'sms_status' => 'disable',
                'push_notification_status' => 'active',
                'created_at' => '2024-09-24 10:20:37',
                'updated_at' => '2024-09-24 10:20:37',
                'module_type' => 'all',
            ),
            15 => 
            array (
                'id' => 16,
                'title' => 'deliveryman_order_notification',
                'sub_title' => 'Sent_notification_order_notification_to_deliveryman',
                'key' => 'deliveryman_order_notification',
                'type' => 'deliveryman',
                'mail_status' => 'disable',
                'sms_status' => 'disable',
                'push_notification_status' => 'active',
                'created_at' => '2024-09-24 10:20:37',
                'updated_at' => '2025-09-16 16:14:44',
                'module_type' => 'all',
            ),
            16 => 
            array (
                'id' => 17,
                'title' => 'deliveryman_order_assign_or_unassign',
                'sub_title' => 'Sent_notification_on_deliveryman_order_assign_or_unassign',
                'key' => 'deliveryman_order_assign_unassign',
                'type' => 'deliveryman',
                'mail_status' => 'disable',
                'sms_status' => 'disable',
                'push_notification_status' => 'active',
                'created_at' => '2024-09-24 10:20:37',
                'updated_at' => '2024-09-24 10:20:37',
                'module_type' => 'all',
            ),
            17 => 
            array (
                'id' => 18,
                'title' => 'store_registration',
                'sub_title' => 'Sent_notification_on_store_registration',
                'key' => 'store_registration',
                'type' => 'store',
                'mail_status' => 'active',
                'sms_status' => 'disable',
                'push_notification_status' => 'disable',
                'created_at' => '2024-09-24 10:20:37',
                'updated_at' => '2024-09-24 10:20:37',
                'module_type' => 'all',
            ),
            18 => 
            array (
                'id' => 19,
                'title' => 'store_registration_approval',
                'sub_title' => 'Sent_notification_on_store_registration_approval',
                'key' => 'store_registration_approval',
                'type' => 'store',
                'mail_status' => 'active',
                'sms_status' => 'disable',
                'push_notification_status' => 'disable',
                'created_at' => '2024-09-24 10:20:37',
                'updated_at' => '2024-09-24 10:20:37',
                'module_type' => 'all',
            ),
            19 => 
            array (
                'id' => 20,
                'title' => 'store_registration_deny',
                'sub_title' => 'Sent_notification_on_store_registration_deny',
                'key' => 'store_registration_deny',
                'type' => 'store',
                'mail_status' => 'active',
                'sms_status' => 'disable',
                'push_notification_status' => 'disable',
                'created_at' => '2024-09-24 10:20:37',
                'updated_at' => '2024-09-24 10:20:37',
                'module_type' => 'all',
            ),
            20 => 
            array (
                'id' => 21,
                'title' => 'store_account_block',
                'sub_title' => 'Sent_notification_on_store_account_block',
                'key' => 'store_account_block',
                'type' => 'store',
                'mail_status' => 'active',
                'sms_status' => 'disable',
                'push_notification_status' => 'active',
                'created_at' => '2024-09-24 10:20:37',
                'updated_at' => '2024-09-24 10:20:37',
                'module_type' => 'all',
            ),
            21 => 
            array (
                'id' => 22,
                'title' => 'store_account_unblock',
                'sub_title' => 'Sent_notification_on_store_account_unblock',
                'key' => 'store_account_unblock',
                'type' => 'store',
                'mail_status' => 'active',
                'sms_status' => 'disable',
                'push_notification_status' => 'active',
                'created_at' => '2024-09-24 10:20:37',
                'updated_at' => '2024-09-24 10:20:37',
                'module_type' => 'all',
            ),
            22 => 
            array (
                'id' => 23,
                'title' => 'store_withdraw_approve',
                'sub_title' => 'Sent_notification_on_store_withdraw_approve',
                'key' => 'store_withdraw_approve',
                'type' => 'store',
                'mail_status' => 'active',
                'sms_status' => 'disable',
                'push_notification_status' => 'active',
                'created_at' => '2024-09-24 10:20:37',
                'updated_at' => '2024-09-24 10:20:37',
                'module_type' => 'all',
            ),
            23 => 
            array (
                'id' => 24,
                'title' => 'store_withdraw_rejaction',
                'sub_title' => 'Sent_notification_on_store_withdraw_rejaction',
                'key' => 'store_withdraw_rejaction',
                'type' => 'store',
                'mail_status' => 'active',
                'sms_status' => 'disable',
                'push_notification_status' => 'active',
                'created_at' => '2024-09-24 10:20:37',
                'updated_at' => '2024-09-24 10:20:37',
                'module_type' => 'all',
            ),
            24 => 
            array (
                'id' => 25,
                'title' => 'store_campaign_join_request',
                'sub_title' => 'Sent_notification_on_store_campaign_join_request',
                'key' => 'store_campaign_join_request',
                'type' => 'store',
                'mail_status' => 'active',
                'sms_status' => 'disable',
                'push_notification_status' => 'disable',
                'created_at' => '2024-09-24 10:20:37',
                'updated_at' => '2024-09-24 10:20:37',
                'module_type' => 'all',
            ),
            25 => 
            array (
                'id' => 26,
                'title' => 'store_campaign_join_rejaction',
                'sub_title' => 'Sent_notification_on_store_campaign_join_rejaction',
                'key' => 'store_campaign_join_rejaction',
                'type' => 'store',
                'mail_status' => 'active',
                'sms_status' => 'disable',
                'push_notification_status' => 'active',
                'created_at' => '2024-09-24 10:20:37',
                'updated_at' => '2024-09-24 10:20:37',
                'module_type' => 'all',
            ),
            26 => 
            array (
                'id' => 27,
                'title' => 'store_campaign_join_approval',
                'sub_title' => 'Sent_notification_on_store_campaign_join_approval',
                'key' => 'store_campaign_join_approval',
                'type' => 'store',
                'mail_status' => 'active',
                'sms_status' => 'disable',
                'push_notification_status' => 'active',
                'created_at' => '2024-09-24 10:20:37',
                'updated_at' => '2024-09-24 10:20:37',
                'module_type' => 'all',
            ),
            27 => 
            array (
                'id' => 28,
                'title' => 'store_order_notification',
                'sub_title' => 'Sent_notification_on_store_order_notification',
                'key' => 'store_order_notification',
                'type' => 'store',
                'mail_status' => 'disable',
                'sms_status' => 'disable',
                'push_notification_status' => 'active',
                'created_at' => '2024-09-24 10:20:37',
                'updated_at' => '2024-09-24 10:20:37',
                'module_type' => 'all',
            ),
            28 => 
            array (
                'id' => 29,
                'title' => 'store_product_approve',
                'sub_title' => 'Sent_notification_on_store_product_approve',
                'key' => 'store_product_approve',
                'type' => 'store',
                'mail_status' => 'active',
                'sms_status' => 'disable',
                'push_notification_status' => 'active',
                'created_at' => '2024-09-24 10:20:37',
                'updated_at' => '2024-09-24 10:20:37',
                'module_type' => 'all',
            ),
            29 => 
            array (
                'id' => 30,
                'title' => 'store_product_reject',
                'sub_title' => 'Sent_notification_on_store_product_reject',
                'key' => 'store_product_reject',
                'type' => 'store',
                'mail_status' => 'active',
                'sms_status' => 'disable',
                'push_notification_status' => 'active',
                'created_at' => '2024-09-24 10:20:37',
                'updated_at' => '2024-09-24 10:20:37',
                'module_type' => 'all',
            ),
            30 => 
            array (
                'id' => 31,
                'title' => 'store_subscription_success',
                'sub_title' => 'Sent_notification_on_store_subscription_success',
                'key' => 'store_subscription_success',
                'type' => 'store',
                'mail_status' => 'active',
                'sms_status' => 'disable',
                'push_notification_status' => 'active',
                'created_at' => '2024-09-24 10:20:37',
                'updated_at' => '2024-09-24 10:20:37',
                'module_type' => 'all',
            ),
            31 => 
            array (
                'id' => 32,
                'title' => 'store_subscription_renew',
                'sub_title' => 'Sent_notification_on_store_subscription_renew',
                'key' => 'store_subscription_renew',
                'type' => 'store',
                'mail_status' => 'active',
                'sms_status' => 'disable',
                'push_notification_status' => 'active',
                'created_at' => '2024-09-24 10:20:37',
                'updated_at' => '2024-09-24 10:20:37',
                'module_type' => 'all',
            ),
            32 => 
            array (
                'id' => 33,
                'title' => 'store_subscription_shift',
                'sub_title' => 'Sent_notification_on_store_subscription_shift',
                'key' => 'store_subscription_shift',
                'type' => 'store',
                'mail_status' => 'active',
                'sms_status' => 'disable',
                'push_notification_status' => 'active',
                'created_at' => '2024-09-24 10:20:37',
                'updated_at' => '2024-09-24 10:20:37',
                'module_type' => 'all',
            ),
            33 => 
            array (
                'id' => 34,
                'title' => 'store_subscription_cancel',
                'sub_title' => 'Sent_notification_on_store_subscription_cancel',
                'key' => 'store_subscription_cancel',
                'type' => 'store',
                'mail_status' => 'active',
                'sms_status' => 'disable',
                'push_notification_status' => 'active',
                'created_at' => '2024-09-24 10:20:37',
                'updated_at' => '2024-09-24 10:20:37',
                'module_type' => 'all',
            ),
            34 => 
            array (
                'id' => 35,
                'title' => 'store_subscription_plan_update',
                'sub_title' => 'Sent_notification_on_store_subscription_plan_update',
                'key' => 'store_subscription_plan_update',
                'type' => 'store',
                'mail_status' => 'active',
                'sms_status' => 'disable',
                'push_notification_status' => 'inactive',
                'created_at' => '2024-09-24 10:20:37',
                'updated_at' => '2024-09-24 10:20:37',
                'module_type' => 'all',
            ),
            35 => 
            array (
                'id' => 36,
                'title' => 'store_advertisement_create_by_admin',
                'sub_title' => 'Sent_notification_on_store_advertisement_create_by_admin',
                'key' => 'store_advertisement_create_by_admin',
                'type' => 'store',
                'mail_status' => 'active',
                'sms_status' => 'disable',
                'push_notification_status' => 'active',
                'created_at' => '2024-09-24 10:20:37',
                'updated_at' => '2024-09-24 10:20:37',
                'module_type' => 'all',
            ),
            36 => 
            array (
                'id' => 37,
                'title' => 'store_advertisement_approval',
                'sub_title' => 'Sent_notification_on_store_advertisement_approval',
                'key' => 'store_advertisement_approval',
                'type' => 'store',
                'mail_status' => 'active',
                'sms_status' => 'disable',
                'push_notification_status' => 'active',
                'created_at' => '2024-09-24 10:20:37',
                'updated_at' => '2024-09-24 10:20:37',
                'module_type' => 'all',
            ),
            37 => 
            array (
                'id' => 38,
                'title' => 'store_advertisement_deny',
                'sub_title' => 'Sent_notification_on_store_advertisement_deny',
                'key' => 'store_advertisement_deny',
                'type' => 'store',
                'mail_status' => 'active',
                'sms_status' => 'disable',
                'push_notification_status' => 'active',
                'created_at' => '2024-09-24 10:20:37',
                'updated_at' => '2024-09-24 10:20:37',
                'module_type' => 'all',
            ),
            38 => 
            array (
                'id' => 39,
                'title' => 'store_advertisement_resume',
                'sub_title' => 'Sent_notification_on_store_advertisement_resume',
                'key' => 'store_advertisement_resume',
                'type' => 'store',
                'mail_status' => 'active',
                'sms_status' => 'disable',
                'push_notification_status' => 'active',
                'created_at' => '2024-09-24 10:20:37',
                'updated_at' => '2024-09-24 10:20:37',
                'module_type' => 'all',
            ),
            39 => 
            array (
                'id' => 40,
                'title' => 'store_advertisement_pause',
                'sub_title' => 'Sent_notification_on_store_advertisement_pause',
                'key' => 'store_advertisement_pause',
                'type' => 'store',
                'mail_status' => 'active',
                'sms_status' => 'disable',
                'push_notification_status' => 'active',
                'created_at' => '2024-09-24 10:20:37',
                'updated_at' => '2024-09-24 10:20:37',
                'module_type' => 'all',
            ),
            40 => 
            array (
                'id' => 41,
                'title' => 'customer_registration',
                'sub_title' => 'Sent_notification_on_customer_registration',
                'key' => 'customer_registration',
                'type' => 'customer',
                'mail_status' => 'active',
                'sms_status' => 'disable',
                'push_notification_status' => 'disable',
                'created_at' => '2024-09-24 10:20:37',
                'updated_at' => '2024-09-24 10:20:37',
                'module_type' => 'all',
            ),
            41 => 
            array (
                'id' => 42,
                'title' => 'customer_pos_registration',
                'sub_title' => 'Sent_notification_on_customer_pos_registration',
                'key' => 'customer_pos_registration',
                'type' => 'customer',
                'mail_status' => 'active',
                'sms_status' => 'disable',
                'push_notification_status' => 'disable',
                'created_at' => '2024-09-24 10:20:37',
                'updated_at' => '2024-09-24 10:20:37',
                'module_type' => 'all',
            ),
            42 => 
            array (
                'id' => 46,
                'title' => 'customer_order_notification',
                'sub_title' => 'Sent_notification_on_customer_order_notification',
                'key' => 'customer_order_notification',
                'type' => 'customer',
                'mail_status' => 'active',
                'sms_status' => 'disable',
                'push_notification_status' => 'active',
                'created_at' => '2024-09-24 10:20:37',
                'updated_at' => '2024-09-24 10:20:37',
                'module_type' => 'all',
            ),
            43 => 
            array (
                'id' => 47,
                'title' => 'customer_delivery_verification',
                'sub_title' => 'Sent_notification_on_customer_delivery_verification',
                'key' => 'customer_delivery_verification',
                'type' => 'customer',
                'mail_status' => 'active',
                'sms_status' => 'disable',
                'push_notification_status' => 'active',
                'created_at' => '2024-09-24 10:20:37',
                'updated_at' => '2024-09-24 10:20:37',
                'module_type' => 'all',
            ),
            44 => 
            array (
                'id' => 48,
                'title' => 'customer_refund_request_approval',
                'sub_title' => 'Sent_notification_on_customer_refund_request_approval',
                'key' => 'customer_refund_request_approval',
                'type' => 'customer',
                'mail_status' => 'active',
                'sms_status' => 'disable',
                'push_notification_status' => 'active',
                'created_at' => '2024-09-24 10:20:37',
                'updated_at' => '2024-09-24 10:20:37',
                'module_type' => 'all',
            ),
            45 => 
            array (
                'id' => 49,
                'title' => 'customer_refund_request_rejaction',
                'sub_title' => 'Sent_notification_on_customer_refund_request_rejaction',
                'key' => 'customer_refund_request_rejaction',
                'type' => 'customer',
                'mail_status' => 'active',
                'sms_status' => 'disable',
                'push_notification_status' => 'active',
                'created_at' => '2024-09-24 10:20:37',
                'updated_at' => '2024-09-24 10:20:37',
                'module_type' => 'all',
            ),
            46 => 
            array (
                'id' => 50,
                'title' => 'customer_add_fund_to_wallet',
                'sub_title' => 'Sent_notification_on_customer_add_fund_to_wallet',
                'key' => 'customer_add_fund_to_wallet',
                'type' => 'customer',
                'mail_status' => 'active',
                'sms_status' => 'disable',
                'push_notification_status' => 'active',
                'created_at' => '2024-09-24 10:20:37',
                'updated_at' => '2024-09-24 10:20:37',
                'module_type' => 'all',
            ),
            47 => 
            array (
                'id' => 51,
                'title' => 'customer_offline_payment_approve',
                'sub_title' => 'Sent_notification_on_customer_offline_payment_approve',
                'key' => 'customer_offline_payment_approve',
                'type' => 'customer',
                'mail_status' => 'active',
                'sms_status' => 'disable',
                'push_notification_status' => 'active',
                'created_at' => '2024-09-24 10:20:37',
                'updated_at' => '2024-09-24 10:20:37',
                'module_type' => 'all',
            ),
            48 => 
            array (
                'id' => 52,
                'title' => 'customer_offline_payment_deny',
                'sub_title' => 'Sent_notification_on_customer_offline_payment_deny',
                'key' => 'customer_offline_payment_deny',
                'type' => 'customer',
                'mail_status' => 'active',
                'sms_status' => 'disable',
                'push_notification_status' => 'active',
                'created_at' => '2024-09-24 10:20:37',
                'updated_at' => '2024-09-24 10:20:37',
                'module_type' => 'all',
            ),
            49 => 
            array (
                'id' => 53,
                'title' => 'customer_account_block',
                'sub_title' => 'Sent_notification_on_customer_account_block',
                'key' => 'customer_account_block',
                'type' => 'customer',
                'mail_status' => 'active',
                'sms_status' => 'disable',
                'push_notification_status' => 'active',
                'created_at' => '2024-09-24 10:20:37',
                'updated_at' => '2024-09-24 10:20:37',
                'module_type' => 'all',
            ),
            50 => 
            array (
                'id' => 54,
                'title' => 'customer_account_unblock',
                'sub_title' => 'Sent_notification_on_customer_account_unblock',
                'key' => 'customer_account_unblock',
                'type' => 'customer',
                'mail_status' => 'active',
                'sms_status' => 'disable',
                'push_notification_status' => 'active',
                'created_at' => '2024-09-24 10:20:37',
                'updated_at' => '2024-09-24 10:20:37',
                'module_type' => 'all',
            ),
            51 => 
            array (
                'id' => 55,
                'title' => 'customer_cashback',
                'sub_title' => 'Sent_notification_on_customer_cashback',
                'key' => 'customer_cashback',
                'type' => 'customer',
                'mail_status' => 'disable',
                'sms_status' => 'disable',
                'push_notification_status' => 'active',
                'created_at' => '2024-09-24 10:20:37',
                'updated_at' => '2024-09-24 10:20:37',
                'module_type' => 'all',
            ),
            52 => 
            array (
                'id' => 56,
                'title' => 'customer_referral_bonus_earning',
                'sub_title' => 'Sent_notification_on_customer_referral_bonus_earning',
                'key' => 'customer_referral_bonus_earning',
                'type' => 'customer',
                'mail_status' => 'disable',
                'sms_status' => 'disable',
                'push_notification_status' => 'active',
                'created_at' => '2024-09-24 10:20:37',
                'updated_at' => '2024-09-24 10:20:37',
                'module_type' => 'all',
            ),
            53 => 
            array (
                'id' => 57,
                'title' => 'customer_new_referral_join',
                'sub_title' => 'Sent_notification_on_customer_new_referral_join',
                'key' => 'customer_new_referral_join',
                'type' => 'customer',
                'mail_status' => 'disable',
                'sms_status' => 'disable',
                'push_notification_status' => 'active',
                'created_at' => '2024-09-24 10:20:37',
                'updated_at' => '2024-09-24 10:20:37',
                'module_type' => 'all',
            ),
            54 => 
            array (
                'id' => 58,
                'title' => 'customer_pos_order_wallet_notification',
                'sub_title' => 'Sent_notification_on_wallet_payment_on_POS',
                'key' => 'customer_pos_order_wallet_notification',
                'type' => 'customer',
                'mail_status' => 'disable',
                'sms_status' => 'disable',
                'push_notification_status' => 'active',
                'created_at' => '2024-09-24 10:20:37',
                'updated_at' => '2024-09-24 10:20:37',
                'module_type' => 'all',
            ),
            55 => 
            array (
                'id' => 59,
                'title' => 'provider_registration',
                'sub_title' => 'Sent_notification_on_provider_self_registration',
                'key' => 'provider_self_registration',
                'type' => 'admin',
                'mail_status' => 'active',
                'sms_status' => 'disable',
                'push_notification_status' => 'disable',
                'created_at' => '2025-02-08 09:31:38',
                'updated_at' => '2025-02-08 09:31:38',
                'module_type' => 'rental',
            ),
            56 => 
            array (
                'id' => 60,
                'title' => 'provider_withdraw_request',
                'sub_title' => 'Sent_notification_on_provider_withdraw_request',
                'key' => 'provider_withdraw_request',
                'type' => 'admin',
                'mail_status' => 'active',
                'sms_status' => 'disable',
                'push_notification_status' => 'disable',
                'created_at' => '2025-02-08 09:31:38',
                'updated_at' => '2025-02-08 09:31:38',
                'module_type' => 'rental',
            ),
            57 => 
            array (
                'id' => 61,
                'title' => 'provider_registration',
                'sub_title' => 'Sent_notification_on_provider_registration',
                'key' => 'provider_registration',
                'type' => 'provider',
                'mail_status' => 'active',
                'sms_status' => 'disable',
                'push_notification_status' => 'disable',
                'created_at' => '2025-02-08 09:31:38',
                'updated_at' => '2025-02-08 09:31:38',
                'module_type' => 'rental',
            ),
            58 => 
            array (
                'id' => 62,
                'title' => 'provider_registration_approval',
                'sub_title' => 'Sent_notification_on_provider_registration_approval',
                'key' => 'provider_registration_approval',
                'type' => 'provider',
                'mail_status' => 'active',
                'sms_status' => 'disable',
                'push_notification_status' => 'disable',
                'created_at' => '2025-02-08 09:31:38',
                'updated_at' => '2025-02-08 09:31:38',
                'module_type' => 'rental',
            ),
            59 => 
            array (
                'id' => 63,
                'title' => 'provider_registration_deny',
                'sub_title' => 'Sent_notification_on_provider_registration_deny',
                'key' => 'provider_registration_deny',
                'type' => 'provider',
                'mail_status' => 'active',
                'sms_status' => 'disable',
                'push_notification_status' => 'disable',
                'created_at' => '2025-02-08 09:31:38',
                'updated_at' => '2025-02-08 09:31:38',
                'module_type' => 'rental',
            ),
            60 => 
            array (
                'id' => 64,
                'title' => 'provider_account_block',
                'sub_title' => 'Sent_notification_on_provider_account_block',
                'key' => 'provider_account_block',
                'type' => 'provider',
                'mail_status' => 'active',
                'sms_status' => 'disable',
                'push_notification_status' => 'active',
                'created_at' => '2025-02-08 09:31:38',
                'updated_at' => '2025-02-08 09:31:38',
                'module_type' => 'rental',
            ),
            61 => 
            array (
                'id' => 65,
                'title' => 'provider_account_unblock',
                'sub_title' => 'Sent_notification_on_provider_account_unblock',
                'key' => 'provider_account_unblock',
                'type' => 'provider',
                'mail_status' => 'active',
                'sms_status' => 'disable',
                'push_notification_status' => 'active',
                'created_at' => '2025-02-08 09:31:38',
                'updated_at' => '2025-02-08 09:31:38',
                'module_type' => 'rental',
            ),
            62 => 
            array (
                'id' => 66,
                'title' => 'provider_withdraw_approve',
                'sub_title' => 'Sent_notification_on_provider_withdraw_approve',
                'key' => 'provider_withdraw_approve',
                'type' => 'provider',
                'mail_status' => 'active',
                'sms_status' => 'disable',
                'push_notification_status' => 'active',
                'created_at' => '2025-02-08 09:31:38',
                'updated_at' => '2025-02-08 09:31:38',
                'module_type' => 'rental',
            ),
            63 => 
            array (
                'id' => 67,
                'title' => 'provider_withdraw_rejaction',
                'sub_title' => 'Sent_notification_on_provider_withdraw_rejaction',
                'key' => 'provider_withdraw_rejaction',
                'type' => 'provider',
                'mail_status' => 'active',
                'sms_status' => 'disable',
                'push_notification_status' => 'active',
                'created_at' => '2025-02-08 09:31:38',
                'updated_at' => '2025-02-08 09:31:38',
                'module_type' => 'rental',
            ),
            64 => 
            array (
                'id' => 68,
                'title' => 'provider_trip_notification',
                'sub_title' => 'Sent_notification_on_provider_trip_notification',
                'key' => 'provider_trip_notification',
                'type' => 'provider',
                'mail_status' => 'disable',
                'sms_status' => 'disable',
                'push_notification_status' => 'active',
                'created_at' => '2025-02-08 09:31:38',
                'updated_at' => '2025-02-08 09:31:38',
                'module_type' => 'rental',
            ),
            65 => 
            array (
                'id' => 69,
                'title' => 'provider_subscription_success',
                'sub_title' => 'Sent_notification_on_provider_subscription_success',
                'key' => 'provider_subscription_success',
                'type' => 'provider',
                'mail_status' => 'active',
                'sms_status' => 'disable',
                'push_notification_status' => 'active',
                'created_at' => '2025-02-08 09:31:38',
                'updated_at' => '2025-02-08 09:31:38',
                'module_type' => 'rental',
            ),
            66 => 
            array (
                'id' => 70,
                'title' => 'provider_subscription_renew',
                'sub_title' => 'Sent_notification_on_provider_subscription_renew',
                'key' => 'provider_subscription_renew',
                'type' => 'provider',
                'mail_status' => 'active',
                'sms_status' => 'disable',
                'push_notification_status' => 'active',
                'created_at' => '2025-02-08 09:31:38',
                'updated_at' => '2025-02-08 09:31:38',
                'module_type' => 'rental',
            ),
            67 => 
            array (
                'id' => 71,
                'title' => 'provider_subscription_shift',
                'sub_title' => 'Sent_notification_on_provider_subscription_shift',
                'key' => 'provider_subscription_shift',
                'type' => 'provider',
                'mail_status' => 'active',
                'sms_status' => 'disable',
                'push_notification_status' => 'active',
                'created_at' => '2025-02-08 09:31:38',
                'updated_at' => '2025-02-08 09:31:38',
                'module_type' => 'rental',
            ),
            68 => 
            array (
                'id' => 72,
                'title' => 'provider_subscription_cancel',
                'sub_title' => 'Sent_notification_on_provider_subscription_cancel',
                'key' => 'provider_subscription_cancel',
                'type' => 'provider',
                'mail_status' => 'active',
                'sms_status' => 'disable',
                'push_notification_status' => 'active',
                'created_at' => '2025-02-08 09:31:38',
                'updated_at' => '2025-02-08 09:31:38',
                'module_type' => 'rental',
            ),
            69 => 
            array (
                'id' => 73,
                'title' => 'provider_subscription_plan_update',
                'sub_title' => 'Sent_notification_on_provider_subscription_plan_update',
                'key' => 'provider_subscription_plan_update',
                'type' => 'provider',
                'mail_status' => 'active',
                'sms_status' => 'disable',
                'push_notification_status' => 'active',
                'created_at' => '2025-02-08 09:31:38',
                'updated_at' => '2025-02-08 09:32:05',
                'module_type' => 'rental',
            ),
            70 => 
            array (
                'id' => 74,
                'title' => 'customer_trip_notification',
                'sub_title' => 'Sent_notification_on_customer_trip_notification',
                'key' => 'customer_trip_notification',
                'type' => 'customer',
                'mail_status' => 'active',
                'sms_status' => 'disable',
                'push_notification_status' => 'active',
                'created_at' => '2025-02-08 09:31:38',
                'updated_at' => '2025-02-08 09:31:38',
                'module_type' => 'rental',
            ),
            71 => 
            array (
                'id' => 75,
                'title' => 'customer_loyalty_point_earning',
                'sub_title' => 'Sent_notification_on_loyalty_point_earning',
                'key' => 'customer_loyalty_point_earning',
                'type' => 'customer',
                'mail_status' => 'disable',
                'sms_status' => 'disable',
                'push_notification_status' => 'active',
                'created_at' => '2025-02-08 09:31:38',
                'updated_at' => '2025-02-08 09:31:38',
                'module_type' => 'all',
            ),
            72 => 
            array (
                'id' => 76,
                'title' => 'Chatting',
                'sub_title' => 'Choose how the customer will get notified of message reply, attachment received',
                'key' => 'chatting',
                'type' => 'user',
                'mail_status' => 'disable',
                'sms_status' => 'disable',
                'push_notification_status' => 'active',
                'created_at' => '2025-09-04 04:55:09',
                'updated_at' => '2025-09-04 04:55:09',
                'module_type' => 'service',
            ),
            73 => 
            array (
                'id' => 77,
                'title' => 'Privacy policy update',
                'sub_title' => 'Choose how the customer will get notified of Privacy policy updates by the admin',
                'key' => 'privacy_policy_update',
                'type' => 'user',
                'mail_status' => 'disable',
                'sms_status' => 'disable',
                'push_notification_status' => 'active',
                'created_at' => '2025-09-04 04:55:09',
                'updated_at' => '2025-09-04 04:55:09',
                'module_type' => 'service',
            ),
            74 => 
            array (
                'id' => 78,
                'title' => 'Terms & Conditions',
                'sub_title' => 'Choose how the customer will get notified of Terms & Conditions Update by the admin',
                'key' => 'terms_&_conditions_update',
                'type' => 'user',
                'mail_status' => 'disable',
                'sms_status' => 'disable',
                'push_notification_status' => 'active',
                'created_at' => '2025-09-04 04:55:09',
                'updated_at' => '2025-09-04 04:55:09',
                'module_type' => 'service',
            ),
            75 => 
            array (
                'id' => 79,
                'title' => 'Loyalty point',
                'sub_title' => 'Choose how the customer will get notified of earning loyalty points as a reward',
                'key' => 'loyality_point',
                'type' => 'user',
                'mail_status' => 'disable',
                'sms_status' => 'disable',
                'push_notification_status' => 'active',
                'created_at' => '2025-09-04 04:55:09',
                'updated_at' => '2025-09-04 04:55:09',
                'module_type' => 'service',
            ),
            76 => 
            array (
                'id' => 80,
                'title' => 'Verification',
                'sub_title' => 'Choose how the customer will get notified of Email/Phone Verification and password recovery OTP sent via Email/Phone',
                'key' => 'verification',
                'type' => 'user',
                'mail_status' => 'active',
                'sms_status' => 'active',
                'push_notification_status' => 'disable',
                'created_at' => '2025-09-04 04:55:09',
                'updated_at' => '2025-09-04 04:55:09',
                'module_type' => 'service',
            ),
            77 => 
            array (
                'id' => 81,
                'title' => 'Booking',
                'sub_title' => 'Choose how the customer will get notified of all the bookings they placed in the system',
                'key' => 'booking',
                'type' => 'user',
                'mail_status' => 'active',
                'sms_status' => 'disable',
                'push_notification_status' => 'active',
                'created_at' => '2025-09-04 04:55:09',
                'updated_at' => '2025-09-04 04:55:09',
                'module_type' => 'service',
            ),
            78 => 
            array (
                'id' => 82,
                'title' => 'Wallet',
                'sub_title' => 'Choose how the customer will get notified of getting a bonus & Wallet balance from admin or add funds by himself',
                'key' => 'wallet',
                'type' => 'user',
                'mail_status' => 'disable',
                'sms_status' => 'disable',
                'push_notification_status' => 'active',
                'created_at' => '2025-09-04 04:55:09',
                'updated_at' => '2025-09-04 04:55:09',
                'module_type' => 'service',
            ),
            79 => 
            array (
                'id' => 83,
                'title' => 'Refer & earn',
                'sub_title' => 'Choose how the customer will get notified of refer code use, first booking completion, and get cashback as a reward',
                'key' => 'refer_earn',
                'type' => 'user',
                'mail_status' => 'disable',
                'sms_status' => 'disable',
                'push_notification_status' => 'active',
                'created_at' => '2025-09-04 04:55:09',
                'updated_at' => '2025-09-04 04:55:09',
                'module_type' => 'service',
            ),
            80 => 
            array (
                'id' => 84,
                'title' => 'Registration',
                'sub_title' => 'Choose how the customer will get notified when the admin registers the customer to the system',
                'key' => 'registration',
                'type' => 'user',
                'mail_status' => 'active',
                'sms_status' => 'disable',
                'push_notification_status' => 'disable',
                'created_at' => '2025-09-04 04:55:09',
                'updated_at' => '2025-09-04 04:55:09',
                'module_type' => 'service',
            ),
            81 => 
            array (
                'id' => 85,
                'title' => 'Chatting',
                'sub_title' => 'Choose how the provider will get notified of message reply, attachment received',
                'key' => 'chatting',
                'type' => 'provider',
                'mail_status' => 'disable',
                'sms_status' => 'disable',
                'push_notification_status' => 'active',
                'created_at' => '2025-09-04 04:55:09',
                'updated_at' => '2025-09-04 04:55:09',
                'module_type' => 'service',
            ),
            82 => 
            array (
                'id' => 86,
                'title' => 'Privacy policy update',
                'sub_title' => 'Choose how the provider will get notified of Privacy policy updates by the admin',
                'key' => 'privacy_policy_update',
                'type' => 'provider',
                'mail_status' => 'disable',
                'sms_status' => 'disable',
                'push_notification_status' => 'active',
                'created_at' => '2025-09-04 04:55:09',
                'updated_at' => '2025-09-04 04:55:09',
                'module_type' => 'service',
            ),
            83 => 
            array (
                'id' => 87,
                'title' => 'Terms & Conditions',
                'sub_title' => 'Choose how the provider will get notified of Terms & Conditions Update by the admin',
                'key' => 'terms_&_conditions_update',
                'type' => 'provider',
                'mail_status' => 'disable',
                'sms_status' => 'disable',
                'push_notification_status' => 'active',
                'created_at' => '2025-09-04 04:55:09',
                'updated_at' => '2025-09-04 04:55:09',
                'module_type' => 'service',
            ),
            84 => 
            array (
                'id' => 88,
                'title' => 'Verification',
                'sub_title' => 'Choose how the provider will get notified of Email/Phone Verification and password recovery OTP sent via Email/Phone',
                'key' => 'verification',
                'type' => 'provider',
                'mail_status' => 'active',
                'sms_status' => 'active',
                'push_notification_status' => 'disable',
                'created_at' => '2025-09-04 04:55:09',
                'updated_at' => '2025-09-04 04:55:09',
                'module_type' => 'service',
            ),
            85 => 
            array (
                'id' => 89,
                'title' => 'Booking',
                'sub_title' => 'Choose how the providers will get notified of new bookings, Booking Edits, Booking Status updates, Schedule time changes, and withdrawal request',
                'key' => 'booking',
                'type' => 'provider',
                'mail_status' => 'disable',
                'sms_status' => 'disable',
                'push_notification_status' => 'active',
                'created_at' => '2025-09-04 04:55:09',
                'updated_at' => '2025-09-04 04:55:09',
                'module_type' => 'service',
            ),
            86 => 
            array (
                'id' => 90,
                'title' => 'Advertisement',
                'sub_title' => 'Choose how the provider will get notified of advertisement requests accept, deny, run ads, expire ads, etc.',
                'key' => 'advertisement',
                'type' => 'provider',
                'mail_status' => 'disable',
                'sms_status' => 'disable',
                'push_notification_status' => 'active',
                'created_at' => '2025-09-04 04:55:09',
                'updated_at' => '2025-09-04 04:55:09',
                'module_type' => 'service',
            ),
            87 => 
            array (
                'id' => 91,
                'title' => 'System Update',
                'sub_title' => 'Choose how the provider will get notified of System Updates by the admin',
                'key' => 'system_update',
                'type' => 'provider',
                'mail_status' => 'active',
                'sms_status' => 'disable',
                'push_notification_status' => 'disable',
                'created_at' => '2025-09-04 04:55:09',
                'updated_at' => '2025-09-04 04:55:09',
                'module_type' => 'service',
            ),
            88 => 
            array (
                'id' => 92,
                'title' => 'Transaction',
                'sub_title' => 'Choose how the provider will get notified of suspend on exceeding cash in hand balance',
                'key' => 'transaction',
                'type' => 'provider',
                'mail_status' => 'disable',
                'sms_status' => 'disable',
                'push_notification_status' => 'active',
                'created_at' => '2025-09-04 04:55:09',
                'updated_at' => '2025-09-04 04:55:09',
                'module_type' => 'service',
            ),
            89 => 
            array (
                'id' => 93,
                'title' => 'Subscription',
                'sub_title' => 'Choose how the provider will get notified of the Subscription plan subscribe, shifted, renewed, canceled & updated.',
                'key' => 'subscription',
                'type' => 'provider',
                'mail_status' => 'active',
                'sms_status' => 'disable',
                'push_notification_status' => 'disable',
                'created_at' => '2025-09-04 04:55:09',
                'updated_at' => '2025-09-04 04:55:09',
                'module_type' => 'service',
            ),
            90 => 
            array (
                'id' => 94,
                'title' => 'Registration',
                'sub_title' => 'Choose how the provider will get notified of new registration approval or deny',
                'key' => 'registration',
                'type' => 'provider',
                'mail_status' => 'active',
                'sms_status' => 'disable',
                'push_notification_status' => 'disable',
                'created_at' => '2025-09-04 04:55:09',
                'updated_at' => '2025-09-04 04:55:09',
                'module_type' => 'service',
            ),
            91 => 
            array (
                'id' => 95,
                'title' => 'Verification',
                'sub_title' => 'Choose how the serviceman will get notified of password recovery OTP sent via Email/Phone',
                'key' => 'verification',
                'type' => 'serviceman',
                'mail_status' => 'active',
                'sms_status' => 'active',
                'push_notification_status' => 'disable',
                'created_at' => '2025-09-04 04:55:09',
                'updated_at' => '2025-09-04 04:55:09',
                'module_type' => 'service',
            ),
            92 => 
            array (
                'id' => 96,
                'title' => 'Chatting',
                'sub_title' => 'Choose how the serviceman will get notified of message reply, attachment received',
                'key' => 'chatting',
                'type' => 'serviceman',
                'mail_status' => 'disable',
                'sms_status' => 'disable',
                'push_notification_status' => 'active',
                'created_at' => '2025-09-04 04:55:09',
                'updated_at' => '2025-09-04 04:55:09',
                'module_type' => 'service',
            ),
            93 => 
            array (
                'id' => 97,
                'title' => 'Privacy policy update',
                'sub_title' => 'Choose how the serviceman  will get notified of Privacy policy updates by the admin',
                'key' => 'privacy_policy_update',
                'type' => 'serviceman',
                'mail_status' => 'disable',
                'sms_status' => 'disable',
                'push_notification_status' => 'active',
                'created_at' => '2025-09-04 04:55:09',
                'updated_at' => '2025-09-04 04:55:09',
                'module_type' => 'service',
            ),
            94 => 
            array (
                'id' => 98,
                'title' => 'Terms & Conditions Update',
                'sub_title' => 'Choose how the serviceman will get notified of Terms & Conditions Update by the admin',
                'key' => 'terms_&_conditions_update',
                'type' => 'serviceman',
                'mail_status' => 'disable',
                'sms_status' => 'disable',
                'push_notification_status' => 'active',
                'created_at' => '2025-09-04 04:55:09',
                'updated_at' => '2025-09-04 04:55:09',
                'module_type' => 'service',
            ),
            95 => 
            array (
                'id' => 99,
                'title' => 'Booking',
                'sub_title' => 'Choose how the serviceman will get notified of new booking assign, Booking Edits, Booking Status updates, Schedule time changes',
                'key' => 'booking',
                'type' => 'serviceman',
                'mail_status' => 'disable',
                'sms_status' => 'disable',
                'push_notification_status' => 'active',
                'created_at' => '2025-09-04 04:55:09',
                'updated_at' => '2025-09-04 04:55:09',
                'module_type' => 'service',
            ),
        ));
        
        
    }
}