<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class ReviewsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('reviews')->delete();
        
        \DB::table('reviews')->insert(array (
            0 => 
            array (
                'id' => 1,
                'item_id' => 264,
                'user_id' => 12,
                'comment' => 'So testy. 👌',
                'attachment' => '[]',
                'rating' => 5,
                'order_id' => 100039,
                'created_at' => '2022-09-29 14:42:55',
                'updated_at' => '2024-06-06 12:48:40',
                'item_campaign_id' => NULL,
                'status' => 1,
                'module_id' => 4,
                'store_id' => 45,
                'reply' => 'Thanks for your nice complement.',
                'review_id' => '100039',
                'replied_at' => NULL,
            ),
            1 => 
            array (
                'id' => 2,
                'item_id' => 10,
                'user_id' => 8,
                'comment' => 'Good product',
                'attachment' => '[]',
                'rating' => 4,
                'order_id' => 100104,
                'created_at' => '2025-04-20 18:16:31',
                'updated_at' => '2025-04-20 18:16:31',
                'item_campaign_id' => NULL,
                'status' => 1,
                'module_id' => 1,
                'store_id' => NULL,
                'reply' => NULL,
                'review_id' => '100104',
                'replied_at' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'item_id' => 7,
                'user_id' => 8,
                'comment' => NULL,
                'attachment' => '[]',
                'rating' => 4,
                'order_id' => 100104,
                'created_at' => '2025-04-20 18:16:34',
                'updated_at' => '2025-04-20 18:16:34',
                'item_campaign_id' => NULL,
                'status' => 1,
                'module_id' => 1,
                'store_id' => NULL,
                'reply' => NULL,
                'review_id' => '100104-2',
                'replied_at' => NULL,
            ),
            3 => 
            array (
                'id' => 4,
                'item_id' => 13,
                'user_id' => 8,
                'comment' => NULL,
                'attachment' => '[]',
                'rating' => 5,
                'order_id' => 100104,
                'created_at' => '2025-04-20 18:16:37',
                'updated_at' => '2025-04-20 18:16:37',
                'item_campaign_id' => NULL,
                'status' => 1,
                'module_id' => 1,
                'store_id' => NULL,
                'reply' => NULL,
                'review_id' => '100104-3',
                'replied_at' => NULL,
            ),
            4 => 
            array (
                'id' => 5,
                'item_id' => 88,
                'user_id' => 8,
                'comment' => 'Nice kit',
                'attachment' => '[]',
                'rating' => 5,
                'order_id' => 100103,
                'created_at' => '2025-04-20 18:16:52',
                'updated_at' => '2025-04-20 18:16:52',
                'item_campaign_id' => NULL,
                'status' => 1,
                'module_id' => 2,
                'store_id' => NULL,
                'reply' => NULL,
                'review_id' => '100103',
                'replied_at' => NULL,
            ),
            5 => 
            array (
                'id' => 6,
                'item_id' => 86,
                'user_id' => 8,
                'comment' => 'Good pressure machine',
                'attachment' => '[]',
                'rating' => 4,
                'order_id' => 100103,
                'created_at' => '2025-04-20 18:17:10',
                'updated_at' => '2025-04-20 18:17:10',
                'item_campaign_id' => NULL,
                'status' => 1,
                'module_id' => 2,
                'store_id' => NULL,
                'reply' => NULL,
                'review_id' => '100103-2',
                'replied_at' => NULL,
            ),
            6 => 
            array (
                'id' => 7,
                'item_id' => 79,
                'user_id' => 8,
                'comment' => NULL,
                'attachment' => '[]',
                'rating' => 5,
                'order_id' => 100103,
                'created_at' => '2025-04-20 18:17:13',
                'updated_at' => '2025-04-20 18:17:13',
                'item_campaign_id' => NULL,
                'status' => 1,
                'module_id' => 2,
                'store_id' => NULL,
                'reply' => NULL,
                'review_id' => '100103-3',
                'replied_at' => NULL,
            ),
            7 => 
            array (
                'id' => 8,
                'item_id' => 76,
                'user_id' => 8,
                'comment' => NULL,
                'attachment' => '[]',
                'rating' => 5,
                'order_id' => 100103,
                'created_at' => '2025-04-20 18:17:17',
                'updated_at' => '2025-04-20 18:17:17',
                'item_campaign_id' => NULL,
                'status' => 1,
                'module_id' => 2,
                'store_id' => NULL,
                'reply' => NULL,
                'review_id' => '100103-4',
                'replied_at' => NULL,
            ),
            8 => 
            array (
                'id' => 9,
                'item_id' => 132,
                'user_id' => 8,
                'comment' => NULL,
                'attachment' => '[]',
                'rating' => 2,
                'order_id' => 100105,
                'created_at' => '2025-04-20 18:19:16',
                'updated_at' => '2025-04-20 18:19:16',
                'item_campaign_id' => NULL,
                'status' => 1,
                'module_id' => 3,
                'store_id' => NULL,
                'reply' => NULL,
                'review_id' => '100105',
                'replied_at' => NULL,
            ),
            9 => 
            array (
                'id' => 10,
                'item_id' => 126,
                'user_id' => 8,
                'comment' => NULL,
                'attachment' => '[]',
                'rating' => 5,
                'order_id' => 100105,
                'created_at' => '2025-04-20 18:19:17',
                'updated_at' => '2025-04-20 18:19:17',
                'item_campaign_id' => NULL,
                'status' => 1,
                'module_id' => 3,
                'store_id' => NULL,
                'reply' => NULL,
                'review_id' => '100105-2',
                'replied_at' => NULL,
            ),
            10 => 
            array (
                'id' => 11,
                'item_id' => 95,
                'user_id' => 8,
                'comment' => NULL,
                'attachment' => '[]',
                'rating' => 5,
                'order_id' => 100105,
                'created_at' => '2025-04-20 18:19:20',
                'updated_at' => '2025-04-20 18:19:20',
                'item_campaign_id' => NULL,
                'status' => 1,
                'module_id' => 3,
                'store_id' => NULL,
                'reply' => NULL,
                'review_id' => '100105-3',
                'replied_at' => NULL,
            ),
            11 => 
            array (
                'id' => 12,
                'item_id' => 58,
                'user_id' => 8,
                'comment' => 'Nice dress',
                'attachment' => '[]',
                'rating' => 4,
                'order_id' => 100105,
                'created_at' => '2025-04-20 18:19:32',
                'updated_at' => '2025-04-20 18:19:32',
                'item_campaign_id' => NULL,
                'status' => 1,
                'module_id' => 3,
                'store_id' => NULL,
                'reply' => NULL,
                'review_id' => '100105-4',
                'replied_at' => NULL,
            ),
            12 => 
            array (
                'id' => 13,
                'item_id' => 324,
                'user_id' => 8,
                'comment' => 'Good food',
                'attachment' => '[]',
                'rating' => 5,
                'order_id' => 100106,
                'created_at' => '2025-04-20 18:20:03',
                'updated_at' => '2025-04-20 18:20:03',
                'item_campaign_id' => NULL,
                'status' => 1,
                'module_id' => 4,
                'store_id' => NULL,
                'reply' => NULL,
                'review_id' => '100106',
                'replied_at' => NULL,
            ),
            13 => 
            array (
                'id' => 14,
                'item_id' => 328,
                'user_id' => 8,
                'comment' => 'Good food',
                'attachment' => '[]',
                'rating' => 5,
                'order_id' => 100106,
                'created_at' => '2025-04-20 18:20:05',
                'updated_at' => '2025-04-20 18:20:05',
                'item_campaign_id' => NULL,
                'status' => 1,
                'module_id' => 4,
                'store_id' => NULL,
                'reply' => NULL,
                'review_id' => '100106-2',
                'replied_at' => NULL,
            ),
            14 => 
            array (
                'id' => 15,
                'item_id' => 316,
                'user_id' => 8,
                'comment' => NULL,
                'attachment' => '[]',
                'rating' => 4,
                'order_id' => 100106,
                'created_at' => '2025-04-20 18:20:09',
                'updated_at' => '2025-04-20 18:20:09',
                'item_campaign_id' => NULL,
                'status' => 1,
                'module_id' => 4,
                'store_id' => NULL,
                'reply' => NULL,
                'review_id' => '100106-3',
                'replied_at' => NULL,
            ),
        ));
        
        
    }
}