<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class RideReviewsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('ride_reviews')->delete();
        
        \DB::table('ride_reviews')->insert(array (
            0 => 
            array (
                'id' => 1,
                'ride_request_id' => 1,
                'given_by' => 1,
                'received_by' => 8,
                'ride_type' => 'ride_request',
                'rating' => 5,
                'feedback' => NULL,
                'images' => NULL,
                'review_for' => 'customer',
                'is_saved' => 0,
                'deleted_at' => NULL,
                'created_at' => '2025-09-08 06:21:59',
                'updated_at' => '2025-09-08 06:21:59',
            ),
            1 => 
            array (
                'id' => 2,
                'ride_request_id' => 1,
                'given_by' => 8,
                'received_by' => 1,
                'ride_type' => 'ride_request',
                'rating' => 5,
                'feedback' => NULL,
                'images' => NULL,
                'review_for' => 'driver',
                'is_saved' => 0,
                'deleted_at' => NULL,
                'created_at' => '2025-09-08 06:23:27',
                'updated_at' => '2025-09-08 06:23:27',
            ),
            2 => 
            array (
                'id' => 3,
                'ride_request_id' => 9,
                'given_by' => 10,
                'received_by' => 1,
                'ride_type' => 'ride_request',
                'rating' => 1,
                'feedback' => 'dr',
                'images' => NULL,
                'review_for' => 'driver',
                'is_saved' => 1,
                'deleted_at' => NULL,
                'created_at' => '2025-09-08 09:08:14',
                'updated_at' => '2025-09-08 09:08:39',
            ),
            3 => 
            array (
                'id' => 4,
                'ride_request_id' => 9,
                'given_by' => 1,
                'received_by' => 10,
                'ride_type' => 'ride_request',
                'rating' => 1,
                'feedback' => 'sd',
                'images' => NULL,
                'review_for' => 'customer',
                'is_saved' => 0,
                'deleted_at' => NULL,
                'created_at' => '2025-09-08 09:08:56',
                'updated_at' => '2025-09-08 09:08:56',
            ),
            4 => 
            array (
                'id' => 5,
                'ride_request_id' => 10,
                'given_by' => 1,
                'received_by' => 10,
                'ride_type' => 'ride_request',
                'rating' => 4,
                'feedback' => 'ttttttt',
                'images' => NULL,
                'review_for' => 'customer',
                'is_saved' => 0,
                'deleted_at' => NULL,
                'created_at' => '2025-09-08 10:09:28',
                'updated_at' => '2025-09-08 10:09:28',
            ),
            5 => 
            array (
                'id' => 6,
                'ride_request_id' => 10,
                'given_by' => 10,
                'received_by' => 1,
                'ride_type' => 'ride_request',
                'rating' => 4,
                'feedback' => 'ggggggg',
                'images' => NULL,
                'review_for' => 'driver',
                'is_saved' => 0,
                'deleted_at' => NULL,
                'created_at' => '2025-09-08 10:09:58',
                'updated_at' => '2025-09-08 10:09:58',
            ),
            6 => 
            array (
                'id' => 7,
                'ride_request_id' => 12,
                'given_by' => 21,
                'received_by' => 10,
                'ride_type' => 'ride_request',
                'rating' => 3,
                'feedback' => 'fsdgbfdgbfsd',
                'images' => NULL,
                'review_for' => 'driver',
                'is_saved' => 0,
                'deleted_at' => NULL,
                'created_at' => '2025-09-09 13:01:13',
                'updated_at' => '2025-09-09 13:01:13',
            ),
            7 => 
            array (
                'id' => 8,
                'ride_request_id' => 25,
                'given_by' => 21,
                'received_by' => 11,
                'ride_type' => 'ride_request',
                'rating' => 5,
                'feedback' => NULL,
                'images' => NULL,
                'review_for' => 'driver',
                'is_saved' => 0,
                'deleted_at' => NULL,
                'created_at' => '2025-09-11 13:05:18',
                'updated_at' => '2025-09-11 13:05:18',
            ),
            8 => 
            array (
                'id' => 9,
                'ride_request_id' => 35,
                'given_by' => 9,
                'received_by' => 33,
                'ride_type' => 'ride_request',
                'rating' => 3,
                'feedback' => NULL,
                'images' => NULL,
                'review_for' => 'customer',
                'is_saved' => 0,
                'deleted_at' => NULL,
                'created_at' => '2025-09-14 10:35:58',
                'updated_at' => '2025-09-14 10:35:58',
            ),
            9 => 
            array (
                'id' => 10,
                'ride_request_id' => 35,
                'given_by' => 33,
                'received_by' => 9,
                'ride_type' => 'ride_request',
                'rating' => 3,
                'feedback' => NULL,
                'images' => NULL,
                'review_for' => 'driver',
                'is_saved' => 0,
                'deleted_at' => NULL,
                'created_at' => '2025-09-14 10:36:04',
                'updated_at' => '2025-09-14 10:36:04',
            ),
            10 => 
            array (
                'id' => 11,
                'ride_request_id' => 53,
                'given_by' => 33,
                'received_by' => 9,
                'ride_type' => 'ride_request',
                'rating' => 5,
                'feedback' => 'Bbjjj',
                'images' => NULL,
                'review_for' => 'driver',
                'is_saved' => 0,
                'deleted_at' => NULL,
                'created_at' => '2025-09-15 16:42:04',
                'updated_at' => '2025-09-15 16:42:04',
            ),
            11 => 
            array (
                'id' => 12,
                'ride_request_id' => 52,
                'given_by' => 33,
                'received_by' => 9,
                'ride_type' => 'ride_request',
                'rating' => 5,
                'feedback' => NULL,
                'images' => NULL,
                'review_for' => 'driver',
                'is_saved' => 0,
                'deleted_at' => NULL,
                'created_at' => '2025-09-15 16:44:37',
                'updated_at' => '2025-09-15 16:44:37',
            ),
            12 => 
            array (
                'id' => 13,
                'ride_request_id' => 56,
                'given_by' => 9,
                'received_by' => 33,
                'ride_type' => 'ride_request',
                'rating' => 5,
                'feedback' => 'Nice',
                'images' => NULL,
                'review_for' => 'customer',
                'is_saved' => 0,
                'deleted_at' => NULL,
                'created_at' => '2025-09-15 17:59:19',
                'updated_at' => '2025-09-15 17:59:19',
            ),
            13 => 
            array (
                'id' => 14,
                'ride_request_id' => 55,
                'given_by' => 9,
                'received_by' => 33,
                'ride_type' => 'ride_request',
                'rating' => 5,
                'feedback' => NULL,
                'images' => NULL,
                'review_for' => 'customer',
                'is_saved' => 0,
                'deleted_at' => NULL,
                'created_at' => '2025-09-15 18:04:38',
                'updated_at' => '2025-09-15 18:04:38',
            ),
            14 => 
            array (
                'id' => 15,
                'ride_request_id' => 67,
                'given_by' => 21,
                'received_by' => 11,
                'ride_type' => 'ride_request',
                'rating' => 5,
                'feedback' => NULL,
                'images' => NULL,
                'review_for' => 'driver',
                'is_saved' => 0,
                'deleted_at' => NULL,
                'created_at' => '2025-09-16 17:56:15',
                'updated_at' => '2025-09-16 17:56:15',
            ),
            15 => 
            array (
                'id' => 16,
                'ride_request_id' => 79,
                'given_by' => 21,
                'received_by' => 9,
                'ride_type' => 'ride_request',
                'rating' => 5,
                'feedback' => NULL,
                'images' => NULL,
                'review_for' => 'driver',
                'is_saved' => 0,
                'deleted_at' => NULL,
                'created_at' => '2025-09-18 13:20:00',
                'updated_at' => '2025-09-18 13:20:00',
            ),
            16 => 
            array (
                'id' => 17,
                'ride_request_id' => 79,
                'given_by' => 9,
                'received_by' => 21,
                'ride_type' => 'ride_request',
                'rating' => 5,
                'feedback' => NULL,
                'images' => NULL,
                'review_for' => 'customer',
                'is_saved' => 0,
                'deleted_at' => NULL,
                'created_at' => '2025-09-18 13:20:04',
                'updated_at' => '2025-09-18 13:20:04',
            ),
            17 => 
            array (
                'id' => 18,
                'ride_request_id' => 78,
                'given_by' => 33,
                'received_by' => 9,
                'ride_type' => 'ride_request',
                'rating' => 5,
                'feedback' => 'b bvh',
                'images' => NULL,
                'review_for' => 'driver',
                'is_saved' => 0,
                'deleted_at' => NULL,
                'created_at' => '2025-09-18 15:24:53',
                'updated_at' => '2025-09-18 15:24:53',
            ),
            18 => 
            array (
                'id' => 19,
                'ride_request_id' => 86,
                'given_by' => 10,
                'received_by' => 8,
                'ride_type' => 'ride_request',
                'rating' => 5,
                'feedback' => NULL,
                'images' => NULL,
                'review_for' => 'customer',
                'is_saved' => 0,
                'deleted_at' => NULL,
                'created_at' => '2025-09-18 21:21:41',
                'updated_at' => '2025-09-18 21:21:41',
            ),
            19 => 
            array (
                'id' => 20,
                'ride_request_id' => 91,
                'given_by' => 21,
                'received_by' => 1,
                'ride_type' => 'ride_request',
                'rating' => 5,
                'feedback' => 'gtfdgfdcgf',
                'images' => NULL,
                'review_for' => 'driver',
                'is_saved' => 0,
                'deleted_at' => NULL,
                'created_at' => '2025-09-21 14:31:31',
                'updated_at' => '2025-09-21 14:31:31',
            ),
            20 => 
            array (
                'id' => 21,
                'ride_request_id' => 98,
                'given_by' => 21,
                'received_by' => 1,
                'ride_type' => 'ride_request',
                'rating' => 5,
                'feedback' => NULL,
                'images' => NULL,
                'review_for' => 'driver',
                'is_saved' => 0,
                'deleted_at' => NULL,
                'created_at' => '2025-09-24 13:13:12',
                'updated_at' => '2025-09-24 13:13:12',
            ),
            21 => 
            array (
                'id' => 22,
                'ride_request_id' => 98,
                'given_by' => 1,
                'received_by' => 21,
                'ride_type' => 'ride_request',
                'rating' => 5,
                'feedback' => NULL,
                'images' => NULL,
                'review_for' => 'customer',
                'is_saved' => 0,
                'deleted_at' => NULL,
                'created_at' => '2025-09-24 13:13:16',
                'updated_at' => '2025-09-24 13:13:16',
            ),
            22 => 
            array (
                'id' => 23,
                'ride_request_id' => 78,
                'given_by' => 9,
                'received_by' => 33,
                'ride_type' => 'ride_request',
                'rating' => 4,
                'feedback' => 'Good',
                'images' => NULL,
                'review_for' => 'customer',
                'is_saved' => 0,
                'deleted_at' => NULL,
                'created_at' => '2025-09-25 17:11:48',
                'updated_at' => '2025-09-25 17:11:48',
            ),
            23 => 
            array (
                'id' => 24,
                'ride_request_id' => 191,
                'given_by' => 33,
                'received_by' => 9,
                'ride_type' => 'ride_request',
                'rating' => 4,
                'feedback' => 'Good',
                'images' => NULL,
                'review_for' => 'driver',
                'is_saved' => 1,
                'deleted_at' => NULL,
                'created_at' => '2025-09-29 16:51:53',
                'updated_at' => '2025-09-29 17:09:57',
            ),
            24 => 
            array (
                'id' => 25,
                'ride_request_id' => 193,
                'given_by' => 9,
                'received_by' => 33,
                'ride_type' => 'ride_request',
                'rating' => 4,
                'feedback' => 'Good',
                'images' => NULL,
                'review_for' => 'customer',
                'is_saved' => 0,
                'deleted_at' => NULL,
                'created_at' => '2025-09-29 17:08:28',
                'updated_at' => '2025-09-29 17:08:28',
            ),
            25 => 
            array (
                'id' => 26,
                'ride_request_id' => 193,
                'given_by' => 33,
                'received_by' => 9,
                'ride_type' => 'ride_request',
                'rating' => 5,
                'feedback' => 'Professional rider',
                'images' => NULL,
                'review_for' => 'driver',
                'is_saved' => 1,
                'deleted_at' => NULL,
                'created_at' => '2025-09-29 17:09:20',
                'updated_at' => '2025-09-29 17:09:55',
            ),
            26 => 
            array (
                'id' => 27,
                'ride_request_id' => 217,
                'given_by' => 1,
                'received_by' => 21,
                'ride_type' => 'ride_request',
                'rating' => 5,
                'feedback' => 'Ghhh',
                'images' => NULL,
                'review_for' => 'customer',
                'is_saved' => 0,
                'deleted_at' => NULL,
                'created_at' => '2025-09-30 20:56:41',
                'updated_at' => '2025-09-30 20:56:41',
            ),
            27 => 
            array (
                'id' => 28,
                'ride_request_id' => 217,
                'given_by' => 21,
                'received_by' => 1,
                'ride_type' => 'ride_request',
                'rating' => 5,
                'feedback' => '👍',
                'images' => NULL,
                'review_for' => 'driver',
                'is_saved' => 0,
                'deleted_at' => NULL,
                'created_at' => '2025-09-30 20:56:53',
                'updated_at' => '2025-09-30 20:56:53',
            ),
            28 => 
            array (
                'id' => 29,
                'ride_request_id' => 219,
                'given_by' => 21,
                'received_by' => 1,
                'ride_type' => 'ride_request',
                'rating' => 5,
                'feedback' => NULL,
                'images' => NULL,
                'review_for' => 'driver',
                'is_saved' => 0,
                'deleted_at' => NULL,
                'created_at' => '2025-10-04 11:36:12',
                'updated_at' => '2025-10-04 11:36:12',
            ),
            29 => 
            array (
                'id' => 30,
                'ride_request_id' => 191,
                'given_by' => 9,
                'received_by' => 33,
                'ride_type' => 'ride_request',
                'rating' => 3,
                'feedback' => 'Nice',
                'images' => NULL,
                'review_for' => 'customer',
                'is_saved' => 0,
                'deleted_at' => NULL,
                'created_at' => '2025-10-06 09:55:15',
                'updated_at' => '2025-10-06 09:55:15',
            ),
            30 => 
            array (
                'id' => 31,
                'ride_request_id' => 183,
                'given_by' => 9,
                'received_by' => 33,
                'ride_type' => 'ride_request',
                'rating' => 4,
                'feedback' => 'Nice Nice nice',
                'images' => NULL,
                'review_for' => 'customer',
                'is_saved' => 0,
                'deleted_at' => NULL,
                'created_at' => '2025-10-06 10:15:16',
                'updated_at' => '2025-10-06 10:15:16',
            ),
            31 => 
            array (
                'id' => 32,
                'ride_request_id' => 177,
                'given_by' => 9,
                'received_by' => 33,
                'ride_type' => 'ride_request',
                'rating' => 3,
                'feedback' => 'Tbtbtbtb',
                'images' => NULL,
                'review_for' => 'customer',
                'is_saved' => 0,
                'deleted_at' => NULL,
                'created_at' => '2025-10-06 10:20:46',
                'updated_at' => '2025-10-06 10:20:46',
            ),
            32 => 
            array (
                'id' => 33,
                'ride_request_id' => 165,
                'given_by' => 9,
                'received_by' => 33,
                'ride_type' => 'ride_request',
                'rating' => 3,
                'feedback' => 'Niceeee',
                'images' => NULL,
                'review_for' => 'customer',
                'is_saved' => 0,
                'deleted_at' => NULL,
                'created_at' => '2025-10-06 10:36:24',
                'updated_at' => '2025-10-06 10:36:24',
            ),
            33 => 
            array (
                'id' => 34,
                'ride_request_id' => 230,
                'given_by' => 9,
                'received_by' => 33,
                'ride_type' => 'ride_request',
                'rating' => 4,
                'feedback' => 'Dsddd',
                'images' => NULL,
                'review_for' => 'customer',
                'is_saved' => 0,
                'deleted_at' => NULL,
                'created_at' => '2025-10-07 13:30:46',
                'updated_at' => '2025-10-07 13:30:46',
            ),
            34 => 
            array (
                'id' => 35,
                'ride_request_id' => 250,
                'given_by' => 33,
                'received_by' => 9,
                'ride_type' => 'ride_request',
                'rating' => 5,
                'feedback' => NULL,
                'images' => NULL,
                'review_for' => 'driver',
                'is_saved' => 0,
                'deleted_at' => NULL,
                'created_at' => '2025-10-07 17:54:54',
                'updated_at' => '2025-10-07 17:54:54',
            ),
            35 => 
            array (
                'id' => 36,
                'ride_request_id' => 259,
                'given_by' => 33,
                'received_by' => 9,
                'ride_type' => 'ride_request',
                'rating' => 5,
                'feedback' => NULL,
                'images' => NULL,
                'review_for' => 'driver',
                'is_saved' => 0,
                'deleted_at' => NULL,
                'created_at' => '2025-10-08 12:43:21',
                'updated_at' => '2025-10-08 12:43:21',
            ),
            36 => 
            array (
                'id' => 37,
                'ride_request_id' => 260,
                'given_by' => 33,
                'received_by' => 9,
                'ride_type' => 'ride_request',
                'rating' => 5,
                'feedback' => NULL,
                'images' => NULL,
                'review_for' => 'driver',
                'is_saved' => 0,
                'deleted_at' => NULL,
                'created_at' => '2025-10-08 12:45:00',
                'updated_at' => '2025-10-08 12:45:00',
            ),
            37 => 
            array (
                'id' => 38,
                'ride_request_id' => 260,
                'given_by' => 9,
                'received_by' => 33,
                'ride_type' => 'ride_request',
                'rating' => 5,
                'feedback' => 'Vxvsvs',
                'images' => NULL,
                'review_for' => 'customer',
                'is_saved' => 0,
                'deleted_at' => NULL,
                'created_at' => '2025-10-08 12:45:16',
                'updated_at' => '2025-10-08 12:45:16',
            ),
            38 => 
            array (
                'id' => 39,
                'ride_request_id' => 264,
                'given_by' => 9,
                'received_by' => 33,
                'ride_type' => 'ride_request',
                'rating' => 5,
                'feedback' => 'Yfyffy',
                'images' => NULL,
                'review_for' => 'customer',
                'is_saved' => 0,
                'deleted_at' => NULL,
                'created_at' => '2025-10-08 17:01:02',
                'updated_at' => '2025-10-08 17:01:02',
            ),
            39 => 
            array (
                'id' => 40,
                'ride_request_id' => 269,
                'given_by' => 33,
                'received_by' => 9,
                'ride_type' => 'ride_request',
                'rating' => 5,
                'feedback' => 'Testtt',
                'images' => NULL,
                'review_for' => 'driver',
                'is_saved' => 0,
                'deleted_at' => NULL,
                'created_at' => '2025-10-09 15:16:20',
                'updated_at' => '2025-10-09 15:16:20',
            ),
            40 => 
            array (
                'id' => 41,
                'ride_request_id' => 377,
                'given_by' => 33,
                'received_by' => 9,
                'ride_type' => 'ride_request',
                'rating' => 1,
                'feedback' => 'Nice',
                'images' => NULL,
                'review_for' => 'driver',
                'is_saved' => 1,
                'deleted_at' => NULL,
                'created_at' => '2025-10-12 10:46:59',
                'updated_at' => '2025-10-12 10:47:27',
            ),
            41 => 
            array (
                'id' => 42,
                'ride_request_id' => 437,
                'given_by' => 37,
                'received_by' => 24,
                'ride_type' => 'ride_request',
                'rating' => 5,
                'feedback' => NULL,
                'images' => NULL,
                'review_for' => 'driver',
                'is_saved' => 0,
                'deleted_at' => NULL,
                'created_at' => '2025-10-12 16:08:27',
                'updated_at' => '2025-10-12 16:08:27',
            ),
            42 => 
            array (
                'id' => 43,
                'ride_request_id' => 437,
                'given_by' => 24,
                'received_by' => 37,
                'ride_type' => 'ride_request',
                'rating' => 5,
                'feedback' => NULL,
                'images' => NULL,
                'review_for' => 'customer',
                'is_saved' => 0,
                'deleted_at' => NULL,
                'created_at' => '2025-10-12 16:09:06',
                'updated_at' => '2025-10-12 16:09:06',
            ),
            43 => 
            array (
                'id' => 44,
                'ride_request_id' => 441,
                'given_by' => 37,
                'received_by' => 24,
                'ride_type' => 'ride_request',
                'rating' => 5,
                'feedback' => NULL,
                'images' => NULL,
                'review_for' => 'driver',
                'is_saved' => 0,
                'deleted_at' => NULL,
                'created_at' => '2025-10-12 17:47:54',
                'updated_at' => '2025-10-12 17:47:54',
            ),
            44 => 
            array (
                'id' => 45,
                'ride_request_id' => 441,
                'given_by' => 24,
                'received_by' => 37,
                'ride_type' => 'ride_request',
                'rating' => 5,
                'feedback' => 'Helpfull',
                'images' => NULL,
                'review_for' => 'customer',
                'is_saved' => 0,
                'deleted_at' => NULL,
                'created_at' => '2025-10-12 17:49:46',
                'updated_at' => '2025-10-12 17:49:46',
            ),
            45 => 
            array (
                'id' => 46,
                'ride_request_id' => 453,
                'given_by' => 2,
                'received_by' => 32,
                'ride_type' => 'ride_request',
                'rating' => 1,
                'feedback' => NULL,
                'images' => NULL,
                'review_for' => 'customer',
                'is_saved' => 0,
                'deleted_at' => NULL,
                'created_at' => '2025-10-12 18:38:35',
                'updated_at' => '2025-10-12 18:38:35',
            ),
            46 => 
            array (
                'id' => 47,
                'ride_request_id' => 465,
                'given_by' => 2,
                'received_by' => 32,
                'ride_type' => 'ride_request',
                'rating' => 5,
                'feedback' => NULL,
                'images' => NULL,
                'review_for' => 'customer',
                'is_saved' => 0,
                'deleted_at' => NULL,
                'created_at' => '2025-10-12 19:23:54',
                'updated_at' => '2025-10-12 19:23:54',
            ),
            47 => 
            array (
                'id' => 48,
                'ride_request_id' => 495,
                'given_by' => 21,
                'received_by' => 1,
                'ride_type' => 'ride_request',
                'rating' => 4,
                'feedback' => 'Good',
                'images' => NULL,
                'review_for' => 'driver',
                'is_saved' => 0,
                'deleted_at' => NULL,
                'created_at' => '2025-10-13 14:34:11',
                'updated_at' => '2025-10-13 14:34:11',
            ),
            48 => 
            array (
                'id' => 49,
                'ride_request_id' => 495,
                'given_by' => 1,
                'received_by' => 21,
                'ride_type' => 'ride_request',
                'rating' => 5,
                'feedback' => 'Good',
                'images' => NULL,
                'review_for' => 'customer',
                'is_saved' => 0,
                'deleted_at' => NULL,
                'created_at' => '2025-10-13 14:34:36',
                'updated_at' => '2025-10-13 14:34:36',
            ),
            49 => 
            array (
                'id' => 50,
                'ride_request_id' => 514,
                'given_by' => 2,
                'received_by' => 32,
                'ride_type' => 'ride_request',
                'rating' => 5,
                'feedback' => NULL,
                'images' => NULL,
                'review_for' => 'customer',
                'is_saved' => 0,
                'deleted_at' => NULL,
                'created_at' => '2025-10-13 16:39:20',
                'updated_at' => '2025-10-13 16:39:20',
            ),
        ));
        
        
    }
}