<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class RideSafetyAlertsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('ride_safety_alerts')->delete();
        
        \DB::table('ride_safety_alerts')->insert(array (
            0 => 
            array (
                'id' => 1,
                'ride_request_id' => 4,
                'sent_by' => 8,
                'sent_by_type' => 'customer',
                'reason' => '["Driver stopped to pick up items unrelated to the trip.", "System flagged that a passenger may have been left at the wrong location."]',
                'comment' => NULL,
                'alert_location' => 'H-1007, 9 Avenue 11, ঢাকা, Bangladesh',
                'resolved_location' => 'H-1007, 9 Avenue 11, ঢাকা, Bangladesh',
                'number_of_alert' => 3,
                'resolved_by' => 1,
                'resolved_by_type' => 'admin',
                'ride_status_when_make_alert' => 'ongoing',
                'status' => 'solved',
                'created_at' => '2025-09-08 06:44:15',
                'updated_at' => '2025-09-08 07:56:57',
            ),
            1 => 
            array (
                'id' => 2,
                'ride_request_id' => 4,
                'sent_by' => 1,
                'sent_by_type' => 'driver',
                'reason' => '["Lost item reported: Passenger\'s phone left on the backseat", "Vehicle entered a construction zone without proper notification."]',
                'comment' => NULL,
                'alert_location' => 'H-1007, 9 Avenue 11, ঢাকা, Bangladesh',
                'resolved_location' => 'H-1007, 9 Avenue 11, ঢাকা, Bangladesh',
                'number_of_alert' => 8,
                'resolved_by' => 1,
                'resolved_by_type' => 'admin',
                'ride_status_when_make_alert' => 'ongoing',
                'status' => 'solved',
                'created_at' => '2025-09-08 06:44:22',
                'updated_at' => '2025-09-08 07:57:44',
            ),
            2 => 
            array (
                'id' => 4,
                'ride_request_id' => 25,
                'sent_by' => 21,
                'sent_by_type' => 'customer',
                'reason' => '["Abrupt braking was recorded by the system, indicating a potential risk"]',
                'comment' => NULL,
                'alert_location' => '1005 Avenue 11, Dhaka, Bangladesh',
                'resolved_location' => NULL,
                'number_of_alert' => 1,
                'resolved_by' => NULL,
                'resolved_by_type' => NULL,
                'ride_status_when_make_alert' => 'ongoing',
                'status' => 'pending',
                'created_at' => '2025-09-11 13:02:53',
                'updated_at' => '2025-09-11 13:02:53',
            ),
            3 => 
            array (
                'id' => 5,
                'ride_request_id' => 43,
                'sent_by' => 33,
                'sent_by_type' => 'customer',
                'reason' => '["Driver allowed an additional rider without authorization."]',
                'comment' => NULL,
                'alert_location' => '1005 Avenue 11, Dhaka, Bangladesh',
                'resolved_location' => NULL,
                'number_of_alert' => 1,
                'resolved_by' => NULL,
                'resolved_by_type' => NULL,
                'ride_status_when_make_alert' => 'ongoing',
                'status' => 'pending',
                'created_at' => '2025-09-14 17:07:44',
                'updated_at' => '2025-09-14 17:07:44',
            ),
            4 => 
            array (
                'id' => 6,
                'ride_request_id' => 78,
                'sent_by' => 33,
                'sent_by_type' => 'customer',
                'reason' => '["Abrupt braking was recorded by the system, indicating a potential risk"]',
                'comment' => 'need help',
                'alert_location' => '1005 Avenue 11, Dhaka, Bangladesh',
                'resolved_location' => NULL,
                'number_of_alert' => 1,
                'resolved_by' => NULL,
                'resolved_by_type' => NULL,
                'ride_status_when_make_alert' => 'ongoing',
                'status' => 'pending',
                'created_at' => '2025-09-18 11:37:34',
                'updated_at' => '2025-09-18 11:37:34',
            ),
            5 => 
            array (
                'id' => 7,
                'ride_request_id' => 103,
                'sent_by' => 21,
                'sent_by_type' => 'customer',
                'reason' => '["Abrupt braking was recorded by the system, indicating a potential risk", "The driver strayed significantly from the assigned route"]',
                'comment' => NULL,
                'alert_location' => '13/2 east madartak .Singapore road .basaboo, ঢাকা 1212, Bangladesh',
                'resolved_location' => '1005 Avenue 11, Dhaka, Bangladesh',
                'number_of_alert' => 1,
                'resolved_by' => 21,
                'resolved_by_type' => 'customer',
                'ride_status_when_make_alert' => 'ongoing',
                'status' => 'solved',
                'created_at' => '2025-09-25 10:54:36',
                'updated_at' => '2025-09-25 11:01:41',
            ),
            6 => 
            array (
                'id' => 8,
                'ride_request_id' => 115,
                'sent_by' => 33,
                'sent_by_type' => 'customer',
                'reason' => '["The driver strayed significantly from the assigned route"]',
                'comment' => 'gv bhbh uggu hugu',
                'alert_location' => '1005 Avenue 11, Dhaka, Bangladesh',
                'resolved_location' => NULL,
                'number_of_alert' => 1,
                'resolved_by' => NULL,
                'resolved_by_type' => NULL,
                'ride_status_when_make_alert' => 'ongoing',
                'status' => 'pending',
                'created_at' => '2025-09-25 17:02:02',
                'updated_at' => '2025-09-25 17:02:02',
            ),
            7 => 
            array (
                'id' => 9,
                'ride_request_id' => 120,
                'sent_by' => 33,
                'sent_by_type' => 'customer',
                'reason' => '["The vehicle exceeded the predefined speed limits"]',
                'comment' => NULL,
                'alert_location' => '1005 Avenue 11, Dhaka, Bangladesh',
                'resolved_location' => NULL,
                'number_of_alert' => 1,
                'resolved_by' => NULL,
                'resolved_by_type' => NULL,
                'ride_status_when_make_alert' => 'completed',
                'status' => 'pending',
                'created_at' => '2025-09-25 18:39:08',
                'updated_at' => '2025-09-25 18:39:08',
            ),
            8 => 
            array (
                'id' => 10,
                'ride_request_id' => 221,
                'sent_by' => 9,
                'sent_by_type' => 'driver',
                'reason' => '["Abrupt braking was recorded by the system, indicating a potential risk"]',
                'comment' => NULL,
                'alert_location' => '1005 Avenue 11, Dhaka, Bangladesh',
                'resolved_location' => NULL,
                'number_of_alert' => 1,
                'resolved_by' => NULL,
                'resolved_by_type' => NULL,
                'ride_status_when_make_alert' => 'ongoing',
                'status' => 'pending',
                'created_at' => '2025-10-05 17:38:19',
                'updated_at' => '2025-10-05 17:38:19',
            ),
            9 => 
            array (
                'id' => 11,
                'ride_request_id' => 256,
                'sent_by' => 1,
                'sent_by_type' => 'driver',
                'reason' => '["Abrupt braking was recorded by the system, indicating a potential risk", "The vehicle has remained stationary for an unusual period"]',
                'comment' => NULL,
                'alert_location' => '13/2 east madartak .Singapore road .basaboo, ঢাকা 1212, Bangladesh',
                'resolved_location' => NULL,
                'number_of_alert' => 1,
                'resolved_by' => NULL,
                'resolved_by_type' => NULL,
                'ride_status_when_make_alert' => 'ongoing',
                'status' => 'pending',
                'created_at' => '2025-10-08 10:27:03',
                'updated_at' => '2025-10-08 10:27:03',
            ),
            10 => 
            array (
                'id' => 12,
                'ride_request_id' => 256,
                'sent_by' => 21,
                'sent_by_type' => 'customer',
                'reason' => '[]',
                'comment' => NULL,
                'alert_location' => '1005 Avenue 11, Dhaka, Bangladesh',
                'resolved_location' => NULL,
                'number_of_alert' => 1,
                'resolved_by' => NULL,
                'resolved_by_type' => NULL,
                'ride_status_when_make_alert' => 'ongoing',
                'status' => 'pending',
                'created_at' => '2025-10-08 10:37:59',
                'updated_at' => '2025-10-08 10:37:59',
            ),
            11 => 
            array (
                'id' => 13,
                'ride_request_id' => 261,
                'sent_by' => 21,
                'sent_by_type' => 'customer',
                'reason' => '["Abrupt braking was recorded by the system, indicating a potential risk", "The driver strayed significantly from the assigned route"]',
                'comment' => NULL,
                'alert_location' => '1005 Avenue 11, Dhaka, Bangladesh',
                'resolved_location' => '13/2 east madartak .Singapore road .basaboo, ঢাকা 1212, Bangladesh',
                'number_of_alert' => 1,
                'resolved_by' => 21,
                'resolved_by_type' => 'customer',
                'ride_status_when_make_alert' => 'ongoing',
                'status' => 'solved',
                'created_at' => '2025-10-08 12:46:45',
                'updated_at' => '2025-10-08 13:06:04',
            ),
            12 => 
            array (
                'id' => 14,
                'ride_request_id' => 261,
                'sent_by' => 1,
                'sent_by_type' => 'driver',
                'reason' => '["Abrupt braking was recorded by the system, indicating a potential risk", "The vehicle has remained stationary for an unusual period"]',
                'comment' => NULL,
                'alert_location' => '13/2 east madartak .Singapore road .basaboo, ঢাকা 1212, Bangladesh',
                'resolved_location' => NULL,
                'number_of_alert' => 1,
                'resolved_by' => NULL,
                'resolved_by_type' => NULL,
                'ride_status_when_make_alert' => 'ongoing',
                'status' => 'pending',
                'created_at' => '2025-10-08 12:53:41',
                'updated_at' => '2025-10-08 12:53:41',
            ),
            13 => 
            array (
                'id' => 15,
                'ride_request_id' => 257,
                'sent_by' => 33,
                'sent_by_type' => 'customer',
                'reason' => '["The driver strayed significantly from the assigned route"]',
                'comment' => NULL,
                'alert_location' => '1005 Avenue 11, Dhaka, Bangladesh',
                'resolved_location' => NULL,
                'number_of_alert' => 1,
                'resolved_by' => NULL,
                'resolved_by_type' => NULL,
                'ride_status_when_make_alert' => 'completed',
                'status' => 'pending',
                'created_at' => '2025-10-09 15:26:19',
                'updated_at' => '2025-10-09 15:26:19',
            ),
            14 => 
            array (
                'id' => 18,
                'ride_request_id' => 483,
                'sent_by' => 37,
                'sent_by_type' => 'customer',
                'reason' => '["Driver stopped to pick up items unrelated to the trip."]',
                'comment' => NULL,
                'alert_location' => '1005 Avenue 11, Dhaka, Bangladesh',
                'resolved_location' => NULL,
                'number_of_alert' => 1,
                'resolved_by' => NULL,
                'resolved_by_type' => NULL,
                'ride_status_when_make_alert' => 'ongoing',
                'status' => 'pending',
                'created_at' => '2025-10-13 11:43:20',
                'updated_at' => '2025-10-13 11:43:20',
            ),
        ));
        
        
    }
}