<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class RideCouponSetupsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('ride_coupon_setups')->delete();
        
        \DB::table('ride_coupon_setups')->insert(array (
            0 => 
            array (
                'id' => 1,
                'name' => 'NEW50',
                'description' => 'new 50',
                'user_id' => NULL,
                'min_trip_amount' => '100.00',
                'max_coupon_amount' => '110.00',
                'coupon' => '50.00',
                'amount_type' => 'percentage',
                'coupon_type' => 'default',
                'coupon_code' => 'NEW50',
                'limit' => 1,
                'start_date' => '2025-09-08',
                'end_date' => '2025-09-18',
                'rules' => NULL,
                'total_used' => '2.00',
                'total_amount' => '220.00',
                'is_active' => 0,
                'module_id' => 7,
                'zone_coupon_type' => 'custom',
                'customer_level_coupon_type' => 'custom',
                'customer_coupon_type' => 'custom',
                'category_coupon_type' => '["custom"]',
                'deleted_at' => NULL,
                'created_at' => '2025-09-08 09:18:56',
                'updated_at' => '2025-10-13 10:11:26',
            ),
            1 => 
            array (
                'id' => 2,
                'name' => 'Well Come Coupon',
                'description' => 'Well Come CouponWell Come CouponWell Come CouponWell Come Coupon',
                'user_id' => NULL,
                'min_trip_amount' => '1.00',
                'max_coupon_amount' => '100.00',
                'coupon' => '10.00',
                'amount_type' => 'percentage',
                'coupon_type' => 'default',
                'coupon_code' => 'welcome',
                'limit' => 33,
                'start_date' => '2025-09-09',
                'end_date' => '2025-09-19',
                'rules' => NULL,
                'total_used' => '0.00',
                'total_amount' => '0.00',
                'is_active' => 0,
                'module_id' => 7,
                'zone_coupon_type' => 'custom',
                'customer_level_coupon_type' => 'custom',
                'customer_coupon_type' => 'custom',
                'category_coupon_type' => '["custom"]',
                'deleted_at' => NULL,
                'created_at' => '2025-09-09 12:39:44',
                'updated_at' => '2025-10-13 10:11:26',
            ),
            2 => 
            array (
                'id' => 3,
                'name' => 'Good Deal',
                'description' => 'test',
                'user_id' => NULL,
                'min_trip_amount' => '50.00',
                'max_coupon_amount' => '50.00',
                'coupon' => '5.00',
                'amount_type' => 'percentage',
                'coupon_type' => 'default',
                'coupon_code' => 'test20',
                'limit' => 100,
                'start_date' => '2025-05-13',
                'end_date' => '2025-11-30',
                'rules' => NULL,
                'total_used' => '5.00',
                'total_amount' => '21.34',
                'is_active' => 1,
                'module_id' => 7,
                'zone_coupon_type' => 'custom',
                'customer_level_coupon_type' => 'custom',
                'customer_coupon_type' => 'custom',
                'category_coupon_type' => '["custom"]',
                'deleted_at' => NULL,
                'created_at' => '2025-09-11 12:35:22',
                'updated_at' => '2025-10-11 17:30:40',
            ),
            3 => 
            array (
                'id' => 4,
                'name' => 'Coupon 12344',
                'description' => 'test',
                'user_id' => NULL,
                'min_trip_amount' => '50.00',
                'max_coupon_amount' => '50.00',
                'coupon' => '5.00',
                'amount_type' => 'percentage',
                'coupon_type' => 'default',
                'coupon_code' => '656',
                'limit' => 56,
                'start_date' => '2025-09-14',
                'end_date' => '2026-09-30',
                'rules' => NULL,
                'total_used' => '8.00',
                'total_amount' => '11.82',
                'is_active' => 1,
                'module_id' => 7,
                'zone_coupon_type' => 'custom',
                'customer_level_coupon_type' => 'custom',
                'customer_coupon_type' => 'custom',
                'category_coupon_type' => '["custom"]',
                'deleted_at' => NULL,
                'created_at' => '2025-09-14 14:50:12',
                'updated_at' => '2025-09-14 16:24:25',
            ),
            4 => 
            array (
                'id' => 5,
                'name' => 'Coupon 12344444',
                'description' => '44',
                'user_id' => NULL,
                'min_trip_amount' => '52.00',
                'max_coupon_amount' => '66.00',
                'coupon' => '3.00',
                'amount_type' => 'percentage',
                'coupon_type' => 'default',
                'coupon_code' => '4456',
                'limit' => 44,
                'start_date' => '2025-09-16',
                'end_date' => '2026-10-31',
                'rules' => NULL,
                'total_used' => '12.00',
                'total_amount' => '39.76',
                'is_active' => 1,
                'module_id' => 7,
                'zone_coupon_type' => 'custom',
                'customer_level_coupon_type' => 'custom',
                'customer_coupon_type' => 'all',
                'category_coupon_type' => '["custom"]',
                'deleted_at' => NULL,
                'created_at' => '2025-09-16 17:15:23',
                'updated_at' => '2025-10-11 16:52:25',
            ),
            5 => 
            array (
                'id' => 6,
                'name' => '432',
                'description' => '324',
                'user_id' => NULL,
                'min_trip_amount' => '200.00',
                'max_coupon_amount' => '0.00',
                'coupon' => '66.00',
                'amount_type' => 'amount',
                'coupon_type' => 'default',
                'coupon_code' => '3',
                'limit' => 33,
                'start_date' => '2025-09-16',
                'end_date' => '2026-06-03',
                'rules' => NULL,
                'total_used' => '0.00',
                'total_amount' => '0.00',
                'is_active' => 1,
                'module_id' => 7,
                'zone_coupon_type' => 'custom',
                'customer_level_coupon_type' => 'custom',
                'customer_coupon_type' => 'all',
                'category_coupon_type' => '["custom"]',
                'deleted_at' => NULL,
                'created_at' => '2025-09-16 17:47:45',
                'updated_at' => '2025-10-07 16:30:04',
            ),
            6 => 
            array (
                'id' => 7,
                'name' => 'this is for test coupon',
                'description' => 'Get 25% offer for good reason.',
                'user_id' => NULL,
                'min_trip_amount' => '50.00',
                'max_coupon_amount' => '100.00',
                'coupon' => '25.00',
                'amount_type' => 'percentage',
                'coupon_type' => 'default',
                'coupon_code' => 'TY45',
                'limit' => 5,
                'start_date' => '2025-09-21',
                'end_date' => '2025-10-30',
                'rules' => NULL,
                'total_used' => '0.00',
                'total_amount' => '0.00',
                'is_active' => 1,
                'module_id' => 7,
                'zone_coupon_type' => 'custom',
                'customer_level_coupon_type' => 'custom',
                'customer_coupon_type' => 'custom',
                'category_coupon_type' => '["custom"]',
                'deleted_at' => NULL,
                'created_at' => '2025-09-21 11:21:30',
                'updated_at' => '2025-10-12 18:32:37',
            ),
        ));
        
        
    }
}