<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class RideUserAccountsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('ride_user_accounts')->delete();
        
        \DB::table('ride_user_accounts')->insert(array (
            0 => 
            array (
                'id' => 1,
                'user_id' => 1,
                'user_type' => 'admin',
                'payable_balance' => '6653.16',
                'receivable_balance' => '5321.14',
                'received_balance' => '90423.51',
                'pending_balance' => '8862.65',
                'wallet_balance' => '0.00',
                'total_withdrawn' => '0.00',
                'total_expense' => '839.31',
                'referral_earn' => 0.0,
                'created_at' => '2025-09-04 04:19:32',
                'updated_at' => '2025-10-14 09:24:14',
            ),
            1 => 
            array (
                'id' => 2,
                'user_id' => 1,
                'user_type' => 'provider',
                'payable_balance' => '4070.00',
                'receivable_balance' => '0.00',
                'received_balance' => '27138.11',
                'pending_balance' => '0.00',
                'wallet_balance' => '0.00',
                'total_withdrawn' => '41.31',
                'total_expense' => '21298.31',
                'referral_earn' => 0.0,
                'created_at' => '2025-09-04 05:05:24',
                'updated_at' => '2025-10-11 12:10:47',
            ),
            2 => 
            array (
                'id' => 3,
                'user_id' => 2,
                'user_type' => 'provider',
                'payable_balance' => '0.00',
                'receivable_balance' => '0.00',
                'received_balance' => '0.00',
                'pending_balance' => '0.00',
                'wallet_balance' => '0.00',
                'total_withdrawn' => '0.00',
                'total_expense' => '0.00',
                'referral_earn' => 0.0,
                'created_at' => '2025-09-04 05:50:24',
                'updated_at' => '2025-09-04 05:50:24',
            ),
            3 => 
            array (
                'id' => 4,
                'user_id' => 6,
                'user_type' => 'provider',
                'payable_balance' => '0.00',
                'receivable_balance' => '0.00',
                'received_balance' => '0.00',
                'pending_balance' => '0.00',
                'wallet_balance' => '0.00',
                'total_withdrawn' => '0.00',
                'total_expense' => '0.00',
                'referral_earn' => 0.0,
                'created_at' => '2025-09-04 06:04:23',
                'updated_at' => '2025-09-04 06:04:23',
            ),
            4 => 
            array (
                'id' => 5,
                'user_id' => 4,
                'user_type' => 'provider',
                'payable_balance' => '0.00',
                'receivable_balance' => '0.00',
                'received_balance' => '0.00',
                'pending_balance' => '0.00',
                'wallet_balance' => '0.00',
                'total_withdrawn' => '0.00',
                'total_expense' => '0.00',
                'referral_earn' => 0.0,
                'created_at' => '2025-09-04 10:14:09',
                'updated_at' => '2025-09-04 10:14:09',
            ),
            5 => 
            array (
                'id' => 6,
                'user_id' => 5,
                'user_type' => 'provider',
                'payable_balance' => '0.00',
                'receivable_balance' => '0.00',
                'received_balance' => '0.00',
                'pending_balance' => '0.00',
                'wallet_balance' => '0.00',
                'total_withdrawn' => '0.00',
                'total_expense' => '0.00',
                'referral_earn' => 0.0,
                'created_at' => '2025-09-04 10:22:51',
                'updated_at' => '2025-09-04 10:22:51',
            ),
            6 => 
            array (
                'id' => 7,
                'user_id' => 3,
                'user_type' => 'provider',
                'payable_balance' => '0.00',
                'receivable_balance' => '0.00',
                'received_balance' => '0.00',
                'pending_balance' => '0.00',
                'wallet_balance' => '0.00',
                'total_withdrawn' => '0.00',
                'total_expense' => '0.00',
                'referral_earn' => 0.0,
                'created_at' => '2025-09-07 10:50:35',
                'updated_at' => '2025-09-07 10:50:35',
            ),
            7 => 
            array (
                'id' => 8,
                'user_id' => 1,
                'user_type' => 'driver',
                'payable_balance' => '399.60',
                'receivable_balance' => '-2151.50',
                'received_balance' => '6416.77',
                'pending_balance' => '3476.20',
                'wallet_balance' => '0.00',
                'total_withdrawn' => '0.00',
                'total_expense' => '0.00',
                'referral_earn' => 0.0,
                'created_at' => '2025-09-08 04:47:39',
                'updated_at' => '2025-10-14 09:24:14',
            ),
            8 => 
            array (
                'id' => 9,
                'user_id' => 7,
                'user_type' => 'provider',
                'payable_balance' => '0.00',
                'receivable_balance' => '4160.90',
                'received_balance' => '301.50',
                'pending_balance' => '7.50',
                'wallet_balance' => '0.00',
                'total_withdrawn' => '87.00',
                'total_expense' => '60.00',
                'referral_earn' => 0.0,
                'created_at' => '2025-09-09 10:49:33',
                'updated_at' => '2025-10-12 16:43:46',
            ),
            9 => 
            array (
                'id' => 10,
                'user_id' => 9,
                'user_type' => 'driver',
                'payable_balance' => '315.88',
                'receivable_balance' => '823.73',
                'received_balance' => '8543.90',
                'pending_balance' => '0.00',
                'wallet_balance' => '0.00',
                'total_withdrawn' => '123.00',
                'total_expense' => '0.00',
                'referral_earn' => 80.0,
                'created_at' => '2025-09-09 10:52:24',
                'updated_at' => '2025-10-13 17:14:09',
            ),
            10 => 
            array (
                'id' => 11,
                'user_id' => 8,
                'user_type' => 'provider',
                'payable_balance' => '110.00',
                'receivable_balance' => '0.00',
                'received_balance' => '78906.85',
                'pending_balance' => '2267.05',
                'wallet_balance' => '0.00',
                'total_withdrawn' => '35680.00',
                'total_expense' => '20.00',
                'referral_earn' => 0.0,
                'created_at' => '2025-09-09 12:14:52',
                'updated_at' => '2025-10-12 12:43:17',
            ),
            11 => 
            array (
                'id' => 12,
                'user_id' => 10,
                'user_type' => 'driver',
                'payable_balance' => '76.49',
                'receivable_balance' => '0.00',
                'received_balance' => '606.82',
                'pending_balance' => '0.00',
                'wallet_balance' => '0.00',
                'total_withdrawn' => '0.00',
                'total_expense' => '0.00',
                'referral_earn' => 0.0,
                'created_at' => '2025-09-09 12:47:33',
                'updated_at' => '2025-09-25 07:40:08',
            ),
            12 => 
            array (
                'id' => 13,
                'user_id' => 11,
                'user_type' => 'driver',
                'payable_balance' => '82.57',
                'receivable_balance' => '329.28',
                'received_balance' => '220.19',
                'pending_balance' => '0.00',
                'wallet_balance' => '0.00',
                'total_withdrawn' => '0.00',
                'total_expense' => '0.00',
                'referral_earn' => 0.0,
                'created_at' => '2025-09-11 12:21:26',
                'updated_at' => '2025-09-16 18:05:22',
            ),
            13 => 
            array (
                'id' => 14,
                'user_id' => 12,
                'user_type' => 'driver',
                'payable_balance' => '0.00',
                'receivable_balance' => '0.00',
                'received_balance' => '0.00',
                'pending_balance' => '0.00',
                'wallet_balance' => '0.00',
                'total_withdrawn' => '0.00',
                'total_expense' => '0.00',
                'referral_earn' => 0.0,
                'created_at' => '2025-09-15 15:39:24',
                'updated_at' => '2025-09-15 15:39:24',
            ),
            14 => 
            array (
                'id' => 15,
                'user_id' => 33,
                'user_type' => 'customer',
                'payable_balance' => '0.00',
                'receivable_balance' => '0.00',
                'received_balance' => '0.00',
                'pending_balance' => '0.00',
                'wallet_balance' => '309.01',
                'total_withdrawn' => '0.00',
                'total_expense' => '0.00',
                'referral_earn' => 0.0,
                'created_at' => '2025-09-15 17:29:54',
                'updated_at' => '2025-10-12 16:13:30',
            ),
            15 => 
            array (
                'id' => 16,
                'user_id' => 13,
                'user_type' => 'driver',
                'payable_balance' => '0.00',
                'receivable_balance' => '0.00',
                'received_balance' => '0.00',
                'pending_balance' => '0.00',
                'wallet_balance' => '0.00',
                'total_withdrawn' => '0.00',
                'total_expense' => '0.00',
                'referral_earn' => 0.0,
                'created_at' => '2025-09-15 18:19:09',
                'updated_at' => '2025-09-15 18:19:09',
            ),
            16 => 
            array (
                'id' => 17,
                'user_id' => 14,
                'user_type' => 'driver',
                'payable_balance' => '0.00',
                'receivable_balance' => '50.00',
                'received_balance' => '0.00',
                'pending_balance' => '0.00',
                'wallet_balance' => '0.00',
                'total_withdrawn' => '0.00',
                'total_expense' => '0.00',
                'referral_earn' => 50.0,
                'created_at' => '2025-09-16 15:03:25',
                'updated_at' => '2025-09-16 15:03:25',
            ),
            17 => 
            array (
                'id' => 18,
                'user_id' => NULL,
                'user_type' => 'provider',
                'payable_balance' => '0.00',
                'receivable_balance' => '0.00',
                'received_balance' => '0.00',
                'pending_balance' => '0.00',
                'wallet_balance' => '0.00',
                'total_withdrawn' => '0.00',
                'total_expense' => '0.00',
                'referral_earn' => 0.0,
                'created_at' => '2025-09-23 12:09:28',
                'updated_at' => '2025-09-23 12:09:28',
            ),
            18 => 
            array (
                'id' => 19,
                'user_id' => 11,
                'user_type' => 'provider',
                'payable_balance' => '0.00',
                'receivable_balance' => '0.00',
                'received_balance' => '0.00',
                'pending_balance' => '0.00',
                'wallet_balance' => '0.00',
                'total_withdrawn' => '0.00',
                'total_expense' => '0.00',
                'referral_earn' => 0.0,
                'created_at' => '2025-09-25 15:24:08',
                'updated_at' => '2025-09-25 15:24:08',
            ),
            19 => 
            array (
                'id' => 20,
                'user_id' => 16,
                'user_type' => 'driver',
                'payable_balance' => '25.73',
                'receivable_balance' => '0.00',
                'received_balance' => '68.61',
                'pending_balance' => '0.00',
                'wallet_balance' => '0.00',
                'total_withdrawn' => '0.00',
                'total_expense' => '0.00',
                'referral_earn' => 0.0,
                'created_at' => '2025-09-25 17:27:22',
                'updated_at' => '2025-09-26 01:03:37',
            ),
            20 => 
            array (
                'id' => 21,
                'user_id' => 10,
                'user_type' => 'provider',
                'payable_balance' => '0.00',
                'receivable_balance' => '0.00',
                'received_balance' => '0.00',
                'pending_balance' => '0.00',
                'wallet_balance' => '0.00',
                'total_withdrawn' => '0.00',
                'total_expense' => '0.00',
                'referral_earn' => 0.0,
                'created_at' => '2025-09-25 22:51:31',
                'updated_at' => '2025-09-25 22:51:31',
            ),
            21 => 
            array (
                'id' => 22,
                'user_id' => 8,
                'user_type' => 'customer',
                'payable_balance' => '0.00',
                'receivable_balance' => '0.00',
                'received_balance' => '0.00',
                'pending_balance' => '0.00',
                'wallet_balance' => '5645.11',
                'total_withdrawn' => '0.00',
                'total_expense' => '0.00',
                'referral_earn' => 0.0,
                'created_at' => '2025-09-29 15:26:44',
                'updated_at' => '2025-09-29 15:26:44',
            ),
            22 => 
            array (
                'id' => 23,
                'user_id' => 9,
                'user_type' => 'provider',
                'payable_balance' => '0.00',
                'receivable_balance' => '0.00',
                'received_balance' => '0.00',
                'pending_balance' => '0.00',
                'wallet_balance' => '0.00',
                'total_withdrawn' => '0.00',
                'total_expense' => '0.00',
                'referral_earn' => 0.0,
                'created_at' => '2025-09-30 09:49:08',
                'updated_at' => '2025-09-30 09:49:08',
            ),
            23 => 
            array (
                'id' => 24,
                'user_id' => 32,
                'user_type' => 'customer',
                'payable_balance' => '0.00',
                'receivable_balance' => '0.00',
                'received_balance' => '0.00',
                'pending_balance' => '0.00',
                'wallet_balance' => '110.00',
                'total_withdrawn' => '0.00',
                'total_expense' => '0.00',
                'referral_earn' => 0.0,
                'created_at' => '2025-10-05 11:41:50',
                'updated_at' => '2025-10-05 11:41:50',
            ),
            24 => 
            array (
                'id' => 25,
                'user_id' => 19,
                'user_type' => 'driver',
                'payable_balance' => '0.00',
                'receivable_balance' => '50.00',
                'received_balance' => '0.00',
                'pending_balance' => '0.00',
                'wallet_balance' => '0.00',
                'total_withdrawn' => '0.00',
                'total_expense' => '0.00',
                'referral_earn' => 50.0,
                'created_at' => '2025-10-05 17:53:22',
                'updated_at' => '2025-10-05 17:53:22',
            ),
            25 => 
            array (
                'id' => 26,
                'user_id' => 20,
                'user_type' => 'driver',
                'payable_balance' => '28.26',
                'receivable_balance' => '150.00',
                'received_balance' => '75.34',
                'pending_balance' => '0.00',
                'wallet_balance' => '0.00',
                'total_withdrawn' => '0.00',
                'total_expense' => '0.00',
                'referral_earn' => 50.0,
                'created_at' => '2025-10-08 16:01:26',
                'updated_at' => '2025-10-13 18:25:41',
            ),
            26 => 
            array (
                'id' => 27,
                'user_id' => 21,
                'user_type' => 'driver',
                'payable_balance' => '6.60',
                'receivable_balance' => '50.00',
                'received_balance' => '17.60',
                'pending_balance' => '0.00',
                'wallet_balance' => '0.00',
                'total_withdrawn' => '0.00',
                'total_expense' => '0.00',
                'referral_earn' => 50.0,
                'created_at' => '2025-10-09 15:57:45',
                'updated_at' => '2025-10-09 17:50:53',
            ),
            27 => 
            array (
                'id' => 28,
                'user_id' => 17,
                'user_type' => 'driver',
                'payable_balance' => '0.00',
                'receivable_balance' => '0.00',
                'received_balance' => '0.00',
                'pending_balance' => '0.00',
                'wallet_balance' => '0.00',
                'total_withdrawn' => '0.00',
                'total_expense' => '0.00',
                'referral_earn' => 0.0,
                'created_at' => '2025-10-10 15:45:42',
                'updated_at' => '2025-10-10 15:45:42',
            ),
            28 => 
            array (
                'id' => 29,
                'user_id' => 22,
                'user_type' => 'driver',
                'payable_balance' => '0.00',
                'receivable_balance' => '0.00',
                'received_balance' => '0.00',
                'pending_balance' => '0.00',
                'wallet_balance' => '0.00',
                'total_withdrawn' => '0.00',
                'total_expense' => '0.00',
                'referral_earn' => 0.0,
                'created_at' => '2025-10-10 17:44:43',
                'updated_at' => '2025-10-10 17:44:43',
            ),
            29 => 
            array (
                'id' => 30,
                'user_id' => 18,
                'user_type' => 'driver',
                'payable_balance' => '0.00',
                'receivable_balance' => '0.00',
                'received_balance' => '0.00',
                'pending_balance' => '0.00',
                'wallet_balance' => '0.00',
                'total_withdrawn' => '0.00',
                'total_expense' => '0.00',
                'referral_earn' => 0.0,
                'created_at' => '2025-10-11 11:38:10',
                'updated_at' => '2025-10-11 11:38:10',
            ),
            30 => 
            array (
                'id' => 31,
                'user_id' => 2,
                'user_type' => 'driver',
                'payable_balance' => '62.41',
                'receivable_balance' => '100.00',
                'received_balance' => '166.45',
                'pending_balance' => '0.00',
                'wallet_balance' => '0.00',
                'total_withdrawn' => '0.00',
                'total_expense' => '0.00',
                'referral_earn' => 0.0,
                'created_at' => '2025-10-11 12:08:03',
                'updated_at' => '2025-10-13 16:39:04',
            ),
            31 => 
            array (
                'id' => 32,
                'user_id' => 24,
                'user_type' => 'driver',
                'payable_balance' => '138.60',
                'receivable_balance' => '0.00',
                'received_balance' => '866.09',
                'pending_balance' => '0.00',
                'wallet_balance' => '0.00',
                'total_withdrawn' => '0.00',
                'total_expense' => '0.00',
                'referral_earn' => 0.0,
                'created_at' => '2025-10-11 16:06:57',
                'updated_at' => '2025-10-13 13:06:27',
            ),
            32 => 
            array (
                'id' => 33,
                'user_id' => 25,
                'user_type' => 'driver',
                'payable_balance' => '5.00',
                'receivable_balance' => '50.00',
                'received_balance' => '13.33',
                'pending_balance' => '0.00',
                'wallet_balance' => '0.00',
                'total_withdrawn' => '0.00',
                'total_expense' => '0.00',
                'referral_earn' => 0.0,
                'created_at' => '2025-10-11 17:19:58',
                'updated_at' => '2025-10-12 11:24:27',
            ),
            33 => 
            array (
                'id' => 34,
                'user_id' => 21,
                'user_type' => 'customer',
                'payable_balance' => '0.00',
                'receivable_balance' => '0.00',
                'received_balance' => '0.00',
                'pending_balance' => '0.00',
                'wallet_balance' => '1218.54',
                'total_withdrawn' => '0.00',
                'total_expense' => '0.00',
                'referral_earn' => 0.0,
                'created_at' => '2025-10-12 18:06:21',
                'updated_at' => '2025-10-12 18:06:21',
            ),
        ));
        
        
    }
}