<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class RiderVehiclesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('rider_vehicles')->delete();
        
        \DB::table('rider_vehicles')->insert(array (
            0 => 
            array (
                'id' => 1,
                'name' => 'Hornet 2.0',
                'ref_id' => '100001',
                'brand_id' => 2,
                'model_id' => 3,
                'category_id' => 2,
                'licence_plate_number' => '123456654321',
                'licence_expire_date' => '2025-09-29',
                'vin_number' => '222222',
                'transmission' => 'manual',
                'parcel_weight_capacity' => 0.0,
                'fuel_type' => 'octan',
                'ownership' => 'driver',
                'rider_id' => 1,
                'documents' => '[{"img": "2025-09-08-68be67042158e.jpg", "storage": "public"}, {"img": "2025-09-08-68be67042354b.png", "storage": "public"}]',
                'is_active' => 1,
                'draft' => NULL,
                'vehicle_request_status' => 'approved',
                'deny_note' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-09-08 05:17:56',
                'updated_at' => '2025-10-04 11:09:16',
            ),
            1 => 
            array (
                'id' => 2,
                'name' => 'R15',
                'ref_id' => '100002',
                'brand_id' => 2,
                'model_id' => 3,
                'category_id' => 1,
                'licence_plate_number' => 'dD10',
                'licence_expire_date' => '2025-09-24',
                'vin_number' => '2314AAA',
                'transmission' => 'manual',
                'parcel_weight_capacity' => 0.0,
                'fuel_type' => 'petrol',
                'ownership' => 'driver',
                'rider_id' => 9,
                'documents' => '[{"img": "2025-10-05-68e25a16a7301.jpg", "storage": "s3"}]',
                'is_active' => 1,
                'draft' => NULL,
                'vehicle_request_status' => 'approved',
                'deny_note' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-09-09 10:53:14',
                'updated_at' => '2025-10-05 17:44:22',
            ),
            2 => 
            array (
                'id' => 3,
                'name' => 'R15-350cc',
                'ref_id' => '100003',
                'brand_id' => 2,
                'model_id' => 3,
                'category_id' => 1,
                'licence_plate_number' => 'D2456',
                'licence_expire_date' => '2025-09-30',
                'vin_number' => '234455SA',
                'transmission' => 'semi_automatic',
                'parcel_weight_capacity' => 0.0,
                'fuel_type' => 'octan',
                'ownership' => 'driver',
                'rider_id' => 10,
                'documents' => '[{"img": "2025-09-09-68bfcdb7a9cd5.png", "storage": "public"}]',
                'is_active' => 1,
                'draft' => NULL,
                'vehicle_request_status' => 'approved',
                'deny_note' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-09-09 12:48:23',
                'updated_at' => '2025-09-09 12:48:40',
            ),
            3 => 
            array (
                'id' => 4,
                'name' => 'test',
                'ref_id' => '100004',
                'brand_id' => 1,
                'model_id' => 2,
                'category_id' => 3,
                'licence_plate_number' => '5437',
                'licence_expire_date' => '2025-10-11',
                'vin_number' => '546545436',
                'transmission' => 'automatic',
                'parcel_weight_capacity' => NULL,
                'fuel_type' => 'diesel',
                'ownership' => 'rider',
                'rider_id' => 11,
                'documents' => '"[{\\"img\\":\\"2025-09-11-68c26b5ea30d3.png\\",\\"storage\\":\\"public\\"}]"',
                'is_active' => 1,
                'draft' => NULL,
                'vehicle_request_status' => 'approved',
                'deny_note' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-09-11 12:25:34',
                'updated_at' => '2025-09-15 18:03:09',
            ),
            4 => 
            array (
                'id' => 5,
                'name' => 'Khub Valo Gari',
                'ref_id' => '100005',
                'brand_id' => 4,
                'model_id' => 5,
                'category_id' => 2,
                'licence_plate_number' => 'T5S6',
                'licence_expire_date' => '2025-09-30',
                'vin_number' => '45454545',
                'transmission' => 'dual_clutch',
                'parcel_weight_capacity' => 0.0,
                'fuel_type' => 'cng',
                'ownership' => 'driver',
                'rider_id' => 12,
                'documents' => '[{"img": "2025-09-15-68c7df1c7f15a.jpg", "storage": "public"}]',
                'is_active' => 1,
                'draft' => NULL,
                'vehicle_request_status' => 'approved',
                'deny_note' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-09-15 15:40:44',
                'updated_at' => '2025-09-15 16:14:49',
            ),
            5 => 
            array (
                'id' => 6,
                'name' => 'Mari Peterson',
                'ref_id' => '100006',
                'brand_id' => 2,
                'model_id' => 3,
                'category_id' => 1,
                'licence_plate_number' => '112233',
                'licence_expire_date' => '2025-09-15',
                'vin_number' => '112233',
                'transmission' => 'automatic',
                'parcel_weight_capacity' => NULL,
                'fuel_type' => 'cng',
                'ownership' => 'rider',
                'rider_id' => 5,
                'documents' => '"[{\\"img\\":\\"2025-09-15-68c7feab654cf.jpg\\",\\"storage\\":\\"public\\"}]"',
                'is_active' => 1,
                'draft' => NULL,
                'vehicle_request_status' => 'approved',
                'deny_note' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-09-15 17:55:23',
                'updated_at' => '2025-09-15 17:55:23',
            ),
            6 => 
            array (
                'id' => 7,
                'name' => '342534',
                'ref_id' => '100007',
                'brand_id' => 2,
                'model_id' => 3,
                'category_id' => 1,
                'licence_plate_number' => '5544',
                'licence_expire_date' => '2025-09-25',
                'vin_number' => '25433235',
                'transmission' => 'semi_automatic',
                'parcel_weight_capacity' => NULL,
                'fuel_type' => 'cng',
                'ownership' => 'admin',
                'rider_id' => 6,
                'documents' => '"[{\\"img\\":\\"2025-09-25-68d4df18a9a0f.pdf\\",\\"storage\\":\\"s3\\"}]"',
                'is_active' => 1,
                'draft' => NULL,
                'vehicle_request_status' => 'approved',
                'deny_note' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-09-25 12:20:08',
                'updated_at' => '2025-09-25 12:20:08',
            ),
            7 => 
            array (
                'id' => 8,
                'name' => 'H 2.0',
                'ref_id' => '100008',
                'brand_id' => 1,
                'model_id' => 3,
                'category_id' => 1,
                'licence_plate_number' => 'Dhaka Metro LA-20-2020',
                'licence_expire_date' => '2027-09-25',
                'vin_number' => '112222',
                'transmission' => 'manual',
                'parcel_weight_capacity' => 0.0,
                'fuel_type' => 'octan',
                'ownership' => 'admin',
                'rider_id' => 16,
                'documents' => '"[{\\"img\\":\\"2025-09-25-68d52772e7163.jpg\\",\\"storage\\":\\"s3\\"},{\\"img\\":\\"2025-09-25-68d52772eba4b.jpg\\",\\"storage\\":\\"s3\\"},{\\"img\\":\\"2025-10-08-68e5e1bb7583c.pdf\\",\\"storage\\":\\"s3\\"}]"',
                'is_active' => 1,
                'draft' => NULL,
                'vehicle_request_status' => 'approved',
                'deny_note' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-09-25 17:28:50',
                'updated_at' => '2025-10-08 09:59:55',
            ),
            8 => 
            array (
                'id' => 9,
                'name' => 'Dttd',
                'ref_id' => '100009',
                'brand_id' => 2,
                'model_id' => 3,
                'category_id' => 1,
                'licence_plate_number' => 'Yffyfgu',
                'licence_expire_date' => '2025-10-09',
                'vin_number' => 'Cggccg',
                'transmission' => 'manual',
                'parcel_weight_capacity' => 0.0,
                'fuel_type' => 'octan',
                'ownership' => 'driver',
                'rider_id' => 20,
                'documents' => '[{"img": "2025-10-09-68e77a07da051.jpg", "storage": "s3"}]',
                'is_active' => 1,
                'draft' => NULL,
                'vehicle_request_status' => 'approved',
                'deny_note' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-10-09 15:01:59',
                'updated_at' => '2025-10-09 15:04:30',
            ),
            9 => 
            array (
                'id' => 10,
                'name' => 'Vssv',
                'ref_id' => '100010',
                'brand_id' => 4,
                'model_id' => 5,
                'category_id' => 1,
                'licence_plate_number' => 'Yrey',
                'licence_expire_date' => '2025-10-09',
                'vin_number' => 'Bsshh',
                'transmission' => 'automatic',
                'parcel_weight_capacity' => 0.0,
                'fuel_type' => 'octan',
                'ownership' => 'driver',
                'rider_id' => 21,
                'documents' => '[{"img": "2025-10-09-68e79ffd42793.jpg", "storage": "s3"}]',
                'is_active' => 1,
                'draft' => NULL,
                'vehicle_request_status' => 'approved',
                'deny_note' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-10-09 17:43:57',
                'updated_at' => '2025-10-09 17:44:32',
            ),
            10 => 
            array (
                'id' => 11,
                'name' => 'Vzv',
                'ref_id' => '100011',
                'brand_id' => 2,
                'model_id' => 3,
                'category_id' => 1,
                'licence_plate_number' => 'E6e6',
                'licence_expire_date' => '2025-10-10',
                'vin_number' => 'Vssg',
                'transmission' => 'continuously_variable',
                'parcel_weight_capacity' => 0.0,
                'fuel_type' => 'octan',
                'ownership' => 'driver',
                'rider_id' => 17,
                'documents' => '[{"img": "2025-10-10-68e8d616a44e0.jpg", "storage": "s3"}]',
                'is_active' => 1,
                'draft' => NULL,
                'vehicle_request_status' => 'approved',
                'deny_note' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-10-10 15:47:02',
                'updated_at' => '2025-10-10 15:47:15',
            ),
            11 => 
            array (
                'id' => 12,
                'name' => 'Royal Enfield 1',
                'ref_id' => '100012',
                'brand_id' => 4,
                'model_id' => 5,
                'category_id' => 1,
                'licence_plate_number' => '1232',
                'licence_expire_date' => '2028-10-10',
                'vin_number' => '123456',
                'transmission' => 'manual',
                'parcel_weight_capacity' => 0.0,
                'fuel_type' => 'octan',
                'ownership' => 'driver',
                'rider_id' => 22,
                'documents' => '[{"img": "2025-10-10-68e8f305b9907.jpg", "storage": "s3"}]',
                'is_active' => 1,
                'draft' => NULL,
                'vehicle_request_status' => 'approved',
                'deny_note' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-10-10 17:50:29',
                'updated_at' => '2025-10-10 17:51:34',
            ),
            12 => 
            array (
                'id' => 14,
                'name' => 't6yre',
                'ref_id' => '100013',
                'brand_id' => 2,
                'model_id' => 3,
                'category_id' => 1,
                'licence_plate_number' => 'ytreyery',
                'licence_expire_date' => '2025-10-25',
                'vin_number' => 'rtyerty',
                'transmission' => 'automatic',
                'parcel_weight_capacity' => 0.0,
                'fuel_type' => 'octan',
                'ownership' => 'driver',
                'rider_id' => 2,
                'documents' => '[{"img": "2025-10-11-68e9fda59ce4e.png", "storage": "s3"}, {"img": "2025-10-11-68e9fda5a3173.png", "storage": "s3"}]',
                'is_active' => 1,
                'draft' => NULL,
                'vehicle_request_status' => 'approved',
                'deny_note' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-10-11 12:48:05',
                'updated_at' => '2025-10-11 12:50:54',
            ),
            13 => 
            array (
                'id' => 15,
                'name' => 'Horse',
                'ref_id' => '100014',
                'brand_id' => 2,
                'model_id' => 3,
                'category_id' => 1,
                'licence_plate_number' => '17822',
                'licence_expire_date' => '2025-10-31',
                'vin_number' => '2537',
                'transmission' => 'manual',
                'parcel_weight_capacity' => 0.0,
                'fuel_type' => 'octan',
                'ownership' => 'driver',
                'rider_id' => 24,
                'documents' => '[{"img": "2025-10-11-68ea2cadb961f.jpg", "storage": "public"}]',
                'is_active' => 1,
                'draft' => NULL,
                'vehicle_request_status' => 'approved',
                'deny_note' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-10-11 16:08:45',
                'updated_at' => '2025-10-11 16:09:05',
            ),
            14 => 
            array (
                'id' => 17,
                'name' => 'Yyysxdh',
                'ref_id' => '100015',
                'brand_id' => 2,
                'model_id' => 3,
                'category_id' => 2,
                'licence_plate_number' => 'Gzdggshs',
                'licence_expire_date' => '2025-10-11',
                'vin_number' => 'Gdgsgs',
                'transmission' => 'continuously_variable',
                'parcel_weight_capacity' => 0.0,
                'fuel_type' => 'octan',
                'ownership' => 'driver',
                'rider_id' => 25,
                'documents' => '[{"img": "2025-10-11-68ea3e639cadb.jpg", "storage": "public"}, {"img": "2025-10-11-68ea3e63a0c76.jpg", "storage": "public"}]',
                'is_active' => 1,
                'draft' => NULL,
                'vehicle_request_status' => 'approved',
                'deny_note' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-10-11 17:24:19',
                'updated_at' => '2025-10-12 11:11:14',
            ),
            15 => 
            array (
                'id' => 18,
                'name' => 'ertewrt',
                'ref_id' => '100016',
                'brand_id' => 4,
                'model_id' => 5,
                'category_id' => 3,
                'licence_plate_number' => '457675567',
                'licence_expire_date' => '2025-10-12',
                'vin_number' => '6546435634576',
                'transmission' => 'semi_automatic',
                'parcel_weight_capacity' => NULL,
                'fuel_type' => 'octan',
                'ownership' => 'admin',
                'rider_id' => 3,
                'documents' => '"[{\\"img\\":\\"2025-10-12-68eb420f322e3.pdf\\",\\"storage\\":\\"public\\"}]"',
                'is_active' => 1,
                'draft' => NULL,
                'vehicle_request_status' => 'approved',
                'deny_note' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-10-12 11:52:15',
                'updated_at' => '2025-10-12 11:52:15',
            ),
        ));
        
        
    }
}