<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class RiderDetailsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('rider_details')->delete();
        
        \DB::table('rider_details')->insert(array (
            0 => 
            array (
                'id' => 1,
                'user_id' => 1,
                'is_online' => '1',
                'availability_status' => 'available',
                'online' => NULL,
                'offline' => NULL,
                'online_time' => 0.0,
                'accepted' => NULL,
                'completed' => NULL,
                'start_driving' => NULL,
                'on_driving_time' => 0.0,
                'idle_time' => 0.0,
                'service' => NULL,
                'ride_count' => 1,
                'created_at' => '2025-09-08 04:57:21',
                'updated_at' => '2025-10-14 09:28:15',
            ),
            1 => 
            array (
                'id' => 2,
                'user_id' => 8,
                'is_online' => '0',
                'availability_status' => 'unavailable',
                'online' => NULL,
                'offline' => NULL,
                'online_time' => 0.0,
                'accepted' => NULL,
                'completed' => NULL,
                'start_driving' => NULL,
                'on_driving_time' => 0.0,
                'idle_time' => 0.0,
                'service' => NULL,
                'ride_count' => 0,
                'created_at' => '2025-09-08 09:13:00',
                'updated_at' => '2025-09-08 09:13:00',
            ),
            2 => 
            array (
                'id' => 3,
                'user_id' => 9,
                'is_online' => '1',
                'availability_status' => 'available',
                'online' => NULL,
                'offline' => NULL,
                'online_time' => 0.0,
                'accepted' => NULL,
                'completed' => NULL,
                'start_driving' => NULL,
                'on_driving_time' => 0.0,
                'idle_time' => 0.0,
                'service' => NULL,
                'ride_count' => 0,
                'created_at' => '2025-09-09 10:51:43',
                'updated_at' => '2025-10-13 17:45:03',
            ),
            3 => 
            array (
                'id' => 4,
                'user_id' => 10,
                'is_online' => '1',
                'availability_status' => 'available',
                'online' => NULL,
                'offline' => NULL,
                'online_time' => 0.0,
                'accepted' => NULL,
                'completed' => NULL,
                'start_driving' => NULL,
                'on_driving_time' => 0.0,
                'idle_time' => 0.0,
                'service' => NULL,
                'ride_count' => 0,
                'created_at' => '2025-09-09 12:46:57',
                'updated_at' => '2025-10-01 00:22:07',
            ),
            4 => 
            array (
                'id' => 5,
                'user_id' => 11,
                'is_online' => '1',
                'availability_status' => 'available',
                'online' => NULL,
                'offline' => NULL,
                'online_time' => 0.0,
                'accepted' => NULL,
                'completed' => NULL,
                'start_driving' => NULL,
                'on_driving_time' => 0.0,
                'idle_time' => 0.0,
                'service' => NULL,
                'ride_count' => 0,
                'created_at' => '2025-09-11 12:16:23',
                'updated_at' => '2025-09-17 09:21:48',
            ),
            5 => 
            array (
                'id' => 6,
                'user_id' => 12,
                'is_online' => '1',
                'availability_status' => 'available',
                'online' => NULL,
                'offline' => NULL,
                'online_time' => 0.0,
                'accepted' => NULL,
                'completed' => NULL,
                'start_driving' => NULL,
                'on_driving_time' => 0.0,
                'idle_time' => 0.0,
                'service' => NULL,
                'ride_count' => 0,
                'created_at' => '2025-09-15 15:28:09',
                'updated_at' => '2025-09-15 15:39:26',
            ),
            6 => 
            array (
                'id' => 7,
                'user_id' => 13,
                'is_online' => '1',
                'availability_status' => 'available',
                'online' => NULL,
                'offline' => NULL,
                'online_time' => 0.0,
                'accepted' => NULL,
                'completed' => NULL,
                'start_driving' => NULL,
                'on_driving_time' => 0.0,
                'idle_time' => 0.0,
                'service' => NULL,
                'ride_count' => 0,
                'created_at' => '2025-09-15 18:12:00',
                'updated_at' => '2025-09-16 10:28:23',
            ),
            7 => 
            array (
                'id' => 8,
                'user_id' => 14,
                'is_online' => '1',
                'availability_status' => 'available',
                'online' => NULL,
                'offline' => NULL,
                'online_time' => 0.0,
                'accepted' => NULL,
                'completed' => NULL,
                'start_driving' => NULL,
                'on_driving_time' => 0.0,
                'idle_time' => 0.0,
                'service' => NULL,
                'ride_count' => 0,
                'created_at' => '2025-09-16 15:03:24',
                'updated_at' => '2025-09-16 15:49:52',
            ),
            8 => 
            array (
                'id' => 9,
                'user_id' => 15,
                'is_online' => '0',
                'availability_status' => 'unavailable',
                'online' => NULL,
                'offline' => NULL,
                'online_time' => 0.0,
                'accepted' => NULL,
                'completed' => NULL,
                'start_driving' => NULL,
                'on_driving_time' => 0.0,
                'idle_time' => 0.0,
                'service' => NULL,
                'ride_count' => 0,
                'created_at' => '2025-09-16 16:13:05',
                'updated_at' => '2025-09-16 16:13:05',
            ),
            9 => 
            array (
                'id' => 10,
                'user_id' => 16,
                'is_online' => '1',
                'availability_status' => 'available',
                'online' => NULL,
                'offline' => NULL,
                'online_time' => 0.0,
                'accepted' => NULL,
                'completed' => NULL,
                'start_driving' => NULL,
                'on_driving_time' => 0.0,
                'idle_time' => 0.0,
                'service' => NULL,
                'ride_count' => 0,
                'created_at' => '2025-09-25 17:25:21',
                'updated_at' => '2025-09-26 01:03:26',
            ),
            10 => 
            array (
                'id' => 11,
                'user_id' => 17,
                'is_online' => '1',
                'availability_status' => 'available',
                'online' => NULL,
                'offline' => NULL,
                'online_time' => 0.0,
                'accepted' => NULL,
                'completed' => NULL,
                'start_driving' => NULL,
                'on_driving_time' => 0.0,
                'idle_time' => 0.0,
                'service' => NULL,
                'ride_count' => 0,
                'created_at' => '2025-09-25 18:01:17',
                'updated_at' => '2025-10-11 10:23:38',
            ),
            11 => 
            array (
                'id' => 12,
                'user_id' => 18,
                'is_online' => '0',
                'availability_status' => 'unavailable',
                'online' => NULL,
                'offline' => NULL,
                'online_time' => 0.0,
                'accepted' => NULL,
                'completed' => NULL,
                'start_driving' => NULL,
                'on_driving_time' => 0.0,
                'idle_time' => 0.0,
                'service' => NULL,
                'ride_count' => 0,
                'created_at' => '2025-09-25 18:04:16',
                'updated_at' => '2025-09-25 18:04:16',
            ),
            12 => 
            array (
                'id' => 13,
                'user_id' => 19,
                'is_online' => '1',
                'availability_status' => 'available',
                'online' => NULL,
                'offline' => NULL,
                'online_time' => 0.0,
                'accepted' => NULL,
                'completed' => NULL,
                'start_driving' => NULL,
                'on_driving_time' => 0.0,
                'idle_time' => 0.0,
                'service' => NULL,
                'ride_count' => 0,
                'created_at' => '2025-10-05 17:53:22',
                'updated_at' => '2025-10-06 09:51:10',
            ),
            13 => 
            array (
                'id' => 14,
                'user_id' => 20,
                'is_online' => '1',
                'availability_status' => 'available',
                'online' => NULL,
                'offline' => NULL,
                'online_time' => 0.0,
                'accepted' => NULL,
                'completed' => NULL,
                'start_driving' => NULL,
                'on_driving_time' => 0.0,
                'idle_time' => 0.0,
                'service' => NULL,
                'ride_count' => 0,
                'created_at' => '2025-10-08 16:01:26',
                'updated_at' => '2025-10-14 09:22:39',
            ),
            14 => 
            array (
                'id' => 15,
                'user_id' => 21,
                'is_online' => '1',
                'availability_status' => 'available',
                'online' => NULL,
                'offline' => NULL,
                'online_time' => 0.0,
                'accepted' => NULL,
                'completed' => NULL,
                'start_driving' => NULL,
                'on_driving_time' => 0.0,
                'idle_time' => 0.0,
                'service' => NULL,
                'ride_count' => 0,
                'created_at' => '2025-10-09 15:57:45',
                'updated_at' => '2025-10-09 17:50:47',
            ),
            15 => 
            array (
                'id' => 16,
                'user_id' => 22,
                'is_online' => '1',
                'availability_status' => 'available',
                'online' => NULL,
                'offline' => NULL,
                'online_time' => 0.0,
                'accepted' => NULL,
                'completed' => NULL,
                'start_driving' => NULL,
                'on_driving_time' => 0.0,
                'idle_time' => 0.0,
                'service' => NULL,
                'ride_count' => 0,
                'created_at' => '2025-10-10 17:36:12',
                'updated_at' => '2025-10-10 17:48:05',
            ),
            16 => 
            array (
                'id' => 17,
                'user_id' => 2,
                'is_online' => '1',
                'availability_status' => 'available',
                'online' => NULL,
                'offline' => NULL,
                'online_time' => 0.0,
                'accepted' => NULL,
                'completed' => NULL,
                'start_driving' => NULL,
                'on_driving_time' => 0.0,
                'idle_time' => 0.0,
                'service' => NULL,
                'ride_count' => 0,
                'created_at' => '2025-10-11 12:08:13',
                'updated_at' => '2025-10-14 09:33:30',
            ),
            17 => 
            array (
                'id' => 18,
                'user_id' => 23,
                'is_online' => '0',
                'availability_status' => 'unavailable',
                'online' => NULL,
                'offline' => NULL,
                'online_time' => 0.0,
                'accepted' => NULL,
                'completed' => NULL,
                'start_driving' => NULL,
                'on_driving_time' => 0.0,
                'idle_time' => 0.0,
                'service' => NULL,
                'ride_count' => 0,
                'created_at' => '2025-10-11 14:35:14',
                'updated_at' => '2025-10-11 14:35:14',
            ),
            18 => 
            array (
                'id' => 19,
                'user_id' => 24,
                'is_online' => '1',
                'availability_status' => 'available',
                'online' => NULL,
                'offline' => NULL,
                'online_time' => 0.0,
                'accepted' => NULL,
                'completed' => NULL,
                'start_driving' => NULL,
                'on_driving_time' => 0.0,
                'idle_time' => 0.0,
                'service' => NULL,
                'ride_count' => 0,
                'created_at' => '2025-10-11 16:06:11',
                'updated_at' => '2025-10-13 18:30:00',
            ),
            19 => 
            array (
                'id' => 20,
                'user_id' => 25,
                'is_online' => '1',
                'availability_status' => 'available',
                'online' => NULL,
                'offline' => NULL,
                'online_time' => 0.0,
                'accepted' => NULL,
                'completed' => NULL,
                'start_driving' => NULL,
                'on_driving_time' => 0.0,
                'idle_time' => 0.0,
                'service' => NULL,
                'ride_count' => 0,
                'created_at' => '2025-10-11 17:18:30',
                'updated_at' => '2025-10-12 11:14:39',
            ),
            20 => 
            array (
                'id' => 21,
                'user_id' => 26,
                'is_online' => '0',
                'availability_status' => 'unavailable',
                'online' => NULL,
                'offline' => NULL,
                'online_time' => 0.0,
                'accepted' => NULL,
                'completed' => NULL,
                'start_driving' => NULL,
                'on_driving_time' => 0.0,
                'idle_time' => 0.0,
                'service' => NULL,
                'ride_count' => 0,
                'created_at' => '2025-10-12 14:33:23',
                'updated_at' => '2025-10-12 14:33:23',
            ),
        ));
        
        
    }
}