<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class ServiceBookingStatusHistoriesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('service_booking_status_histories')->delete();
        
        \DB::table('service_booking_status_histories')->insert(array (
            0 => 
            array (
                'id' => 1,
                'booking_id' => 1001,
                'changed_by' => 1,
                'booking_status' => 'accepted',
                'booking_repeat_id' => NULL,
                'is_guest' => 0,
                'created_at' => '2025-09-04 08:00:13',
                'updated_at' => '2025-09-04 08:00:13',
                'user_type' => 'provider',
            ),
            1 => 
            array (
                'id' => 2,
                'booking_id' => 1003,
                'changed_by' => 1,
                'booking_status' => 'accepted',
                'booking_repeat_id' => NULL,
                'is_guest' => 0,
                'created_at' => '2025-09-04 09:27:47',
                'updated_at' => '2025-09-04 09:27:47',
                'user_type' => 'provider',
            ),
            2 => 
            array (
                'id' => 3,
                'booking_id' => 1003,
                'changed_by' => 1,
                'booking_status' => 'completed',
                'booking_repeat_id' => NULL,
                'is_guest' => 0,
                'created_at' => '2025-09-04 09:29:33',
                'updated_at' => '2025-09-04 09:29:33',
                'user_type' => 'provider',
            ),
            3 => 
            array (
                'id' => 4,
                'booking_id' => 1004,
                'changed_by' => 1,
                'booking_status' => 'accepted',
                'booking_repeat_id' => NULL,
                'is_guest' => 0,
                'created_at' => '2025-09-04 09:39:26',
                'updated_at' => '2025-09-04 09:39:26',
                'user_type' => 'provider',
            ),
            4 => 
            array (
                'id' => 5,
                'booking_id' => 1004,
                'changed_by' => 1,
                'booking_status' => 'ongoing',
                'booking_repeat_id' => NULL,
                'is_guest' => 0,
                'created_at' => '2025-09-04 10:04:56',
                'updated_at' => '2025-09-04 10:04:56',
                'user_type' => 'serviceman',
            ),
            5 => 
            array (
                'id' => 6,
                'booking_id' => 1004,
                'changed_by' => 1,
                'booking_status' => 'completed',
                'booking_repeat_id' => NULL,
                'is_guest' => 0,
                'created_at' => '2025-09-04 10:09:26',
                'updated_at' => '2025-09-04 10:09:26',
                'user_type' => 'serviceman',
            ),
            6 => 
            array (
                'id' => 7,
                'booking_id' => 1006,
                'changed_by' => 1,
                'booking_status' => 'accepted',
                'booking_repeat_id' => NULL,
                'is_guest' => 0,
                'created_at' => '2025-09-04 10:20:31',
                'updated_at' => '2025-09-04 10:20:31',
                'user_type' => 'provider',
            ),
            7 => 
            array (
                'id' => 8,
                'booking_id' => 1005,
                'changed_by' => 1,
                'booking_status' => 'accepted',
                'booking_repeat_id' => NULL,
                'is_guest' => 0,
                'created_at' => '2025-09-04 10:20:58',
                'updated_at' => '2025-09-04 10:20:58',
                'user_type' => 'provider',
            ),
            8 => 
            array (
                'id' => 9,
                'booking_id' => 1007,
                'changed_by' => 29,
                'booking_status' => 'canceled',
                'booking_repeat_id' => NULL,
                'is_guest' => 0,
                'created_at' => '2025-09-04 10:38:39',
                'updated_at' => '2025-09-04 10:38:39',
                'user_type' => 'customer',
            ),
            9 => 
            array (
                'id' => 10,
                'booking_id' => 0,
                'changed_by' => 29,
                'booking_status' => 'canceled',
                'booking_repeat_id' => 1,
                'is_guest' => 0,
                'created_at' => '2025-09-04 10:38:39',
                'updated_at' => '2025-09-04 10:38:39',
                'user_type' => 'customer',
            ),
            10 => 
            array (
                'id' => 11,
                'booking_id' => 0,
                'changed_by' => 29,
                'booking_status' => 'canceled',
                'booking_repeat_id' => 2,
                'is_guest' => 0,
                'created_at' => '2025-09-04 10:38:39',
                'updated_at' => '2025-09-04 10:38:39',
                'user_type' => 'customer',
            ),
            11 => 
            array (
                'id' => 12,
                'booking_id' => 0,
                'changed_by' => 29,
                'booking_status' => 'canceled',
                'booking_repeat_id' => 3,
                'is_guest' => 0,
                'created_at' => '2025-09-04 10:38:39',
                'updated_at' => '2025-09-04 10:38:39',
                'user_type' => 'customer',
            ),
            12 => 
            array (
                'id' => 13,
                'booking_id' => 0,
                'changed_by' => 29,
                'booking_status' => 'canceled',
                'booking_repeat_id' => 4,
                'is_guest' => 0,
                'created_at' => '2025-09-04 10:38:39',
                'updated_at' => '2025-09-04 10:38:39',
                'user_type' => 'customer',
            ),
            13 => 
            array (
                'id' => 14,
                'booking_id' => 0,
                'changed_by' => 29,
                'booking_status' => 'canceled',
                'booking_repeat_id' => 5,
                'is_guest' => 0,
                'created_at' => '2025-09-04 10:38:39',
                'updated_at' => '2025-09-04 10:38:39',
                'user_type' => 'customer',
            ),
            14 => 
            array (
                'id' => 15,
                'booking_id' => 0,
                'changed_by' => 29,
                'booking_status' => 'canceled',
                'booking_repeat_id' => 6,
                'is_guest' => 0,
                'created_at' => '2025-09-04 10:38:39',
                'updated_at' => '2025-09-04 10:38:39',
                'user_type' => 'customer',
            ),
            15 => 
            array (
                'id' => 16,
                'booking_id' => 0,
                'changed_by' => 29,
                'booking_status' => 'canceled',
                'booking_repeat_id' => 7,
                'is_guest' => 0,
                'created_at' => '2025-09-04 10:38:39',
                'updated_at' => '2025-09-04 10:38:39',
                'user_type' => 'customer',
            ),
            16 => 
            array (
                'id' => 17,
                'booking_id' => 1008,
                'changed_by' => 1,
                'booking_status' => 'accepted',
                'booking_repeat_id' => NULL,
                'is_guest' => 0,
                'created_at' => '2025-09-04 10:40:37',
                'updated_at' => '2025-09-04 10:40:37',
                'user_type' => 'provider',
            ),
            17 => 
            array (
                'id' => 18,
                'booking_id' => 0,
                'changed_by' => 1,
                'booking_status' => 'accepted',
                'booking_repeat_id' => 8,
                'is_guest' => 0,
                'created_at' => '2025-09-04 10:40:37',
                'updated_at' => '2025-09-04 10:40:37',
                'user_type' => 'provider',
            ),
            18 => 
            array (
                'id' => 19,
                'booking_id' => 0,
                'changed_by' => 1,
                'booking_status' => 'accepted',
                'booking_repeat_id' => 9,
                'is_guest' => 0,
                'created_at' => '2025-09-04 10:40:37',
                'updated_at' => '2025-09-04 10:40:37',
                'user_type' => 'provider',
            ),
            19 => 
            array (
                'id' => 20,
                'booking_id' => 0,
                'changed_by' => 1,
                'booking_status' => 'accepted',
                'booking_repeat_id' => 10,
                'is_guest' => 0,
                'created_at' => '2025-09-04 10:40:37',
                'updated_at' => '2025-09-04 10:40:37',
                'user_type' => 'provider',
            ),
            20 => 
            array (
                'id' => 21,
                'booking_id' => 0,
                'changed_by' => 1,
                'booking_status' => 'accepted',
                'booking_repeat_id' => 11,
                'is_guest' => 0,
                'created_at' => '2025-09-04 10:40:37',
                'updated_at' => '2025-09-04 10:40:37',
                'user_type' => 'provider',
            ),
            21 => 
            array (
                'id' => 22,
                'booking_id' => 0,
                'changed_by' => 1,
                'booking_status' => 'accepted',
                'booking_repeat_id' => 12,
                'is_guest' => 0,
                'created_at' => '2025-09-04 10:40:37',
                'updated_at' => '2025-09-04 10:40:37',
                'user_type' => 'provider',
            ),
            22 => 
            array (
                'id' => 23,
                'booking_id' => 0,
                'changed_by' => 1,
                'booking_status' => 'accepted',
                'booking_repeat_id' => 13,
                'is_guest' => 0,
                'created_at' => '2025-09-04 10:40:37',
                'updated_at' => '2025-09-04 10:40:37',
                'user_type' => 'provider',
            ),
            23 => 
            array (
                'id' => 24,
                'booking_id' => 0,
                'changed_by' => 1,
                'booking_status' => 'accepted',
                'booking_repeat_id' => 14,
                'is_guest' => 0,
                'created_at' => '2025-09-04 10:40:37',
                'updated_at' => '2025-09-04 10:40:37',
                'user_type' => 'provider',
            ),
            24 => 
            array (
                'id' => 25,
                'booking_id' => 0,
                'changed_by' => 1,
                'booking_status' => 'accepted',
                'booking_repeat_id' => 15,
                'is_guest' => 0,
                'created_at' => '2025-09-04 10:40:37',
                'updated_at' => '2025-09-04 10:40:37',
                'user_type' => 'provider',
            ),
            25 => 
            array (
                'id' => 26,
                'booking_id' => 0,
                'changed_by' => 1,
                'booking_status' => 'accepted',
                'booking_repeat_id' => 16,
                'is_guest' => 0,
                'created_at' => '2025-09-04 10:40:37',
                'updated_at' => '2025-09-04 10:40:37',
                'user_type' => 'provider',
            ),
            26 => 
            array (
                'id' => 27,
                'booking_id' => 0,
                'changed_by' => 1,
                'booking_status' => 'accepted',
                'booking_repeat_id' => 17,
                'is_guest' => 0,
                'created_at' => '2025-09-04 10:40:37',
                'updated_at' => '2025-09-04 10:40:37',
                'user_type' => 'provider',
            ),
            27 => 
            array (
                'id' => 28,
                'booking_id' => 0,
                'changed_by' => 1,
                'booking_status' => 'accepted',
                'booking_repeat_id' => 18,
                'is_guest' => 0,
                'created_at' => '2025-09-04 10:40:37',
                'updated_at' => '2025-09-04 10:40:37',
                'user_type' => 'provider',
            ),
            28 => 
            array (
                'id' => 29,
                'booking_id' => 0,
                'changed_by' => 1,
                'booking_status' => 'accepted',
                'booking_repeat_id' => 19,
                'is_guest' => 0,
                'created_at' => '2025-09-04 10:40:37',
                'updated_at' => '2025-09-04 10:40:37',
                'user_type' => 'provider',
            ),
            29 => 
            array (
                'id' => 30,
                'booking_id' => 0,
                'changed_by' => 1,
                'booking_status' => 'accepted',
                'booking_repeat_id' => 20,
                'is_guest' => 0,
                'created_at' => '2025-09-04 10:40:37',
                'updated_at' => '2025-09-04 10:40:37',
                'user_type' => 'provider',
            ),
            30 => 
            array (
                'id' => 31,
                'booking_id' => 0,
                'changed_by' => 1,
                'booking_status' => 'accepted',
                'booking_repeat_id' => 21,
                'is_guest' => 0,
                'created_at' => '2025-09-04 10:40:37',
                'updated_at' => '2025-09-04 10:40:37',
                'user_type' => 'provider',
            ),
            31 => 
            array (
                'id' => 32,
                'booking_id' => 0,
                'changed_by' => 1,
                'booking_status' => 'accepted',
                'booking_repeat_id' => 22,
                'is_guest' => 0,
                'created_at' => '2025-09-04 10:40:37',
                'updated_at' => '2025-09-04 10:40:37',
                'user_type' => 'provider',
            ),
            32 => 
            array (
                'id' => 33,
                'booking_id' => 0,
                'changed_by' => 1,
                'booking_status' => 'ongoing',
                'booking_repeat_id' => 8,
                'is_guest' => 0,
                'created_at' => '2025-09-04 10:44:19',
                'updated_at' => '2025-09-04 10:44:19',
                'user_type' => 'serviceman',
            ),
            33 => 
            array (
                'id' => 34,
                'booking_id' => 0,
                'changed_by' => 1,
                'booking_status' => 'completed',
                'booking_repeat_id' => 8,
                'is_guest' => 0,
                'created_at' => '2025-09-04 10:45:28',
                'updated_at' => '2025-09-04 10:45:28',
                'user_type' => 'serviceman',
            ),
            34 => 
            array (
                'id' => 35,
                'booking_id' => 1008,
                'changed_by' => 1,
                'booking_status' => 'ongoing',
                'booking_repeat_id' => 11,
                'is_guest' => 0,
                'created_at' => '2025-09-04 10:48:22',
                'updated_at' => '2025-09-04 10:48:22',
                'user_type' => 'provider',
            ),
            35 => 
            array (
                'id' => 36,
                'booking_id' => 0,
                'changed_by' => 1,
                'booking_status' => 'completed',
                'booking_repeat_id' => 11,
                'is_guest' => 0,
                'created_at' => '2025-09-04 10:51:01',
                'updated_at' => '2025-09-04 10:51:01',
                'user_type' => 'serviceman',
            ),
            36 => 
            array (
                'id' => 37,
                'booking_id' => 0,
                'changed_by' => 1,
                'booking_status' => 'ongoing',
                'booking_repeat_id' => 12,
                'is_guest' => 0,
                'created_at' => '2025-09-04 10:55:27',
                'updated_at' => '2025-09-04 10:55:27',
                'user_type' => 'serviceman',
            ),
            37 => 
            array (
                'id' => 38,
                'booking_id' => 1006,
                'changed_by' => 1,
                'booking_status' => 'ongoing',
                'booking_repeat_id' => NULL,
                'is_guest' => 0,
                'created_at' => '2025-09-04 11:49:52',
                'updated_at' => '2025-09-04 11:49:52',
                'user_type' => 'provider',
            ),
            38 => 
            array (
                'id' => 39,
                'booking_id' => 1010,
                'changed_by' => 1,
                'booking_status' => 'accepted',
                'booking_repeat_id' => NULL,
                'is_guest' => 0,
                'created_at' => '2025-09-07 04:55:12',
                'updated_at' => '2025-09-07 04:55:12',
                'user_type' => 'provider',
            ),
            39 => 
            array (
                'id' => 40,
                'booking_id' => 1011,
                'changed_by' => 1,
                'booking_status' => 'accepted',
                'booking_repeat_id' => NULL,
                'is_guest' => 0,
                'created_at' => '2025-09-07 06:28:40',
                'updated_at' => '2025-09-07 06:28:40',
                'user_type' => 'provider',
            ),
            40 => 
            array (
                'id' => 41,
                'booking_id' => 1011,
                'changed_by' => 1,
                'booking_status' => 'ongoing',
                'booking_repeat_id' => NULL,
                'is_guest' => 0,
                'created_at' => '2025-09-07 06:29:26',
                'updated_at' => '2025-09-07 06:29:26',
                'user_type' => 'provider',
            ),
            41 => 
            array (
                'id' => 42,
                'booking_id' => 1011,
                'changed_by' => 1,
                'booking_status' => 'completed',
                'booking_repeat_id' => NULL,
                'is_guest' => 0,
                'created_at' => '2025-09-07 07:01:06',
                'updated_at' => '2025-09-07 07:01:06',
                'user_type' => 'serviceman',
            ),
            42 => 
            array (
                'id' => 43,
                'booking_id' => 1012,
                'changed_by' => 1,
                'booking_status' => 'accepted',
                'booking_repeat_id' => NULL,
                'is_guest' => 0,
                'created_at' => '2025-09-07 07:04:29',
                'updated_at' => '2025-09-07 07:04:29',
                'user_type' => 'provider',
            ),
            43 => 
            array (
                'id' => 44,
                'booking_id' => 1030,
                'changed_by' => 8,
                'booking_status' => 'canceled',
                'booking_repeat_id' => NULL,
                'is_guest' => 0,
                'created_at' => '2025-09-07 10:06:46',
                'updated_at' => '2025-09-07 10:06:46',
                'user_type' => 'customer',
            ),
            44 => 
            array (
                'id' => 45,
                'booking_id' => 1039,
                'changed_by' => 8,
                'booking_status' => 'canceled',
                'booking_repeat_id' => NULL,
                'is_guest' => 0,
                'created_at' => '2025-09-07 11:25:57',
                'updated_at' => '2025-09-07 11:25:57',
                'user_type' => 'customer',
            ),
            45 => 
            array (
                'id' => 46,
                'booking_id' => 1040,
                'changed_by' => 8,
                'booking_status' => 'canceled',
                'booking_repeat_id' => NULL,
                'is_guest' => 0,
                'created_at' => '2025-09-07 11:29:40',
                'updated_at' => '2025-09-07 11:29:40',
                'user_type' => 'customer',
            ),
            46 => 
            array (
                'id' => 47,
                'booking_id' => 1002,
                'changed_by' => 7,
                'booking_status' => 'accepted',
                'booking_repeat_id' => NULL,
                'is_guest' => 0,
                'created_at' => '2025-09-09 10:59:19',
                'updated_at' => '2025-09-09 10:59:19',
                'user_type' => 'provider',
            ),
            47 => 
            array (
                'id' => 48,
                'booking_id' => 1002,
                'changed_by' => 7,
                'booking_status' => 'ongoing',
                'booking_repeat_id' => NULL,
                'is_guest' => 0,
                'created_at' => '2025-09-09 11:00:17',
                'updated_at' => '2025-09-09 11:00:17',
                'user_type' => 'provider',
            ),
            48 => 
            array (
                'id' => 49,
                'booking_id' => 1002,
                'changed_by' => 7,
                'booking_status' => 'completed',
                'booking_repeat_id' => NULL,
                'is_guest' => 0,
                'created_at' => '2025-09-09 11:05:55',
                'updated_at' => '2025-09-09 11:05:55',
                'user_type' => 'provider',
            ),
            49 => 
            array (
                'id' => 50,
                'booking_id' => 1056,
                'changed_by' => 7,
                'booking_status' => 'accepted',
                'booking_repeat_id' => NULL,
                'is_guest' => 0,
                'created_at' => '2025-09-09 11:58:59',
                'updated_at' => '2025-09-09 11:58:59',
                'user_type' => 'provider',
            ),
            50 => 
            array (
                'id' => 51,
                'booking_id' => 1056,
                'changed_by' => 7,
                'booking_status' => 'ongoing',
                'booking_repeat_id' => NULL,
                'is_guest' => 0,
                'created_at' => '2025-09-09 12:00:22',
                'updated_at' => '2025-09-09 12:00:22',
                'user_type' => 'provider',
            ),
            51 => 
            array (
                'id' => 52,
                'booking_id' => 1056,
                'changed_by' => 7,
                'booking_status' => 'completed',
                'booking_repeat_id' => NULL,
                'is_guest' => 0,
                'created_at' => '2025-09-09 12:00:53',
                'updated_at' => '2025-09-09 12:00:53',
                'user_type' => 'provider',
            ),
            52 => 
            array (
                'id' => 53,
                'booking_id' => 1058,
                'changed_by' => 7,
                'booking_status' => 'accepted',
                'booking_repeat_id' => NULL,
                'is_guest' => 0,
                'created_at' => '2025-09-09 12:10:57',
                'updated_at' => '2025-09-09 12:10:57',
                'user_type' => 'provider',
            ),
            53 => 
            array (
                'id' => 54,
                'booking_id' => 1060,
                'changed_by' => 1,
                'booking_status' => 'accepted',
                'booking_repeat_id' => NULL,
                'is_guest' => 0,
                'created_at' => '2025-09-09 12:22:13',
                'updated_at' => '2025-09-09 12:22:13',
                'user_type' => 'provider',
            ),
            54 => 
            array (
                'id' => 55,
                'booking_id' => 1031,
                'changed_by' => 1,
                'booking_status' => 'accepted',
                'booking_repeat_id' => NULL,
                'is_guest' => 0,
                'created_at' => '2025-09-09 12:34:39',
                'updated_at' => '2025-09-09 12:34:39',
                'user_type' => 'provider',
            ),
            55 => 
            array (
                'id' => 56,
                'booking_id' => 0,
                'changed_by' => 1,
                'booking_status' => 'accepted',
                'booking_repeat_id' => 23,
                'is_guest' => 0,
                'created_at' => '2025-09-09 12:34:39',
                'updated_at' => '2025-09-09 12:34:39',
                'user_type' => 'provider',
            ),
            56 => 
            array (
                'id' => 57,
                'booking_id' => 0,
                'changed_by' => 1,
                'booking_status' => 'accepted',
                'booking_repeat_id' => 24,
                'is_guest' => 0,
                'created_at' => '2025-09-09 12:34:39',
                'updated_at' => '2025-09-09 12:34:39',
                'user_type' => 'provider',
            ),
            57 => 
            array (
                'id' => 58,
                'booking_id' => 0,
                'changed_by' => 1,
                'booking_status' => 'accepted',
                'booking_repeat_id' => 25,
                'is_guest' => 0,
                'created_at' => '2025-09-09 12:34:39',
                'updated_at' => '2025-09-09 12:34:39',
                'user_type' => 'provider',
            ),
            58 => 
            array (
                'id' => 59,
                'booking_id' => 0,
                'changed_by' => 1,
                'booking_status' => 'accepted',
                'booking_repeat_id' => 26,
                'is_guest' => 0,
                'created_at' => '2025-09-09 12:34:39',
                'updated_at' => '2025-09-09 12:34:39',
                'user_type' => 'provider',
            ),
            59 => 
            array (
                'id' => 60,
                'booking_id' => 0,
                'changed_by' => 1,
                'booking_status' => 'accepted',
                'booking_repeat_id' => 27,
                'is_guest' => 0,
                'created_at' => '2025-09-09 12:34:39',
                'updated_at' => '2025-09-09 12:34:39',
                'user_type' => 'provider',
            ),
            60 => 
            array (
                'id' => 61,
                'booking_id' => 0,
                'changed_by' => 1,
                'booking_status' => 'accepted',
                'booking_repeat_id' => 28,
                'is_guest' => 0,
                'created_at' => '2025-09-09 12:34:39',
                'updated_at' => '2025-09-09 12:34:39',
                'user_type' => 'provider',
            ),
            61 => 
            array (
                'id' => 62,
                'booking_id' => 0,
                'changed_by' => 1,
                'booking_status' => 'accepted',
                'booking_repeat_id' => 29,
                'is_guest' => 0,
                'created_at' => '2025-09-09 12:34:39',
                'updated_at' => '2025-09-09 12:34:39',
                'user_type' => 'provider',
            ),
            62 => 
            array (
                'id' => 63,
                'booking_id' => 1066,
                'changed_by' => 7,
                'booking_status' => 'accepted',
                'booking_repeat_id' => NULL,
                'is_guest' => 0,
                'created_at' => '2025-09-09 14:38:54',
                'updated_at' => '2025-09-09 14:38:54',
                'user_type' => 'provider',
            ),
            63 => 
            array (
                'id' => 64,
                'booking_id' => 1069,
                'changed_by' => 8,
                'booking_status' => 'accepted',
                'booking_repeat_id' => NULL,
                'is_guest' => 0,
                'created_at' => '2025-09-09 14:46:02',
                'updated_at' => '2025-09-09 14:46:02',
                'user_type' => 'customer',
            ),
            64 => 
            array (
                'id' => 65,
                'booking_id' => 1066,
                'changed_by' => 7,
                'booking_status' => 'ongoing',
                'booking_repeat_id' => NULL,
                'is_guest' => 0,
                'created_at' => '2025-09-09 14:52:56',
                'updated_at' => '2025-09-09 14:52:56',
                'user_type' => 'provider',
            ),
            65 => 
            array (
                'id' => 66,
                'booking_id' => 1072,
                'changed_by' => 7,
                'booking_status' => 'accepted',
                'booking_repeat_id' => NULL,
                'is_guest' => 0,
                'created_at' => '2025-09-10 17:42:37',
                'updated_at' => '2025-09-10 17:42:37',
                'user_type' => 'provider',
            ),
            66 => 
            array (
                'id' => 67,
                'booking_id' => 0,
                'changed_by' => 7,
                'booking_status' => 'accepted',
                'booking_repeat_id' => 82,
                'is_guest' => 0,
                'created_at' => '2025-09-10 17:42:37',
                'updated_at' => '2025-09-10 17:42:37',
                'user_type' => 'provider',
            ),
            67 => 
            array (
                'id' => 68,
                'booking_id' => 0,
                'changed_by' => 7,
                'booking_status' => 'accepted',
                'booking_repeat_id' => 83,
                'is_guest' => 0,
                'created_at' => '2025-09-10 17:42:37',
                'updated_at' => '2025-09-10 17:42:37',
                'user_type' => 'provider',
            ),
            68 => 
            array (
                'id' => 69,
                'booking_id' => 1064,
                'changed_by' => 7,
                'booking_status' => 'accepted',
                'booking_repeat_id' => NULL,
                'is_guest' => 0,
                'created_at' => '2025-09-10 17:44:51',
                'updated_at' => '2025-09-10 17:44:51',
                'user_type' => 'provider',
            ),
            69 => 
            array (
                'id' => 70,
                'booking_id' => 1080,
                'changed_by' => 7,
                'booking_status' => 'accepted',
                'booking_repeat_id' => NULL,
                'is_guest' => 0,
                'created_at' => '2025-09-11 23:29:40',
                'updated_at' => '2025-09-11 23:29:40',
                'user_type' => 'provider',
            ),
            70 => 
            array (
                'id' => 71,
                'booking_id' => 1080,
                'changed_by' => 3,
                'booking_status' => 'ongoing',
                'booking_repeat_id' => NULL,
                'is_guest' => 0,
                'created_at' => '2025-09-11 23:32:08',
                'updated_at' => '2025-09-11 23:32:08',
                'user_type' => 'serviceman',
            ),
            71 => 
            array (
                'id' => 72,
                'booking_id' => 1080,
                'changed_by' => 3,
                'booking_status' => 'completed',
                'booking_repeat_id' => NULL,
                'is_guest' => 0,
                'created_at' => '2025-09-11 23:33:24',
                'updated_at' => '2025-09-11 23:33:24',
                'user_type' => 'serviceman',
            ),
            72 => 
            array (
                'id' => 73,
                'booking_id' => 1078,
                'changed_by' => 7,
                'booking_status' => 'accepted',
                'booking_repeat_id' => NULL,
                'is_guest' => 0,
                'created_at' => '2025-09-16 12:49:08',
                'updated_at' => '2025-09-16 12:49:08',
                'user_type' => 'provider',
            ),
            73 => 
            array (
                'id' => 74,
                'booking_id' => 1082,
                'changed_by' => 1,
                'booking_status' => 'accepted',
                'booking_repeat_id' => NULL,
                'is_guest' => 0,
                'created_at' => '2025-09-17 11:45:20',
                'updated_at' => '2025-09-17 11:45:20',
                'user_type' => 'provider',
            ),
            74 => 
            array (
                'id' => 75,
                'booking_id' => 1084,
                'changed_by' => 14,
                'booking_status' => 'accepted',
                'booking_repeat_id' => NULL,
                'is_guest' => 0,
                'created_at' => '2025-09-17 12:39:03',
                'updated_at' => '2025-09-17 12:39:03',
                'user_type' => 'customer',
            ),
            75 => 
            array (
                'id' => 76,
                'booking_id' => 1085,
                'changed_by' => 14,
                'booking_status' => 'canceled',
                'booking_repeat_id' => NULL,
                'is_guest' => 0,
                'created_at' => '2025-09-18 13:02:30',
                'updated_at' => '2025-09-18 13:02:30',
                'user_type' => 'customer',
            ),
            76 => 
            array (
                'id' => 77,
                'booking_id' => 1084,
                'changed_by' => 1,
                'booking_status' => 'ongoing',
                'booking_repeat_id' => NULL,
                'is_guest' => 0,
                'created_at' => '2025-09-18 13:16:17',
                'updated_at' => '2025-09-18 13:16:17',
                'user_type' => 'provider',
            ),
            77 => 
            array (
                'id' => 78,
                'booking_id' => 1090,
                'changed_by' => 8,
                'booking_status' => 'accepted',
                'booking_repeat_id' => NULL,
                'is_guest' => 0,
                'created_at' => '2025-09-21 15:06:34',
                'updated_at' => '2025-09-21 15:06:34',
                'user_type' => 'provider',
            ),
            78 => 
            array (
                'id' => 79,
                'booking_id' => 1090,
                'changed_by' => 8,
                'booking_status' => 'ongoing',
                'booking_repeat_id' => NULL,
                'is_guest' => 0,
                'created_at' => '2025-09-21 15:16:36',
                'updated_at' => '2025-09-21 15:16:36',
                'user_type' => 'provider',
            ),
            79 => 
            array (
                'id' => 80,
                'booking_id' => 1090,
                'changed_by' => 1,
                'booking_status' => 'completed',
                'booking_repeat_id' => NULL,
                'is_guest' => 0,
                'created_at' => '2025-09-21 15:22:19',
                'updated_at' => '2025-09-21 15:22:19',
                'user_type' => 'provider',
            ),
            80 => 
            array (
                'id' => 81,
                'booking_id' => 1091,
                'changed_by' => 33,
                'booking_status' => 'canceled',
                'booking_repeat_id' => NULL,
                'is_guest' => 0,
                'created_at' => '2025-09-21 15:58:31',
                'updated_at' => '2025-09-21 15:58:31',
                'user_type' => 'customer',
            ),
            81 => 
            array (
                'id' => 82,
                'booking_id' => 0,
                'changed_by' => 33,
                'booking_status' => 'canceled',
                'booking_repeat_id' => 84,
                'is_guest' => 0,
                'created_at' => '2025-09-21 15:58:31',
                'updated_at' => '2025-09-21 15:58:31',
                'user_type' => 'customer',
            ),
            82 => 
            array (
                'id' => 83,
                'booking_id' => 0,
                'changed_by' => 33,
                'booking_status' => 'canceled',
                'booking_repeat_id' => 85,
                'is_guest' => 0,
                'created_at' => '2025-09-21 15:58:31',
                'updated_at' => '2025-09-21 15:58:31',
                'user_type' => 'customer',
            ),
            83 => 
            array (
                'id' => 84,
                'booking_id' => 0,
                'changed_by' => 33,
                'booking_status' => 'canceled',
                'booking_repeat_id' => 86,
                'is_guest' => 0,
                'created_at' => '2025-09-21 15:58:31',
                'updated_at' => '2025-09-21 15:58:31',
                'user_type' => 'customer',
            ),
            84 => 
            array (
                'id' => 85,
                'booking_id' => 0,
                'changed_by' => 33,
                'booking_status' => 'canceled',
                'booking_repeat_id' => 87,
                'is_guest' => 0,
                'created_at' => '2025-09-21 15:58:31',
                'updated_at' => '2025-09-21 15:58:31',
                'user_type' => 'customer',
            ),
            85 => 
            array (
                'id' => 86,
                'booking_id' => 0,
                'changed_by' => 33,
                'booking_status' => 'canceled',
                'booking_repeat_id' => 88,
                'is_guest' => 0,
                'created_at' => '2025-09-21 15:58:31',
                'updated_at' => '2025-09-21 15:58:31',
                'user_type' => 'customer',
            ),
            86 => 
            array (
                'id' => 87,
                'booking_id' => 0,
                'changed_by' => 33,
                'booking_status' => 'canceled',
                'booking_repeat_id' => 89,
                'is_guest' => 0,
                'created_at' => '2025-09-21 15:58:31',
                'updated_at' => '2025-09-21 15:58:31',
                'user_type' => 'customer',
            ),
            87 => 
            array (
                'id' => 88,
                'booking_id' => 0,
                'changed_by' => 33,
                'booking_status' => 'canceled',
                'booking_repeat_id' => 90,
                'is_guest' => 0,
                'created_at' => '2025-09-21 15:58:31',
                'updated_at' => '2025-09-21 15:58:31',
                'user_type' => 'customer',
            ),
            88 => 
            array (
                'id' => 89,
                'booking_id' => 0,
                'changed_by' => 33,
                'booking_status' => 'canceled',
                'booking_repeat_id' => 91,
                'is_guest' => 0,
                'created_at' => '2025-09-21 15:58:31',
                'updated_at' => '2025-09-21 15:58:31',
                'user_type' => 'customer',
            ),
            89 => 
            array (
                'id' => 90,
                'booking_id' => 0,
                'changed_by' => 33,
                'booking_status' => 'canceled',
                'booking_repeat_id' => 92,
                'is_guest' => 0,
                'created_at' => '2025-09-21 15:58:31',
                'updated_at' => '2025-09-21 15:58:31',
                'user_type' => 'customer',
            ),
            90 => 
            array (
                'id' => 91,
                'booking_id' => 1094,
                'changed_by' => 8,
                'booking_status' => 'accepted',
                'booking_repeat_id' => NULL,
                'is_guest' => 0,
                'created_at' => '2025-09-22 11:57:56',
                'updated_at' => '2025-09-22 11:57:56',
                'user_type' => 'provider',
            ),
            91 => 
            array (
                'id' => 92,
                'booking_id' => 1094,
                'changed_by' => 8,
                'booking_status' => 'canceled',
                'booking_repeat_id' => NULL,
                'is_guest' => 0,
                'created_at' => '2025-09-22 11:59:14',
                'updated_at' => '2025-09-22 11:59:14',
                'user_type' => 'provider',
            ),
            92 => 
            array (
                'id' => 93,
                'booking_id' => 1095,
                'changed_by' => 8,
                'booking_status' => 'accepted',
                'booking_repeat_id' => NULL,
                'is_guest' => 0,
                'created_at' => '2025-09-22 12:01:47',
                'updated_at' => '2025-09-22 12:01:47',
                'user_type' => 'provider',
            ),
            93 => 
            array (
                'id' => 94,
                'booking_id' => 1095,
                'changed_by' => 7,
                'booking_status' => 'ongoing',
                'booking_repeat_id' => NULL,
                'is_guest' => 0,
                'created_at' => '2025-09-22 13:30:21',
                'updated_at' => '2025-09-22 13:30:21',
                'user_type' => 'serviceman',
            ),
            94 => 
            array (
                'id' => 95,
                'booking_id' => 1098,
                'changed_by' => 8,
                'booking_status' => 'accepted',
                'booking_repeat_id' => NULL,
                'is_guest' => 0,
                'created_at' => '2025-09-22 15:07:16',
                'updated_at' => '2025-09-22 15:07:16',
                'user_type' => 'provider',
            ),
            95 => 
            array (
                'id' => 96,
                'booking_id' => 0,
                'changed_by' => 8,
                'booking_status' => 'accepted',
                'booking_repeat_id' => 113,
                'is_guest' => 0,
                'created_at' => '2025-09-22 15:07:16',
                'updated_at' => '2025-09-22 15:07:16',
                'user_type' => 'provider',
            ),
            96 => 
            array (
                'id' => 97,
                'booking_id' => 0,
                'changed_by' => 8,
                'booking_status' => 'accepted',
                'booking_repeat_id' => 114,
                'is_guest' => 0,
                'created_at' => '2025-09-22 15:07:16',
                'updated_at' => '2025-09-22 15:07:16',
                'user_type' => 'provider',
            ),
            97 => 
            array (
                'id' => 98,
                'booking_id' => 0,
                'changed_by' => 8,
                'booking_status' => 'accepted',
                'booking_repeat_id' => 115,
                'is_guest' => 0,
                'created_at' => '2025-09-22 15:07:16',
                'updated_at' => '2025-09-22 15:07:16',
                'user_type' => 'provider',
            ),
            98 => 
            array (
                'id' => 99,
                'booking_id' => 0,
                'changed_by' => 8,
                'booking_status' => 'accepted',
                'booking_repeat_id' => 116,
                'is_guest' => 0,
                'created_at' => '2025-09-22 15:07:16',
                'updated_at' => '2025-09-22 15:07:16',
                'user_type' => 'provider',
            ),
            99 => 
            array (
                'id' => 100,
                'booking_id' => 0,
                'changed_by' => 8,
                'booking_status' => 'accepted',
                'booking_repeat_id' => 117,
                'is_guest' => 0,
                'created_at' => '2025-09-22 15:07:16',
                'updated_at' => '2025-09-22 15:07:16',
                'user_type' => 'provider',
            ),
            100 => 
            array (
                'id' => 101,
                'booking_id' => 0,
                'changed_by' => 8,
                'booking_status' => 'accepted',
                'booking_repeat_id' => 118,
                'is_guest' => 0,
                'created_at' => '2025-09-22 15:07:16',
                'updated_at' => '2025-09-22 15:07:16',
                'user_type' => 'provider',
            ),
            101 => 
            array (
                'id' => 102,
                'booking_id' => 0,
                'changed_by' => 8,
                'booking_status' => 'accepted',
                'booking_repeat_id' => 119,
                'is_guest' => 0,
                'created_at' => '2025-09-22 15:07:16',
                'updated_at' => '2025-09-22 15:07:16',
                'user_type' => 'provider',
            ),
            102 => 
            array (
                'id' => 103,
                'booking_id' => 0,
                'changed_by' => 8,
                'booking_status' => 'accepted',
                'booking_repeat_id' => 120,
                'is_guest' => 0,
                'created_at' => '2025-09-22 15:07:16',
                'updated_at' => '2025-09-22 15:07:16',
                'user_type' => 'provider',
            ),
            103 => 
            array (
                'id' => 104,
                'booking_id' => 0,
                'changed_by' => 8,
                'booking_status' => 'accepted',
                'booking_repeat_id' => 121,
                'is_guest' => 0,
                'created_at' => '2025-09-22 15:07:16',
                'updated_at' => '2025-09-22 15:07:16',
                'user_type' => 'provider',
            ),
            104 => 
            array (
                'id' => 105,
                'booking_id' => 113,
                'changed_by' => 8,
                'booking_status' => 'ongoing',
                'booking_repeat_id' => 113,
                'is_guest' => 0,
                'created_at' => '2025-09-22 15:14:52',
                'updated_at' => '2025-09-22 15:14:52',
                'user_type' => 'provider',
            ),
            105 => 
            array (
                'id' => 106,
                'booking_id' => 1092,
                'changed_by' => 8,
                'booking_status' => 'accepted',
                'booking_repeat_id' => NULL,
                'is_guest' => 0,
                'created_at' => '2025-09-22 15:17:11',
                'updated_at' => '2025-09-22 15:17:11',
                'user_type' => 'provider',
            ),
            106 => 
            array (
                'id' => 107,
                'booking_id' => 1097,
                'changed_by' => 8,
                'booking_status' => 'accepted',
                'booking_repeat_id' => NULL,
                'is_guest' => 0,
                'created_at' => '2025-09-22 16:07:50',
                'updated_at' => '2025-09-22 16:07:50',
                'user_type' => 'provider',
            ),
            107 => 
            array (
                'id' => 108,
                'booking_id' => 0,
                'changed_by' => 8,
                'booking_status' => 'accepted',
                'booking_repeat_id' => 93,
                'is_guest' => 0,
                'created_at' => '2025-09-22 16:07:50',
                'updated_at' => '2025-09-22 16:07:50',
                'user_type' => 'provider',
            ),
            108 => 
            array (
                'id' => 109,
                'booking_id' => 0,
                'changed_by' => 8,
                'booking_status' => 'accepted',
                'booking_repeat_id' => 94,
                'is_guest' => 0,
                'created_at' => '2025-09-22 16:07:50',
                'updated_at' => '2025-09-22 16:07:50',
                'user_type' => 'provider',
            ),
            109 => 
            array (
                'id' => 110,
                'booking_id' => 0,
                'changed_by' => 8,
                'booking_status' => 'accepted',
                'booking_repeat_id' => 95,
                'is_guest' => 0,
                'created_at' => '2025-09-22 16:07:50',
                'updated_at' => '2025-09-22 16:07:50',
                'user_type' => 'provider',
            ),
            110 => 
            array (
                'id' => 111,
                'booking_id' => 0,
                'changed_by' => 8,
                'booking_status' => 'accepted',
                'booking_repeat_id' => 96,
                'is_guest' => 0,
                'created_at' => '2025-09-22 16:07:50',
                'updated_at' => '2025-09-22 16:07:50',
                'user_type' => 'provider',
            ),
            111 => 
            array (
                'id' => 112,
                'booking_id' => 0,
                'changed_by' => 8,
                'booking_status' => 'accepted',
                'booking_repeat_id' => 97,
                'is_guest' => 0,
                'created_at' => '2025-09-22 16:07:50',
                'updated_at' => '2025-09-22 16:07:50',
                'user_type' => 'provider',
            ),
            112 => 
            array (
                'id' => 113,
                'booking_id' => 0,
                'changed_by' => 8,
                'booking_status' => 'accepted',
                'booking_repeat_id' => 98,
                'is_guest' => 0,
                'created_at' => '2025-09-22 16:07:50',
                'updated_at' => '2025-09-22 16:07:50',
                'user_type' => 'provider',
            ),
            113 => 
            array (
                'id' => 114,
                'booking_id' => 0,
                'changed_by' => 8,
                'booking_status' => 'accepted',
                'booking_repeat_id' => 99,
                'is_guest' => 0,
                'created_at' => '2025-09-22 16:07:50',
                'updated_at' => '2025-09-22 16:07:50',
                'user_type' => 'provider',
            ),
            114 => 
            array (
                'id' => 115,
                'booking_id' => 0,
                'changed_by' => 8,
                'booking_status' => 'accepted',
                'booking_repeat_id' => 100,
                'is_guest' => 0,
                'created_at' => '2025-09-22 16:07:50',
                'updated_at' => '2025-09-22 16:07:50',
                'user_type' => 'provider',
            ),
            115 => 
            array (
                'id' => 116,
                'booking_id' => 0,
                'changed_by' => 8,
                'booking_status' => 'accepted',
                'booking_repeat_id' => 101,
                'is_guest' => 0,
                'created_at' => '2025-09-22 16:07:50',
                'updated_at' => '2025-09-22 16:07:50',
                'user_type' => 'provider',
            ),
            116 => 
            array (
                'id' => 117,
                'booking_id' => 0,
                'changed_by' => 8,
                'booking_status' => 'accepted',
                'booking_repeat_id' => 102,
                'is_guest' => 0,
                'created_at' => '2025-09-22 16:07:50',
                'updated_at' => '2025-09-22 16:07:50',
                'user_type' => 'provider',
            ),
            117 => 
            array (
                'id' => 118,
                'booking_id' => 0,
                'changed_by' => 8,
                'booking_status' => 'accepted',
                'booking_repeat_id' => 103,
                'is_guest' => 0,
                'created_at' => '2025-09-22 16:07:50',
                'updated_at' => '2025-09-22 16:07:50',
                'user_type' => 'provider',
            ),
            118 => 
            array (
                'id' => 119,
                'booking_id' => 0,
                'changed_by' => 8,
                'booking_status' => 'accepted',
                'booking_repeat_id' => 104,
                'is_guest' => 0,
                'created_at' => '2025-09-22 16:07:50',
                'updated_at' => '2025-09-22 16:07:50',
                'user_type' => 'provider',
            ),
            119 => 
            array (
                'id' => 120,
                'booking_id' => 0,
                'changed_by' => 8,
                'booking_status' => 'accepted',
                'booking_repeat_id' => 105,
                'is_guest' => 0,
                'created_at' => '2025-09-22 16:07:50',
                'updated_at' => '2025-09-22 16:07:50',
                'user_type' => 'provider',
            ),
            120 => 
            array (
                'id' => 121,
                'booking_id' => 0,
                'changed_by' => 8,
                'booking_status' => 'accepted',
                'booking_repeat_id' => 106,
                'is_guest' => 0,
                'created_at' => '2025-09-22 16:07:50',
                'updated_at' => '2025-09-22 16:07:50',
                'user_type' => 'provider',
            ),
            121 => 
            array (
                'id' => 122,
                'booking_id' => 0,
                'changed_by' => 8,
                'booking_status' => 'accepted',
                'booking_repeat_id' => 107,
                'is_guest' => 0,
                'created_at' => '2025-09-22 16:07:50',
                'updated_at' => '2025-09-22 16:07:50',
                'user_type' => 'provider',
            ),
            122 => 
            array (
                'id' => 123,
                'booking_id' => 0,
                'changed_by' => 8,
                'booking_status' => 'accepted',
                'booking_repeat_id' => 108,
                'is_guest' => 0,
                'created_at' => '2025-09-22 16:07:50',
                'updated_at' => '2025-09-22 16:07:50',
                'user_type' => 'provider',
            ),
            123 => 
            array (
                'id' => 124,
                'booking_id' => 0,
                'changed_by' => 8,
                'booking_status' => 'accepted',
                'booking_repeat_id' => 109,
                'is_guest' => 0,
                'created_at' => '2025-09-22 16:07:50',
                'updated_at' => '2025-09-22 16:07:50',
                'user_type' => 'provider',
            ),
            124 => 
            array (
                'id' => 125,
                'booking_id' => 0,
                'changed_by' => 8,
                'booking_status' => 'accepted',
                'booking_repeat_id' => 110,
                'is_guest' => 0,
                'created_at' => '2025-09-22 16:07:50',
                'updated_at' => '2025-09-22 16:07:50',
                'user_type' => 'provider',
            ),
            125 => 
            array (
                'id' => 126,
                'booking_id' => 0,
                'changed_by' => 8,
                'booking_status' => 'accepted',
                'booking_repeat_id' => 111,
                'is_guest' => 0,
                'created_at' => '2025-09-22 16:07:50',
                'updated_at' => '2025-09-22 16:07:50',
                'user_type' => 'provider',
            ),
            126 => 
            array (
                'id' => 127,
                'booking_id' => 0,
                'changed_by' => 8,
                'booking_status' => 'accepted',
                'booking_repeat_id' => 112,
                'is_guest' => 0,
                'created_at' => '2025-09-22 16:07:50',
                'updated_at' => '2025-09-22 16:07:50',
                'user_type' => 'provider',
            ),
            127 => 
            array (
                'id' => 128,
                'booking_id' => 113,
                'changed_by' => 8,
                'booking_status' => 'completed',
                'booking_repeat_id' => 113,
                'is_guest' => 0,
                'created_at' => '2025-09-22 16:15:45',
                'updated_at' => '2025-09-22 16:15:45',
                'user_type' => 'provider',
            ),
            128 => 
            array (
                'id' => 129,
                'booking_id' => 93,
                'changed_by' => 8,
                'booking_status' => 'completed',
                'booking_repeat_id' => 93,
                'is_guest' => 0,
                'created_at' => '2025-09-22 16:16:33',
                'updated_at' => '2025-09-22 16:16:33',
                'user_type' => 'provider',
            ),
            129 => 
            array (
                'id' => 130,
                'booking_id' => 1101,
                'changed_by' => 8,
                'booking_status' => 'accepted',
                'booking_repeat_id' => NULL,
                'is_guest' => 0,
                'created_at' => '2025-09-22 18:14:51',
                'updated_at' => '2025-09-22 18:14:51',
                'user_type' => 'provider',
            ),
            130 => 
            array (
                'id' => 131,
                'booking_id' => 1101,
                'changed_by' => 8,
                'booking_status' => 'ongoing',
                'booking_repeat_id' => NULL,
                'is_guest' => 0,
                'created_at' => '2025-09-22 18:15:13',
                'updated_at' => '2025-09-22 18:15:13',
                'user_type' => 'provider',
            ),
            131 => 
            array (
                'id' => 132,
                'booking_id' => 1104,
                'changed_by' => 8,
                'booking_status' => 'accepted',
                'booking_repeat_id' => NULL,
                'is_guest' => 0,
                'created_at' => '2025-09-23 11:19:00',
                'updated_at' => '2025-09-23 11:19:00',
                'user_type' => 'provider',
            ),
            132 => 
            array (
                'id' => 133,
                'booking_id' => 1104,
                'changed_by' => 8,
                'booking_status' => 'ongoing',
                'booking_repeat_id' => NULL,
                'is_guest' => 0,
                'created_at' => '2025-09-23 11:19:45',
                'updated_at' => '2025-09-23 11:19:45',
                'user_type' => 'provider',
            ),
            133 => 
            array (
                'id' => 134,
                'booking_id' => 1104,
                'changed_by' => 8,
                'booking_status' => 'completed',
                'booking_repeat_id' => NULL,
                'is_guest' => 0,
                'created_at' => '2025-09-23 14:33:58',
                'updated_at' => '2025-09-23 14:33:58',
                'user_type' => 'provider',
            ),
            134 => 
            array (
                'id' => 135,
                'booking_id' => 1102,
                'changed_by' => 8,
                'booking_status' => 'accepted',
                'booking_repeat_id' => NULL,
                'is_guest' => 0,
                'created_at' => '2025-09-23 14:40:16',
                'updated_at' => '2025-09-23 14:40:16',
                'user_type' => 'provider',
            ),
            135 => 
            array (
                'id' => 136,
                'booking_id' => 1106,
                'changed_by' => 8,
                'booking_status' => 'accepted',
                'booking_repeat_id' => NULL,
                'is_guest' => 0,
                'created_at' => '2025-09-23 15:49:23',
                'updated_at' => '2025-09-23 15:49:23',
                'user_type' => 'provider',
            ),
            136 => 
            array (
                'id' => 137,
                'booking_id' => 1106,
                'changed_by' => 8,
                'booking_status' => 'ongoing',
                'booking_repeat_id' => NULL,
                'is_guest' => 0,
                'created_at' => '2025-09-23 15:49:30',
                'updated_at' => '2025-09-23 15:49:30',
                'user_type' => 'provider',
            ),
            137 => 
            array (
                'id' => 138,
                'booking_id' => 1106,
                'changed_by' => 8,
                'booking_status' => 'completed',
                'booking_repeat_id' => NULL,
                'is_guest' => 0,
                'created_at' => '2025-09-23 15:49:53',
                'updated_at' => '2025-09-23 15:49:53',
                'user_type' => 'provider',
            ),
            138 => 
            array (
                'id' => 139,
                'booking_id' => 1107,
                'changed_by' => 33,
                'booking_status' => 'accepted',
                'booking_repeat_id' => NULL,
                'is_guest' => 0,
                'created_at' => '2025-09-23 17:15:46',
                'updated_at' => '2025-09-23 17:15:46',
                'user_type' => 'customer',
            ),
            139 => 
            array (
                'id' => 140,
                'booking_id' => 1107,
                'changed_by' => 7,
                'booking_status' => 'completed',
                'booking_repeat_id' => NULL,
                'is_guest' => 0,
                'created_at' => '2025-09-23 17:35:57',
                'updated_at' => '2025-09-23 17:35:57',
                'user_type' => 'provider',
            ),
            140 => 
            array (
                'id' => 141,
                'booking_id' => 1109,
                'changed_by' => 8,
                'booking_status' => 'accepted',
                'booking_repeat_id' => NULL,
                'is_guest' => 0,
                'created_at' => '2025-09-24 11:53:05',
                'updated_at' => '2025-09-24 11:53:05',
                'user_type' => 'provider',
            ),
            141 => 
            array (
                'id' => 142,
                'booking_id' => 1109,
                'changed_by' => 8,
                'booking_status' => 'ongoing',
                'booking_repeat_id' => NULL,
                'is_guest' => 0,
                'created_at' => '2025-09-24 11:53:32',
                'updated_at' => '2025-09-24 11:53:32',
                'user_type' => 'provider',
            ),
            142 => 
            array (
                'id' => 143,
                'booking_id' => 1109,
                'changed_by' => 8,
                'booking_status' => 'completed',
                'booking_repeat_id' => NULL,
                'is_guest' => 0,
                'created_at' => '2025-09-24 11:54:42',
                'updated_at' => '2025-09-24 11:54:42',
                'user_type' => 'provider',
            ),
            143 => 
            array (
                'id' => 144,
                'booking_id' => 1110,
                'changed_by' => 8,
                'booking_status' => 'accepted',
                'booking_repeat_id' => NULL,
                'is_guest' => 0,
                'created_at' => '2025-09-24 12:04:57',
                'updated_at' => '2025-09-24 12:04:57',
                'user_type' => 'provider',
            ),
            144 => 
            array (
                'id' => 145,
                'booking_id' => 1110,
                'changed_by' => 8,
                'booking_status' => 'completed',
                'booking_repeat_id' => NULL,
                'is_guest' => 0,
                'created_at' => '2025-09-24 12:08:34',
                'updated_at' => '2025-09-24 12:08:34',
                'user_type' => 'provider',
            ),
            145 => 
            array (
                'id' => 146,
                'booking_id' => 1114,
                'changed_by' => 8,
                'booking_status' => 'accepted',
                'booking_repeat_id' => NULL,
                'is_guest' => 0,
                'created_at' => '2025-09-24 16:56:31',
                'updated_at' => '2025-09-24 16:56:31',
                'user_type' => 'provider',
            ),
            146 => 
            array (
                'id' => 147,
                'booking_id' => 1115,
                'changed_by' => 8,
                'booking_status' => 'accepted',
                'booking_repeat_id' => NULL,
                'is_guest' => 0,
                'created_at' => '2025-09-24 16:57:05',
                'updated_at' => '2025-09-24 16:57:05',
                'user_type' => 'provider',
            ),
            147 => 
            array (
                'id' => 148,
                'booking_id' => 1116,
                'changed_by' => 8,
                'booking_status' => 'accepted',
                'booking_repeat_id' => NULL,
                'is_guest' => 0,
                'created_at' => '2025-09-24 16:57:13',
                'updated_at' => '2025-09-24 16:57:13',
                'user_type' => 'provider',
            ),
            148 => 
            array (
                'id' => 149,
                'booking_id' => 1117,
                'changed_by' => 8,
                'booking_status' => 'accepted',
                'booking_repeat_id' => NULL,
                'is_guest' => 0,
                'created_at' => '2025-09-24 16:57:28',
                'updated_at' => '2025-09-24 16:57:28',
                'user_type' => 'provider',
            ),
            149 => 
            array (
                'id' => 150,
                'booking_id' => 1082,
                'changed_by' => 1,
                'booking_status' => 'completed',
                'booking_repeat_id' => NULL,
                'is_guest' => 0,
                'created_at' => '2025-09-25 12:28:44',
                'updated_at' => '2025-09-25 12:28:44',
                'user_type' => 'provider',
            ),
            150 => 
            array (
                'id' => 151,
                'booking_id' => 1060,
                'changed_by' => 1,
                'booking_status' => 'completed',
                'booking_repeat_id' => NULL,
                'is_guest' => 0,
                'created_at' => '2025-09-25 12:29:16',
                'updated_at' => '2025-09-25 12:29:16',
                'user_type' => 'provider',
            ),
            151 => 
            array (
                'id' => 152,
                'booking_id' => 1121,
                'changed_by' => 1,
                'booking_status' => 'accepted',
                'booking_repeat_id' => NULL,
                'is_guest' => 0,
                'created_at' => '2025-09-25 12:47:09',
                'updated_at' => '2025-09-25 12:47:09',
                'user_type' => 'provider',
            ),
            152 => 
            array (
                'id' => 153,
                'booking_id' => 1123,
                'changed_by' => 1,
                'booking_status' => 'accepted',
                'booking_repeat_id' => NULL,
                'is_guest' => 0,
                'created_at' => '2025-09-28 12:55:01',
                'updated_at' => '2025-09-28 12:55:01',
                'user_type' => 'provider',
            ),
            153 => 
            array (
                'id' => 154,
                'booking_id' => 1123,
                'changed_by' => 1,
                'booking_status' => 'ongoing',
                'booking_repeat_id' => NULL,
                'is_guest' => 0,
                'created_at' => '2025-09-28 16:03:33',
                'updated_at' => '2025-09-28 16:03:33',
                'user_type' => 'provider',
            ),
            154 => 
            array (
                'id' => 155,
                'booking_id' => 1124,
                'changed_by' => 32,
                'booking_status' => 'accepted',
                'booking_repeat_id' => NULL,
                'is_guest' => 0,
                'created_at' => '2025-09-28 16:54:59',
                'updated_at' => '2025-09-28 16:54:59',
                'user_type' => 'customer',
            ),
            155 => 
            array (
                'id' => 156,
                'booking_id' => 1124,
                'changed_by' => 1,
                'booking_status' => 'completed',
                'booking_repeat_id' => NULL,
                'is_guest' => 0,
                'created_at' => '2025-09-28 16:56:40',
                'updated_at' => '2025-09-28 16:56:40',
                'user_type' => 'provider',
            ),
            156 => 
            array (
                'id' => 157,
                'booking_id' => 1126,
                'changed_by' => 7,
                'booking_status' => 'accepted',
                'booking_repeat_id' => NULL,
                'is_guest' => 0,
                'created_at' => '2025-09-28 17:12:56',
                'updated_at' => '2025-09-28 17:12:56',
                'user_type' => 'provider',
            ),
            157 => 
            array (
                'id' => 158,
                'booking_id' => 0,
                'changed_by' => 7,
                'booking_status' => 'accepted',
                'booking_repeat_id' => 134,
                'is_guest' => 0,
                'created_at' => '2025-09-28 17:12:56',
                'updated_at' => '2025-09-28 17:12:56',
                'user_type' => 'provider',
            ),
            158 => 
            array (
                'id' => 159,
                'booking_id' => 0,
                'changed_by' => 7,
                'booking_status' => 'accepted',
                'booking_repeat_id' => 135,
                'is_guest' => 0,
                'created_at' => '2025-09-28 17:12:56',
                'updated_at' => '2025-09-28 17:12:56',
                'user_type' => 'provider',
            ),
            159 => 
            array (
                'id' => 160,
                'booking_id' => 0,
                'changed_by' => 7,
                'booking_status' => 'accepted',
                'booking_repeat_id' => 136,
                'is_guest' => 0,
                'created_at' => '2025-09-28 17:12:56',
                'updated_at' => '2025-09-28 17:12:56',
                'user_type' => 'provider',
            ),
            160 => 
            array (
                'id' => 161,
                'booking_id' => 1130,
                'changed_by' => 32,
                'booking_status' => 'accepted',
                'booking_repeat_id' => NULL,
                'is_guest' => 0,
                'created_at' => '2025-09-29 17:21:06',
                'updated_at' => '2025-09-29 17:21:06',
                'user_type' => 'customer',
            ),
            161 => 
            array (
                'id' => 162,
                'booking_id' => 1116,
                'changed_by' => 1,
                'booking_status' => 'ongoing',
                'booking_repeat_id' => NULL,
                'is_guest' => 0,
                'created_at' => '2025-09-30 11:11:04',
                'updated_at' => '2025-09-30 11:11:04',
                'user_type' => 'provider',
            ),
            162 => 
            array (
                'id' => 163,
                'booking_id' => 1114,
                'changed_by' => 1,
                'booking_status' => 'ongoing',
                'booking_repeat_id' => NULL,
                'is_guest' => 0,
                'created_at' => '2025-09-30 11:11:21',
                'updated_at' => '2025-09-30 11:11:21',
                'user_type' => 'provider',
            ),
            163 => 
            array (
                'id' => 164,
                'booking_id' => 1122,
                'changed_by' => 1,
                'booking_status' => 'accepted',
                'booking_repeat_id' => NULL,
                'is_guest' => 0,
                'created_at' => '2025-09-30 11:35:27',
                'updated_at' => '2025-09-30 11:35:27',
                'user_type' => 'provider',
            ),
            164 => 
            array (
                'id' => 165,
                'booking_id' => 1119,
                'changed_by' => 1,
                'booking_status' => 'accepted',
                'booking_repeat_id' => NULL,
                'is_guest' => 0,
                'created_at' => '2025-09-30 11:48:34',
                'updated_at' => '2025-09-30 11:48:34',
                'user_type' => 'provider',
            ),
            165 => 
            array (
                'id' => 166,
                'booking_id' => 1119,
                'changed_by' => 1,
                'booking_status' => 'completed',
                'booking_repeat_id' => NULL,
                'is_guest' => 0,
                'created_at' => '2025-09-30 11:49:03',
                'updated_at' => '2025-09-30 11:49:03',
                'user_type' => 'provider',
            ),
            166 => 
            array (
                'id' => 167,
                'booking_id' => 1142,
                'changed_by' => 33,
                'booking_status' => 'accepted',
                'booking_repeat_id' => NULL,
                'is_guest' => 0,
                'created_at' => '2025-10-05 15:52:28',
                'updated_at' => '2025-10-05 15:52:28',
                'user_type' => 'customer',
            ),
            167 => 
            array (
                'id' => 168,
                'booking_id' => 1143,
                'changed_by' => 33,
                'booking_status' => 'accepted',
                'booking_repeat_id' => NULL,
                'is_guest' => 0,
                'created_at' => '2025-10-05 17:14:26',
                'updated_at' => '2025-10-05 17:14:26',
                'user_type' => 'customer',
            ),
            168 => 
            array (
                'id' => 169,
                'booking_id' => 1142,
                'changed_by' => 1,
                'booking_status' => 'completed',
                'booking_repeat_id' => NULL,
                'is_guest' => 0,
                'created_at' => '2025-10-05 17:15:11',
                'updated_at' => '2025-10-05 17:15:11',
                'user_type' => 'provider',
            ),
            169 => 
            array (
                'id' => 170,
                'booking_id' => 1118,
                'changed_by' => 8,
                'booking_status' => 'accepted',
                'booking_repeat_id' => NULL,
                'is_guest' => 0,
                'created_at' => '2025-10-06 17:42:19',
                'updated_at' => '2025-10-06 17:42:19',
                'user_type' => 'provider',
            ),
            170 => 
            array (
                'id' => 171,
                'booking_id' => 1149,
                'changed_by' => 8,
                'booking_status' => 'accepted',
                'booking_repeat_id' => NULL,
                'is_guest' => 0,
                'created_at' => '2025-10-07 10:33:23',
                'updated_at' => '2025-10-07 10:33:23',
                'user_type' => 'provider',
            ),
            171 => 
            array (
                'id' => 172,
                'booking_id' => 1149,
                'changed_by' => 8,
                'booking_status' => 'ongoing',
                'booking_repeat_id' => NULL,
                'is_guest' => 0,
                'created_at' => '2025-10-07 10:33:37',
                'updated_at' => '2025-10-07 10:33:37',
                'user_type' => 'provider',
            ),
            172 => 
            array (
                'id' => 173,
                'booking_id' => 1149,
                'changed_by' => 8,
                'booking_status' => 'completed',
                'booking_repeat_id' => NULL,
                'is_guest' => 0,
                'created_at' => '2025-10-07 10:34:33',
                'updated_at' => '2025-10-07 10:34:33',
                'user_type' => 'provider',
            ),
            173 => 
            array (
                'id' => 174,
                'booking_id' => 1150,
                'changed_by' => 8,
                'booking_status' => 'accepted',
                'booking_repeat_id' => NULL,
                'is_guest' => 0,
                'created_at' => '2025-10-07 10:51:46',
                'updated_at' => '2025-10-07 10:51:46',
                'user_type' => 'provider',
            ),
            174 => 
            array (
                'id' => 175,
                'booking_id' => 1150,
                'changed_by' => 8,
                'booking_status' => 'completed',
                'booking_repeat_id' => NULL,
                'is_guest' => 0,
                'created_at' => '2025-10-07 11:00:48',
                'updated_at' => '2025-10-07 11:00:48',
                'user_type' => 'provider',
            ),
            175 => 
            array (
                'id' => 176,
                'booking_id' => 1148,
                'changed_by' => 1,
                'booking_status' => 'accepted',
                'booking_repeat_id' => NULL,
                'is_guest' => 0,
                'created_at' => '2025-10-07 13:04:23',
                'updated_at' => '2025-10-07 13:04:23',
                'user_type' => 'provider',
            ),
            176 => 
            array (
                'id' => 177,
                'booking_id' => 1146,
                'changed_by' => 1,
                'booking_status' => 'accepted',
                'booking_repeat_id' => NULL,
                'is_guest' => 0,
                'created_at' => '2025-10-07 13:04:50',
                'updated_at' => '2025-10-07 13:04:50',
                'user_type' => 'provider',
            ),
            177 => 
            array (
                'id' => 178,
                'booking_id' => 1146,
                'changed_by' => 1,
                'booking_status' => 'ongoing',
                'booking_repeat_id' => NULL,
                'is_guest' => 0,
                'created_at' => '2025-10-07 13:05:07',
                'updated_at' => '2025-10-07 13:05:07',
                'user_type' => 'provider',
            ),
            178 => 
            array (
                'id' => 179,
                'booking_id' => 1153,
                'changed_by' => 14,
                'booking_status' => 'accepted',
                'booking_repeat_id' => NULL,
                'is_guest' => 0,
                'created_at' => '2025-10-07 14:07:01',
                'updated_at' => '2025-10-07 14:07:01',
                'user_type' => 'customer',
            ),
            179 => 
            array (
                'id' => 180,
                'booking_id' => 1153,
                'changed_by' => 8,
                'booking_status' => 'completed',
                'booking_repeat_id' => NULL,
                'is_guest' => 0,
                'created_at' => '2025-10-07 14:08:18',
                'updated_at' => '2025-10-07 14:08:18',
                'user_type' => 'provider',
            ),
            180 => 
            array (
                'id' => 181,
                'booking_id' => 1154,
                'changed_by' => 1,
                'booking_status' => 'accepted',
                'booking_repeat_id' => NULL,
                'is_guest' => 0,
                'created_at' => '2025-10-07 17:14:07',
                'updated_at' => '2025-10-07 17:14:07',
                'user_type' => 'provider',
            ),
            181 => 
            array (
                'id' => 182,
                'booking_id' => 1154,
                'changed_by' => 1,
                'booking_status' => 'completed',
                'booking_repeat_id' => NULL,
                'is_guest' => 0,
                'created_at' => '2025-10-07 17:14:54',
                'updated_at' => '2025-10-07 17:14:54',
                'user_type' => 'provider',
            ),
            182 => 
            array (
                'id' => 183,
                'booking_id' => 1155,
                'changed_by' => 1,
                'booking_status' => 'accepted',
                'booking_repeat_id' => NULL,
                'is_guest' => 0,
                'created_at' => '2025-10-08 09:57:39',
                'updated_at' => '2025-10-08 09:57:39',
                'user_type' => 'provider',
            ),
            183 => 
            array (
                'id' => 184,
                'booking_id' => 1083,
                'changed_by' => 1,
                'booking_status' => 'accepted',
                'booking_repeat_id' => NULL,
                'is_guest' => 0,
                'created_at' => '2025-10-08 10:04:51',
                'updated_at' => '2025-10-08 10:04:51',
                'user_type' => 'provider',
            ),
            184 => 
            array (
                'id' => 185,
                'booking_id' => 1155,
                'changed_by' => 6,
                'booking_status' => 'ongoing',
                'booking_repeat_id' => NULL,
                'is_guest' => 0,
                'created_at' => '2025-10-08 10:12:46',
                'updated_at' => '2025-10-08 10:12:46',
                'user_type' => 'serviceman',
            ),
            185 => 
            array (
                'id' => 186,
                'booking_id' => 1130,
                'changed_by' => 1,
                'booking_status' => 'completed',
                'booking_repeat_id' => NULL,
                'is_guest' => 0,
                'created_at' => '2025-10-09 15:17:58',
                'updated_at' => '2025-10-09 15:17:58',
                'user_type' => 'provider',
            ),
            186 => 
            array (
                'id' => 187,
                'booking_id' => 1165,
                'changed_by' => 1,
                'booking_status' => 'accepted',
                'booking_repeat_id' => NULL,
                'is_guest' => 0,
                'created_at' => '2025-10-09 17:36:15',
                'updated_at' => '2025-10-09 17:36:15',
                'user_type' => 'provider',
            ),
            187 => 
            array (
                'id' => 188,
                'booking_id' => 1155,
                'changed_by' => 1,
                'booking_status' => 'completed',
                'booking_repeat_id' => NULL,
                'is_guest' => 0,
                'created_at' => '2025-10-10 17:08:34',
                'updated_at' => '2025-10-10 17:08:34',
                'user_type' => 'provider',
            ),
            188 => 
            array (
                'id' => 189,
                'booking_id' => 1148,
                'changed_by' => 1,
                'booking_status' => 'completed',
                'booking_repeat_id' => NULL,
                'is_guest' => 0,
                'created_at' => '2025-10-10 17:11:16',
                'updated_at' => '2025-10-10 17:11:16',
                'user_type' => 'provider',
            ),
            189 => 
            array (
                'id' => 190,
                'booking_id' => 1012,
                'changed_by' => 1,
                'booking_status' => 'completed',
                'booking_repeat_id' => NULL,
                'is_guest' => 0,
                'created_at' => '2025-10-10 17:20:00',
                'updated_at' => '2025-10-10 17:20:00',
                'user_type' => 'provider',
            ),
            190 => 
            array (
                'id' => 191,
                'booking_id' => 1170,
                'changed_by' => 1,
                'booking_status' => 'accepted',
                'booking_repeat_id' => NULL,
                'is_guest' => 0,
                'created_at' => '2025-10-11 09:31:24',
                'updated_at' => '2025-10-11 09:31:24',
                'user_type' => 'provider',
            ),
            191 => 
            array (
                'id' => 192,
                'booking_id' => 1170,
                'changed_by' => 1,
                'booking_status' => 'completed',
                'booking_repeat_id' => NULL,
                'is_guest' => 0,
                'created_at' => '2025-10-11 09:44:28',
                'updated_at' => '2025-10-11 09:44:28',
                'user_type' => 'provider',
            ),
            192 => 
            array (
                'id' => 193,
                'booking_id' => 1171,
                'changed_by' => 1,
                'booking_status' => 'accepted',
                'booking_repeat_id' => NULL,
                'is_guest' => 0,
                'created_at' => '2025-10-11 10:13:22',
                'updated_at' => '2025-10-11 10:13:22',
                'user_type' => 'provider',
            ),
            193 => 
            array (
                'id' => 194,
                'booking_id' => 1171,
                'changed_by' => 1,
                'booking_status' => 'completed',
                'booking_repeat_id' => NULL,
                'is_guest' => 0,
                'created_at' => '2025-10-11 10:13:47',
                'updated_at' => '2025-10-11 10:13:47',
                'user_type' => 'provider',
            ),
            194 => 
            array (
                'id' => 195,
                'booking_id' => 1172,
                'changed_by' => 1,
                'booking_status' => 'accepted',
                'booking_repeat_id' => NULL,
                'is_guest' => 0,
                'created_at' => '2025-10-11 10:16:42',
                'updated_at' => '2025-10-11 10:16:42',
                'user_type' => 'provider',
            ),
            195 => 
            array (
                'id' => 196,
                'booking_id' => 1172,
                'changed_by' => 1,
                'booking_status' => 'ongoing',
                'booking_repeat_id' => NULL,
                'is_guest' => 0,
                'created_at' => '2025-10-11 10:17:11',
                'updated_at' => '2025-10-11 10:17:11',
                'user_type' => 'provider',
            ),
            196 => 
            array (
                'id' => 197,
                'booking_id' => 1172,
                'changed_by' => 1,
                'booking_status' => 'completed',
                'booking_repeat_id' => NULL,
                'is_guest' => 0,
                'created_at' => '2025-10-11 10:17:32',
                'updated_at' => '2025-10-11 10:17:32',
                'user_type' => 'provider',
            ),
            197 => 
            array (
                'id' => 198,
                'booking_id' => 1173,
                'changed_by' => 1,
                'booking_status' => 'accepted',
                'booking_repeat_id' => NULL,
                'is_guest' => 0,
                'created_at' => '2025-10-11 11:14:51',
                'updated_at' => '2025-10-11 11:14:51',
                'user_type' => 'provider',
            ),
            198 => 
            array (
                'id' => 199,
                'booking_id' => 1169,
                'changed_by' => 1,
                'booking_status' => 'accepted',
                'booking_repeat_id' => NULL,
                'is_guest' => 0,
                'created_at' => '2025-10-11 11:43:38',
                'updated_at' => '2025-10-11 11:43:38',
                'user_type' => 'provider',
            ),
            199 => 
            array (
                'id' => 200,
                'booking_id' => 1173,
                'changed_by' => 1,
                'booking_status' => 'ongoing',
                'booking_repeat_id' => NULL,
                'is_guest' => 0,
                'created_at' => '2025-10-11 12:09:17',
                'updated_at' => '2025-10-11 12:09:17',
                'user_type' => 'serviceman',
            ),
            200 => 
            array (
                'id' => 201,
                'booking_id' => 1173,
                'changed_by' => 1,
                'booking_status' => 'completed',
                'booking_repeat_id' => NULL,
                'is_guest' => 0,
                'created_at' => '2025-10-11 12:10:47',
                'updated_at' => '2025-10-11 12:10:47',
                'user_type' => 'serviceman',
            ),
            201 => 
            array (
                'id' => 202,
                'booking_id' => 1165,
                'changed_by' => 1,
                'booking_status' => 'ongoing',
                'booking_repeat_id' => NULL,
                'is_guest' => 0,
                'created_at' => '2025-10-11 12:14:07',
                'updated_at' => '2025-10-11 12:14:07',
                'user_type' => 'serviceman',
            ),
            202 => 
            array (
                'id' => 203,
                'booking_id' => 1005,
                'changed_by' => 1,
                'booking_status' => 'canceled',
                'booking_repeat_id' => NULL,
                'is_guest' => 0,
                'created_at' => '2025-10-11 12:16:50',
                'updated_at' => '2025-10-11 12:16:50',
                'user_type' => 'provider',
            ),
            203 => 
            array (
                'id' => 204,
                'booking_id' => 1169,
                'changed_by' => 6,
                'booking_status' => 'ongoing',
                'booking_repeat_id' => NULL,
                'is_guest' => 0,
                'created_at' => '2025-10-11 18:57:46',
                'updated_at' => '2025-10-11 18:57:46',
                'user_type' => 'serviceman',
            ),
            204 => 
            array (
                'id' => 205,
                'booking_id' => 1152,
                'changed_by' => 8,
                'booking_status' => 'accepted',
                'booking_repeat_id' => NULL,
                'is_guest' => 0,
                'created_at' => '2025-10-12 12:22:59',
                'updated_at' => '2025-10-12 12:22:59',
                'user_type' => 'provider',
            ),
            205 => 
            array (
                'id' => 206,
                'booking_id' => 0,
                'changed_by' => 8,
                'booking_status' => 'accepted',
                'booking_repeat_id' => 193,
                'is_guest' => 0,
                'created_at' => '2025-10-12 12:22:59',
                'updated_at' => '2025-10-12 12:22:59',
                'user_type' => 'provider',
            ),
            206 => 
            array (
                'id' => 207,
                'booking_id' => 0,
                'changed_by' => 8,
                'booking_status' => 'accepted',
                'booking_repeat_id' => 194,
                'is_guest' => 0,
                'created_at' => '2025-10-12 12:22:59',
                'updated_at' => '2025-10-12 12:22:59',
                'user_type' => 'provider',
            ),
            207 => 
            array (
                'id' => 208,
                'booking_id' => 0,
                'changed_by' => 8,
                'booking_status' => 'accepted',
                'booking_repeat_id' => 195,
                'is_guest' => 0,
                'created_at' => '2025-10-12 12:22:59',
                'updated_at' => '2025-10-12 12:22:59',
                'user_type' => 'provider',
            ),
            208 => 
            array (
                'id' => 209,
                'booking_id' => 0,
                'changed_by' => 8,
                'booking_status' => 'accepted',
                'booking_repeat_id' => 196,
                'is_guest' => 0,
                'created_at' => '2025-10-12 12:22:59',
                'updated_at' => '2025-10-12 12:22:59',
                'user_type' => 'provider',
            ),
            209 => 
            array (
                'id' => 210,
                'booking_id' => 0,
                'changed_by' => 8,
                'booking_status' => 'accepted',
                'booking_repeat_id' => 197,
                'is_guest' => 0,
                'created_at' => '2025-10-12 12:22:59',
                'updated_at' => '2025-10-12 12:22:59',
                'user_type' => 'provider',
            ),
            210 => 
            array (
                'id' => 211,
                'booking_id' => 1176,
                'changed_by' => 14,
                'booking_status' => 'accepted',
                'booking_repeat_id' => NULL,
                'is_guest' => 0,
                'created_at' => '2025-10-12 12:41:57',
                'updated_at' => '2025-10-12 12:41:57',
                'user_type' => 'customer',
            ),
            211 => 
            array (
                'id' => 212,
                'booking_id' => 1176,
                'changed_by' => 8,
                'booking_status' => 'ongoing',
                'booking_repeat_id' => NULL,
                'is_guest' => 0,
                'created_at' => '2025-10-12 12:42:27',
                'updated_at' => '2025-10-12 12:42:27',
                'user_type' => 'provider',
            ),
            212 => 
            array (
                'id' => 213,
                'booking_id' => 1176,
                'changed_by' => 8,
                'booking_status' => 'completed',
                'booking_repeat_id' => NULL,
                'is_guest' => 0,
                'created_at' => '2025-10-12 12:43:18',
                'updated_at' => '2025-10-12 12:43:18',
                'user_type' => 'provider',
            ),
            213 => 
            array (
                'id' => 214,
                'booking_id' => 1180,
                'changed_by' => 7,
                'booking_status' => 'accepted',
                'booking_repeat_id' => NULL,
                'is_guest' => 0,
                'created_at' => '2025-10-12 16:45:28',
                'updated_at' => '2025-10-12 16:45:28',
                'user_type' => 'provider',
            ),
            214 => 
            array (
                'id' => 215,
                'booking_id' => 1180,
                'changed_by' => 7,
                'booking_status' => 'canceled',
                'booking_repeat_id' => NULL,
                'is_guest' => 0,
                'created_at' => '2025-10-12 16:45:42',
                'updated_at' => '2025-10-12 16:45:42',
                'user_type' => 'provider',
            ),
            215 => 
            array (
                'id' => 216,
                'booking_id' => 1186,
                'changed_by' => 8,
                'booking_status' => 'canceled',
                'booking_repeat_id' => NULL,
                'is_guest' => 0,
                'created_at' => '2025-10-13 16:24:17',
                'updated_at' => '2025-10-13 16:24:17',
                'user_type' => 'customer',
            ),
        ));
        
        
    }
}