<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class ServiceServicemenTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('service_servicemen')->delete();
        
        \DB::table('service_servicemen')->insert(array (
            0 => 
            array (
                'id' => 1,
                'module_id' => 8,
                'service_provider_id' => 1,
                'first_name' => 'Jhon',
                'last_name' => 'Doe',
                'phone' => '+8801900000001',
                'email' => 'serviceman1@provider1.com',
                'password' => '$2y$10$6u8q48JzjhBekv6gmKnWSebtd.fn7BPBST4o99vYYrUz390aztfRq',
                'profile_image' => '2025-09-04-68b92caed4879.png',
                'identification_number' => '123213',
                'identification_type' => 'nid',
                'identification_image' => '"[{\\"image\\":\\"2025-09-04-68b92caed3a59.png\\",\\"storage\\":\\"public\\"}]"',
                'fcm_token' => 'fAPtCyH-RmOnQyztVR2-vx:APA91bHfHiQmaJlfxbu0jQ7zKpDROugI-3GkqBr1UNKzTcAILoP2ZQWB71J_yhJ7GPAYvo6TAzlNCV-Oy1ocJ7Vqf6Kp6-YqhLz5LdOlRLhyv40pQ0egq3g',
                'auth_token' => 'vYkg1fQIlxiRBgeihBn4yyq0fa8BSeGftTj0u7UjTgyrTfx3LlpIKiyQb6PgtcvK9Nd0DIf9WqE1O5WiyEfS0QPIZnqlLGu2Wra3lUFGITDoZ0UFZVDvCre8',
                'is_phone_verified' => 0,
                'is_email_verified' => 0,
                'phone_verified_at' => NULL,
                'email_verified_at' => NULL,
                'remember_token' => NULL,
                'wallet_balance' => '0.000',
                'loyalty_point' => '0.000',
                'rating_count' => 0,
                'avg_rating' => 0.0,
                'is_active' => 0,
                'is_approved' => 1,
                'deleted_at' => NULL,
                'created_at' => '2025-09-04 06:07:42',
                'updated_at' => '2025-10-13 10:31:49',
                'current_language_key' => 'en',
            ),
            1 => 
            array (
                'id' => 2,
                'module_id' => 8,
                'service_provider_id' => 1,
                'first_name' => 'Mariaa',
                'last_name' => 'Gomez',
                'phone' => '+8801900000002',
                'email' => 'serviceman2@provider1.com',
                'password' => '$2y$10$C8h/CKn5IKCp/xXT6ty./ugI3K7cSomQThlH4mmUah8rBASkaMFBG',
                'profile_image' => '2025-09-04-68b92d23300e9.png',
                'identification_number' => '123213',
                'identification_type' => 'passport',
                'identification_image' => '[{"image":"2025-09-04-68b92d232f23f.png","storage":"public"}]',
                'fcm_token' => NULL,
                'auth_token' => NULL,
                'is_phone_verified' => 0,
                'is_email_verified' => 0,
                'phone_verified_at' => NULL,
                'email_verified_at' => NULL,
                'remember_token' => NULL,
                'wallet_balance' => '0.000',
                'loyalty_point' => '0.000',
                'rating_count' => 0,
                'avg_rating' => 0.0,
                'is_active' => 1,
                'is_approved' => 1,
                'deleted_at' => NULL,
                'created_at' => '2025-09-04 06:09:39',
                'updated_at' => '2025-09-22 09:36:15',
                'current_language_key' => 'en',
            ),
            2 => 
            array (
                'id' => 3,
                'module_id' => 8,
                'service_provider_id' => 7,
                'first_name' => 'Jhon',
                'last_name' => 'Doe',
                'phone' => '+8801755555555',
                'email' => 'serviceman@serviceman.com',
                'password' => '$2y$10$SxK9uy8oavFLAxxKfTp0ku44O8cfmAmwQ.OIBZp7dt5plO8rsJNmq',
                'profile_image' => '2025-09-09-68bfb4cb516ba.png',
                'identification_number' => 'yuirtyuiytrit',
                'identification_type' => 'nid',
                'identification_image' => '[{"image":"2025-09-09-68bfb4cb4cdf3.png","storage":"public"}]',
                'fcm_token' => 'dYON1Dx6RUiDWjhaVhCp3D:APA91bG0ixBS34I62WsBYNINAw7SWgNNnilOeM1eVrYuL7E1CnVxHFn8in1mTKW5eD2JqkBGY5kAfCeYj0HpONIfuXu6g3I85yTWp7vF1h9m_HxyoK52iuw',
                'auth_token' => 'CQRWao8S5dIwi14yRoS9EZUXoMTkVtGpQH178jGZidZ513PzeQ9gZ7AwWrra8flP44PeVGpeDL6BQsiNefntp19homsTWFdyUd5UFr9me2qUxjTatpz7dqT0',
                'is_phone_verified' => 0,
                'is_email_verified' => 0,
                'phone_verified_at' => NULL,
                'email_verified_at' => NULL,
                'remember_token' => NULL,
                'wallet_balance' => '0.000',
                'loyalty_point' => '0.000',
                'rating_count' => 0,
                'avg_rating' => 0.0,
                'is_active' => 1,
                'is_approved' => 1,
                'deleted_at' => NULL,
                'created_at' => '2025-09-09 11:02:03',
                'updated_at' => '2025-09-18 21:48:08',
                'current_language_key' => 'en',
            ),
            3 => 
            array (
                'id' => 4,
                'module_id' => 8,
                'service_provider_id' => 3,
                'first_name' => 'Donal',
                'last_name' => 'Row',
                'phone' => '+8801722334466',
                'email' => 'test.serviceman@gmail.com',
                'password' => '$2y$10$sK7ympwiDZECwnGFmpaSkuUE4NeLdN22gXk7eVxsFYZUdE9PfRUvW',
                'profile_image' => '2025-09-09-68bfbdb7277a9.png',
                'identification_number' => '567476',
                'identification_type' => 'nid',
                'identification_image' => '[{"image":"2025-09-09-68bfbdc2b8ac6.png","storage":"public"},{"image":"2025-09-09-68bfbdc2bb36e.png","storage":"public"}]',
                'fcm_token' => NULL,
                'auth_token' => NULL,
                'is_phone_verified' => 0,
                'is_email_verified' => 0,
                'phone_verified_at' => NULL,
                'email_verified_at' => NULL,
                'remember_token' => NULL,
                'wallet_balance' => '0.000',
                'loyalty_point' => '0.000',
                'rating_count' => 0,
                'avg_rating' => 0.0,
                'is_active' => 1,
                'is_approved' => 1,
                'deleted_at' => NULL,
                'created_at' => '2025-09-09 11:40:07',
                'updated_at' => '2025-09-09 11:40:32',
                'current_language_key' => 'en',
            ),
            4 => 
            array (
                'id' => 5,
                'module_id' => 8,
                'service_provider_id' => 1,
                'first_name' => 'Trevor',
                'last_name' => 'Warren',
                'phone' => '+1 856-959-7885',
                'email' => 'jije@mailinator.com',
                'password' => '$2y$10$7/4uRAgQKUIvmarEFZ2uOe6Jwf3rs5zhR57eZr6xv1gYlTsSMQeMK',
                'profile_image' => '2025-09-17-68ca36740b969.png',
                'identification_number' => '494',
                'identification_type' => 'passport',
                'identification_image' => '"[{\\"image\\":\\"2025-09-17-68ca3673ef917.png\\",\\"storage\\":\\"public\\"}]"',
                'fcm_token' => NULL,
                'auth_token' => NULL,
                'is_phone_verified' => 0,
                'is_email_verified' => 0,
                'phone_verified_at' => NULL,
                'email_verified_at' => NULL,
                'remember_token' => NULL,
                'wallet_balance' => '0.000',
                'loyalty_point' => '0.000',
                'rating_count' => 0,
                'avg_rating' => 0.0,
                'is_active' => 1,
                'is_approved' => 1,
                'deleted_at' => NULL,
                'created_at' => '2025-09-17 10:17:56',
                'updated_at' => '2025-09-17 10:17:56',
                'current_language_key' => 'en',
            ),
            5 => 
            array (
                'id' => 6,
                'module_id' => 8,
                'service_provider_id' => 1,
                'first_name' => 'Tess',
                'last_name' => 'Ppp',
                'phone' => '+8801700002569',
                'email' => 'Cccc@gmail.com',
                'password' => '$2y$10$a/9LYbniq4TRXLB.g0sK2.Opn4VuGDVaSXHvWRPr0vcB6WDboD.yi',
                'profile_image' => '2025-09-21-68cfe35488503.png',
                'identification_number' => 'ffof',
                'identification_type' => 'passport',
                'identification_image' => '[{"image":"2025-09-21-68cfe354873b9.png","storage":"public"}]',
                'fcm_token' => 'dJNt64ifTWiBFirVvtD8O6:APA91bGaayRECSfI3DsnkhcQngaTBYmTV7g_3Euwdj0Rh7Bktlu1qQXzBnRwerdqBXLwNK3OvXEnlMFrwVWxvLlq_GHcM1pxXs1DPFs0ZvyQ_m9BH5oPBLk',
                'auth_token' => 'k7w2Eqfm1sKyWcoa16CdA9Jyt0Vs4VDLMIZLeO33HnS4nGDzNmPMJYMhke1EhRChJrCLuzIewNiJ2rCKcu4M3rjTAT0KWVRolm2Hh9Z9kSpUdyOrHuL23FEu',
                'is_phone_verified' => 0,
                'is_email_verified' => 0,
                'phone_verified_at' => NULL,
                'email_verified_at' => NULL,
                'remember_token' => NULL,
                'wallet_balance' => '0.000',
                'loyalty_point' => '0.000',
                'rating_count' => 0,
                'avg_rating' => 0.0,
                'is_active' => 1,
                'is_approved' => 1,
                'deleted_at' => NULL,
                'created_at' => '2025-09-21 17:36:52',
                'updated_at' => '2025-10-12 17:30:48',
                'current_language_key' => 'en',
            ),
            6 => 
            array (
                'id' => 7,
                'module_id' => 8,
                'service_provider_id' => 8,
                'first_name' => 'Tester',
                'last_name' => 'Serviceman app',
                'phone' => '+8801700008526',
                'email' => 'service@gmail.com',
                'password' => '$2y$10$yEEn47NqgIZh9i.Vkc5p7OrCY9NRpvO.5RP86EY6QpcvUyEflVE/y',
                'profile_image' => '2025-09-22-68d0e5a64c61f.png',
                'identification_number' => 'jffj',
                'identification_type' => 'nid',
                'identification_image' => '[{"image":"2025-09-22-68d0e5a649e59.png","storage":"public"}]',
                'fcm_token' => 'dLFvjf1GRYWnhbhmnaCs7N:APA91bFWZ9MHnCYhtrQsPZn_uvxnudP5TIlpR7-CF1c5P_4ANQF2aQf5_apqbZdipMge3W_mQVbwP3puMnjgR9PWD1Fl_R2fllYe1SY3RuLVa9o5Ase0ZSA',
                'auth_token' => 'VkITR4TFFBeBUPyxRQwOMdWEOXAtBkR20iM8CgrQG9KEJOEB7AoOylcT5JcB1UTOuxE1F6299yqCxtsexXyNu9rjQuA6EwsRP6bzaRwfvOGo4ruH12bXAaLO',
                'is_phone_verified' => 0,
                'is_email_verified' => 0,
                'phone_verified_at' => NULL,
                'email_verified_at' => NULL,
                'remember_token' => NULL,
                'wallet_balance' => '0.000',
                'loyalty_point' => '0.000',
                'rating_count' => 0,
                'avg_rating' => 0.0,
                'is_active' => 1,
                'is_approved' => 1,
                'deleted_at' => NULL,
                'created_at' => '2025-09-22 11:59:02',
                'updated_at' => '2025-09-22 16:37:58',
                'current_language_key' => 'en',
            ),
        ));
        
        
    }
}