<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class ServiceSearchedDataTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('service_searched_data')->delete();
        
        \DB::table('service_searched_data')->insert(array (
            0 => 
            array (
                'id' => 1,
                'module_id' => 8,
                'user_id' => 8,
                'zone_id' => 1,
                'attribute' => 'search',
                'attribute_id' => 1,
                'response_data_count' => 15,
                'volume' => 5,
                'created_at' => '2025-09-07 11:07:54',
                'updated_at' => '2025-09-07 11:41:18',
            ),
            1 => 
            array (
                'id' => 2,
                'module_id' => 8,
                'user_id' => 14,
                'zone_id' => 1,
                'attribute' => 'search',
                'attribute_id' => 6,
                'response_data_count' => 2,
                'volume' => 1,
                'created_at' => '2025-09-16 12:18:53',
                'updated_at' => '2025-09-16 12:18:53',
            ),
            2 => 
            array (
                'id' => 3,
                'module_id' => 8,
                'user_id' => 33,
                'zone_id' => 1,
                'attribute' => 'search',
                'attribute_id' => 7,
                'response_data_count' => 27,
                'volume' => 8,
                'created_at' => '2025-09-17 12:24:24',
                'updated_at' => '2025-09-20 13:06:17',
            ),
            3 => 
            array (
                'id' => 4,
                'module_id' => 8,
                'user_id' => 33,
                'zone_id' => 1,
                'attribute' => 'search',
                'attribute_id' => 8,
                'response_data_count' => 8,
                'volume' => 2,
                'created_at' => '2025-09-17 12:24:51',
                'updated_at' => '2025-09-17 12:25:05',
            ),
            4 => 
            array (
                'id' => 5,
                'module_id' => 8,
                'user_id' => 33,
                'zone_id' => 1,
                'attribute' => 'search',
                'attribute_id' => 10,
                'response_data_count' => 2,
                'volume' => 2,
                'created_at' => '2025-09-17 12:25:19',
                'updated_at' => '2025-09-18 10:01:24',
            ),
            5 => 
            array (
                'id' => 6,
                'module_id' => 8,
                'user_id' => 14,
                'zone_id' => 1,
                'attribute' => 'search',
                'attribute_id' => 12,
                'response_data_count' => 1,
                'volume' => 2,
                'created_at' => '2025-09-18 12:26:50',
                'updated_at' => '2025-09-25 15:16:42',
            ),
            6 => 
            array (
                'id' => 7,
                'module_id' => 8,
                'user_id' => 14,
                'zone_id' => 1,
                'attribute' => 'search',
                'attribute_id' => 13,
                'response_data_count' => 76,
                'volume' => 17,
                'created_at' => '2025-09-18 12:27:09',
                'updated_at' => '2025-09-18 12:30:07',
            ),
            7 => 
            array (
                'id' => 8,
                'module_id' => 8,
                'user_id' => 33,
                'zone_id' => 1,
                'attribute' => 'search',
                'attribute_id' => 30,
                'response_data_count' => 21,
                'volume' => 4,
                'created_at' => '2025-09-20 12:19:28',
                'updated_at' => '2025-09-24 10:48:37',
            ),
            8 => 
            array (
                'id' => 9,
                'module_id' => 8,
                'user_id' => 33,
                'zone_id' => 1,
                'attribute' => 'search',
                'attribute_id' => 33,
                'response_data_count' => 104,
                'volume' => 29,
                'created_at' => '2025-09-20 12:24:36',
                'updated_at' => '2025-09-20 13:04:40',
            ),
            9 => 
            array (
                'id' => 10,
                'module_id' => 8,
                'user_id' => 8,
                'zone_id' => 1,
                'attribute' => 'search',
                'attribute_id' => 34,
                'response_data_count' => 0,
                'volume' => 1,
                'created_at' => '2025-09-20 12:30:23',
                'updated_at' => '2025-09-20 12:30:23',
            ),
            10 => 
            array (
                'id' => 11,
                'module_id' => 8,
                'user_id' => 33,
                'zone_id' => 1,
                'attribute' => 'search',
                'attribute_id' => 35,
                'response_data_count' => 0,
                'volume' => 2,
                'created_at' => '2025-09-20 12:35:55',
                'updated_at' => '2025-09-20 12:57:35',
            ),
            11 => 
            array (
                'id' => 12,
                'module_id' => 8,
                'user_id' => 33,
                'zone_id' => 1,
                'attribute' => 'search',
                'attribute_id' => 36,
                'response_data_count' => 0,
                'volume' => 7,
                'created_at' => '2025-09-20 12:36:05',
                'updated_at' => '2025-09-20 12:39:44',
            ),
            12 => 
            array (
                'id' => 13,
                'module_id' => 8,
                'user_id' => 33,
                'zone_id' => 1,
                'attribute' => 'search',
                'attribute_id' => 13,
                'response_data_count' => 20,
                'volume' => 4,
                'created_at' => '2025-09-20 12:40:07',
                'updated_at' => '2025-09-20 12:40:46',
            ),
            13 => 
            array (
                'id' => 14,
                'module_id' => 8,
                'user_id' => 33,
                'zone_id' => 1,
                'attribute' => 'search',
                'attribute_id' => 47,
                'response_data_count' => 62,
                'volume' => 9,
                'created_at' => '2025-09-20 12:42:45',
                'updated_at' => '2025-09-30 09:59:38',
            ),
            14 => 
            array (
                'id' => 15,
                'module_id' => 8,
                'user_id' => 33,
                'zone_id' => 1,
                'attribute' => 'search',
                'attribute_id' => 49,
                'response_data_count' => 0,
                'volume' => 1,
                'created_at' => '2025-09-20 12:42:59',
                'updated_at' => '2025-09-20 12:42:59',
            ),
            15 => 
            array (
                'id' => 16,
                'module_id' => 8,
                'user_id' => 33,
                'zone_id' => 1,
                'attribute' => 'search',
                'attribute_id' => 79,
                'response_data_count' => 8,
                'volume' => 2,
                'created_at' => '2025-09-20 13:05:04',
                'updated_at' => '2025-09-21 17:25:11',
            ),
            16 => 
            array (
                'id' => 17,
                'module_id' => 8,
                'user_id' => 21,
                'zone_id' => 1,
                'attribute' => 'search',
                'attribute_id' => 33,
                'response_data_count' => 10,
                'volume' => 2,
                'created_at' => '2025-09-21 12:13:02',
                'updated_at' => '2025-09-21 12:13:05',
            ),
            17 => 
            array (
                'id' => 18,
                'module_id' => 8,
                'user_id' => 33,
                'zone_id' => 1,
                'attribute' => 'search',
                'attribute_id' => 90,
                'response_data_count' => 21,
                'volume' => 3,
                'created_at' => '2025-09-23 16:04:14',
                'updated_at' => '2025-09-23 16:07:36',
            ),
            18 => 
            array (
                'id' => 19,
                'module_id' => 8,
                'user_id' => 33,
                'zone_id' => 1,
                'attribute' => 'search',
                'attribute_id' => 94,
                'response_data_count' => 0,
                'volume' => 2,
                'created_at' => '2025-09-24 10:52:07',
                'updated_at' => '2025-09-24 13:40:21',
            ),
            19 => 
            array (
                'id' => 20,
                'module_id' => 8,
                'user_id' => 33,
                'zone_id' => 1,
                'attribute' => 'search',
                'attribute_id' => 95,
                'response_data_count' => 21,
                'volume' => 3,
                'created_at' => '2025-09-24 10:54:29',
                'updated_at' => '2025-09-24 10:55:17',
            ),
            20 => 
            array (
                'id' => 21,
                'module_id' => 8,
                'user_id' => 8,
                'zone_id' => 1,
                'attribute' => 'search',
                'attribute_id' => 94,
                'response_data_count' => 0,
                'volume' => 1,
                'created_at' => '2025-09-25 14:50:59',
                'updated_at' => '2025-09-25 14:50:59',
            ),
            21 => 
            array (
                'id' => 22,
                'module_id' => 8,
                'user_id' => 14,
                'zone_id' => 1,
                'attribute' => 'search',
                'attribute_id' => 101,
                'response_data_count' => 1,
                'volume' => 1,
                'created_at' => '2025-09-25 15:17:33',
                'updated_at' => '2025-09-25 15:17:33',
            ),
            22 => 
            array (
                'id' => 23,
                'module_id' => 8,
                'user_id' => 14,
                'zone_id' => 1,
                'attribute' => 'search',
                'attribute_id' => 33,
                'response_data_count' => 6,
                'volume' => 1,
                'created_at' => '2025-09-25 15:18:17',
                'updated_at' => '2025-09-25 15:18:17',
            ),
            23 => 
            array (
                'id' => 24,
                'module_id' => 8,
                'user_id' => 14,
                'zone_id' => 1,
                'attribute' => 'search',
                'attribute_id' => 94,
                'response_data_count' => 0,
                'volume' => 12,
                'created_at' => '2025-09-25 15:20:42',
                'updated_at' => '2025-10-05 11:36:53',
            ),
            24 => 
            array (
                'id' => 25,
                'module_id' => 8,
                'user_id' => 14,
                'zone_id' => 1,
                'attribute' => 'search',
                'attribute_id' => 1,
                'response_data_count' => 40,
                'volume' => 8,
                'created_at' => '2025-09-25 15:20:50',
                'updated_at' => '2025-10-12 13:48:23',
            ),
            25 => 
            array (
                'id' => 26,
                'module_id' => 8,
                'user_id' => 14,
                'zone_id' => 1,
                'attribute' => 'search',
                'attribute_id' => 105,
                'response_data_count' => 0,
                'volume' => 1,
                'created_at' => '2025-09-25 15:23:13',
                'updated_at' => '2025-09-25 15:23:13',
            ),
            26 => 
            array (
                'id' => 27,
                'module_id' => 8,
                'user_id' => 33,
                'zone_id' => 1,
                'attribute' => 'search',
                'attribute_id' => 112,
                'response_data_count' => 18,
                'volume' => 2,
                'created_at' => '2025-09-28 10:06:58',
                'updated_at' => '2025-09-28 10:07:25',
            ),
            27 => 
            array (
                'id' => 28,
                'module_id' => 8,
                'user_id' => 33,
                'zone_id' => 1,
                'attribute' => 'search',
                'attribute_id' => 114,
                'response_data_count' => 450,
                'volume' => 45,
                'created_at' => '2025-09-28 16:14:29',
                'updated_at' => '2025-09-28 17:10:36',
            ),
            28 => 
            array (
                'id' => 29,
                'module_id' => 8,
                'user_id' => 33,
                'zone_id' => 1,
                'attribute' => 'search',
                'attribute_id' => 120,
                'response_data_count' => 1,
                'volume' => 1,
                'created_at' => '2025-09-28 16:16:09',
                'updated_at' => '2025-09-28 16:16:09',
            ),
            29 => 
            array (
                'id' => 30,
                'module_id' => 8,
                'user_id' => 32,
                'zone_id' => 1,
                'attribute' => 'search',
                'attribute_id' => 30,
                'response_data_count' => 12,
                'volume' => 2,
                'created_at' => '2025-09-29 10:04:41',
                'updated_at' => '2025-09-29 10:04:53',
            ),
            30 => 
            array (
                'id' => 31,
                'module_id' => 8,
                'user_id' => 32,
                'zone_id' => 1,
                'attribute' => 'search',
                'attribute_id' => 162,
                'response_data_count' => 16,
                'volume' => 4,
                'created_at' => '2025-09-29 11:35:17',
                'updated_at' => '2025-10-11 15:10:56',
            ),
            31 => 
            array (
                'id' => 32,
                'module_id' => 8,
                'user_id' => 32,
                'zone_id' => 1,
                'attribute' => 'search',
                'attribute_id' => 164,
                'response_data_count' => 3,
                'volume' => 3,
                'created_at' => '2025-09-29 11:42:57',
                'updated_at' => '2025-09-29 11:43:24',
            ),
            32 => 
            array (
                'id' => 33,
                'module_id' => 8,
                'user_id' => 32,
                'zone_id' => 1,
                'attribute' => 'search',
                'attribute_id' => 167,
                'response_data_count' => 0,
                'volume' => 1,
                'created_at' => '2025-09-29 11:44:11',
                'updated_at' => '2025-09-29 11:44:11',
            ),
            33 => 
            array (
                'id' => 34,
                'module_id' => 8,
                'user_id' => 32,
                'zone_id' => 1,
                'attribute' => 'search',
                'attribute_id' => 168,
                'response_data_count' => 0,
                'volume' => 1,
                'created_at' => '2025-09-29 11:44:39',
                'updated_at' => '2025-09-29 11:44:39',
            ),
            34 => 
            array (
                'id' => 35,
                'module_id' => 8,
                'user_id' => 32,
                'zone_id' => 1,
                'attribute' => 'search',
                'attribute_id' => 90,
                'response_data_count' => 25,
                'volume' => 4,
                'created_at' => '2025-09-29 17:15:05',
                'updated_at' => '2025-10-09 11:07:49',
            ),
            35 => 
            array (
                'id' => 36,
                'module_id' => 8,
                'user_id' => 33,
                'zone_id' => 1,
                'attribute' => 'search',
                'attribute_id' => 164,
                'response_data_count' => 2,
                'volume' => 2,
                'created_at' => '2025-09-29 18:21:16',
                'updated_at' => '2025-09-30 10:45:50',
            ),
            36 => 
            array (
                'id' => 37,
                'module_id' => 8,
                'user_id' => 33,
                'zone_id' => 1,
                'attribute' => 'search',
                'attribute_id' => 1,
                'response_data_count' => 13,
                'volume' => 3,
                'created_at' => '2025-09-29 18:21:41',
                'updated_at' => '2025-09-29 18:21:55',
            ),
            37 => 
            array (
                'id' => 38,
                'module_id' => 8,
                'user_id' => 32,
                'zone_id' => 1,
                'attribute' => 'search',
                'attribute_id' => 176,
                'response_data_count' => 12,
                'volume' => 6,
                'created_at' => '2025-09-30 09:49:58',
                'updated_at' => '2025-09-30 11:19:17',
            ),
            38 => 
            array (
                'id' => 39,
                'module_id' => 8,
                'user_id' => 33,
                'zone_id' => 1,
                'attribute' => 'search',
                'attribute_id' => 187,
                'response_data_count' => 0,
                'volume' => 1,
                'created_at' => '2025-09-30 10:01:37',
                'updated_at' => '2025-09-30 10:01:37',
            ),
            39 => 
            array (
                'id' => 40,
                'module_id' => 8,
                'user_id' => 33,
                'zone_id' => 1,
                'attribute' => 'search',
                'attribute_id' => 191,
                'response_data_count' => 30,
                'volume' => 3,
                'created_at' => '2025-09-30 14:57:13',
                'updated_at' => '2025-09-30 14:58:42',
            ),
            40 => 
            array (
                'id' => 41,
                'module_id' => 8,
                'user_id' => 14,
                'zone_id' => 1,
                'attribute' => 'search',
                'attribute_id' => 30,
                'response_data_count' => 31,
                'volume' => 6,
                'created_at' => '2025-10-05 11:25:19',
                'updated_at' => '2025-10-05 11:27:15',
            ),
            41 => 
            array (
                'id' => 42,
                'module_id' => 8,
                'user_id' => 14,
                'zone_id' => 1,
                'attribute' => 'search',
                'attribute_id' => 211,
                'response_data_count' => 4,
                'volume' => 1,
                'created_at' => '2025-10-05 12:04:14',
                'updated_at' => '2025-10-05 12:04:14',
            ),
            42 => 
            array (
                'id' => 43,
                'module_id' => 8,
                'user_id' => 32,
                'zone_id' => 1,
                'attribute' => 'search',
                'attribute_id' => 33,
                'response_data_count' => 120,
                'volume' => 20,
                'created_at' => '2025-10-05 12:34:07',
                'updated_at' => '2025-10-11 15:29:45',
            ),
            43 => 
            array (
                'id' => 44,
                'module_id' => 8,
                'user_id' => 32,
                'zone_id' => 1,
                'attribute' => 'search',
                'attribute_id' => 120,
                'response_data_count' => 2,
                'volume' => 2,
                'created_at' => '2025-10-05 14:37:11',
                'updated_at' => '2025-10-05 14:54:17',
            ),
            44 => 
            array (
                'id' => 45,
                'module_id' => 8,
                'user_id' => 8,
                'zone_id' => 1,
                'attribute' => 'search',
                'attribute_id' => 164,
                'response_data_count' => 1,
                'volume' => 1,
                'created_at' => '2025-10-06 09:56:43',
                'updated_at' => '2025-10-06 09:56:43',
            ),
            45 => 
            array (
                'id' => 46,
                'module_id' => 8,
                'user_id' => 14,
                'zone_id' => 1,
                'attribute' => 'search',
                'attribute_id' => 232,
                'response_data_count' => 13,
                'volume' => 2,
                'created_at' => '2025-10-07 12:20:22',
                'updated_at' => '2025-10-07 12:20:25',
            ),
            46 => 
            array (
                'id' => 47,
                'module_id' => 8,
                'user_id' => 32,
                'zone_id' => 1,
                'attribute' => 'search',
                'attribute_id' => 235,
                'response_data_count' => 4,
                'volume' => 1,
                'created_at' => '2025-10-09 11:09:46',
                'updated_at' => '2025-10-09 11:09:46',
            ),
            47 => 
            array (
                'id' => 48,
                'module_id' => 8,
                'user_id' => 8,
                'zone_id' => 1,
                'attribute' => 'search',
                'attribute_id' => 236,
                'response_data_count' => 33,
                'volume' => 23,
                'created_at' => '2025-10-11 09:52:34',
                'updated_at' => '2025-10-11 09:54:22',
            ),
            48 => 
            array (
                'id' => 49,
                'module_id' => 8,
                'user_id' => 32,
                'zone_id' => 1,
                'attribute' => 'search',
                'attribute_id' => 264,
                'response_data_count' => 98,
                'volume' => 18,
                'created_at' => '2025-10-11 15:29:58',
                'updated_at' => '2025-10-11 15:59:48',
            ),
            49 => 
            array (
                'id' => 50,
                'module_id' => 8,
                'user_id' => 8,
                'zone_id' => 1,
                'attribute' => 'search',
                'attribute_id' => 282,
                'response_data_count' => 9,
                'volume' => 1,
                'created_at' => '2025-10-12 09:53:49',
                'updated_at' => '2025-10-12 09:53:49',
            ),
        ));
        
        
    }
}