<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class ServiceCartsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('service_carts')->delete();
        
        \DB::table('service_carts')->insert(array (
            0 => 
            array (
                'id' => 9,
                'module_id' => 8,
                'customer_id' => 2,
                'provider_id' => 1,
                'service_id' => 3,
                'category_id' => 1,
                'sub_category_id' => 5,
                'variant_key' => '5000-SFT',
                'service_cost' => '350.00',
                'quantity' => 1,
                'discount_amount' => '0.00',
                'campaign_discount' => '0.00',
                'coupon_discount' => '0.00',
                'coupon_code' => NULL,
                'tax_amount' => '35.00',
                'total_cost' => '385.00',
                'coupon_id' => 0,
                'is_guest' => 1,
                'created_at' => '2025-09-04 07:36:20',
                'updated_at' => '2025-09-04 07:37:46',
            ),
            1 => 
            array (
                'id' => 19,
                'module_id' => 8,
                'customer_id' => 4,
                'provider_id' => NULL,
                'service_id' => 2,
                'category_id' => 1,
                'sub_category_id' => 4,
                'variant_key' => 'In-2000-SFT',
                'service_cost' => '200.00',
                'quantity' => 2,
                'discount_amount' => '0.00',
                'campaign_discount' => '0.00',
                'coupon_discount' => '0.00',
                'coupon_code' => NULL,
                'tax_amount' => '40.00',
                'total_cost' => '440.00',
                'coupon_id' => 0,
                'is_guest' => 1,
                'created_at' => '2025-09-04 10:24:00',
                'updated_at' => '2025-09-04 10:24:04',
            ),
            2 => 
            array (
                'id' => 34,
                'module_id' => 8,
                'customer_id' => 9,
                'provider_id' => NULL,
                'service_id' => 2,
                'category_id' => 1,
                'sub_category_id' => 4,
                'variant_key' => 'More-than-2000-SFT',
                'service_cost' => '400.00',
                'quantity' => 1,
                'discount_amount' => '0.00',
                'campaign_discount' => '0.00',
                'coupon_discount' => '0.00',
                'coupon_code' => NULL,
                'tax_amount' => '40.00',
                'total_cost' => '440.00',
                'coupon_id' => 0,
                'is_guest' => 1,
                'created_at' => '2025-09-07 07:43:04',
                'updated_at' => '2025-09-07 07:43:04',
            ),
            3 => 
            array (
                'id' => 87,
                'module_id' => 8,
                'customer_id' => 20,
                'provider_id' => 2,
                'service_id' => 1,
                'category_id' => 1,
                'sub_category_id' => 4,
                'variant_key' => 'In-1200-SFT',
                'service_cost' => '50.00',
                'quantity' => 2,
                'discount_amount' => '0.00',
                'campaign_discount' => '0.00',
                'coupon_discount' => '0.00',
                'coupon_code' => NULL,
                'tax_amount' => '10.00',
                'total_cost' => '110.00',
                'coupon_id' => 0,
                'is_guest' => 1,
                'created_at' => '2025-09-07 11:15:39',
                'updated_at' => '2025-09-07 11:25:11',
            ),
            4 => 
            array (
                'id' => 106,
                'module_id' => 8,
                'customer_id' => 265,
                'provider_id' => NULL,
                'service_id' => 2,
                'category_id' => 1,
                'sub_category_id' => 4,
                'variant_key' => 'In-2000-SFT',
                'service_cost' => '200.00',
                'quantity' => 1,
                'discount_amount' => '0.00',
                'campaign_discount' => '0.00',
                'coupon_discount' => '0.00',
                'coupon_code' => NULL,
                'tax_amount' => '20.00',
                'total_cost' => '220.00',
                'coupon_id' => 0,
                'is_guest' => 1,
                'created_at' => '2025-09-07 11:30:36',
                'updated_at' => '2025-09-07 11:30:36',
            ),
            5 => 
            array (
                'id' => 107,
                'module_id' => 8,
                'customer_id' => 265,
                'provider_id' => NULL,
                'service_id' => 2,
                'category_id' => 1,
                'sub_category_id' => 4,
                'variant_key' => 'More-than-2000-SFT',
                'service_cost' => '400.00',
                'quantity' => 1,
                'discount_amount' => '0.00',
                'campaign_discount' => '0.00',
                'coupon_discount' => '0.00',
                'coupon_code' => NULL,
                'tax_amount' => '40.00',
                'total_cost' => '440.00',
                'coupon_id' => 0,
                'is_guest' => 1,
                'created_at' => '2025-09-07 11:30:37',
                'updated_at' => '2025-09-07 11:30:37',
            ),
            6 => 
            array (
                'id' => 114,
                'module_id' => 8,
                'customer_id' => 276,
                'provider_id' => NULL,
                'service_id' => 1,
                'category_id' => 1,
                'sub_category_id' => 4,
                'variant_key' => 'In-1200-SFT',
                'service_cost' => '50.00',
                'quantity' => 1,
                'discount_amount' => '0.00',
                'campaign_discount' => '0.00',
                'coupon_discount' => '0.00',
                'coupon_code' => NULL,
                'tax_amount' => '5.00',
                'total_cost' => '55.00',
                'coupon_id' => 0,
                'is_guest' => 1,
                'created_at' => '2025-09-07 12:08:29',
                'updated_at' => '2025-09-07 12:08:29',
            ),
            7 => 
            array (
                'id' => 115,
                'module_id' => 8,
                'customer_id' => 276,
                'provider_id' => NULL,
                'service_id' => 1,
                'category_id' => 1,
                'sub_category_id' => 4,
                'variant_key' => 'In-3000-SFT',
                'service_cost' => '350.00',
                'quantity' => 1,
                'discount_amount' => '0.00',
                'campaign_discount' => '0.00',
                'coupon_discount' => '0.00',
                'coupon_code' => NULL,
                'tax_amount' => '35.00',
                'total_cost' => '385.00',
                'coupon_id' => 0,
                'is_guest' => 1,
                'created_at' => '2025-09-07 12:08:29',
                'updated_at' => '2025-09-07 12:08:29',
            ),
            8 => 
            array (
                'id' => 116,
                'module_id' => 8,
                'customer_id' => 276,
                'provider_id' => NULL,
                'service_id' => 1,
                'category_id' => 1,
                'sub_category_id' => 4,
                'variant_key' => 'In-2000-SFT',
                'service_cost' => '200.00',
                'quantity' => 1,
                'discount_amount' => '0.00',
                'campaign_discount' => '0.00',
                'coupon_discount' => '0.00',
                'coupon_code' => NULL,
                'tax_amount' => '20.00',
                'total_cost' => '220.00',
                'coupon_id' => 0,
                'is_guest' => 1,
                'created_at' => '2025-09-07 12:08:29',
                'updated_at' => '2025-09-07 12:08:29',
            ),
            9 => 
            array (
                'id' => 117,
                'module_id' => 8,
                'customer_id' => 34,
                'provider_id' => NULL,
                'service_id' => 1,
                'category_id' => 1,
                'sub_category_id' => 4,
                'variant_key' => 'In-3000-SFT',
                'service_cost' => '350.00',
                'quantity' => 1,
                'discount_amount' => '0.00',
                'campaign_discount' => '0.00',
                'coupon_discount' => '0.00',
                'coupon_code' => NULL,
                'tax_amount' => '35.00',
                'total_cost' => '385.00',
                'coupon_id' => 0,
                'is_guest' => 1,
                'created_at' => '2025-09-08 04:58:49',
                'updated_at' => '2025-09-08 04:58:49',
            ),
            10 => 
            array (
                'id' => 118,
                'module_id' => 8,
                'customer_id' => 10,
                'provider_id' => NULL,
                'service_id' => 1,
                'category_id' => 1,
                'sub_category_id' => 4,
                'variant_key' => 'In-2000-SFT',
                'service_cost' => '200.00',
                'quantity' => 1,
                'discount_amount' => '0.00',
                'campaign_discount' => '0.00',
                'coupon_discount' => '0.00',
                'coupon_code' => NULL,
                'tax_amount' => '20.00',
                'total_cost' => '220.00',
                'coupon_id' => 0,
                'is_guest' => 0,
                'created_at' => '2025-09-08 11:55:29',
                'updated_at' => '2025-09-08 11:58:01',
            ),
            11 => 
            array (
                'id' => 119,
                'module_id' => 8,
                'customer_id' => 43,
                'provider_id' => NULL,
                'service_id' => 1,
                'category_id' => 1,
                'sub_category_id' => 4,
                'variant_key' => 'In-1200-SFT',
                'service_cost' => '50.00',
                'quantity' => 1,
                'discount_amount' => '0.00',
                'campaign_discount' => '0.00',
                'coupon_discount' => '0.00',
                'coupon_code' => NULL,
                'tax_amount' => '5.00',
                'total_cost' => '55.00',
                'coupon_id' => 0,
                'is_guest' => 1,
                'created_at' => '2025-09-09 10:39:38',
                'updated_at' => '2025-09-09 10:39:38',
            ),
            12 => 
            array (
                'id' => 120,
                'module_id' => 8,
                'customer_id' => 43,
                'provider_id' => NULL,
                'service_id' => 1,
                'category_id' => 1,
                'sub_category_id' => 4,
                'variant_key' => 'In-2000-SFT',
                'service_cost' => '200.00',
                'quantity' => 1,
                'discount_amount' => '0.00',
                'campaign_discount' => '0.00',
                'coupon_discount' => '0.00',
                'coupon_code' => NULL,
                'tax_amount' => '20.00',
                'total_cost' => '220.00',
                'coupon_id' => 0,
                'is_guest' => 1,
                'created_at' => '2025-09-09 10:39:38',
                'updated_at' => '2025-09-09 10:39:38',
            ),
            13 => 
            array (
                'id' => 151,
                'module_id' => 8,
                'customer_id' => 72,
                'provider_id' => 2,
                'service_id' => 3,
                'category_id' => 1,
                'sub_category_id' => 5,
                'variant_key' => '500-SFT',
                'service_cost' => '100.00',
                'quantity' => 1,
                'discount_amount' => '30.00',
                'campaign_discount' => '0.00',
                'coupon_discount' => '0.00',
                'coupon_code' => NULL,
                'tax_amount' => '7.00',
                'total_cost' => '77.00',
                'coupon_id' => 0,
                'is_guest' => 1,
                'created_at' => '2025-09-09 13:16:54',
                'updated_at' => '2025-09-09 13:17:00',
            ),
            14 => 
            array (
                'id' => 152,
                'module_id' => 8,
                'customer_id' => 72,
                'provider_id' => 2,
                'service_id' => 3,
                'category_id' => 1,
                'sub_category_id' => 5,
                'variant_key' => '1000-SFT',
                'service_cost' => '200.00',
                'quantity' => 1,
                'discount_amount' => '50.00',
                'campaign_discount' => '0.00',
                'coupon_discount' => '0.00',
                'coupon_code' => NULL,
                'tax_amount' => '15.00',
                'total_cost' => '165.00',
                'coupon_id' => 0,
                'is_guest' => 1,
                'created_at' => '2025-09-09 13:16:54',
                'updated_at' => '2025-09-09 13:17:00',
            ),
            15 => 
            array (
                'id' => 154,
                'module_id' => 8,
                'customer_id' => 93,
                'provider_id' => NULL,
                'service_id' => 4,
                'category_id' => 1,
                'sub_category_id' => 4,
                'variant_key' => 'Full-house-glass-clean',
                'service_cost' => '200.00',
                'quantity' => 1,
                'discount_amount' => '50.00',
                'campaign_discount' => '0.00',
                'coupon_discount' => '0.00',
                'coupon_code' => NULL,
                'tax_amount' => '7.50',
                'total_cost' => '157.50',
                'coupon_id' => 0,
                'is_guest' => 1,
                'created_at' => '2025-09-09 13:55:52',
                'updated_at' => '2025-09-09 13:55:52',
            ),
            16 => 
            array (
                'id' => 162,
                'module_id' => 8,
                'customer_id' => 116,
                'provider_id' => NULL,
                'service_id' => 1,
                'category_id' => 1,
                'sub_category_id' => 4,
                'variant_key' => 'In-1200-SFT',
                'service_cost' => '50.00',
                'quantity' => 1,
                'discount_amount' => '15.00',
                'campaign_discount' => '0.00',
                'coupon_discount' => '0.00',
                'coupon_code' => NULL,
                'tax_amount' => '3.50',
                'total_cost' => '38.50',
                'coupon_id' => 0,
                'is_guest' => 1,
                'created_at' => '2025-09-10 17:22:26',
                'updated_at' => '2025-09-10 17:22:26',
            ),
            17 => 
            array (
                'id' => 170,
                'module_id' => 8,
                'customer_id' => 21,
                'provider_id' => NULL,
                'service_id' => 1,
                'category_id' => 1,
                'sub_category_id' => 4,
                'variant_key' => 'In-1200-SFT',
                'service_cost' => '50.00',
                'quantity' => 1,
                'discount_amount' => '15.00',
                'campaign_discount' => '0.00',
                'coupon_discount' => '0.00',
                'coupon_code' => NULL,
                'tax_amount' => '3.50',
                'total_cost' => '38.50',
                'coupon_id' => 0,
                'is_guest' => 0,
                'created_at' => '2025-09-11 11:28:49',
                'updated_at' => '2025-09-11 11:28:49',
            ),
            18 => 
            array (
                'id' => 173,
                'module_id' => 8,
                'customer_id' => 136,
                'provider_id' => NULL,
                'service_id' => 2,
                'category_id' => 1,
                'sub_category_id' => 4,
                'variant_key' => 'In-2000-SFT',
                'service_cost' => '200.00',
                'quantity' => 1,
                'discount_amount' => '50.00',
                'campaign_discount' => '0.00',
                'coupon_discount' => '0.00',
                'coupon_code' => NULL,
                'tax_amount' => '15.00',
                'total_cost' => '165.00',
                'coupon_id' => 0,
                'is_guest' => 1,
                'created_at' => '2025-09-11 11:54:44',
                'updated_at' => '2025-09-11 11:54:44',
            ),
            19 => 
            array (
                'id' => 182,
                'module_id' => 8,
                'customer_id' => 146,
                'provider_id' => NULL,
                'service_id' => 4,
                'category_id' => 1,
                'sub_category_id' => 4,
                'variant_key' => 'Window-clean',
                'service_cost' => '51.00',
                'quantity' => 3,
                'discount_amount' => '45.90',
                'campaign_discount' => '0.00',
                'coupon_discount' => '0.00',
                'coupon_code' => NULL,
                'tax_amount' => '5.36',
                'total_cost' => '112.46',
                'coupon_id' => 0,
                'is_guest' => 1,
                'created_at' => '2025-09-11 13:15:35',
                'updated_at' => '2025-09-11 13:15:35',
            ),
            20 => 
            array (
                'id' => 183,
                'module_id' => 8,
                'customer_id' => 118,
                'provider_id' => NULL,
                'service_id' => 3,
                'category_id' => 1,
                'sub_category_id' => 5,
                'variant_key' => '500-SFT',
                'service_cost' => '100.00',
                'quantity' => 1,
                'discount_amount' => '30.00',
                'campaign_discount' => '0.00',
                'coupon_discount' => '0.00',
                'coupon_code' => NULL,
                'tax_amount' => '7.00',
                'total_cost' => '77.00',
                'coupon_id' => 0,
                'is_guest' => 1,
                'created_at' => '2025-09-11 13:17:48',
                'updated_at' => '2025-09-11 13:17:48',
            ),
            21 => 
            array (
                'id' => 184,
                'module_id' => 8,
                'customer_id' => 147,
                'provider_id' => NULL,
                'service_id' => 6,
                'category_id' => 3,
                'sub_category_id' => 10,
                'variant_key' => 'fan-service',
                'service_cost' => '50.00',
                'quantity' => 1,
                'discount_amount' => '15.00',
                'campaign_discount' => '0.00',
                'coupon_discount' => '0.00',
                'coupon_code' => NULL,
                'tax_amount' => '1.75',
                'total_cost' => '36.75',
                'coupon_id' => 0,
                'is_guest' => 1,
                'created_at' => '2025-09-11 13:23:52',
                'updated_at' => '2025-09-11 13:23:52',
            ),
            22 => 
            array (
                'id' => 191,
                'module_id' => 8,
                'customer_id' => 282,
                'provider_id' => 7,
                'service_id' => 1,
                'category_id' => 1,
                'sub_category_id' => 4,
                'variant_key' => 'In-1200-SFT',
                'service_cost' => '50.00',
                'quantity' => 1,
                'discount_amount' => '15.00',
                'campaign_discount' => '0.00',
                'coupon_discount' => '0.00',
                'coupon_code' => NULL,
                'tax_amount' => '3.50',
                'total_cost' => '38.50',
                'coupon_id' => 0,
                'is_guest' => 1,
                'created_at' => '2025-09-16 15:30:19',
                'updated_at' => '2025-09-16 15:30:41',
            ),
            23 => 
            array (
                'id' => 212,
                'module_id' => 8,
                'customer_id' => 416,
                'provider_id' => NULL,
                'service_id' => 4,
                'category_id' => 1,
                'sub_category_id' => 4,
                'variant_key' => 'Full-house-glass-clean',
                'service_cost' => '200.00',
                'quantity' => 2,
                'discount_amount' => '50.00',
                'campaign_discount' => '0.00',
                'coupon_discount' => '0.00',
                'coupon_code' => NULL,
                'tax_amount' => '17.50',
                'total_cost' => '367.50',
                'coupon_id' => 0,
                'is_guest' => 1,
                'created_at' => '2025-09-17 12:37:55',
                'updated_at' => '2025-09-17 12:37:55',
            ),
            24 => 
            array (
                'id' => 213,
                'module_id' => 8,
                'customer_id' => 416,
                'provider_id' => NULL,
                'service_id' => 4,
                'category_id' => 1,
                'sub_category_id' => 4,
                'variant_key' => 'Window-clean',
                'service_cost' => '51.00',
                'quantity' => 2,
                'discount_amount' => '30.60',
                'campaign_discount' => '0.00',
                'coupon_discount' => '0.00',
                'coupon_code' => NULL,
                'tax_amount' => '3.57',
                'total_cost' => '74.97',
                'coupon_id' => 0,
                'is_guest' => 1,
                'created_at' => '2025-09-17 12:37:55',
                'updated_at' => '2025-09-17 12:37:55',
            ),
            25 => 
            array (
                'id' => 287,
                'module_id' => 8,
                'customer_id' => 482,
                'provider_id' => NULL,
                'service_id' => 1,
                'category_id' => 1,
                'sub_category_id' => 4,
                'variant_key' => 'In-3000-SFT',
                'service_cost' => '350.00',
                'quantity' => 1,
                'discount_amount' => '0.00',
                'campaign_discount' => '87.00',
                'coupon_discount' => '0.00',
                'coupon_code' => NULL,
                'tax_amount' => '26.30',
                'total_cost' => '289.30',
                'coupon_id' => 0,
                'is_guest' => 1,
                'created_at' => '2025-09-21 14:40:51',
                'updated_at' => '2025-09-21 14:40:51',
            ),
            26 => 
            array (
                'id' => 331,
                'module_id' => 8,
                'customer_id' => 519,
                'provider_id' => NULL,
                'service_id' => 5,
                'category_id' => 1,
                'sub_category_id' => 4,
                'variant_key' => 'Floor-clean',
                'service_cost' => '100.00',
                'quantity' => 3,
                'discount_amount' => '30.00',
                'campaign_discount' => '0.00',
                'coupon_discount' => '0.00',
                'coupon_code' => NULL,
                'tax_amount' => '27.00',
                'total_cost' => '297.00',
                'coupon_id' => 0,
                'is_guest' => 1,
                'created_at' => '2025-09-24 16:27:55',
                'updated_at' => '2025-09-24 16:27:55',
            ),
            27 => 
            array (
                'id' => 349,
                'module_id' => 8,
                'customer_id' => 526,
                'provider_id' => NULL,
                'service_id' => 1,
                'category_id' => 1,
                'sub_category_id' => 4,
                'variant_key' => 'In-2000-SFT',
                'service_cost' => '200.00',
                'quantity' => 1,
                'discount_amount' => '20.00',
                'campaign_discount' => '0.00',
                'coupon_discount' => '0.00',
                'coupon_code' => NULL,
                'tax_amount' => '18.00',
                'total_cost' => '198.00',
                'coupon_id' => 0,
                'is_guest' => 1,
                'created_at' => '2025-09-25 15:25:55',
                'updated_at' => '2025-09-25 15:25:55',
            ),
            28 => 
            array (
                'id' => 462,
                'module_id' => 8,
                'customer_id' => 576,
                'provider_id' => NULL,
                'service_id' => 1,
                'category_id' => 1,
                'sub_category_id' => 4,
                'variant_key' => 'In-1200-SFT',
                'service_cost' => '50.00',
                'quantity' => 1,
                'discount_amount' => '50.00',
                'campaign_discount' => '0.00',
                'coupon_discount' => '0.00',
                'coupon_code' => NULL,
                'tax_amount' => '0.00',
                'total_cost' => '0.00',
                'coupon_id' => 0,
                'is_guest' => 1,
                'created_at' => '2025-10-05 10:42:05',
                'updated_at' => '2025-10-05 10:42:05',
            ),
            29 => 
            array (
                'id' => 508,
                'module_id' => 8,
                'customer_id' => 580,
                'provider_id' => NULL,
                'service_id' => 6,
                'category_id' => 3,
                'sub_category_id' => 10,
                'variant_key' => 'fan-service',
                'service_cost' => '50.00',
                'quantity' => 2,
                'discount_amount' => '0.00',
                'campaign_discount' => '42.00',
                'coupon_discount' => '0.00',
                'coupon_code' => NULL,
                'tax_amount' => '2.90',
                'total_cost' => '60.90',
                'coupon_id' => 0,
                'is_guest' => 1,
                'created_at' => '2025-10-06 09:55:10',
                'updated_at' => '2025-10-06 09:55:16',
            ),
            30 => 
            array (
                'id' => 517,
                'module_id' => 8,
                'customer_id' => 584,
                'provider_id' => 8,
                'service_id' => 1,
                'category_id' => 1,
                'sub_category_id' => 4,
                'variant_key' => 'In-2000-SFT',
                'service_cost' => '200.00',
                'quantity' => 1,
                'discount_amount' => '0.00',
                'campaign_discount' => '0.00',
                'coupon_discount' => '0.00',
                'coupon_code' => NULL,
                'tax_amount' => '20.00',
                'total_cost' => '220.00',
                'coupon_id' => 0,
                'is_guest' => 1,
                'created_at' => '2025-10-06 17:40:15',
                'updated_at' => '2025-10-06 17:40:15',
            ),
            31 => 
            array (
                'id' => 518,
                'module_id' => 8,
                'customer_id' => 584,
                'provider_id' => 8,
                'service_id' => 1,
                'category_id' => 1,
                'sub_category_id' => 4,
                'variant_key' => 'In-1200-SFT',
                'service_cost' => '50.00',
                'quantity' => 1,
                'discount_amount' => '0.00',
                'campaign_discount' => '0.00',
                'coupon_discount' => '0.00',
                'coupon_code' => NULL,
                'tax_amount' => '5.00',
                'total_cost' => '55.00',
                'coupon_id' => 0,
                'is_guest' => 1,
                'created_at' => '2025-10-06 17:40:15',
                'updated_at' => '2025-10-06 17:40:15',
            ),
            32 => 
            array (
                'id' => 519,
                'module_id' => 8,
                'customer_id' => 584,
                'provider_id' => 8,
                'service_id' => 5,
                'category_id' => 1,
                'sub_category_id' => 4,
                'variant_key' => 'Floor-clean',
                'service_cost' => '100.00',
                'quantity' => 1,
                'discount_amount' => '0.00',
                'campaign_discount' => '0.00',
                'coupon_discount' => '0.00',
                'coupon_code' => NULL,
                'tax_amount' => '10.00',
                'total_cost' => '110.00',
                'coupon_id' => 0,
                'is_guest' => 1,
                'created_at' => '2025-10-06 17:40:15',
                'updated_at' => '2025-10-06 17:40:15',
            ),
            33 => 
            array (
                'id' => 552,
                'module_id' => 8,
                'customer_id' => 604,
                'provider_id' => NULL,
                'service_id' => 3,
                'category_id' => 1,
                'sub_category_id' => 5,
                'variant_key' => '500-SFT',
                'service_cost' => '100.00',
                'quantity' => 1,
                'discount_amount' => '10.00',
                'campaign_discount' => '0.00',
                'coupon_discount' => '0.00',
                'coupon_code' => NULL,
                'tax_amount' => '9.00',
                'total_cost' => '99.00',
                'coupon_id' => 0,
                'is_guest' => 1,
                'created_at' => '2025-10-09 10:32:13',
                'updated_at' => '2025-10-09 10:32:13',
            ),
            34 => 
            array (
                'id' => 553,
                'module_id' => 8,
                'customer_id' => 604,
                'provider_id' => NULL,
                'service_id' => 3,
                'category_id' => 1,
                'sub_category_id' => 5,
                'variant_key' => '1000-SFT',
                'service_cost' => '200.00',
                'quantity' => 1,
                'discount_amount' => '20.00',
                'campaign_discount' => '0.00',
                'coupon_discount' => '0.00',
                'coupon_code' => NULL,
                'tax_amount' => '18.00',
                'total_cost' => '198.00',
                'coupon_id' => 0,
                'is_guest' => 1,
                'created_at' => '2025-10-09 10:32:13',
                'updated_at' => '2025-10-09 10:32:13',
            ),
            35 => 
            array (
                'id' => 554,
                'module_id' => 8,
                'customer_id' => 604,
                'provider_id' => NULL,
                'service_id' => 3,
                'category_id' => 1,
                'sub_category_id' => 5,
                'variant_key' => '5000-SFT',
                'service_cost' => '350.00',
                'quantity' => 1,
                'discount_amount' => '35.00',
                'campaign_discount' => '0.00',
                'coupon_discount' => '0.00',
                'coupon_code' => NULL,
                'tax_amount' => '31.50',
                'total_cost' => '346.50',
                'coupon_id' => 0,
                'is_guest' => 1,
                'created_at' => '2025-10-09 10:32:14',
                'updated_at' => '2025-10-09 10:32:14',
            ),
            36 => 
            array (
                'id' => 578,
                'module_id' => 8,
                'customer_id' => 641,
                'provider_id' => NULL,
                'service_id' => 1,
                'category_id' => 1,
                'sub_category_id' => 4,
                'variant_key' => 'In-1200-SFT',
                'service_cost' => '50.00',
                'quantity' => 4,
                'discount_amount' => '200.00',
                'campaign_discount' => '0.00',
                'coupon_discount' => '0.00',
                'coupon_code' => NULL,
                'tax_amount' => '0.00',
                'total_cost' => '0.00',
                'coupon_id' => 0,
                'is_guest' => 1,
                'created_at' => '2025-10-11 08:03:31',
                'updated_at' => '2025-10-11 08:03:59',
            ),
            37 => 
            array (
                'id' => 579,
                'module_id' => 8,
                'customer_id' => 641,
                'provider_id' => NULL,
                'service_id' => 1,
                'category_id' => 1,
                'sub_category_id' => 4,
                'variant_key' => 'In-2000-SFT',
                'service_cost' => '200.00',
                'quantity' => 1,
                'discount_amount' => '200.00',
                'campaign_discount' => '0.00',
                'coupon_discount' => '0.00',
                'coupon_code' => NULL,
                'tax_amount' => '0.00',
                'total_cost' => '0.00',
                'coupon_id' => 0,
                'is_guest' => 1,
                'created_at' => '2025-10-11 08:03:32',
                'updated_at' => '2025-10-11 08:03:32',
            ),
            38 => 
            array (
                'id' => 580,
                'module_id' => 8,
                'customer_id' => 641,
                'provider_id' => NULL,
                'service_id' => 1,
                'category_id' => 1,
                'sub_category_id' => 4,
                'variant_key' => 'In-3000-SFT',
                'service_cost' => '350.00',
                'quantity' => 1,
                'discount_amount' => '350.00',
                'campaign_discount' => '0.00',
                'coupon_discount' => '0.00',
                'coupon_code' => NULL,
                'tax_amount' => '0.00',
                'total_cost' => '0.00',
                'coupon_id' => 0,
                'is_guest' => 1,
                'created_at' => '2025-10-11 08:03:32',
                'updated_at' => '2025-10-11 08:03:32',
            ),
            39 => 
            array (
                'id' => 581,
                'module_id' => 8,
                'customer_id' => 641,
                'provider_id' => NULL,
                'service_id' => 1,
                'category_id' => 1,
                'sub_category_id' => 4,
                'variant_key' => 'In-10000-SFT',
                'service_cost' => '2500.00',
                'quantity' => 1,
                'discount_amount' => '2500.00',
                'campaign_discount' => '0.00',
                'coupon_discount' => '0.00',
                'coupon_code' => NULL,
                'tax_amount' => '0.00',
                'total_cost' => '0.00',
                'coupon_id' => 0,
                'is_guest' => 1,
                'created_at' => '2025-10-11 08:03:32',
                'updated_at' => '2025-10-11 08:03:32',
            ),
            40 => 
            array (
                'id' => 647,
                'module_id' => 8,
                'customer_id' => 37,
                'provider_id' => NULL,
                'service_id' => 7,
                'category_id' => 3,
                'sub_category_id' => 9,
                'variant_key' => 'House-hold-electric-service',
                'service_cost' => '5000.00',
                'quantity' => 3,
                'discount_amount' => '50.00',
                'campaign_discount' => '0.00',
                'coupon_discount' => '0.00',
                'coupon_code' => NULL,
                'tax_amount' => '448.50',
                'total_cost' => '15398.50',
                'coupon_id' => 0,
                'is_guest' => 0,
                'created_at' => '2025-10-11 16:37:03',
                'updated_at' => '2025-10-11 16:37:03',
            ),
            41 => 
            array (
                'id' => 690,
                'module_id' => 8,
                'customer_id' => 680,
                'provider_id' => NULL,
                'service_id' => 2,
                'category_id' => 1,
                'sub_category_id' => 4,
                'variant_key' => 'In-2000-SFT',
                'service_cost' => '200.00',
                'quantity' => 1,
                'discount_amount' => '20.00',
                'campaign_discount' => '0.00',
                'coupon_discount' => '0.00',
                'coupon_code' => NULL,
                'tax_amount' => '18.00',
                'total_cost' => '198.00',
                'coupon_id' => 0,
                'is_guest' => 1,
                'created_at' => '2025-10-12 15:48:35',
                'updated_at' => '2025-10-12 15:48:35',
            ),
            42 => 
            array (
                'id' => 691,
                'module_id' => 8,
                'customer_id' => 680,
                'provider_id' => NULL,
                'service_id' => 2,
                'category_id' => 1,
                'sub_category_id' => 4,
                'variant_key' => 'More-than-2000-SFT',
                'service_cost' => '400.00',
                'quantity' => 1,
                'discount_amount' => '40.00',
                'campaign_discount' => '0.00',
                'coupon_discount' => '0.00',
                'coupon_code' => NULL,
                'tax_amount' => '36.00',
                'total_cost' => '396.00',
                'coupon_id' => 0,
                'is_guest' => 1,
                'created_at' => '2025-10-12 15:48:36',
                'updated_at' => '2025-10-12 15:48:36',
            ),
            43 => 
            array (
                'id' => 695,
                'module_id' => 8,
                'customer_id' => 14,
                'provider_id' => NULL,
                'service_id' => 2,
                'category_id' => 1,
                'sub_category_id' => 4,
                'variant_key' => 'More-than-2000-SFT',
                'service_cost' => '400.00',
                'quantity' => 1,
                'discount_amount' => '40.00',
                'campaign_discount' => '0.00',
                'coupon_discount' => '0.00',
                'coupon_code' => NULL,
                'tax_amount' => '36.00',
                'total_cost' => '396.00',
                'coupon_id' => 0,
                'is_guest' => 0,
                'created_at' => '2025-10-12 16:00:09',
                'updated_at' => '2025-10-12 16:00:30',
            ),
            44 => 
            array (
                'id' => 696,
                'module_id' => 8,
                'customer_id' => 14,
                'provider_id' => NULL,
                'service_id' => 1,
                'category_id' => 1,
                'sub_category_id' => 4,
                'variant_key' => 'In-10000-SFT',
                'service_cost' => '2500.00',
                'quantity' => 3,
                'discount_amount' => '100.00',
                'campaign_discount' => '0.00',
                'coupon_discount' => '0.00',
                'coupon_code' => NULL,
                'tax_amount' => '740.00',
                'total_cost' => '8140.00',
                'coupon_id' => 0,
                'is_guest' => 0,
                'created_at' => '2025-10-12 16:00:15',
                'updated_at' => '2025-10-12 16:00:30',
            ),
            45 => 
            array (
                'id' => 697,
                'module_id' => 8,
                'customer_id' => 14,
                'provider_id' => NULL,
                'service_id' => 4,
                'category_id' => 1,
                'sub_category_id' => 4,
                'variant_key' => 'Full-house-glass-clean',
                'service_cost' => '200.00',
                'quantity' => 2,
                'discount_amount' => '100.00',
                'campaign_discount' => '0.00',
                'coupon_discount' => '0.00',
                'coupon_code' => NULL,
                'tax_amount' => '15.00',
                'total_cost' => '315.00',
                'coupon_id' => 0,
                'is_guest' => 0,
                'created_at' => '2025-10-12 16:00:30',
                'updated_at' => '2025-10-12 16:00:30',
            ),
            46 => 
            array (
                'id' => 714,
                'module_id' => 8,
                'customer_id' => 475,
                'provider_id' => NULL,
                'service_id' => 2,
                'category_id' => 1,
                'sub_category_id' => 4,
                'variant_key' => 'In-2000-SFT',
                'service_cost' => '200.00',
                'quantity' => 3,
                'discount_amount' => '50.00',
                'campaign_discount' => '0.00',
                'coupon_discount' => '0.00',
                'coupon_code' => NULL,
                'tax_amount' => '55.00',
                'total_cost' => '605.00',
                'coupon_id' => 0,
                'is_guest' => 1,
                'created_at' => '2025-10-13 15:15:03',
                'updated_at' => '2025-10-13 15:15:28',
            ),
            47 => 
            array (
                'id' => 715,
                'module_id' => 8,
                'customer_id' => 475,
                'provider_id' => NULL,
                'service_id' => 1,
                'category_id' => 1,
                'sub_category_id' => 4,
                'variant_key' => 'In-1200-SFT',
                'service_cost' => '50.00',
                'quantity' => 2,
                'discount_amount' => '100.00',
                'campaign_discount' => '0.00',
                'coupon_discount' => '0.00',
                'coupon_code' => NULL,
                'tax_amount' => '0.00',
                'total_cost' => '0.00',
                'coupon_id' => 0,
                'is_guest' => 1,
                'created_at' => '2025-10-13 15:15:18',
                'updated_at' => '2025-10-13 15:15:28',
            ),
            48 => 
            array (
                'id' => 716,
                'module_id' => 8,
                'customer_id' => 475,
                'provider_id' => NULL,
                'service_id' => 4,
                'category_id' => 1,
                'sub_category_id' => 4,
                'variant_key' => 'Full-house-glass-clean',
                'service_cost' => '200.00',
                'quantity' => 3,
                'discount_amount' => '100.00',
                'campaign_discount' => '0.00',
                'coupon_discount' => '0.00',
                'coupon_code' => NULL,
                'tax_amount' => '25.00',
                'total_cost' => '525.00',
                'coupon_id' => 0,
                'is_guest' => 1,
                'created_at' => '2025-10-13 15:15:28',
                'updated_at' => '2025-10-13 15:15:28',
            ),
            49 => 
            array (
                'id' => 719,
                'module_id' => 8,
                'customer_id' => 32,
                'provider_id' => NULL,
                'service_id' => 1,
                'category_id' => 1,
                'sub_category_id' => 4,
                'variant_key' => 'In-1200-SFT',
                'service_cost' => '50.00',
                'quantity' => 1,
                'discount_amount' => '50.00',
                'campaign_discount' => '0.00',
                'coupon_discount' => '0.00',
                'coupon_code' => NULL,
                'tax_amount' => '0.00',
                'total_cost' => '0.00',
                'coupon_id' => 0,
                'is_guest' => 0,
                'created_at' => '2025-10-13 17:46:40',
                'updated_at' => '2025-10-13 17:46:40',
            ),
            50 => 
            array (
                'id' => 720,
                'module_id' => 8,
                'customer_id' => 32,
                'provider_id' => NULL,
                'service_id' => 1,
                'category_id' => 1,
                'sub_category_id' => 4,
                'variant_key' => 'In-2000-SFT',
                'service_cost' => '200.00',
                'quantity' => 2,
                'discount_amount' => '100.00',
                'campaign_discount' => '0.00',
                'coupon_discount' => '0.00',
                'coupon_code' => NULL,
                'tax_amount' => '30.00',
                'total_cost' => '330.00',
                'coupon_id' => 0,
                'is_guest' => 0,
                'created_at' => '2025-10-13 17:46:41',
                'updated_at' => '2025-10-13 17:46:41',
            ),
            51 => 
            array (
                'id' => 721,
                'module_id' => 8,
                'customer_id' => 32,
                'provider_id' => NULL,
                'service_id' => 1,
                'category_id' => 1,
                'sub_category_id' => 4,
                'variant_key' => 'In-10000-SFT',
                'service_cost' => '2500.00',
                'quantity' => 7,
                'discount_amount' => '100.00',
                'campaign_discount' => '0.00',
                'coupon_discount' => '0.00',
                'coupon_code' => NULL,
                'tax_amount' => '1740.00',
                'total_cost' => '19140.00',
                'coupon_id' => 0,
                'is_guest' => 0,
                'created_at' => '2025-10-13 17:46:41',
                'updated_at' => '2025-10-13 17:46:41',
            ),
            52 => 
            array (
                'id' => 723,
                'module_id' => 8,
                'customer_id' => 33,
                'provider_id' => NULL,
                'service_id' => 7,
                'category_id' => 3,
                'sub_category_id' => 9,
                'variant_key' => 'House-hold-electric-service',
                'service_cost' => '5000.00',
                'quantity' => 2,
                'discount_amount' => '50.00',
                'campaign_discount' => '0.00',
                'coupon_discount' => '0.00',
                'coupon_code' => NULL,
                'tax_amount' => '298.50',
                'total_cost' => '10248.50',
                'coupon_id' => 0,
                'is_guest' => 0,
                'created_at' => '2025-10-13 17:51:01',
                'updated_at' => '2025-10-13 17:51:01',
            ),
            53 => 
            array (
                'id' => 725,
                'module_id' => 8,
                'customer_id' => 8,
                'provider_id' => NULL,
                'service_id' => 3,
                'category_id' => 1,
                'sub_category_id' => 5,
                'variant_key' => '500-SFT',
                'service_cost' => '100.00',
                'quantity' => 1,
                'discount_amount' => '10.00',
                'campaign_discount' => '0.00',
                'coupon_discount' => '0.00',
                'coupon_code' => NULL,
                'tax_amount' => '9.00',
                'total_cost' => '99.00',
                'coupon_id' => 0,
                'is_guest' => 0,
                'created_at' => '2025-10-13 21:58:36',
                'updated_at' => '2025-10-13 21:58:36',
            ),
        ));
        
        
    }
}