<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class ServicePostsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('service_posts')->delete();
        
        \DB::table('service_posts')->insert(array (
            0 => 
            array (
                'id' => 1,
                'service_description' => 'frdg dfwsef',
                'booking_schedule' => '2025-09-07 16:52:13',
                'is_booked' => 0,
                'is_checked' => 1,
                'module_id' => 8,
                'booking_id' => NULL,
                'user_id' => 8,
                'zone_id' => 1,
                'service_id' => 2,
                'category_id' => 1,
                'sub_category_id' => 4,
                'service_address_id' => 57,
                'created_at' => '2025-09-07 10:54:05',
                'updated_at' => '2025-09-09 14:44:47',
            ),
            1 => 
            array (
                'id' => 2,
                'service_description' => 'StackFood - React User Website - CodeCanyon Item for Sale
Live Preview Screenshots
Introducing the React User Website for StackFood Multi Restaurant – Food Delivery solution. A fast, powerful and responsive web platform for customers. Now you must be thinking, why do you need',
                'booking_schedule' => '2025-09-09 12:36:08',
                'is_booked' => 0,
                'is_checked' => 1,
                'module_id' => 8,
                'booking_id' => NULL,
                'user_id' => 8,
                'zone_id' => 1,
                'service_id' => 6,
                'category_id' => 3,
                'sub_category_id' => 10,
                'service_address_id' => 80,
                'created_at' => '2025-09-09 12:36:54',
                'updated_at' => '2025-09-09 14:44:47',
            ),
            2 => 
            array (
                'id' => 3,
                'service_description' => 'StackFood - React User Website - CodeCanyon Item for Sale
Live Preview Screenshots
Introducing the React User Website for StackFood Multi Restaurant – Food Delivery',
                'booking_schedule' => '2025-09-09 14:43:52',
                'is_booked' => 1,
                'is_checked' => 1,
                'module_id' => 8,
                'booking_id' => 1069,
                'user_id' => 8,
                'zone_id' => 1,
                'service_id' => 3,
                'category_id' => 1,
                'sub_category_id' => 5,
                'service_address_id' => 87,
                'created_at' => '2025-09-09 14:44:46',
                'updated_at' => '2025-09-09 14:46:02',
            ),
            3 => 
            array (
                'id' => 4,
                'service_description' => 'check',
                'booking_schedule' => '2025-09-16 16:10:30',
                'is_booked' => 0,
                'is_checked' => 1,
                'module_id' => 8,
                'booking_id' => NULL,
                'user_id' => 14,
                'zone_id' => 1,
                'service_id' => 3,
                'category_id' => 1,
                'sub_category_id' => 5,
                'service_address_id' => 109,
                'created_at' => '2025-09-16 16:10:56',
                'updated_at' => '2025-09-17 09:45:40',
            ),
            4 => 
            array (
                'id' => 5,
                'service_description' => 'Pp',
                'booking_schedule' => '2025-09-16 16:20:35',
                'is_booked' => 0,
                'is_checked' => 1,
                'module_id' => 8,
                'booking_id' => NULL,
                'user_id' => 14,
                'zone_id' => 1,
                'service_id' => 3,
                'category_id' => 1,
                'sub_category_id' => 5,
                'service_address_id' => 110,
                'created_at' => '2025-09-16 16:18:47',
                'updated_at' => '2025-09-17 09:45:40',
            ),
            5 => 
            array (
                'id' => 6,
                'service_description' => 'fddsfs',
                'booking_schedule' => '2025-09-17 09:44:01',
                'is_booked' => 0,
                'is_checked' => 1,
                'module_id' => 8,
                'booking_id' => NULL,
                'user_id' => 14,
                'zone_id' => 1,
                'service_id' => 3,
                'category_id' => 1,
                'sub_category_id' => 5,
                'service_address_id' => 111,
                'created_at' => '2025-09-17 09:44:15',
                'updated_at' => '2025-09-17 09:45:40',
            ),
            6 => 
            array (
                'id' => 7,
                'service_description' => 'sfdsfd',
                'booking_schedule' => '2025-09-17 09:44:30',
                'is_booked' => 1,
                'is_checked' => 1,
                'module_id' => 8,
                'booking_id' => 1084,
                'user_id' => 14,
                'zone_id' => 1,
                'service_id' => 3,
                'category_id' => 1,
                'sub_category_id' => 5,
                'service_address_id' => 112,
                'created_at' => '2025-09-17 09:44:43',
                'updated_at' => '2025-09-17 12:39:03',
            ),
            7 => 
            array (
                'id' => 8,
                'service_description' => 'Pp',
                'booking_schedule' => '2025-09-22 17:18:35',
                'is_booked' => 0,
                'is_checked' => 1,
                'module_id' => 8,
                'booking_id' => NULL,
                'user_id' => 33,
                'zone_id' => 1,
                'service_id' => 5,
                'category_id' => 1,
                'sub_category_id' => 4,
                'service_address_id' => 133,
                'created_at' => '2025-09-22 17:17:04',
                'updated_at' => '2025-09-23 10:12:52',
            ),
            8 => 
            array (
                'id' => 9,
                'service_description' => 'Gas prices coarse varieties najirshail and said they love with dg Gas prices coarse varieties najirshail and said they love with dg Gas prices coarse varieties najirshail and said they love with dg Gas prices coarse varieties najirshail and said they love with dg',
                'booking_schedule' => '2025-09-23 16:00:36',
                'is_booked' => 0,
                'is_checked' => 1,
                'module_id' => 8,
                'booking_id' => NULL,
                'user_id' => 33,
                'zone_id' => 1,
                'service_id' => 9,
                'category_id' => 1,
                'sub_category_id' => 4,
                'service_address_id' => 137,
                'created_at' => '2025-09-23 15:59:43',
                'updated_at' => '2025-09-23 16:20:07',
            ),
            9 => 
            array (
                'id' => 10,
                'service_description' => 'Gas prices coarse varieties najirshail and said they love with dg',
                'booking_schedule' => '2025-09-23 16:17:39',
                'is_booked' => 1,
                'is_checked' => 1,
                'module_id' => 8,
                'booking_id' => 1107,
                'user_id' => 33,
                'zone_id' => 1,
                'service_id' => 6,
                'category_id' => 3,
                'sub_category_id' => 10,
                'service_address_id' => 138,
                'created_at' => '2025-09-23 16:16:26',
                'updated_at' => '2025-09-23 17:15:47',
            ),
            10 => 
            array (
                'id' => 11,
                'service_description' => 'Nzznznnz',
                'booking_schedule' => '2025-09-25 23:02:55',
                'is_booked' => 0,
                'is_checked' => 1,
                'module_id' => 8,
                'booking_id' => NULL,
                'user_id' => 33,
                'zone_id' => 1,
                'service_id' => 3,
                'category_id' => 1,
                'sub_category_id' => 5,
                'service_address_id' => 138,
                'created_at' => '2025-09-23 18:03:02',
                'updated_at' => '2025-09-23 18:04:24',
            ),
            11 => 
            array (
                'id' => 12,
                'service_description' => 'Fhdb zzbshejw',
                'booking_schedule' => '2025-09-24 16:38:42',
                'is_booked' => 0,
                'is_checked' => 1,
                'module_id' => 8,
                'booking_id' => NULL,
                'user_id' => 33,
                'zone_id' => 1,
                'service_id' => 3,
                'category_id' => 1,
                'sub_category_id' => 5,
                'service_address_id' => 142,
                'created_at' => '2025-09-24 16:37:26',
                'updated_at' => '2025-09-24 16:38:21',
            ),
            12 => 
            array (
                'id' => 13,
                'service_description' => 'Susu',
                'booking_schedule' => '2025-09-25 13:01:51',
                'is_booked' => 0,
                'is_checked' => 1,
                'module_id' => 8,
                'booking_id' => NULL,
                'user_id' => 14,
                'zone_id' => 1,
                'service_id' => 3,
                'category_id' => 1,
                'sub_category_id' => 5,
                'service_address_id' => 150,
                'created_at' => '2025-09-25 13:00:08',
                'updated_at' => '2025-09-25 16:35:34',
            ),
            13 => 
            array (
                'id' => 14,
                'service_description' => 'Kvkv',
                'booking_schedule' => '2025-09-28 12:30:25',
                'is_booked' => 0,
                'is_checked' => 1,
                'module_id' => 8,
                'booking_id' => NULL,
                'user_id' => 14,
                'zone_id' => 1,
                'service_id' => 5,
                'category_id' => 1,
                'sub_category_id' => 4,
                'service_address_id' => 154,
                'created_at' => '2025-09-28 12:37:12',
                'updated_at' => '2025-09-28 12:37:17',
            ),
            14 => 
            array (
                'id' => 15,
                'service_description' => '678567856',
                'booking_schedule' => '2025-09-28 13:11:32',
                'is_booked' => 1,
                'is_checked' => 1,
                'module_id' => 8,
                'booking_id' => 1124,
                'user_id' => 32,
                'zone_id' => 1,
                'service_id' => 10,
                'category_id' => 3,
                'sub_category_id' => 10,
                'service_address_id' => 156,
                'created_at' => '2025-09-28 13:09:48',
                'updated_at' => '2025-09-28 16:54:59',
            ),
            15 => 
            array (
                'id' => 16,
                'service_description' => 'i9ouiyoyuio',
                'booking_schedule' => '2025-09-28 16:55:59',
                'is_booked' => 0,
                'is_checked' => 1,
                'module_id' => 8,
                'booking_id' => NULL,
                'user_id' => 32,
                'zone_id' => 1,
                'service_id' => 10,
                'category_id' => 3,
                'sub_category_id' => 10,
                'service_address_id' => 156,
                'created_at' => '2025-09-28 16:54:33',
                'updated_at' => '2025-09-29 16:25:52',
            ),
            16 => 
            array (
                'id' => 17,
                'service_description' => 'Test',
                'booking_schedule' => '2025-09-29 17:21:14',
                'is_booked' => 1,
                'is_checked' => 1,
                'module_id' => 8,
                'booking_id' => 1130,
                'user_id' => 32,
                'zone_id' => 1,
                'service_id' => 8,
                'category_id' => 3,
                'sub_category_id' => 10,
                'service_address_id' => 156,
                'created_at' => '2025-09-29 17:19:32',
                'updated_at' => '2025-09-30 12:29:03',
            ),
            17 => 
            array (
                'id' => 18,
                'service_description' => 'Mvmv',
                'booking_schedule' => '2025-10-05 13:59:09',
                'is_booked' => 0,
                'is_checked' => 1,
                'module_id' => 8,
                'booking_id' => NULL,
                'user_id' => 14,
                'zone_id' => 1,
                'service_id' => 6,
                'category_id' => 3,
                'sub_category_id' => 10,
                'service_address_id' => 154,
                'created_at' => '2025-10-05 13:57:33',
                'updated_at' => '2025-10-05 15:50:11',
            ),
            18 => 
            array (
                'id' => 19,
                'service_description' => 'tre tryrt https://www.awesomescreenshot.com/image/56770273?key=f90d8de98710bbff06ad9c1d97aa4bae',
                'booking_schedule' => '2025-10-05 15:37:18',
                'is_booked' => 0,
                'is_checked' => 1,
                'module_id' => 8,
                'booking_id' => NULL,
                'user_id' => 33,
                'zone_id' => 1,
                'service_id' => 2,
                'category_id' => 1,
                'sub_category_id' => 4,
                'service_address_id' => 170,
                'created_at' => '2025-10-05 15:38:48',
                'updated_at' => '2025-10-05 15:50:11',
            ),
            19 => 
            array (
                'id' => 20,
                'service_description' => 'https://www.awesomescreenshot.com/image/56770273?key=f90d8de98710bbff06ad9c1d97aa4bae',
                'booking_schedule' => '2025-10-05 15:50:29',
                'is_booked' => 1,
                'is_checked' => 1,
                'module_id' => 8,
                'booking_id' => 1142,
                'user_id' => 33,
                'zone_id' => 1,
                'service_id' => 3,
                'category_id' => 1,
                'sub_category_id' => 5,
                'service_address_id' => 171,
                'created_at' => '2025-10-05 15:50:59',
                'updated_at' => '2025-10-05 15:52:28',
            ),
            20 => 
            array (
                'id' => 21,
                'service_description' => '3245123',
                'booking_schedule' => '2025-10-05 16:43:22',
                'is_booked' => 1,
                'is_checked' => 1,
                'module_id' => 8,
                'booking_id' => 1143,
                'user_id' => 33,
                'zone_id' => 1,
                'service_id' => 3,
                'category_id' => 1,
                'sub_category_id' => 5,
                'service_address_id' => 172,
                'created_at' => '2025-10-05 16:44:46',
                'updated_at' => '2025-10-05 17:14:26',
            ),
            21 => 
            array (
                'id' => 22,
                'service_description' => 'Testttt',
                'booking_schedule' => '2025-10-07 14:07:33',
                'is_booked' => 1,
                'is_checked' => 1,
                'module_id' => 8,
                'booking_id' => 1153,
                'user_id' => 14,
                'zone_id' => 1,
                'service_id' => 3,
                'category_id' => 1,
                'sub_category_id' => 5,
                'service_address_id' => 182,
                'created_at' => '2025-10-07 14:06:12',
                'updated_at' => '2025-10-07 14:07:01',
            ),
            22 => 
            array (
                'id' => 23,
                'service_description' => 'Vuvu',
                'booking_schedule' => '2025-10-07 16:31:40',
                'is_booked' => 0,
                'is_checked' => 1,
                'module_id' => 8,
                'booking_id' => NULL,
                'user_id' => 14,
                'zone_id' => 1,
                'service_id' => 3,
                'category_id' => 1,
                'sub_category_id' => 5,
                'service_address_id' => 183,
                'created_at' => '2025-10-07 16:29:49',
                'updated_at' => '2025-10-07 16:29:52',
            ),
            23 => 
            array (
                'id' => 24,
                'service_description' => 'Hhdjd',
                'booking_schedule' => '2025-10-12 12:42:36',
                'is_booked' => 1,
                'is_checked' => 1,
                'module_id' => 8,
                'booking_id' => 1176,
                'user_id' => 14,
                'zone_id' => 1,
                'service_id' => 3,
                'category_id' => 1,
                'sub_category_id' => 5,
                'service_address_id' => 221,
                'created_at' => '2025-10-12 12:40:48',
                'updated_at' => '2025-10-12 12:41:57',
            ),
        ));
        
        
    }
}