<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class ServiceRecentViewsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('service_recent_views')->delete();
        
        \DB::table('service_recent_views')->insert(array (
            0 => 
            array (
                'id' => 1,
                'module_id' => 8,
                'user_id' => 29,
                'service_id' => 3,
                'total_service_view' => 1,
                'category_id' => NULL,
                'total_category_view' => 0,
                'sub_category_id' => NULL,
                'total_sub_category_view' => 0,
                'deleted_at' => NULL,
                'created_at' => '2025-09-04 10:35:55',
                'updated_at' => '2025-09-04 10:35:55',
            ),
            1 => 
            array (
                'id' => 2,
                'module_id' => 8,
                'user_id' => 29,
                'service_id' => 1,
                'total_service_view' => 2,
                'category_id' => NULL,
                'total_category_view' => 0,
                'sub_category_id' => NULL,
                'total_sub_category_view' => 0,
                'deleted_at' => NULL,
                'created_at' => '2025-09-04 10:39:03',
                'updated_at' => '2025-09-04 10:58:28',
            ),
            2 => 
            array (
                'id' => 3,
                'module_id' => 8,
                'user_id' => 8,
                'service_id' => 1,
                'total_service_view' => 24,
                'category_id' => NULL,
                'total_category_view' => 0,
                'sub_category_id' => NULL,
                'total_sub_category_view' => 0,
                'deleted_at' => NULL,
                'created_at' => '2025-09-07 04:50:34',
                'updated_at' => '2025-10-13 16:30:12',
            ),
            3 => 
            array (
                'id' => 4,
                'module_id' => 8,
                'user_id' => 8,
                'service_id' => 2,
                'total_service_view' => 5,
                'category_id' => NULL,
                'total_category_view' => 0,
                'sub_category_id' => NULL,
                'total_sub_category_view' => 0,
                'deleted_at' => NULL,
                'created_at' => '2025-09-07 10:17:10',
                'updated_at' => '2025-09-09 14:53:04',
            ),
            4 => 
            array (
                'id' => 5,
                'module_id' => 8,
                'user_id' => 8,
                'service_id' => 3,
                'total_service_view' => 3,
                'category_id' => NULL,
                'total_category_view' => 0,
                'sub_category_id' => NULL,
                'total_sub_category_view' => 0,
                'deleted_at' => NULL,
                'created_at' => '2025-09-07 10:26:29',
                'updated_at' => '2025-10-13 21:58:19',
            ),
            5 => 
            array (
                'id' => 6,
                'module_id' => NULL,
                'user_id' => 8,
                'service_id' => NULL,
                'total_service_view' => 0,
                'category_id' => 2,
                'total_category_view' => 14,
                'sub_category_id' => NULL,
                'total_sub_category_view' => 0,
                'deleted_at' => NULL,
                'created_at' => '2025-09-07 10:52:35',
                'updated_at' => '2025-10-05 16:33:50',
            ),
            6 => 
            array (
                'id' => 7,
                'module_id' => NULL,
                'user_id' => 8,
                'service_id' => NULL,
                'total_service_view' => 0,
                'category_id' => 1,
                'total_category_view' => 9,
                'sub_category_id' => NULL,
                'total_sub_category_view' => 0,
                'deleted_at' => NULL,
                'created_at' => '2025-09-07 10:52:40',
                'updated_at' => '2025-10-05 16:32:52',
            ),
            7 => 
            array (
                'id' => 8,
                'module_id' => 8,
                'user_id' => 8,
                'service_id' => NULL,
                'total_service_view' => 0,
                'category_id' => NULL,
                'total_category_view' => 0,
                'sub_category_id' => 5,
                'total_sub_category_view' => 11,
                'deleted_at' => NULL,
                'created_at' => '2025-09-07 10:52:41',
                'updated_at' => '2025-10-06 09:13:52',
            ),
            8 => 
            array (
                'id' => 9,
                'module_id' => 8,
                'user_id' => 8,
                'service_id' => NULL,
                'total_service_view' => 0,
                'category_id' => NULL,
                'total_category_view' => 0,
                'sub_category_id' => 4,
                'total_sub_category_view' => 6,
                'deleted_at' => NULL,
                'created_at' => '2025-09-07 10:53:03',
                'updated_at' => '2025-09-11 23:24:19',
            ),
            9 => 
            array (
                'id' => 10,
                'module_id' => NULL,
                'user_id' => 8,
                'service_id' => NULL,
                'total_service_view' => 0,
                'category_id' => 3,
                'total_category_view' => 12,
                'sub_category_id' => NULL,
                'total_sub_category_view' => 0,
                'deleted_at' => NULL,
                'created_at' => '2025-09-07 10:53:11',
                'updated_at' => '2025-10-06 09:13:59',
            ),
            10 => 
            array (
                'id' => 11,
                'module_id' => 8,
                'user_id' => 10,
                'service_id' => 1,
                'total_service_view' => 1,
                'category_id' => NULL,
                'total_category_view' => 0,
                'sub_category_id' => NULL,
                'total_sub_category_view' => 0,
                'deleted_at' => NULL,
                'created_at' => '2025-09-08 11:55:22',
                'updated_at' => '2025-09-08 11:55:22',
            ),
            11 => 
            array (
                'id' => 12,
                'module_id' => NULL,
                'user_id' => 21,
                'service_id' => NULL,
                'total_service_view' => 0,
                'category_id' => 3,
                'total_category_view' => 6,
                'sub_category_id' => NULL,
                'total_sub_category_view' => 0,
                'deleted_at' => NULL,
                'created_at' => '2025-09-09 10:55:46',
                'updated_at' => '2025-09-11 12:22:23',
            ),
            12 => 
            array (
                'id' => 13,
                'module_id' => NULL,
                'user_id' => 21,
                'service_id' => NULL,
                'total_service_view' => 0,
                'category_id' => 2,
                'total_category_view' => 2,
                'sub_category_id' => NULL,
                'total_sub_category_view' => 0,
                'deleted_at' => NULL,
                'created_at' => '2025-09-09 10:55:51',
                'updated_at' => '2025-09-11 12:22:26',
            ),
            13 => 
            array (
                'id' => 14,
                'module_id' => NULL,
                'user_id' => 21,
                'service_id' => NULL,
                'total_service_view' => 0,
                'category_id' => 1,
                'total_category_view' => 6,
                'sub_category_id' => NULL,
                'total_sub_category_view' => 0,
                'deleted_at' => NULL,
                'created_at' => '2025-09-09 10:56:41',
                'updated_at' => '2025-09-09 12:15:46',
            ),
            14 => 
            array (
                'id' => 15,
                'module_id' => 8,
                'user_id' => 21,
                'service_id' => NULL,
                'total_service_view' => 0,
                'category_id' => NULL,
                'total_category_view' => 0,
                'sub_category_id' => 5,
                'total_sub_category_view' => 7,
                'deleted_at' => NULL,
                'created_at' => '2025-09-09 10:56:41',
                'updated_at' => '2025-09-09 12:15:47',
            ),
            15 => 
            array (
                'id' => 16,
                'module_id' => 8,
                'user_id' => 21,
                'service_id' => NULL,
                'total_service_view' => 0,
                'category_id' => NULL,
                'total_category_view' => 0,
                'sub_category_id' => 4,
                'total_sub_category_view' => 6,
                'deleted_at' => NULL,
                'created_at' => '2025-09-09 10:56:43',
                'updated_at' => '2025-09-09 12:15:48',
            ),
            16 => 
            array (
                'id' => 17,
                'module_id' => 8,
                'user_id' => 21,
                'service_id' => 3,
                'total_service_view' => 1,
                'category_id' => NULL,
                'total_category_view' => 0,
                'sub_category_id' => NULL,
                'total_sub_category_view' => 0,
                'deleted_at' => NULL,
                'created_at' => '2025-09-09 11:28:10',
                'updated_at' => '2025-09-09 11:28:10',
            ),
            17 => 
            array (
                'id' => 18,
                'module_id' => 8,
                'user_id' => 21,
                'service_id' => NULL,
                'total_service_view' => 0,
                'category_id' => NULL,
                'total_category_view' => 0,
                'sub_category_id' => 10,
                'total_sub_category_view' => 5,
                'deleted_at' => NULL,
                'created_at' => '2025-09-09 11:36:37',
                'updated_at' => '2025-09-11 12:22:23',
            ),
            18 => 
            array (
                'id' => 19,
                'module_id' => 8,
                'user_id' => 21,
                'service_id' => 6,
                'total_service_view' => 1,
                'category_id' => NULL,
                'total_category_view' => 0,
                'sub_category_id' => NULL,
                'total_sub_category_view' => 0,
                'deleted_at' => NULL,
                'created_at' => '2025-09-09 11:36:41',
                'updated_at' => '2025-09-09 11:36:41',
            ),
            19 => 
            array (
                'id' => 20,
                'module_id' => 8,
                'user_id' => 21,
                'service_id' => 4,
                'total_service_view' => 2,
                'category_id' => NULL,
                'total_category_view' => 0,
                'sub_category_id' => NULL,
                'total_sub_category_view' => 0,
                'deleted_at' => NULL,
                'created_at' => '2025-09-09 11:40:41',
                'updated_at' => '2025-09-09 11:40:56',
            ),
            20 => 
            array (
                'id' => 21,
                'module_id' => 8,
                'user_id' => 21,
                'service_id' => NULL,
                'total_service_view' => 0,
                'category_id' => NULL,
                'total_category_view' => 0,
                'sub_category_id' => 9,
                'total_sub_category_view' => 1,
                'deleted_at' => NULL,
                'created_at' => '2025-09-09 11:40:47',
                'updated_at' => '2025-09-09 11:40:47',
            ),
            21 => 
            array (
                'id' => 22,
                'module_id' => 8,
                'user_id' => 21,
                'service_id' => 1,
                'total_service_view' => 3,
                'category_id' => NULL,
                'total_category_view' => 0,
                'sub_category_id' => NULL,
                'total_sub_category_view' => 0,
                'deleted_at' => NULL,
                'created_at' => '2025-09-09 11:57:33',
                'updated_at' => '2025-09-11 11:28:44',
            ),
            22 => 
            array (
                'id' => 23,
                'module_id' => 8,
                'user_id' => 21,
                'service_id' => 5,
                'total_service_view' => 1,
                'category_id' => NULL,
                'total_category_view' => 0,
                'sub_category_id' => NULL,
                'total_sub_category_view' => 0,
                'deleted_at' => NULL,
                'created_at' => '2025-09-09 12:19:03',
                'updated_at' => '2025-09-09 12:19:03',
            ),
            23 => 
            array (
                'id' => 24,
                'module_id' => 8,
                'user_id' => 8,
                'service_id' => 7,
                'total_service_view' => 4,
                'category_id' => NULL,
                'total_category_view' => 0,
                'sub_category_id' => NULL,
                'total_sub_category_view' => 0,
                'deleted_at' => NULL,
                'created_at' => '2025-09-09 12:34:00',
                'updated_at' => '2025-10-13 16:21:46',
            ),
            24 => 
            array (
                'id' => 25,
                'module_id' => 8,
                'user_id' => 8,
                'service_id' => NULL,
                'total_service_view' => 0,
                'category_id' => NULL,
                'total_category_view' => 0,
                'sub_category_id' => 10,
                'total_sub_category_view' => 8,
                'deleted_at' => NULL,
                'created_at' => '2025-09-09 12:36:20',
                'updated_at' => '2025-10-06 10:00:32',
            ),
            25 => 
            array (
                'id' => 26,
                'module_id' => 8,
                'user_id' => 30,
                'service_id' => 1,
                'total_service_view' => 3,
                'category_id' => NULL,
                'total_category_view' => 0,
                'sub_category_id' => NULL,
                'total_sub_category_view' => 0,
                'deleted_at' => NULL,
                'created_at' => '2025-09-09 14:23:04',
                'updated_at' => '2025-09-09 14:27:12',
            ),
            26 => 
            array (
                'id' => 27,
                'module_id' => 8,
                'user_id' => 8,
                'service_id' => 5,
                'total_service_view' => 3,
                'category_id' => NULL,
                'total_category_view' => 0,
                'sub_category_id' => NULL,
                'total_sub_category_view' => 0,
                'deleted_at' => NULL,
                'created_at' => '2025-09-09 14:49:02',
                'updated_at' => '2025-10-11 17:48:56',
            ),
            27 => 
            array (
                'id' => 28,
                'module_id' => 8,
                'user_id' => 21,
                'service_id' => 7,
                'total_service_view' => 1,
                'category_id' => NULL,
                'total_category_view' => 0,
                'sub_category_id' => NULL,
                'total_sub_category_view' => 0,
                'deleted_at' => NULL,
                'created_at' => '2025-09-11 13:15:48',
                'updated_at' => '2025-09-11 13:15:48',
            ),
            28 => 
            array (
                'id' => 29,
                'module_id' => 8,
                'user_id' => 8,
                'service_id' => NULL,
                'total_service_view' => 0,
                'category_id' => NULL,
                'total_category_view' => 0,
                'sub_category_id' => 9,
                'total_sub_category_view' => 2,
                'deleted_at' => NULL,
                'created_at' => '2025-09-11 23:23:12',
                'updated_at' => '2025-10-05 16:32:47',
            ),
            29 => 
            array (
                'id' => 30,
                'module_id' => 8,
                'user_id' => 14,
                'service_id' => 2,
                'total_service_view' => 19,
                'category_id' => NULL,
                'total_category_view' => 0,
                'sub_category_id' => NULL,
                'total_sub_category_view' => 0,
                'deleted_at' => NULL,
                'created_at' => '2025-09-16 12:18:36',
                'updated_at' => '2025-10-12 12:48:02',
            ),
            30 => 
            array (
                'id' => 31,
                'module_id' => 8,
                'user_id' => 14,
                'service_id' => 3,
                'total_service_view' => 22,
                'category_id' => NULL,
                'total_category_view' => 0,
                'sub_category_id' => NULL,
                'total_sub_category_view' => 0,
                'deleted_at' => NULL,
                'created_at' => '2025-09-16 15:02:07',
                'updated_at' => '2025-10-12 13:05:14',
            ),
            31 => 
            array (
                'id' => 32,
                'module_id' => NULL,
                'user_id' => 14,
                'service_id' => NULL,
                'total_service_view' => 0,
                'category_id' => 1,
                'total_category_view' => 31,
                'sub_category_id' => NULL,
                'total_sub_category_view' => 0,
                'deleted_at' => NULL,
                'created_at' => '2025-09-16 15:17:12',
                'updated_at' => '2025-10-12 13:05:12',
            ),
            32 => 
            array (
                'id' => 33,
                'module_id' => NULL,
                'user_id' => 14,
                'service_id' => NULL,
                'total_service_view' => 0,
                'category_id' => 2,
                'total_category_view' => 1,
                'sub_category_id' => NULL,
                'total_sub_category_view' => 0,
                'deleted_at' => NULL,
                'created_at' => '2025-09-16 15:17:15',
                'updated_at' => '2025-09-16 15:17:15',
            ),
            33 => 
            array (
                'id' => 34,
                'module_id' => 8,
                'user_id' => 14,
                'service_id' => NULL,
                'total_service_view' => 0,
                'category_id' => NULL,
                'total_category_view' => 0,
                'sub_category_id' => 5,
                'total_sub_category_view' => 38,
                'deleted_at' => NULL,
                'created_at' => '2025-09-16 15:17:16',
                'updated_at' => '2025-10-12 13:05:13',
            ),
            34 => 
            array (
                'id' => 35,
                'module_id' => 8,
                'user_id' => 14,
                'service_id' => NULL,
                'total_service_view' => 0,
                'category_id' => NULL,
                'total_category_view' => 0,
                'sub_category_id' => 4,
                'total_sub_category_view' => 17,
                'deleted_at' => NULL,
                'created_at' => '2025-09-16 15:17:22',
                'updated_at' => '2025-10-12 13:05:22',
            ),
            35 => 
            array (
                'id' => 36,
                'module_id' => 8,
                'user_id' => 14,
                'service_id' => 5,
                'total_service_view' => 7,
                'category_id' => NULL,
                'total_category_view' => 0,
                'sub_category_id' => NULL,
                'total_sub_category_view' => 0,
                'deleted_at' => NULL,
                'created_at' => '2025-09-16 16:01:56',
                'updated_at' => '2025-10-12 16:06:51',
            ),
            36 => 
            array (
                'id' => 37,
                'module_id' => 8,
                'user_id' => 14,
                'service_id' => 1,
                'total_service_view' => 68,
                'category_id' => NULL,
                'total_category_view' => 0,
                'sub_category_id' => NULL,
                'total_sub_category_view' => 0,
                'deleted_at' => NULL,
                'created_at' => '2025-09-17 11:29:32',
                'updated_at' => '2025-10-12 13:46:34',
            ),
            37 => 
            array (
                'id' => 38,
                'module_id' => 8,
                'user_id' => 14,
                'service_id' => 4,
                'total_service_view' => 8,
                'category_id' => NULL,
                'total_category_view' => 0,
                'sub_category_id' => NULL,
                'total_sub_category_view' => 0,
                'deleted_at' => NULL,
                'created_at' => '2025-09-17 11:29:52',
                'updated_at' => '2025-10-12 13:05:35',
            ),
            38 => 
            array (
                'id' => 39,
                'module_id' => 8,
                'user_id' => 33,
                'service_id' => 5,
                'total_service_view' => 4,
                'category_id' => NULL,
                'total_category_view' => 0,
                'sub_category_id' => NULL,
                'total_sub_category_view' => 0,
                'deleted_at' => NULL,
                'created_at' => '2025-09-17 12:25:43',
                'updated_at' => '2025-10-06 10:36:27',
            ),
            39 => 
            array (
                'id' => 40,
                'module_id' => NULL,
                'user_id' => 33,
                'service_id' => NULL,
                'total_service_view' => 0,
                'category_id' => 1,
                'total_category_view' => 18,
                'sub_category_id' => NULL,
                'total_sub_category_view' => 0,
                'deleted_at' => NULL,
                'created_at' => '2025-09-17 13:13:19',
                'updated_at' => '2025-10-05 16:44:41',
            ),
            40 => 
            array (
                'id' => 41,
                'module_id' => 8,
                'user_id' => 33,
                'service_id' => NULL,
                'total_service_view' => 0,
                'category_id' => NULL,
                'total_category_view' => 0,
                'sub_category_id' => 5,
                'total_sub_category_view' => 18,
                'deleted_at' => NULL,
                'created_at' => '2025-09-17 13:13:20',
                'updated_at' => '2025-10-05 16:44:41',
            ),
            41 => 
            array (
                'id' => 42,
                'module_id' => 8,
                'user_id' => 33,
                'service_id' => NULL,
                'total_service_view' => 0,
                'category_id' => NULL,
                'total_category_view' => 0,
                'sub_category_id' => 4,
                'total_sub_category_view' => 8,
                'deleted_at' => NULL,
                'created_at' => '2025-09-17 13:14:27',
                'updated_at' => '2025-10-05 15:37:58',
            ),
            42 => 
            array (
                'id' => 43,
                'module_id' => 8,
                'user_id' => 33,
                'service_id' => 3,
                'total_service_view' => 10,
                'category_id' => NULL,
                'total_category_view' => 0,
                'sub_category_id' => NULL,
                'total_sub_category_view' => 0,
                'deleted_at' => NULL,
                'created_at' => '2025-09-17 13:16:34',
                'updated_at' => '2025-10-11 12:45:46',
            ),
            43 => 
            array (
                'id' => 44,
                'module_id' => 8,
                'user_id' => 14,
                'service_id' => 8,
                'total_service_view' => 6,
                'category_id' => NULL,
                'total_category_view' => 0,
                'sub_category_id' => NULL,
                'total_sub_category_view' => 0,
                'deleted_at' => NULL,
                'created_at' => '2025-09-18 10:48:01',
                'updated_at' => '2025-10-07 13:30:10',
            ),
            44 => 
            array (
                'id' => 45,
                'module_id' => 8,
                'user_id' => 33,
                'service_id' => 6,
                'total_service_view' => 12,
                'category_id' => NULL,
                'total_category_view' => 0,
                'sub_category_id' => NULL,
                'total_sub_category_view' => 0,
                'deleted_at' => NULL,
                'created_at' => '2025-09-20 11:56:06',
                'updated_at' => '2025-10-13 15:13:53',
            ),
            45 => 
            array (
                'id' => 46,
                'module_id' => 8,
                'user_id' => 33,
                'service_id' => 4,
                'total_service_view' => 7,
                'category_id' => NULL,
                'total_category_view' => 0,
                'sub_category_id' => NULL,
                'total_sub_category_view' => 0,
                'deleted_at' => NULL,
                'created_at' => '2025-09-20 12:09:29',
                'updated_at' => '2025-10-11 15:15:00',
            ),
            46 => 
            array (
                'id' => 47,
                'module_id' => 8,
                'user_id' => 33,
                'service_id' => 7,
                'total_service_view' => 11,
                'category_id' => NULL,
                'total_category_view' => 0,
                'sub_category_id' => NULL,
                'total_sub_category_view' => 0,
                'deleted_at' => NULL,
                'created_at' => '2025-09-20 14:57:13',
                'updated_at' => '2025-10-13 17:50:58',
            ),
            47 => 
            array (
                'id' => 48,
                'module_id' => 8,
                'user_id' => 33,
                'service_id' => 1,
                'total_service_view' => 84,
                'category_id' => NULL,
                'total_category_view' => 0,
                'sub_category_id' => NULL,
                'total_sub_category_view' => 0,
                'deleted_at' => NULL,
                'created_at' => '2025-09-20 14:57:58',
                'updated_at' => '2025-10-13 17:50:39',
            ),
            48 => 
            array (
                'id' => 49,
                'module_id' => NULL,
                'user_id' => 33,
                'service_id' => NULL,
                'total_service_view' => 0,
                'category_id' => 2,
                'total_category_view' => 2,
                'sub_category_id' => NULL,
                'total_sub_category_view' => 0,
                'deleted_at' => NULL,
                'created_at' => '2025-09-21 16:59:48',
                'updated_at' => '2025-09-23 16:16:03',
            ),
            49 => 
            array (
                'id' => 50,
                'module_id' => 8,
                'user_id' => 33,
                'service_id' => 2,
                'total_service_view' => 8,
                'category_id' => NULL,
                'total_category_view' => 0,
                'sub_category_id' => NULL,
                'total_sub_category_view' => 0,
                'deleted_at' => NULL,
                'created_at' => '2025-09-22 11:43:34',
                'updated_at' => '2025-10-11 13:08:57',
            ),
            50 => 
            array (
                'id' => 51,
                'module_id' => 8,
                'user_id' => 33,
                'service_id' => 9,
                'total_service_view' => 17,
                'category_id' => NULL,
                'total_category_view' => 0,
                'sub_category_id' => NULL,
                'total_sub_category_view' => 0,
                'deleted_at' => NULL,
                'created_at' => '2025-09-22 17:25:33',
                'updated_at' => '2025-10-13 14:44:56',
            ),
            51 => 
            array (
                'id' => 52,
                'module_id' => 8,
                'user_id' => 14,
                'service_id' => 9,
                'total_service_view' => 9,
                'category_id' => NULL,
                'total_category_view' => 0,
                'sub_category_id' => NULL,
                'total_sub_category_view' => 0,
                'deleted_at' => NULL,
                'created_at' => '2025-09-23 10:49:48',
                'updated_at' => '2025-10-12 13:05:24',
            ),
            52 => 
            array (
                'id' => 53,
                'module_id' => 8,
                'user_id' => 14,
                'service_id' => 7,
                'total_service_view' => 1,
                'category_id' => NULL,
                'total_category_view' => 0,
                'sub_category_id' => NULL,
                'total_sub_category_view' => 0,
                'deleted_at' => NULL,
                'created_at' => '2025-09-23 14:36:42',
                'updated_at' => '2025-09-23 14:36:42',
            ),
            53 => 
            array (
                'id' => 54,
                'module_id' => 8,
                'user_id' => 14,
                'service_id' => 6,
                'total_service_view' => 5,
                'category_id' => NULL,
                'total_category_view' => 0,
                'sub_category_id' => NULL,
                'total_sub_category_view' => 0,
                'deleted_at' => NULL,
                'created_at' => '2025-09-23 15:48:14',
                'updated_at' => '2025-10-07 13:30:04',
            ),
            54 => 
            array (
                'id' => 55,
                'module_id' => NULL,
                'user_id' => 33,
                'service_id' => NULL,
                'total_service_view' => 0,
                'category_id' => 3,
                'total_category_view' => 2,
                'sub_category_id' => NULL,
                'total_sub_category_view' => 0,
                'deleted_at' => NULL,
                'created_at' => '2025-09-23 16:16:14',
                'updated_at' => '2025-09-24 15:09:55',
            ),
            55 => 
            array (
                'id' => 56,
                'module_id' => 8,
                'user_id' => 33,
                'service_id' => NULL,
                'total_service_view' => 0,
                'category_id' => NULL,
                'total_category_view' => 0,
                'sub_category_id' => 10,
                'total_sub_category_view' => 2,
                'deleted_at' => NULL,
                'created_at' => '2025-09-23 16:16:14',
                'updated_at' => '2025-09-24 15:09:56',
            ),
            56 => 
            array (
                'id' => 57,
                'module_id' => 8,
                'user_id' => 32,
                'service_id' => 6,
                'total_service_view' => 6,
                'category_id' => NULL,
                'total_category_view' => 0,
                'sub_category_id' => NULL,
                'total_sub_category_view' => 0,
                'deleted_at' => NULL,
                'created_at' => '2025-09-24 17:21:03',
                'updated_at' => '2025-10-06 15:15:10',
            ),
            57 => 
            array (
                'id' => 58,
                'module_id' => 8,
                'user_id' => 32,
                'service_id' => 1,
                'total_service_view' => 51,
                'category_id' => NULL,
                'total_category_view' => 0,
                'sub_category_id' => NULL,
                'total_sub_category_view' => 0,
                'deleted_at' => NULL,
                'created_at' => '2025-09-24 17:21:16',
                'updated_at' => '2025-10-13 17:46:25',
            ),
            58 => 
            array (
                'id' => 59,
                'module_id' => 8,
                'user_id' => 33,
                'service_id' => 8,
                'total_service_view' => 4,
                'category_id' => NULL,
                'total_category_view' => 0,
                'sub_category_id' => NULL,
                'total_sub_category_view' => 0,
                'deleted_at' => NULL,
                'created_at' => '2025-09-24 17:47:22',
                'updated_at' => '2025-10-05 14:39:24',
            ),
            59 => 
            array (
                'id' => 60,
                'module_id' => NULL,
                'user_id' => 32,
                'service_id' => NULL,
                'total_service_view' => 0,
                'category_id' => 2,
                'total_category_view' => 6,
                'sub_category_id' => NULL,
                'total_sub_category_view' => 0,
                'deleted_at' => NULL,
                'created_at' => '2025-09-25 11:02:44',
                'updated_at' => '2025-10-09 11:28:56',
            ),
            60 => 
            array (
                'id' => 61,
                'module_id' => NULL,
                'user_id' => 32,
                'service_id' => NULL,
                'total_service_view' => 0,
                'category_id' => 1,
                'total_category_view' => 5,
                'sub_category_id' => NULL,
                'total_sub_category_view' => 0,
                'deleted_at' => NULL,
                'created_at' => '2025-09-25 11:02:57',
                'updated_at' => '2025-10-09 17:15:34',
            ),
            61 => 
            array (
                'id' => 62,
                'module_id' => 8,
                'user_id' => 32,
                'service_id' => NULL,
                'total_service_view' => 0,
                'category_id' => NULL,
                'total_category_view' => 0,
                'sub_category_id' => 5,
                'total_sub_category_view' => 12,
                'deleted_at' => NULL,
                'created_at' => '2025-09-25 11:02:57',
                'updated_at' => '2025-10-09 17:15:39',
            ),
            62 => 
            array (
                'id' => 63,
                'module_id' => 8,
                'user_id' => 32,
                'service_id' => NULL,
                'total_service_view' => 0,
                'category_id' => NULL,
                'total_category_view' => 0,
                'sub_category_id' => 4,
                'total_sub_category_view' => 9,
                'deleted_at' => NULL,
                'created_at' => '2025-09-25 11:02:59',
                'updated_at' => '2025-10-09 17:15:36',
            ),
            63 => 
            array (
                'id' => 64,
                'module_id' => 8,
                'user_id' => 8,
                'service_id' => 4,
                'total_service_view' => 7,
                'category_id' => NULL,
                'total_category_view' => 0,
                'sub_category_id' => NULL,
                'total_sub_category_view' => 0,
                'deleted_at' => NULL,
                'created_at' => '2025-09-28 13:03:22',
                'updated_at' => '2025-10-09 15:03:14',
            ),
            64 => 
            array (
                'id' => 65,
                'module_id' => NULL,
                'user_id' => 32,
                'service_id' => NULL,
                'total_service_view' => 0,
                'category_id' => 3,
                'total_category_view' => 16,
                'sub_category_id' => NULL,
                'total_sub_category_view' => 0,
                'deleted_at' => NULL,
                'created_at' => '2025-09-28 13:09:43',
                'updated_at' => '2025-10-09 11:09:26',
            ),
            65 => 
            array (
                'id' => 66,
                'module_id' => 8,
                'user_id' => 32,
                'service_id' => NULL,
                'total_service_view' => 0,
                'category_id' => NULL,
                'total_category_view' => 0,
                'sub_category_id' => 10,
                'total_sub_category_view' => 32,
                'deleted_at' => NULL,
                'created_at' => '2025-09-28 13:09:44',
                'updated_at' => '2025-10-09 11:09:27',
            ),
            66 => 
            array (
                'id' => 67,
                'module_id' => 8,
                'user_id' => 33,
                'service_id' => 10,
                'total_service_view' => 1,
                'category_id' => NULL,
                'total_category_view' => 0,
                'sub_category_id' => NULL,
                'total_sub_category_view' => 0,
                'deleted_at' => NULL,
                'created_at' => '2025-09-28 16:18:44',
                'updated_at' => '2025-09-28 16:18:44',
            ),
            67 => 
            array (
                'id' => 68,
                'module_id' => 8,
                'user_id' => 32,
                'service_id' => NULL,
                'total_service_view' => 0,
                'category_id' => NULL,
                'total_category_view' => 0,
                'sub_category_id' => 9,
                'total_sub_category_view' => 20,
                'deleted_at' => NULL,
                'created_at' => '2025-09-29 09:59:01',
                'updated_at' => '2025-10-09 10:57:50',
            ),
            68 => 
            array (
                'id' => 69,
                'module_id' => 8,
                'user_id' => 32,
                'service_id' => 8,
                'total_service_view' => 11,
                'category_id' => NULL,
                'total_category_view' => 0,
                'sub_category_id' => NULL,
                'total_sub_category_view' => 0,
                'deleted_at' => NULL,
                'created_at' => '2025-09-29 10:55:42',
                'updated_at' => '2025-09-29 13:09:38',
            ),
            69 => 
            array (
                'id' => 70,
                'module_id' => 8,
                'user_id' => 32,
                'service_id' => 10,
                'total_service_view' => 9,
                'category_id' => NULL,
                'total_category_view' => 0,
                'sub_category_id' => NULL,
                'total_sub_category_view' => 0,
                'deleted_at' => NULL,
                'created_at' => '2025-09-29 11:18:46',
                'updated_at' => '2025-09-29 15:07:33',
            ),
            70 => 
            array (
                'id' => 71,
                'module_id' => 8,
                'user_id' => 32,
                'service_id' => 7,
                'total_service_view' => 8,
                'category_id' => NULL,
                'total_category_view' => 0,
                'sub_category_id' => NULL,
                'total_sub_category_view' => 0,
                'deleted_at' => NULL,
                'created_at' => '2025-09-29 11:18:54',
                'updated_at' => '2025-10-05 12:14:12',
            ),
            71 => 
            array (
                'id' => 72,
                'module_id' => 8,
                'user_id' => 32,
                'service_id' => 9,
                'total_service_view' => 9,
                'category_id' => NULL,
                'total_category_view' => 0,
                'sub_category_id' => NULL,
                'total_sub_category_view' => 0,
                'deleted_at' => NULL,
                'created_at' => '2025-09-29 12:40:13',
                'updated_at' => '2025-09-29 13:06:51',
            ),
            72 => 
            array (
                'id' => 73,
                'module_id' => 8,
                'user_id' => 32,
                'service_id' => 2,
                'total_service_view' => 6,
                'category_id' => NULL,
                'total_category_view' => 0,
                'sub_category_id' => NULL,
                'total_sub_category_view' => 0,
                'deleted_at' => NULL,
                'created_at' => '2025-09-30 10:09:10',
                'updated_at' => '2025-10-11 10:52:38',
            ),
            73 => 
            array (
                'id' => 74,
                'module_id' => 8,
                'user_id' => 32,
                'service_id' => 4,
                'total_service_view' => 2,
                'category_id' => NULL,
                'total_category_view' => 0,
                'sub_category_id' => NULL,
                'total_sub_category_view' => 0,
                'deleted_at' => NULL,
                'created_at' => '2025-09-30 10:12:54',
                'updated_at' => '2025-10-07 12:56:54',
            ),
            74 => 
            array (
                'id' => 75,
                'module_id' => NULL,
                'user_id' => 14,
                'service_id' => NULL,
                'total_service_view' => 0,
                'category_id' => 3,
                'total_category_view' => 3,
                'sub_category_id' => NULL,
                'total_sub_category_view' => 0,
                'deleted_at' => NULL,
                'created_at' => '2025-10-05 13:57:22',
                'updated_at' => '2025-10-07 13:18:17',
            ),
            75 => 
            array (
                'id' => 76,
                'module_id' => 8,
                'user_id' => 14,
                'service_id' => NULL,
                'total_service_view' => 0,
                'category_id' => NULL,
                'total_category_view' => 0,
                'sub_category_id' => 10,
                'total_sub_category_view' => 3,
                'deleted_at' => NULL,
                'created_at' => '2025-10-05 13:57:22',
                'updated_at' => '2025-10-07 13:18:17',
            ),
            76 => 
            array (
                'id' => 77,
                'module_id' => 8,
                'user_id' => 8,
                'service_id' => 6,
                'total_service_view' => 6,
                'category_id' => NULL,
                'total_category_view' => 0,
                'sub_category_id' => NULL,
                'total_sub_category_view' => 0,
                'deleted_at' => NULL,
                'created_at' => '2025-10-06 09:56:12',
                'updated_at' => '2025-10-13 16:25:08',
            ),
            77 => 
            array (
                'id' => 78,
                'module_id' => 8,
                'user_id' => 32,
                'service_id' => 5,
                'total_service_view' => 8,
                'category_id' => NULL,
                'total_category_view' => 0,
                'sub_category_id' => NULL,
                'total_sub_category_view' => 0,
                'deleted_at' => NULL,
                'created_at' => '2025-10-11 15:09:28',
                'updated_at' => '2025-10-11 15:24:27',
            ),
            78 => 
            array (
                'id' => 79,
                'module_id' => 8,
                'user_id' => 37,
                'service_id' => 7,
                'total_service_view' => 1,
                'category_id' => NULL,
                'total_category_view' => 0,
                'sub_category_id' => NULL,
                'total_sub_category_view' => 0,
                'deleted_at' => NULL,
                'created_at' => '2025-10-11 16:36:56',
                'updated_at' => '2025-10-11 16:36:56',
            ),
        ));
        
        
    }
}