<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class StoreConfigsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('store_configs')->delete();
        
        \DB::table('store_configs')->insert(array (
            0 => 
            array (
                'id' => 1,
                'store_id' => 45,
                'is_recommended' => 1,
                'is_recommended_deleted' => 0,
                'created_at' => NULL,
                'updated_at' => '2024-04-20 14:52:56',
                'halal_tag_status' => 0,
                'extra_packaging_status' => 1,
                'extra_packaging_amount' => 5.0,
                'minimum_stock_for_warning' => 0,
            ),
            1 => 
            array (
                'id' => 2,
                'store_id' => 46,
                'is_recommended' => 1,
                'is_recommended_deleted' => 0,
                'created_at' => NULL,
                'updated_at' => '2024-04-20 16:44:35',
                'halal_tag_status' => 1,
                'extra_packaging_status' => 1,
                'extra_packaging_amount' => 2.0,
                'minimum_stock_for_warning' => 0,
            ),
            2 => 
            array (
                'id' => 3,
                'store_id' => 27,
                'is_recommended' => 1,
                'is_recommended_deleted' => 0,
                'created_at' => NULL,
                'updated_at' => '2024-04-20 15:27:46',
                'halal_tag_status' => 0,
                'extra_packaging_status' => 1,
                'extra_packaging_amount' => 1.5,
                'minimum_stock_for_warning' => 0,
            ),
            3 => 
            array (
                'id' => 4,
                'store_id' => 21,
                'is_recommended' => 1,
                'is_recommended_deleted' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'halal_tag_status' => 0,
                'extra_packaging_status' => 0,
                'extra_packaging_amount' => 0.0,
                'minimum_stock_for_warning' => 0,
            ),
            4 => 
            array (
                'id' => 5,
                'store_id' => 37,
                'is_recommended' => 1,
                'is_recommended_deleted' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'halal_tag_status' => 0,
                'extra_packaging_status' => 0,
                'extra_packaging_amount' => 0.0,
                'minimum_stock_for_warning' => 0,
            ),
            5 => 
            array (
                'id' => 6,
                'store_id' => 1,
                'is_recommended' => 0,
                'is_recommended_deleted' => 0,
                'created_at' => NULL,
                'updated_at' => '2024-04-20 15:10:03',
                'halal_tag_status' => 0,
                'extra_packaging_status' => 1,
                'extra_packaging_amount' => 3.0,
                'minimum_stock_for_warning' => 0,
            ),
            6 => 
            array (
                'id' => 7,
                'store_id' => 5,
                'is_recommended' => 1,
                'is_recommended_deleted' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'halal_tag_status' => 0,
                'extra_packaging_status' => 0,
                'extra_packaging_amount' => 0.0,
                'minimum_stock_for_warning' => 0,
            ),
            7 => 
            array (
                'id' => 8,
                'store_id' => 3,
                'is_recommended' => 1,
                'is_recommended_deleted' => 0,
                'created_at' => NULL,
                'updated_at' => '2024-11-19 14:28:27',
                'halal_tag_status' => 0,
                'extra_packaging_status' => 0,
                'extra_packaging_amount' => 0.0,
                'minimum_stock_for_warning' => 50,
            ),
            8 => 
            array (
                'id' => 9,
                'store_id' => 7,
                'is_recommended' => 1,
                'is_recommended_deleted' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'halal_tag_status' => 0,
                'extra_packaging_status' => 0,
                'extra_packaging_amount' => 0.0,
                'minimum_stock_for_warning' => 0,
            ),
            9 => 
            array (
                'id' => 10,
                'store_id' => 9,
                'is_recommended' => 1,
                'is_recommended_deleted' => 0,
                'created_at' => NULL,
                'updated_at' => '2024-04-20 16:53:19',
                'halal_tag_status' => 1,
                'extra_packaging_status' => 0,
                'extra_packaging_amount' => 0.0,
                'minimum_stock_for_warning' => 0,
            ),
            10 => 
            array (
                'id' => 11,
                'store_id' => 11,
                'is_recommended' => 1,
                'is_recommended_deleted' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'halal_tag_status' => 0,
                'extra_packaging_status' => 0,
                'extra_packaging_amount' => 0.0,
                'minimum_stock_for_warning' => 0,
            ),
            11 => 
            array (
                'id' => 12,
                'store_id' => 30,
                'is_recommended' => 1,
                'is_recommended_deleted' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'halal_tag_status' => 0,
                'extra_packaging_status' => 0,
                'extra_packaging_amount' => 0.0,
                'minimum_stock_for_warning' => 0,
            ),
            12 => 
            array (
                'id' => 13,
                'store_id' => 23,
                'is_recommended' => 1,
                'is_recommended_deleted' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'halal_tag_status' => 0,
                'extra_packaging_status' => 0,
                'extra_packaging_amount' => 0.0,
                'minimum_stock_for_warning' => 0,
            ),
            13 => 
            array (
                'id' => 14,
                'store_id' => 26,
                'is_recommended' => 1,
                'is_recommended_deleted' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'halal_tag_status' => 0,
                'extra_packaging_status' => 0,
                'extra_packaging_amount' => 0.0,
                'minimum_stock_for_warning' => 0,
            ),
            14 => 
            array (
                'id' => 15,
                'store_id' => 25,
                'is_recommended' => 1,
                'is_recommended_deleted' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'halal_tag_status' => 0,
                'extra_packaging_status' => 0,
                'extra_packaging_amount' => 0.0,
                'minimum_stock_for_warning' => 0,
            ),
            15 => 
            array (
                'id' => 16,
                'store_id' => 28,
                'is_recommended' => 1,
                'is_recommended_deleted' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'halal_tag_status' => 0,
                'extra_packaging_status' => 0,
                'extra_packaging_amount' => 0.0,
                'minimum_stock_for_warning' => 0,
            ),
            16 => 
            array (
                'id' => 17,
                'store_id' => 4,
                'is_recommended' => 1,
                'is_recommended_deleted' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'halal_tag_status' => 0,
                'extra_packaging_status' => 0,
                'extra_packaging_amount' => 0.0,
                'minimum_stock_for_warning' => 0,
            ),
            17 => 
            array (
                'id' => 18,
                'store_id' => 6,
                'is_recommended' => 1,
                'is_recommended_deleted' => 0,
                'created_at' => NULL,
                'updated_at' => '2024-04-20 15:16:44',
                'halal_tag_status' => 0,
                'extra_packaging_status' => 1,
                'extra_packaging_amount' => 3.0,
                'minimum_stock_for_warning' => 0,
            ),
            18 => 
            array (
                'id' => 19,
                'store_id' => 8,
                'is_recommended' => 1,
                'is_recommended_deleted' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'halal_tag_status' => 0,
                'extra_packaging_status' => 0,
                'extra_packaging_amount' => 0.0,
                'minimum_stock_for_warning' => 0,
            ),
            19 => 
            array (
                'id' => 20,
                'store_id' => 17,
                'is_recommended' => 1,
                'is_recommended_deleted' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'halal_tag_status' => 0,
                'extra_packaging_status' => 0,
                'extra_packaging_amount' => 0.0,
                'minimum_stock_for_warning' => 0,
            ),
            20 => 
            array (
                'id' => 21,
                'store_id' => 2,
                'is_recommended' => 1,
                'is_recommended_deleted' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'halal_tag_status' => 0,
                'extra_packaging_status' => 0,
                'extra_packaging_amount' => 0.0,
                'minimum_stock_for_warning' => 0,
            ),
            21 => 
            array (
                'id' => 22,
                'store_id' => 13,
                'is_recommended' => 1,
                'is_recommended_deleted' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'halal_tag_status' => 0,
                'extra_packaging_status' => 0,
                'extra_packaging_amount' => 0.0,
                'minimum_stock_for_warning' => 0,
            ),
            22 => 
            array (
                'id' => 23,
                'store_id' => 19,
                'is_recommended' => 1,
                'is_recommended_deleted' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'halal_tag_status' => 0,
                'extra_packaging_status' => 0,
                'extra_packaging_amount' => 0.0,
                'minimum_stock_for_warning' => 0,
            ),
            23 => 
            array (
                'id' => 24,
                'store_id' => 10,
                'is_recommended' => 1,
                'is_recommended_deleted' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'halal_tag_status' => 0,
                'extra_packaging_status' => 0,
                'extra_packaging_amount' => 0.0,
                'minimum_stock_for_warning' => 0,
            ),
            24 => 
            array (
                'id' => 25,
                'store_id' => 40,
                'is_recommended' => 1,
                'is_recommended_deleted' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'halal_tag_status' => 0,
                'extra_packaging_status' => 0,
                'extra_packaging_amount' => 0.0,
                'minimum_stock_for_warning' => 0,
            ),
            25 => 
            array (
                'id' => 26,
                'store_id' => 47,
                'is_recommended' => 1,
                'is_recommended_deleted' => 0,
                'created_at' => NULL,
                'updated_at' => '2024-04-20 16:46:03',
                'halal_tag_status' => 1,
                'extra_packaging_status' => 0,
                'extra_packaging_amount' => 0.0,
                'minimum_stock_for_warning' => 0,
            ),
            26 => 
            array (
                'id' => 27,
                'store_id' => 51,
                'is_recommended' => 1,
                'is_recommended_deleted' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'halal_tag_status' => 0,
                'extra_packaging_status' => 0,
                'extra_packaging_amount' => 0.0,
                'minimum_stock_for_warning' => 0,
            ),
            27 => 
            array (
                'id' => 28,
                'store_id' => 50,
                'is_recommended' => 1,
                'is_recommended_deleted' => 0,
                'created_at' => NULL,
                'updated_at' => '2024-04-20 16:47:28',
                'halal_tag_status' => 1,
                'extra_packaging_status' => 0,
                'extra_packaging_amount' => 0.0,
                'minimum_stock_for_warning' => 0,
            ),
            28 => 
            array (
                'id' => 29,
                'store_id' => 58,
                'is_recommended' => 1,
                'is_recommended_deleted' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'halal_tag_status' => 0,
                'extra_packaging_status' => 0,
                'extra_packaging_amount' => 0.0,
                'minimum_stock_for_warning' => 0,
            ),
            29 => 
            array (
                'id' => 30,
                'store_id' => 53,
                'is_recommended' => 1,
                'is_recommended_deleted' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'halal_tag_status' => 0,
                'extra_packaging_status' => 0,
                'extra_packaging_amount' => 0.0,
                'minimum_stock_for_warning' => 0,
            ),
            30 => 
            array (
                'id' => 31,
                'store_id' => 56,
                'is_recommended' => 1,
                'is_recommended_deleted' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'halal_tag_status' => 0,
                'extra_packaging_status' => 0,
                'extra_packaging_amount' => 0.0,
                'minimum_stock_for_warning' => 0,
            ),
            31 => 
            array (
                'id' => 32,
                'store_id' => 54,
                'is_recommended' => 1,
                'is_recommended_deleted' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'halal_tag_status' => 0,
                'extra_packaging_status' => 0,
                'extra_packaging_amount' => 0.0,
                'minimum_stock_for_warning' => 0,
            ),
            32 => 
            array (
                'id' => 33,
                'store_id' => 49,
                'is_recommended' => 0,
                'is_recommended_deleted' => 0,
                'created_at' => '2024-04-20 14:46:30',
                'updated_at' => '2024-04-20 16:45:10',
                'halal_tag_status' => 1,
                'extra_packaging_status' => 1,
                'extra_packaging_amount' => 1.5,
                'minimum_stock_for_warning' => 0,
            ),
            33 => 
            array (
                'id' => 34,
                'store_id' => 31,
                'is_recommended' => 0,
                'is_recommended_deleted' => 0,
                'created_at' => '2024-04-20 15:11:58',
                'updated_at' => '2024-04-20 16:52:43',
                'halal_tag_status' => 1,
                'extra_packaging_status' => 1,
                'extra_packaging_amount' => 2.5,
                'minimum_stock_for_warning' => 0,
            ),
            34 => 
            array (
                'id' => 35,
                'store_id' => 33,
                'is_recommended' => 0,
                'is_recommended_deleted' => 0,
                'created_at' => '2024-04-20 15:13:26',
                'updated_at' => '2024-04-20 16:50:44',
                'halal_tag_status' => 1,
                'extra_packaging_status' => 1,
                'extra_packaging_amount' => 4.0,
                'minimum_stock_for_warning' => 0,
            ),
            35 => 
            array (
                'id' => 36,
                'store_id' => 18,
                'is_recommended' => 0,
                'is_recommended_deleted' => 0,
                'created_at' => '2024-04-20 15:14:27',
                'updated_at' => '2024-04-20 15:14:27',
                'halal_tag_status' => 0,
                'extra_packaging_status' => 1,
                'extra_packaging_amount' => 5.5,
                'minimum_stock_for_warning' => 0,
            ),
            36 => 
            array (
                'id' => 37,
                'store_id' => 15,
                'is_recommended' => 0,
                'is_recommended_deleted' => 0,
                'created_at' => '2024-04-20 15:20:32',
                'updated_at' => '2024-04-20 15:20:32',
                'halal_tag_status' => 0,
                'extra_packaging_status' => 1,
                'extra_packaging_amount' => 3.5,
                'minimum_stock_for_warning' => 0,
            ),
            37 => 
            array (
                'id' => 38,
                'store_id' => 39,
                'is_recommended' => 0,
                'is_recommended_deleted' => 0,
                'created_at' => '2024-04-20 15:23:13',
                'updated_at' => '2024-04-20 15:23:13',
                'halal_tag_status' => 0,
                'extra_packaging_status' => 1,
                'extra_packaging_amount' => 5.0,
                'minimum_stock_for_warning' => 0,
            ),
            38 => 
            array (
                'id' => 39,
                'store_id' => 38,
                'is_recommended' => 0,
                'is_recommended_deleted' => 0,
                'created_at' => '2024-04-20 15:25:45',
                'updated_at' => '2024-04-20 15:25:45',
                'halal_tag_status' => 0,
                'extra_packaging_status' => 1,
                'extra_packaging_amount' => 2.5,
                'minimum_stock_for_warning' => 0,
            ),
            39 => 
            array (
                'id' => 40,
                'store_id' => 48,
                'is_recommended' => 0,
                'is_recommended_deleted' => 0,
                'created_at' => '2024-04-20 16:46:46',
                'updated_at' => '2024-04-20 16:46:46',
                'halal_tag_status' => 1,
                'extra_packaging_status' => 0,
                'extra_packaging_amount' => 0.0,
                'minimum_stock_for_warning' => 0,
            ),
            40 => 
            array (
                'id' => 41,
                'store_id' => 34,
                'is_recommended' => 0,
                'is_recommended_deleted' => 0,
                'created_at' => '2024-04-20 16:51:40',
                'updated_at' => '2024-04-20 16:51:40',
                'halal_tag_status' => 1,
                'extra_packaging_status' => 0,
                'extra_packaging_amount' => 0.0,
                'minimum_stock_for_warning' => 0,
            ),
            41 => 
            array (
                'id' => 42,
                'store_id' => 32,
                'is_recommended' => 0,
                'is_recommended_deleted' => 0,
                'created_at' => '2024-04-20 16:52:16',
                'updated_at' => '2024-04-20 16:52:16',
                'halal_tag_status' => 1,
                'extra_packaging_status' => 0,
                'extra_packaging_amount' => 0.0,
                'minimum_stock_for_warning' => 0,
            ),
        ));
        
        
    }
}