<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class SubscriptionPackagesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('subscription_packages')->delete();
        
        \DB::table('subscription_packages')->insert(array (
            0 => 
            array (
                'id' => 1,
                'package_name' => 'Basic',
                'price' => 399.0,
                'validity' => 120,
                'max_order' => '2',
                'max_product' => '2',
                'pos' => 1,
                'mobile_app' => 0,
                'chat' => 0,
                'review' => 0,
                'self_delivery' => 0,
                'scheduled_service' => 0,
                'service_request' => 0,
                'advertisement' => 0,
                'reports_and_analytics' => 0,
                'bidding' => 0,
                'status' => 1,
                'default' => 0,
                'colour' => NULL,
                'text' => 'Get access to the first level, which include all the materials you need to start.',
                'created_at' => '2024-06-06 12:41:46',
                'updated_at' => '2025-10-06 17:25:40',
                'module_type' => 'all',
            ),
            1 => 
            array (
                'id' => 2,
                'package_name' => 'Standard',
                'price' => 700.0,
                'validity' => 180,
                'max_order' => 'unlimited',
                'max_product' => '80',
                'pos' => 0,
                'mobile_app' => 1,
                'chat' => 1,
                'review' => 1,
                'self_delivery' => 1,
                'scheduled_service' => 0,
                'service_request' => 0,
                'advertisement' => 0,
                'reports_and_analytics' => 0,
                'bidding' => 0,
                'status' => 1,
                'default' => 0,
                'colour' => NULL,
                'text' => 'Get access to complete program with massive order limit.',
                'created_at' => '2024-06-06 12:42:48',
                'updated_at' => '2024-06-06 12:42:48',
                'module_type' => 'all',
            ),
            2 => 
            array (
                'id' => 3,
                'package_name' => 'Pro',
                'price' => 1199.0,
                'validity' => 365,
                'max_order' => 'unlimited',
                'max_product' => 'unlimited',
                'pos' => 1,
                'mobile_app' => 1,
                'chat' => 1,
                'review' => 1,
                'self_delivery' => 1,
                'scheduled_service' => 0,
                'service_request' => 0,
                'advertisement' => 0,
                'reports_and_analytics' => 0,
                'bidding' => 0,
                'status' => 1,
                'default' => 0,
                'colour' => NULL,
                'text' => 'Get access to complete program with unlimited order & product upload limit.',
                'created_at' => '2024-06-06 12:43:56',
                'updated_at' => '2024-06-06 12:43:56',
                'module_type' => 'all',
            ),
            3 => 
            array (
                'id' => 4,
                'package_name' => 'Premium',
                'price' => 1000.0,
                'validity' => 365,
                'max_order' => 'unlimited',
                'max_product' => 'unlimited',
                'pos' => 0,
                'mobile_app' => 1,
                'chat' => 1,
                'review' => 1,
                'self_delivery' => 0,
                'scheduled_service' => 0,
                'service_request' => 0,
                'advertisement' => 0,
                'reports_and_analytics' => 0,
                'bidding' => 0,
                'status' => 1,
                'default' => 0,
                'colour' => NULL,
                'text' => 'Premium Package',
                'created_at' => '2025-02-05 17:24:43',
                'updated_at' => '2025-02-05 17:24:43',
                'module_type' => 'rental',
            ),
            4 => 
            array (
                'id' => 5,
                'package_name' => 'Regular',
                'price' => 500.0,
                'validity' => 365,
                'max_order' => '100000',
                'max_product' => '1000',
                'pos' => 0,
                'mobile_app' => 1,
                'chat' => 1,
                'review' => 1,
                'self_delivery' => 0,
                'scheduled_service' => 0,
                'service_request' => 0,
                'advertisement' => 0,
                'reports_and_analytics' => 0,
                'bidding' => 0,
                'status' => 1,
                'default' => 0,
                'colour' => NULL,
                'text' => 'Regular Package',
                'created_at' => '2025-02-05 17:25:43',
                'updated_at' => '2025-02-05 17:25:43',
                'module_type' => 'rental',
            ),
            5 => 
            array (
                'id' => 6,
                'package_name' => 'Service --> Basic',
                'price' => 300.0,
                'validity' => 30,
                'max_order' => '2',
                'max_product' => '3',
                'pos' => 0,
                'mobile_app' => 1,
                'chat' => 1,
                'review' => 1,
                'self_delivery' => 0,
                'scheduled_service' => 0,
                'service_request' => 0,
                'advertisement' => 1,
                'reports_and_analytics' => 0,
                'bidding' => 0,
                'status' => 1,
                'default' => 0,
                'colour' => NULL,
                'text' => NULL,
                'created_at' => '2025-09-17 11:47:19',
                'updated_at' => '2025-10-06 17:34:16',
                'module_type' => 'service',
            ),
            6 => 
            array (
                'id' => 7,
                'package_name' => 'Service --> MEDIUM',
                'price' => 111.0,
                'validity' => 1,
                'max_order' => '2',
                'max_product' => '2',
                'pos' => 0,
                'mobile_app' => 1,
                'chat' => 0,
                'review' => 1,
                'self_delivery' => 0,
                'scheduled_service' => 1,
                'service_request' => 1,
                'advertisement' => 1,
                'reports_and_analytics' => 0,
                'bidding' => 0,
                'status' => 1,
                'default' => 0,
                'colour' => NULL,
                'text' => 'EE',
                'created_at' => '2025-09-24 16:52:11',
                'updated_at' => '2025-10-07 17:46:13',
                'module_type' => 'service',
            ),
            7 => 
            array (
                'id' => 8,
                'package_name' => 'Pro - Service',
                'price' => 10000.0,
                'validity' => 100,
                'max_order' => 'unlimited',
                'max_product' => 'unlimited',
                'pos' => 0,
                'mobile_app' => 1,
                'chat' => 1,
                'review' => 1,
                'self_delivery' => 0,
                'scheduled_service' => 1,
                'service_request' => 1,
                'advertisement' => 1,
                'reports_and_analytics' => 1,
                'bidding' => 1,
                'status' => 1,
                'default' => 0,
                'colour' => NULL,
                'text' => 'This is most demandable package',
                'created_at' => '2025-09-24 17:34:48',
                'updated_at' => '2025-09-24 17:34:48',
                'module_type' => 'service',
            ),
        ));
        
        
    }
}