<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class SubscriptionTransactionsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('subscription_transactions')->delete();
        
        \DB::table('subscription_transactions')->insert(array (
            0 => 
            array (
                'id' => 1000000,
                'package_id' => 1,
                'store_type' => 'store',
                'store_id' => 34,
                'store_subscription_id' => 1,
                'price' => 399.0,
                'previous_due' => 0.0,
                'validity' => 120,
                'payment_method' => 'manual_payment_by_admin',
                'payment_status' => 'success',
                'reference' => 'manual_payment_by_admin',
                'paid_amount' => 399.0,
                'discount' => 0,
                'package_details' => '{"pos":1,"review":1,"self_delivery":0,"chat":0,"mobile_app":1,"max_order":"500","max_product":"20"}',
                'created_by' => 'Admin',
                'is_trial' => 0,
                'transaction_status' => 1,
                'plan_type' => 'first_purchased',
                'created_at' => '2024-06-06 12:44:53',
                'updated_at' => '2024-06-06 12:44:53',
            ),
            1 => 
            array (
                'id' => 1000001,
                'package_id' => 3,
                'store_type' => 'store',
                'store_id' => 12,
                'store_subscription_id' => 2,
                'price' => 1199.0,
                'previous_due' => 0.0,
                'validity' => 365,
                'payment_method' => 'manual_payment_by_admin',
                'payment_status' => 'success',
                'reference' => 'manual_payment_by_admin',
                'paid_amount' => 1199.0,
                'discount' => 0,
                'package_details' => '{"pos":1,"review":1,"self_delivery":1,"chat":1,"mobile_app":1,"max_order":"unlimited","max_product":"unlimited"}',
                'created_by' => 'Admin',
                'is_trial' => 0,
                'transaction_status' => 1,
                'plan_type' => 'first_purchased',
                'created_at' => '2024-06-06 12:45:13',
                'updated_at' => '2024-06-06 12:45:13',
            ),
            2 => 
            array (
                'id' => 1000002,
                'package_id' => 3,
                'store_type' => 'store',
                'store_id' => 8,
                'store_subscription_id' => 3,
                'price' => 1199.0,
                'previous_due' => 0.0,
                'validity' => 365,
                'payment_method' => 'manual_payment_by_admin',
                'payment_status' => 'success',
                'reference' => 'manual_payment_by_admin',
                'paid_amount' => 1199.0,
                'discount' => 0,
                'package_details' => '{"pos":1,"review":1,"self_delivery":1,"chat":1,"mobile_app":1,"max_order":"unlimited","max_product":"unlimited"}',
                'created_by' => 'Admin',
                'is_trial' => 0,
                'transaction_status' => 1,
                'plan_type' => 'first_purchased',
                'created_at' => '2024-06-06 12:45:53',
                'updated_at' => '2024-06-06 12:45:53',
            ),
            3 => 
            array (
                'id' => 1000003,
                'package_id' => 1,
                'store_type' => 'store',
                'store_id' => 10,
                'store_subscription_id' => 4,
                'price' => 399.0,
                'previous_due' => 0.0,
                'validity' => 120,
                'payment_method' => 'manual_payment_by_admin',
                'payment_status' => 'success',
                'reference' => 'manual_payment_by_admin',
                'paid_amount' => 399.0,
                'discount' => 0,
                'package_details' => '{"pos":1,"review":1,"self_delivery":0,"chat":0,"mobile_app":1,"max_order":"500","max_product":"20"}',
                'created_by' => 'Admin',
                'is_trial' => 0,
                'transaction_status' => 1,
                'plan_type' => 'first_purchased',
                'created_at' => '2024-06-06 12:46:09',
                'updated_at' => '2024-06-06 12:46:09',
            ),
            4 => 
            array (
                'id' => 1000004,
                'package_id' => 3,
                'store_type' => 'store',
                'store_id' => 48,
                'store_subscription_id' => 5,
                'price' => 1199.0,
                'previous_due' => 0.0,
                'validity' => 365,
                'payment_method' => 'manual_payment_by_admin',
                'payment_status' => 'success',
                'reference' => 'manual_payment_by_admin',
                'paid_amount' => 1199.0,
                'discount' => 0,
                'package_details' => '{"pos":1,"review":1,"self_delivery":1,"chat":1,"mobile_app":1,"max_order":"unlimited","max_product":"unlimited"}',
                'created_by' => 'Admin',
                'is_trial' => 0,
                'transaction_status' => 1,
                'plan_type' => 'first_purchased',
                'created_at' => '2024-06-06 12:46:43',
                'updated_at' => '2024-06-06 12:46:43',
            ),
            5 => 
            array (
                'id' => 1000005,
                'package_id' => 2,
                'store_type' => 'store',
                'store_id' => 55,
                'store_subscription_id' => 6,
                'price' => 700.0,
                'previous_due' => 0.0,
                'validity' => 180,
                'payment_method' => 'manual_payment_by_admin',
                'payment_status' => 'success',
                'reference' => 'manual_payment_by_admin',
                'paid_amount' => 700.0,
                'discount' => 0,
                'package_details' => '{"pos":0,"review":1,"self_delivery":1,"chat":1,"mobile_app":1,"max_order":"unlimited","max_product":"80"}',
                'created_by' => 'Admin',
                'is_trial' => 0,
                'transaction_status' => 1,
                'plan_type' => 'first_purchased',
                'created_at' => '2024-06-06 12:49:19',
                'updated_at' => '2024-06-06 12:49:19',
            ),
            6 => 
            array (
                'id' => 1000006,
                'package_id' => 4,
                'store_type' => 'store',
                'store_id' => 66,
                'store_subscription_id' => 7,
                'price' => 1000.0,
                'previous_due' => 0.0,
                'validity' => 365,
                'payment_method' => 'manual_payment_by_admin',
                'payment_status' => 'success',
                'reference' => 'manual_payment_by_admin',
                'paid_amount' => 1000.0,
                'discount' => 0,
                'package_details' => '{"pos":0,"review":1,"self_delivery":0,"chat":1,"mobile_app":1,"max_order":"unlimited","max_product":"unlimited"}',
                'created_by' => 'Admin',
                'is_trial' => 0,
                'transaction_status' => 1,
                'plan_type' => 'first_purchased',
                'created_at' => '2025-02-05 17:28:26',
                'updated_at' => '2025-02-05 17:28:26',
            ),
            7 => 
            array (
                'id' => 1000007,
                'package_id' => 5,
                'store_type' => 'store',
                'store_id' => 67,
                'store_subscription_id' => 8,
                'price' => 500.0,
                'previous_due' => 0.0,
                'validity' => 365,
                'payment_method' => 'manual_payment_by_admin',
                'payment_status' => 'success',
                'reference' => 'manual_payment_by_admin',
                'paid_amount' => 500.0,
                'discount' => 0,
                'package_details' => '{"pos":0,"review":1,"self_delivery":0,"chat":1,"mobile_app":1,"max_order":"100000","max_product":"1000"}',
                'created_by' => 'Admin',
                'is_trial' => 0,
                'transaction_status' => 1,
                'plan_type' => 'first_purchased',
                'created_at' => '2025-02-05 17:30:10',
                'updated_at' => '2025-02-05 17:30:10',
            ),
            8 => 
            array (
                'id' => 1000008,
                'package_id' => 6,
                'store_type' => 'service_provider',
                'store_id' => 1,
                'store_subscription_id' => 9,
                'price' => 300.0,
                'previous_due' => 0.0,
                'validity' => 30,
                'payment_method' => 'ssl_commerz',
                'payment_status' => 'success',
                'reference' => 'store_subscription_payment',
                'paid_amount' => 300.0,
                'discount' => 0,
                'package_details' => '{"pos":0,"review":1,"self_delivery":0,"chat":1,"mobile_app":1,"max_order":"10","max_product":"10","scheduled_service":1,"service_request":1,"advertisement":1,"reports_and_analytics":1,"bidding":1}',
                'created_by' => 'Provider',
                'is_trial' => 0,
                'transaction_status' => 1,
                'plan_type' => 'first_purchased',
                'created_at' => '2025-09-21 17:58:35',
                'updated_at' => '2025-09-21 17:58:35',
            ),
            9 => 
            array (
                'id' => 1000009,
                'package_id' => 6,
                'store_type' => 'service_provider',
                'store_id' => 8,
                'store_subscription_id' => 10,
                'price' => 300.0,
                'previous_due' => 0.0,
                'validity' => 30,
                'payment_method' => 'manual_payment_by_admin',
                'payment_status' => 'success',
                'reference' => 'manual_payment_by_admin',
                'paid_amount' => 300.0,
                'discount' => 0,
                'package_details' => '{"pos":0,"review":1,"self_delivery":0,"chat":1,"mobile_app":1,"max_order":"10","max_product":"10","scheduled_service":1,"service_request":1,"advertisement":1,"reports_and_analytics":1,"bidding":1}',
                'created_by' => 'Admin',
                'is_trial' => 0,
                'transaction_status' => 1,
                'plan_type' => 'first_purchased',
                'created_at' => '2025-09-24 16:15:28',
                'updated_at' => '2025-09-24 16:15:28',
            ),
            10 => 
            array (
                'id' => 1000010,
                'package_id' => 6,
                'store_type' => 'service_provider',
                'store_id' => 8,
                'store_subscription_id' => 10,
                'price' => 300.0,
                'previous_due' => 0.0,
                'validity' => 30,
                'payment_method' => 'manual_payment_by_admin',
                'payment_status' => 'success',
                'reference' => 'manual_payment_by_admin',
                'paid_amount' => 300.0,
                'discount' => 0,
                'package_details' => '{"pos":0,"review":1,"self_delivery":0,"chat":1,"mobile_app":0,"max_order":"10","max_product":"10","scheduled_service":1,"service_request":1,"advertisement":1,"reports_and_analytics":1,"bidding":1}',
                'created_by' => 'Admin',
                'is_trial' => 0,
                'transaction_status' => 1,
                'plan_type' => 'renew',
                'created_at' => '2025-09-24 16:20:06',
                'updated_at' => '2025-09-24 16:20:06',
            ),
            11 => 
            array (
                'id' => 1000011,
                'package_id' => 6,
                'store_type' => 'service_provider',
                'store_id' => 8,
                'store_subscription_id' => 10,
                'price' => 300.0,
                'previous_due' => 0.0,
                'validity' => 30,
                'payment_method' => 'manual_payment_by_admin',
                'payment_status' => 'success',
                'reference' => 'manual_payment_by_admin',
                'paid_amount' => 300.0,
                'discount' => 0,
                'package_details' => '{"pos":0,"review":0,"self_delivery":0,"chat":0,"mobile_app":1,"max_order":"10","max_product":"10","scheduled_service":1,"service_request":1,"advertisement":0,"reports_and_analytics":1,"bidding":1}',
                'created_by' => 'Admin',
                'is_trial' => 0,
                'transaction_status' => 1,
                'plan_type' => 'renew',
                'created_at' => '2025-09-24 16:21:16',
                'updated_at' => '2025-09-24 16:21:16',
            ),
            12 => 
            array (
                'id' => 1000012,
                'package_id' => 6,
                'store_type' => 'service_provider',
                'store_id' => 8,
                'store_subscription_id' => 10,
                'price' => 300.0,
                'previous_due' => 0.0,
                'validity' => 30,
                'payment_method' => 'manual_payment_by_admin',
                'payment_status' => 'success',
                'reference' => 'manual_payment_by_admin',
                'paid_amount' => 300.0,
                'discount' => 0,
                'package_details' => '{"pos":0,"review":1,"self_delivery":0,"chat":1,"mobile_app":1,"max_order":"10","max_product":"10","scheduled_service":0,"service_request":0,"advertisement":1,"reports_and_analytics":0,"bidding":0}',
                'created_by' => 'Admin',
                'is_trial' => 0,
                'transaction_status' => 1,
                'plan_type' => 'renew',
                'created_at' => '2025-09-24 16:33:20',
                'updated_at' => '2025-09-24 16:33:20',
            ),
            13 => 
            array (
                'id' => 1000013,
                'package_id' => 6,
                'store_type' => 'service_provider',
                'store_id' => 8,
                'store_subscription_id' => 10,
                'price' => 300.0,
                'previous_due' => 0.0,
                'validity' => 30,
                'payment_method' => 'manual_payment_by_admin',
                'payment_status' => 'success',
                'reference' => 'manual_payment_by_admin',
                'paid_amount' => 300.0,
                'discount' => 0,
                'package_details' => '{"pos":0,"review":1,"self_delivery":0,"chat":1,"mobile_app":1,"max_order":"2","max_product":"2","scheduled_service":0,"service_request":0,"advertisement":1,"reports_and_analytics":0,"bidding":0}',
                'created_by' => 'Admin',
                'is_trial' => 0,
                'transaction_status' => 1,
                'plan_type' => 'renew',
                'created_at' => '2025-09-24 16:48:37',
                'updated_at' => '2025-09-24 16:48:37',
            ),
            14 => 
            array (
                'id' => 1000014,
                'package_id' => 7,
                'store_type' => 'service_provider',
                'store_id' => 8,
                'store_subscription_id' => 11,
                'price' => 111.0,
                'previous_due' => 0.0,
                'validity' => 1,
                'payment_method' => 'manual_payment_by_admin',
                'payment_status' => 'success',
                'reference' => 'manual_payment_by_admin',
                'paid_amount' => 111.0,
                'discount' => 0,
                'package_details' => '{"pos":0,"review":1,"self_delivery":0,"chat":1,"mobile_app":1,"max_order":"2","max_product":"2","scheduled_service":1,"service_request":1,"advertisement":1,"reports_and_analytics":1,"bidding":1}',
                'created_by' => 'Admin',
                'is_trial' => 0,
                'transaction_status' => 1,
                'plan_type' => 'new_plan',
                'created_at' => '2025-09-24 16:52:39',
                'updated_at' => '2025-09-24 16:52:39',
            ),
            15 => 
            array (
                'id' => 1000015,
                'package_id' => 6,
                'store_type' => 'store',
                'store_id' => 8,
                'store_subscription_id' => 12,
                'price' => 300.0,
                'previous_due' => 0.0,
                'validity' => 30,
                'payment_method' => 'plan_shift_by_admin',
                'payment_status' => 'success',
                'reference' => 'plan_shift_by_admin',
                'paid_amount' => 300.0,
                'discount' => 0,
                'package_details' => '{"pos":0,"review":1,"self_delivery":0,"chat":1,"mobile_app":1,"max_order":"2","max_product":"2"}',
                'created_by' => 'Admin',
                'is_trial' => 0,
                'transaction_status' => 1,
                'plan_type' => 'new_plan',
                'created_at' => '2025-09-24 17:40:19',
                'updated_at' => '2025-09-24 17:40:19',
            ),
            16 => 
            array (
                'id' => 1000016,
                'package_id' => 8,
                'store_type' => 'service_provider',
                'store_id' => 7,
                'store_subscription_id' => 13,
                'price' => 10000.0,
                'previous_due' => 0.0,
                'validity' => 100,
                'payment_method' => 'ssl_commerz',
                'payment_status' => 'success',
                'reference' => 'store_subscription_payment',
                'paid_amount' => 10000.0,
                'discount' => 0,
                'package_details' => '{"pos":0,"review":1,"self_delivery":0,"chat":1,"mobile_app":1,"max_order":"unlimited","max_product":"unlimited","scheduled_service":1,"service_request":1,"advertisement":1,"reports_and_analytics":1,"bidding":1}',
                'created_by' => 'Provider',
                'is_trial' => 0,
                'transaction_status' => 1,
                'plan_type' => 'first_purchased',
                'created_at' => '2025-09-28 11:14:22',
                'updated_at' => '2025-09-28 11:14:22',
            ),
            17 => 
            array (
                'id' => 1000017,
                'package_id' => 8,
                'store_type' => 'service_provider',
                'store_id' => 7,
                'store_subscription_id' => 13,
                'price' => 10000.0,
                'previous_due' => 0.0,
                'validity' => 100,
                'payment_method' => 'ssl_commerz',
                'payment_status' => 'success',
                'reference' => 'store_subscription_renew',
                'paid_amount' => 10000.0,
                'discount' => 0,
                'package_details' => '{"pos":0,"review":1,"self_delivery":0,"chat":1,"mobile_app":1,"max_order":"unlimited","max_product":"unlimited","scheduled_service":1,"service_request":1,"advertisement":1,"reports_and_analytics":1,"bidding":1}',
                'created_by' => 'Provider',
                'is_trial' => 0,
                'transaction_status' => 1,
                'plan_type' => 'renew',
                'created_at' => '2025-09-28 11:14:53',
                'updated_at' => '2025-09-28 11:14:53',
            ),
            18 => 
            array (
                'id' => 1000018,
                'package_id' => 6,
                'store_type' => 'service_provider',
                'store_id' => 8,
                'store_subscription_id' => 14,
                'price' => 300.0,
                'previous_due' => 0.0,
                'validity' => 30,
                'payment_method' => 'manual_payment_by_admin',
                'payment_status' => 'success',
                'reference' => 'manual_payment_by_admin',
                'paid_amount' => 300.0,
                'discount' => 0,
                'package_details' => '{"pos":0,"review":1,"self_delivery":0,"chat":1,"mobile_app":1,"max_order":"2","max_product":"2","scheduled_service":0,"service_request":0,"advertisement":1,"reports_and_analytics":0,"bidding":0}',
                'created_by' => 'Admin',
                'is_trial' => 0,
                'transaction_status' => 1,
                'plan_type' => 'new_plan',
                'created_at' => '2025-09-29 16:28:30',
                'updated_at' => '2025-09-29 16:28:30',
            ),
            19 => 
            array (
                'id' => 1000019,
                'package_id' => 8,
                'store_type' => 'service_provider',
                'store_id' => 7,
                'store_subscription_id' => 13,
                'price' => 10000.0,
                'previous_due' => 0.0,
                'validity' => 100,
                'payment_method' => 'ssl_commerz',
                'payment_status' => 'success',
                'reference' => 'store_subscription_renew',
                'paid_amount' => 10000.0,
                'discount' => 0,
                'package_details' => '{"pos":0,"review":1,"self_delivery":0,"chat":1,"mobile_app":1,"max_order":"unlimited","max_product":"unlimited","scheduled_service":1,"service_request":1,"advertisement":1,"reports_and_analytics":1,"bidding":1}',
                'created_by' => 'Provider',
                'is_trial' => 0,
                'transaction_status' => 1,
                'plan_type' => 'renew',
                'created_at' => '2025-09-30 15:03:31',
                'updated_at' => '2025-09-30 15:03:31',
            ),
            20 => 
            array (
                'id' => 1000020,
                'package_id' => 8,
                'store_type' => 'service_provider',
                'store_id' => 7,
                'store_subscription_id' => 13,
                'price' => 10000.0,
                'previous_due' => 0.0,
                'validity' => 100,
                'payment_method' => 'ssl_commerz',
                'payment_status' => 'success',
                'reference' => 'store_subscription_renew',
                'paid_amount' => 10000.0,
                'discount' => 0,
                'package_details' => '{"pos":0,"review":1,"self_delivery":0,"chat":1,"mobile_app":1,"max_order":"unlimited","max_product":"unlimited","scheduled_service":1,"service_request":1,"advertisement":1,"reports_and_analytics":1,"bidding":1}',
                'created_by' => 'Provider',
                'is_trial' => 0,
                'transaction_status' => 1,
                'plan_type' => 'renew',
                'created_at' => '2025-09-30 15:21:37',
                'updated_at' => '2025-09-30 15:21:37',
            ),
            21 => 
            array (
                'id' => 1000021,
                'package_id' => 6,
                'store_type' => 'service_provider',
                'store_id' => 8,
                'store_subscription_id' => 14,
                'price' => 300.0,
                'previous_due' => 0.0,
                'validity' => 30,
                'payment_method' => 'ssl_commerz',
                'payment_status' => 'success',
                'reference' => 'store_subscription_renew',
                'paid_amount' => 300.0,
                'discount' => 0,
                'package_details' => '{"pos":0,"review":1,"self_delivery":0,"chat":1,"mobile_app":1,"max_order":"2","max_product":"2","scheduled_service":0,"service_request":0,"advertisement":1,"reports_and_analytics":0,"bidding":0}',
                'created_by' => 'Provider',
                'is_trial' => 0,
                'transaction_status' => 1,
                'plan_type' => 'renew',
                'created_at' => '2025-10-06 17:24:21',
                'updated_at' => '2025-10-06 17:24:21',
            ),
            22 => 
            array (
                'id' => 1000022,
                'package_id' => 6,
                'store_type' => 'service_provider',
                'store_id' => 8,
                'store_subscription_id' => 14,
                'price' => 300.0,
                'previous_due' => 0.0,
                'validity' => 30,
                'payment_method' => 'manual_payment_by_admin',
                'payment_status' => 'success',
                'reference' => 'manual_payment_by_admin',
                'paid_amount' => 300.0,
                'discount' => 0,
                'package_details' => '{"pos":0,"review":1,"self_delivery":0,"chat":1,"mobile_app":1,"max_order":"2","max_product":"2","scheduled_service":0,"service_request":0,"advertisement":1,"reports_and_analytics":0,"bidding":0}',
                'created_by' => 'Admin',
                'is_trial' => 0,
                'transaction_status' => 1,
                'plan_type' => 'renew',
                'created_at' => '2025-10-06 17:25:52',
                'updated_at' => '2025-10-06 17:25:52',
            ),
            23 => 
            array (
                'id' => 1000023,
                'package_id' => 6,
                'store_type' => 'service_provider',
                'store_id' => 8,
                'store_subscription_id' => 14,
                'price' => 300.0,
                'previous_due' => 0.0,
                'validity' => 30,
                'payment_method' => 'manual_payment_by_admin',
                'payment_status' => 'success',
                'reference' => 'manual_payment_by_admin',
                'paid_amount' => 300.0,
                'discount' => 0,
                'package_details' => '{"pos":0,"review":1,"self_delivery":0,"chat":1,"mobile_app":0,"max_order":"2","max_product":"3","scheduled_service":0,"service_request":0,"advertisement":1,"reports_and_analytics":0,"bidding":0}',
                'created_by' => 'Admin',
                'is_trial' => 0,
                'transaction_status' => 1,
                'plan_type' => 'renew',
                'created_at' => '2025-10-06 17:33:15',
                'updated_at' => '2025-10-06 17:33:15',
            ),
            24 => 
            array (
                'id' => 1000024,
                'package_id' => 6,
                'store_type' => 'service_provider',
                'store_id' => 8,
                'store_subscription_id' => 14,
                'price' => 300.0,
                'previous_due' => 0.0,
                'validity' => 30,
                'payment_method' => 'manual_payment_by_admin',
                'payment_status' => 'success',
                'reference' => 'manual_payment_by_admin',
                'paid_amount' => 300.0,
                'discount' => 0,
                'package_details' => '{"pos":0,"review":1,"self_delivery":0,"chat":1,"mobile_app":1,"max_order":"2","max_product":"3","scheduled_service":0,"service_request":0,"advertisement":1,"reports_and_analytics":0,"bidding":0}',
                'created_by' => 'Admin',
                'is_trial' => 0,
                'transaction_status' => 1,
                'plan_type' => 'renew',
                'created_at' => '2025-10-06 17:34:36',
                'updated_at' => '2025-10-06 17:34:36',
            ),
            25 => 
            array (
                'id' => 1000025,
                'package_id' => 6,
                'store_type' => 'service_provider',
                'store_id' => 8,
                'store_subscription_id' => 14,
                'price' => 300.0,
                'previous_due' => 0.0,
                'validity' => 30,
                'payment_method' => 'manual_payment_by_admin',
                'payment_status' => 'success',
                'reference' => 'manual_payment_by_admin',
                'paid_amount' => 300.0,
                'discount' => 0,
                'package_details' => '{"pos":0,"review":1,"self_delivery":0,"chat":1,"mobile_app":1,"max_order":"2","max_product":"3","scheduled_service":0,"service_request":0,"advertisement":1,"reports_and_analytics":0,"bidding":0}',
                'created_by' => 'Admin',
                'is_trial' => 0,
                'transaction_status' => 1,
                'plan_type' => 'renew',
                'created_at' => '2025-10-07 10:50:53',
                'updated_at' => '2025-10-07 10:50:53',
            ),
            26 => 
            array (
                'id' => 1000026,
                'package_id' => 7,
                'store_type' => 'service_provider',
                'store_id' => 8,
                'store_subscription_id' => 15,
                'price' => 111.0,
                'previous_due' => 0.0,
                'validity' => 1,
                'payment_method' => 'ssl_commerz',
                'payment_status' => 'success',
                'reference' => 'store_subscription_payment',
                'paid_amount' => 111.0,
                'discount' => 0,
                'package_details' => '{"pos":0,"review":1,"self_delivery":0,"chat":0,"mobile_app":1,"max_order":"2","max_product":"2","scheduled_service":1,"service_request":1,"advertisement":1,"reports_and_analytics":0,"bidding":1}',
                'created_by' => 'Provider',
                'is_trial' => 0,
                'transaction_status' => 1,
                'plan_type' => 'new_plan',
                'created_at' => '2025-10-07 17:42:46',
                'updated_at' => '2025-10-07 17:42:46',
            ),
            27 => 
            array (
                'id' => 1000027,
                'package_id' => 7,
                'store_type' => 'service_provider',
                'store_id' => 8,
                'store_subscription_id' => 15,
                'price' => 111.0,
                'previous_due' => 0.0,
                'validity' => 1,
                'payment_method' => 'ssl_commerz',
                'payment_status' => 'success',
                'reference' => 'store_subscription_renew',
                'paid_amount' => 111.0,
                'discount' => 0,
                'package_details' => '{"pos":0,"review":1,"self_delivery":0,"chat":0,"mobile_app":1,"max_order":"2","max_product":"2","scheduled_service":1,"service_request":1,"advertisement":1,"reports_and_analytics":0,"bidding":0}',
                'created_by' => 'Provider',
                'is_trial' => 0,
                'transaction_status' => 1,
                'plan_type' => 'renew',
                'created_at' => '2025-10-07 17:47:50',
                'updated_at' => '2025-10-07 17:47:50',
            ),
            28 => 
            array (
                'id' => 1000028,
                'package_id' => 8,
                'store_type' => 'service_provider',
                'store_id' => 13,
                'store_subscription_id' => 16,
                'price' => 10000.0,
                'previous_due' => 0.0,
                'validity' => 7,
                'payment_method' => 'free_trial',
                'payment_status' => 'success',
                'reference' => 'free_trial',
                'paid_amount' => 0.0,
                'discount' => 0,
                'package_details' => '{"pos":0,"review":1,"self_delivery":0,"chat":1,"mobile_app":1,"max_order":"unlimited","max_product":"unlimited","scheduled_service":1,"service_request":1,"advertisement":1,"reports_and_analytics":1,"bidding":1}',
                'created_by' => 'Provider',
                'is_trial' => 1,
                'transaction_status' => 1,
                'plan_type' => 'first_purchased',
                'created_at' => '2025-10-09 12:57:38',
                'updated_at' => '2025-10-09 12:57:38',
            ),
            29 => 
            array (
                'id' => 1000029,
                'package_id' => 7,
                'store_type' => 'service_provider',
                'store_id' => 14,
                'store_subscription_id' => 17,
                'price' => 111.0,
                'previous_due' => 0.0,
                'validity' => 7,
                'payment_method' => 'free_trial',
                'payment_status' => 'success',
                'reference' => 'free_trial',
                'paid_amount' => 0.0,
                'discount' => 0,
                'package_details' => '{"pos":0,"review":1,"self_delivery":0,"chat":0,"mobile_app":1,"max_order":"2","max_product":"2","scheduled_service":1,"service_request":1,"advertisement":1,"reports_and_analytics":0,"bidding":0}',
                'created_by' => 'Provider',
                'is_trial' => 1,
                'transaction_status' => 1,
                'plan_type' => 'first_purchased',
                'created_at' => '2025-10-09 12:59:21',
                'updated_at' => '2025-10-09 12:59:21',
            ),
            30 => 
            array (
                'id' => 1000030,
                'package_id' => 8,
                'store_type' => 'service_provider',
                'store_id' => 15,
                'store_subscription_id' => 18,
                'price' => 10000.0,
                'previous_due' => 0.0,
                'validity' => 7,
                'payment_method' => 'free_trial',
                'payment_status' => 'success',
                'reference' => 'free_trial',
                'paid_amount' => 0.0,
                'discount' => 0,
                'package_details' => '{"pos":0,"review":1,"self_delivery":0,"chat":1,"mobile_app":1,"max_order":"unlimited","max_product":"unlimited","scheduled_service":1,"service_request":1,"advertisement":1,"reports_and_analytics":1,"bidding":1}',
                'created_by' => 'Provider',
                'is_trial' => 1,
                'transaction_status' => 1,
                'plan_type' => 'first_purchased',
                'created_at' => '2025-10-10 12:59:06',
                'updated_at' => '2025-10-10 12:59:06',
            ),
            31 => 
            array (
                'id' => 1000031,
                'package_id' => 7,
                'store_type' => 'service_provider',
                'store_id' => 16,
                'store_subscription_id' => 19,
                'price' => 111.0,
                'previous_due' => 0.0,
                'validity' => 7,
                'payment_method' => 'free_trial',
                'payment_status' => 'success',
                'reference' => 'free_trial',
                'paid_amount' => 0.0,
                'discount' => 0,
                'package_details' => '{"pos":0,"review":1,"self_delivery":0,"chat":0,"mobile_app":1,"max_order":"2","max_product":"2","scheduled_service":1,"service_request":1,"advertisement":1,"reports_and_analytics":0,"bidding":0}',
                'created_by' => 'Provider',
                'is_trial' => 1,
                'transaction_status' => 1,
                'plan_type' => 'first_purchased',
                'created_at' => '2025-10-10 15:05:24',
                'updated_at' => '2025-10-10 15:05:24',
            ),
            32 => 
            array (
                'id' => 1000032,
                'package_id' => 8,
                'store_type' => 'service_provider',
                'store_id' => 17,
                'store_subscription_id' => 20,
                'price' => 10000.0,
                'previous_due' => 0.0,
                'validity' => 7,
                'payment_method' => 'free_trial',
                'payment_status' => 'success',
                'reference' => 'free_trial',
                'paid_amount' => 0.0,
                'discount' => 0,
                'package_details' => '{"pos":0,"review":1,"self_delivery":0,"chat":1,"mobile_app":1,"max_order":"unlimited","max_product":"unlimited","scheduled_service":1,"service_request":1,"advertisement":1,"reports_and_analytics":1,"bidding":1}',
                'created_by' => 'Provider',
                'is_trial' => 1,
                'transaction_status' => 1,
                'plan_type' => 'first_purchased',
                'created_at' => '2025-10-10 15:12:57',
                'updated_at' => '2025-10-10 15:12:57',
            ),
            33 => 
            array (
                'id' => 1000033,
                'package_id' => 8,
                'store_type' => 'service_provider',
                'store_id' => 17,
                'store_subscription_id' => 21,
                'price' => 10000.0,
                'previous_due' => 0.0,
                'validity' => 7,
                'payment_method' => 'free_trial',
                'payment_status' => 'success',
                'reference' => 'free_trial',
                'paid_amount' => 0.0,
                'discount' => 0,
                'package_details' => '{"pos":0,"review":1,"self_delivery":0,"chat":1,"mobile_app":1,"max_order":"unlimited","max_product":"unlimited","scheduled_service":1,"service_request":1,"advertisement":1,"reports_and_analytics":1,"bidding":1}',
                'created_by' => 'Provider',
                'is_trial' => 1,
                'transaction_status' => 1,
                'plan_type' => 'first_purchased',
                'created_at' => '2025-10-10 15:13:30',
                'updated_at' => '2025-10-10 15:13:30',
            ),
            34 => 
            array (
                'id' => 1000034,
                'package_id' => 8,
                'store_type' => 'service_provider',
                'store_id' => 17,
                'store_subscription_id' => 22,
                'price' => 10000.0,
                'previous_due' => 0.0,
                'validity' => 7,
                'payment_method' => 'free_trial',
                'payment_status' => 'success',
                'reference' => 'free_trial',
                'paid_amount' => 0.0,
                'discount' => 0,
                'package_details' => '{"pos":0,"review":1,"self_delivery":0,"chat":1,"mobile_app":1,"max_order":"unlimited","max_product":"unlimited","scheduled_service":1,"service_request":1,"advertisement":1,"reports_and_analytics":1,"bidding":1}',
                'created_by' => 'Provider',
                'is_trial' => 1,
                'transaction_status' => 1,
                'plan_type' => 'first_purchased',
                'created_at' => '2025-10-10 15:13:47',
                'updated_at' => '2025-10-10 15:13:47',
            ),
            35 => 
            array (
                'id' => 1000035,
                'package_id' => 8,
                'store_type' => 'service_provider',
                'store_id' => 17,
                'store_subscription_id' => 23,
                'price' => 10000.0,
                'previous_due' => 0.0,
                'validity' => 100,
                'payment_method' => 'ssl_commerz',
                'payment_status' => 'success',
                'reference' => 'store_subscription_new_join',
                'paid_amount' => 10000.0,
                'discount' => 0,
                'package_details' => '{"pos":0,"review":1,"self_delivery":0,"chat":1,"mobile_app":1,"max_order":"unlimited","max_product":"unlimited","scheduled_service":1,"service_request":1,"advertisement":1,"reports_and_analytics":1,"bidding":1}',
                'created_by' => 'Provider',
                'is_trial' => 0,
                'transaction_status' => 1,
                'plan_type' => 'first_purchased',
                'created_at' => '2025-10-10 15:28:04',
                'updated_at' => '2025-10-10 15:28:04',
            ),
            36 => 
            array (
                'id' => 1000036,
                'package_id' => 8,
                'store_type' => 'service_provider',
                'store_id' => 8,
                'store_subscription_id' => 24,
                'price' => 10000.0,
                'previous_due' => 0.0,
                'validity' => 100,
                'payment_method' => 'ssl_commerz',
                'payment_status' => 'success',
                'reference' => 'store_subscription_payment',
                'paid_amount' => 10000.0,
                'discount' => 0,
                'package_details' => '{"pos":0,"review":1,"self_delivery":0,"chat":1,"mobile_app":1,"max_order":"unlimited","max_product":"unlimited","scheduled_service":1,"service_request":1,"advertisement":1,"reports_and_analytics":1,"bidding":1}',
                'created_by' => 'Provider',
                'is_trial' => 0,
                'transaction_status' => 1,
                'plan_type' => 'new_plan',
                'created_at' => '2025-10-10 16:26:54',
                'updated_at' => '2025-10-10 16:26:54',
            ),
            37 => 
            array (
                'id' => 1000037,
                'package_id' => 7,
                'store_type' => 'service_provider',
                'store_id' => 1,
                'store_subscription_id' => 25,
                'price' => 111.0,
                'previous_due' => 0.0,
                'validity' => 1,
                'payment_method' => 'manual_payment_by_admin',
                'payment_status' => 'success',
                'reference' => 'manual_payment_by_admin',
                'paid_amount' => 111.0,
                'discount' => 0,
                'package_details' => '{"pos":0,"review":1,"self_delivery":0,"chat":0,"mobile_app":1,"max_order":"2","max_product":"2","scheduled_service":1,"service_request":1,"advertisement":1,"reports_and_analytics":0,"bidding":0}',
                'created_by' => 'Admin',
                'is_trial' => 0,
                'transaction_status' => 1,
                'plan_type' => 'new_plan',
                'created_at' => '2025-10-12 13:16:50',
                'updated_at' => '2025-10-12 13:16:50',
            ),
            38 => 
            array (
                'id' => 1000038,
                'package_id' => 6,
                'store_type' => 'service_provider',
                'store_id' => 7,
                'store_subscription_id' => 26,
                'price' => 300.0,
                'previous_due' => 0.0,
                'validity' => 30,
                'payment_method' => 'manual_payment_by_admin',
                'payment_status' => 'success',
                'reference' => 'manual_payment_by_admin',
                'paid_amount' => 300.0,
                'discount' => 0,
                'package_details' => '{"pos":0,"review":1,"self_delivery":0,"chat":1,"mobile_app":1,"max_order":"2","max_product":"3","scheduled_service":0,"service_request":0,"advertisement":1,"reports_and_analytics":0,"bidding":0}',
                'created_by' => 'Admin',
                'is_trial' => 0,
                'transaction_status' => 1,
                'plan_type' => 'new_plan',
                'created_at' => '2025-10-12 16:13:48',
                'updated_at' => '2025-10-12 16:13:48',
            ),
            39 => 
            array (
                'id' => 1000039,
                'package_id' => 7,
                'store_type' => 'service_provider',
                'store_id' => 7,
                'store_subscription_id' => 27,
                'price' => 111.0,
                'previous_due' => 0.0,
                'validity' => 1,
                'payment_method' => 'ssl_commerz',
                'payment_status' => 'success',
                'reference' => 'store_subscription_payment',
                'paid_amount' => 111.0,
                'discount' => 0,
                'package_details' => '{"pos":0,"review":1,"self_delivery":0,"chat":0,"mobile_app":1,"max_order":"2","max_product":"2","scheduled_service":1,"service_request":1,"advertisement":1,"reports_and_analytics":0,"bidding":0}',
                'created_by' => 'Provider',
                'is_trial' => 0,
                'transaction_status' => 1,
                'plan_type' => 'new_plan',
                'created_at' => '2025-10-12 16:44:11',
                'updated_at' => '2025-10-12 16:44:11',
            ),
        ));
        
        
    }
}