<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class TripTransactionsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('trip_transactions')->delete();
        
        \DB::table('trip_transactions')->insert(array (
            0 => 
            array (
                'id' => 1,
                'provider_id' => 66,
                'vendor_id' => 66,
                'trip_id' => 100008,
                'zone_id' => 1,
                'module_id' => 6,
                'trip_amount' => 7378.96,
                'store_amount' => 7368.96,
                'admin_commission' => 0.0,
                'tax' => 1228.16,
                'received_by' => 'admin',
                'admin_expense' => 0.0,
                'store_expense' => 60.0,
                'status' => NULL,
                'discount_amount_by_store' => 60.0,
                'additional_charge' => 10.0,
                'ref_bonus_amount' => 0.0,
                'is_subscribed' => 1,
                'commission_percentage' => 0.0,
                'admin_net_income' => 10.0,
                'created_at' => '2025-02-06 16:40:52',
                'updated_at' => '2025-02-06 16:40:52',
            ),
            1 => 
            array (
                'id' => 2,
                'provider_id' => 64,
                'vendor_id' => 64,
                'trip_id' => 100024,
                'zone_id' => 1,
                'module_id' => 6,
                'trip_amount' => 385.0,
                'store_amount' => 342.39130435,
                'admin_commission' => 70.10869565,
                'tax' => 48.91304348,
                'received_by' => 'vendor',
                'admin_expense' => 37.5,
                'store_expense' => 337.5,
                'status' => NULL,
                'discount_amount_by_store' => 337.5,
                'additional_charge' => 10.0,
                'ref_bonus_amount' => 0.0,
                'is_subscribed' => 0,
                'commission_percentage' => 10.0,
                'admin_net_income' => 42.60869565,
                'created_at' => '2025-02-06 16:58:00',
                'updated_at' => '2025-02-06 16:58:00',
            ),
            2 => 
            array (
                'id' => 3,
                'provider_id' => 64,
                'vendor_id' => 64,
                'trip_id' => 100015,
                'zone_id' => 1,
                'module_id' => 6,
                'trip_amount' => 4946.17,
                'store_amount' => 4956.93782609,
                'admin_commission' => 1022.85017391,
                'tax' => 643.84826087,
                'received_by' => 'vendor',
                'admin_expense' => 1043.618,
                'store_expense' => 4892.562,
                'status' => NULL,
                'discount_amount_by_store' => 4892.562,
                'additional_charge' => 10.0,
                'ref_bonus_amount' => 0.0,
                'is_subscribed' => 0,
                'commission_percentage' => 10.0,
                'admin_net_income' => -10.76782609,
                'created_at' => '2025-02-06 16:58:19',
                'updated_at' => '2025-02-06 16:58:19',
            ),
            3 => 
            array (
                'id' => 4,
                'provider_id' => 66,
                'vendor_id' => 66,
                'trip_id' => 100025,
                'zone_id' => 1,
                'module_id' => 6,
                'trip_amount' => 6120.7,
                'store_amount' => 6110.7,
                'admin_commission' => 0.0,
                'tax' => 1018.45,
                'received_by' => 'admin',
                'admin_expense' => 0.0,
                'store_expense' => 50.0,
                'status' => NULL,
                'discount_amount_by_store' => 50.0,
                'additional_charge' => 10.0,
                'ref_bonus_amount' => 0.0,
                'is_subscribed' => 1,
                'commission_percentage' => 0.0,
                'admin_net_income' => 10.0,
                'created_at' => '2025-02-06 17:04:22',
                'updated_at' => '2025-02-06 17:04:22',
            ),
            4 => 
            array (
                'id' => 5,
                'provider_id' => 64,
                'vendor_id' => 64,
                'trip_id' => 100030,
                'zone_id' => 1,
                'module_id' => 6,
                'trip_amount' => 3058.5845,
                'store_amount' => 3267.67714565,
                'admin_commission' => 677.55085435,
                'tax' => 397.64145652,
                'received_by' => 'admin',
                'admin_expense' => 896.6435,
                'store_expense' => 3227.922,
                'status' => NULL,
                'discount_amount_by_store' => 3227.922,
                'additional_charge' => 10.0,
                'ref_bonus_amount' => 0.0,
                'is_subscribed' => 0,
                'commission_percentage' => 10.0,
                'admin_net_income' => -209.09264565,
                'created_at' => '2025-02-06 17:19:00',
                'updated_at' => '2025-02-06 17:19:00',
            ),
            5 => 
            array (
                'id' => 6,
                'provider_id' => 60,
                'vendor_id' => 60,
                'trip_id' => 100031,
                'zone_id' => 1,
                'module_id' => 6,
                'trip_amount' => 180.6,
                'store_amount' => 160.32289157,
                'admin_commission' => 12.17310843,
                'tax' => 67.82891566,
                'received_by' => 'vendor',
                'admin_expense' => 1.896,
                'store_expense' => 17.064,
                'status' => NULL,
                'discount_amount_by_store' => 17.064,
                'additional_charge' => 10.0,
                'ref_bonus_amount' => 0.0,
                'is_subscribed' => 0,
                'commission_percentage' => 10.0,
                'admin_net_income' => 20.27710843,
                'created_at' => '2025-02-06 17:23:07',
                'updated_at' => '2025-02-06 17:23:07',
            ),
            6 => 
            array (
                'id' => 7,
                'provider_id' => 66,
                'vendor_id' => 66,
                'trip_id' => 100032,
                'zone_id' => 1,
                'module_id' => 6,
                'trip_amount' => 7880.0,
                'store_amount' => 7870.0,
                'admin_commission' => 0.0,
                'tax' => 1311.66666667,
                'received_by' => 'admin',
                'admin_expense' => 0.0,
                'store_expense' => 90.0,
                'status' => NULL,
                'discount_amount_by_store' => 90.0,
                'additional_charge' => 10.0,
                'ref_bonus_amount' => 0.0,
                'is_subscribed' => 1,
                'commission_percentage' => 0.0,
                'admin_net_income' => 10.0,
                'created_at' => '2025-02-06 17:38:58',
                'updated_at' => '2025-02-06 17:38:58',
            ),
            7 => 
            array (
                'id' => 8,
                'provider_id' => 64,
                'vendor_id' => 64,
                'trip_id' => 100034,
                'zone_id' => 1,
                'module_id' => 6,
                'trip_amount' => 3646.72,
                'store_amount' => 3320.48347826,
                'admin_commission' => 679.90952174,
                'tax' => 474.35478261,
                'received_by' => 'admin',
                'admin_expense' => 363.673,
                'store_expense' => 3273.057,
                'status' => NULL,
                'discount_amount_by_store' => 3273.057,
                'additional_charge' => 10.0,
                'ref_bonus_amount' => 0.0,
                'is_subscribed' => 0,
                'commission_percentage' => 10.0,
                'admin_net_income' => 326.23652174,
                'created_at' => '2025-02-06 17:54:39',
                'updated_at' => '2025-02-06 17:54:39',
            ),
            8 => 
            array (
                'id' => 9,
                'provider_id' => 67,
                'vendor_id' => 67,
                'trip_id' => 100037,
                'zone_id' => 1,
                'module_id' => 6,
                'trip_amount' => 235.0,
                'store_amount' => 225.0,
                'admin_commission' => 0.0,
                'tax' => 51.92307692,
                'received_by' => 'vendor',
                'admin_expense' => 0.0,
                'store_expense' => 25.0,
                'status' => NULL,
                'discount_amount_by_store' => 25.0,
                'additional_charge' => 10.0,
                'ref_bonus_amount' => 0.0,
                'is_subscribed' => 1,
                'commission_percentage' => 0.0,
                'admin_net_income' => 10.0,
                'created_at' => '2025-02-08 12:49:31',
                'updated_at' => '2025-02-08 12:49:31',
            ),
        ));
        
        
    }
}