<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class UserInfosTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('user_infos')->delete();
        
        \DB::table('user_infos')->insert(array (
            0 => 
            array (
                'id' => 1,
                'f_name' => 'Jerry',
                'l_name' => 'Jose',
                'phone' => '+8801680808080',
                'email' => 'jerry@gmail.com',
                'image' => NULL,
                'admin_id' => NULL,
                'user_id' => 9,
                'vendor_id' => NULL,
                'deliveryman_id' => NULL,
                'created_at' => '2022-09-29 12:24:32',
                'updated_at' => '2022-09-29 12:24:32',
                'provider_id' => NULL,
                'serviceman_id' => NULL,
            ),
            1 => 
            array (
                'id' => 2,
                'f_name' => 'Eorange',
                'l_name' => '',
                'phone' => '02000000002',
                'email' => 'grocery.store2@demo.com',
                'image' => '2024-10-27-671e34990da6e.png',
                'admin_id' => NULL,
                'user_id' => NULL,
                'vendor_id' => 3,
                'deliveryman_id' => NULL,
                'created_at' => '2022-09-29 12:24:32',
                'updated_at' => '2024-10-27 18:39:53',
                'provider_id' => NULL,
                'serviceman_id' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'f_name' => 'Jhon',
                'l_name' => 'Doe',
                'phone' => '01700000000',
                'email' => 'admin@admin.com',
                'image' => '2021-08-22-61214c4e9e0cb.png',
                'admin_id' => 1,
                'user_id' => NULL,
                'vendor_id' => NULL,
                'deliveryman_id' => NULL,
                'created_at' => '2022-09-29 12:49:41',
                'updated_at' => '2022-09-29 12:49:41',
                'provider_id' => NULL,
                'serviceman_id' => NULL,
            ),
            3 => 
            array (
                'id' => 4,
                'f_name' => 'Jhon',
                'l_name' => 'Doe',
                'phone' => '+8801700000000',
                'email' => 'deliveryman@6amtech.com',
                'image' => '2022-09-29-63351bf73345f.png',
                'admin_id' => NULL,
                'user_id' => NULL,
                'vendor_id' => NULL,
                'deliveryman_id' => 1,
                'created_at' => '2022-09-29 13:06:38',
                'updated_at' => '2022-09-29 13:06:38',
                'provider_id' => NULL,
                'serviceman_id' => NULL,
            ),
            4 => 
            array (
                'id' => 5,
                'f_name' => 'Ali',
                'l_name' => 'Bey',
                'phone' => '+8801754545454',
                'email' => 'ali@gmail.com',
                'image' => NULL,
                'admin_id' => NULL,
                'user_id' => 13,
                'vendor_id' => NULL,
                'deliveryman_id' => NULL,
                'created_at' => '2022-09-29 15:01:12',
                'updated_at' => '2022-09-29 15:01:12',
                'provider_id' => NULL,
                'serviceman_id' => NULL,
            ),
            5 => 
            array (
                'id' => 6,
                'f_name' => 'Butterfly',
                'l_name' => '',
                'phone' => '01000000020',
                'email' => 'ecommerce.store20@demo.com',
                'image' => '2022-03-23-623aa864cbe3e.png',
                'admin_id' => NULL,
                'user_id' => NULL,
                'vendor_id' => 35,
                'deliveryman_id' => NULL,
                'created_at' => '2022-09-29 15:15:03',
                'updated_at' => '2022-09-29 15:15:03',
                'provider_id' => NULL,
                'serviceman_id' => NULL,
            ),
            6 => 
            array (
                'id' => 7,
                'f_name' => 'Thomas',
                'l_name' => 'Joe',
                'phone' => '+8801700000012',
                'email' => 'margaret@gmail.com',
                'image' => '2022-09-29-6335297b445a3.png',
                'admin_id' => NULL,
                'user_id' => NULL,
                'vendor_id' => NULL,
                'deliveryman_id' => 3,
                'created_at' => '2022-09-29 15:15:10',
                'updated_at' => '2022-09-29 15:15:10',
                'provider_id' => NULL,
                'serviceman_id' => NULL,
            ),
            7 => 
            array (
                'id' => 8,
                'f_name' => 'Hungry Puppets',
                'l_name' => '',
                'phone' => '+8801710000000',
                'email' => 'test.restaurant@gmail.com',
                'image' => '2024-11-03-672753e07595d.png',
                'admin_id' => NULL,
                'user_id' => NULL,
                'vendor_id' => 46,
                'deliveryman_id' => NULL,
                'created_at' => '2022-09-29 15:21:05',
                'updated_at' => '2024-11-03 16:43:44',
                'provider_id' => NULL,
                'serviceman_id' => NULL,
            ),
            8 => 
            array (
                'id' => 9,
                'f_name' => 'Ellen',
                'l_name' => 'Reyna',
                'phone' => '+8801763388119',
                'email' => 'lisa@gmail.com',
                'image' => '2022-09-29-63353fddc42bb.png',
                'admin_id' => NULL,
                'user_id' => 11,
                'vendor_id' => NULL,
                'deliveryman_id' => NULL,
                'created_at' => '2022-09-29 15:37:28',
                'updated_at' => '2022-09-29 15:37:28',
                'provider_id' => NULL,
                'serviceman_id' => NULL,
            ),
            9 => 
            array (
                'id' => 10,
                'f_name' => 'Mehedi',
                'l_name' => 'Hasan',
                'phone' => '+8801677696277',
                'email' => 'm@gmail.com',
                'image' => '2022-03-23-623ac9e8da08d.png',
                'admin_id' => NULL,
                'user_id' => 5,
                'vendor_id' => NULL,
                'deliveryman_id' => NULL,
                'created_at' => '2023-08-22 11:02:22',
                'updated_at' => '2023-08-22 11:02:22',
                'provider_id' => NULL,
                'serviceman_id' => NULL,
            ),
            10 => 
            array (
                'id' => 11,
                'f_name' => 'Bappy',
                'l_name' => 'zia',
                'phone' => '+8801624242424',
                'email' => 'ziaul939@gmail.com',
                'image' => NULL,
                'admin_id' => NULL,
                'user_id' => 20,
                'vendor_id' => NULL,
                'deliveryman_id' => NULL,
                'created_at' => '2023-10-19 09:35:54',
                'updated_at' => '2023-10-19 09:35:54',
                'provider_id' => NULL,
                'serviceman_id' => NULL,
            ),
            11 => 
            array (
                'id' => 12,
                'f_name' => 'Black',
                'l_name' => 'Smith',
                'phone' => '+8801621720022',
                'email' => 'black@gmail.com',
                'image' => '2025-02-06-67a47cada8d79.png',
                'admin_id' => NULL,
                'user_id' => 26,
                'vendor_id' => NULL,
                'deliveryman_id' => NULL,
                'created_at' => '2025-02-06 15:10:09',
                'updated_at' => '2025-02-06 15:11:09',
                'provider_id' => NULL,
                'serviceman_id' => NULL,
            ),
            12 => 
            array (
                'id' => 13,
                'f_name' => 'RideMaster Taxis',
                'l_name' => '',
                'phone' => '+8801621720023',
                'email' => 'blue@gmail.com',
                'image' => '2025-02-05-67a34b2522c75.png',
                'admin_id' => NULL,
                'user_id' => NULL,
                'vendor_id' => 66,
                'deliveryman_id' => NULL,
                'created_at' => '2025-02-06 15:10:09',
                'updated_at' => '2025-02-06 15:10:09',
                'provider_id' => NULL,
                'serviceman_id' => NULL,
            ),
            13 => 
            array (
                'id' => 14,
                'f_name' => 'Jonathon',
                'l_name' => 'Jack',
                'phone' => '+8801632154487',
                'email' => 'shahnewaj.6amtech@gmail.com',
                'image' => '2025-02-06-67a49adaed8d1.png',
                'admin_id' => NULL,
                'user_id' => 28,
                'vendor_id' => NULL,
                'deliveryman_id' => NULL,
                'created_at' => '2025-02-06 17:36:42',
                'updated_at' => '2025-02-08 13:05:35',
                'provider_id' => NULL,
                'serviceman_id' => NULL,
            ),
            14 => 
            array (
                'id' => 15,
                'f_name' => 'GoCar Hire',
                'l_name' => '',
                'phone' => '+8801621720011',
                'email' => 'jhon@gmail.com',
                'image' => '2025-02-05-67a347102879a.png',
                'admin_id' => NULL,
                'user_id' => NULL,
                'vendor_id' => 64,
                'deliveryman_id' => NULL,
                'created_at' => '2025-02-06 17:36:43',
                'updated_at' => '2025-02-06 17:36:43',
                'provider_id' => NULL,
                'serviceman_id' => NULL,
            ),
            15 => 
            array (
                'id' => 16,
                'f_name' => 'SparkleClean Ltd.',
                'l_name' => '',
                'phone' => '+8801700000001',
                'email' => 'provider1@provider.com',
                'image' => '2025-09-04-68b91de904302.png',
                'admin_id' => NULL,
                'user_id' => NULL,
                'vendor_id' => NULL,
                'deliveryman_id' => NULL,
                'created_at' => '2025-09-04 05:05:25',
                'updated_at' => '2025-10-10 16:57:41',
                'provider_id' => 1,
                'serviceman_id' => NULL,
            ),
            16 => 
            array (
                'id' => 17,
                'f_name' => 'Jhon',
                'l_name' => 'Doe',
                'phone' => '+8801900000001',
                'email' => 'serviceman1@provider1.com',
                'image' => NULL,
                'admin_id' => NULL,
                'user_id' => NULL,
                'vendor_id' => NULL,
                'deliveryman_id' => NULL,
                'created_at' => '2025-09-04 06:10:10',
                'updated_at' => '2025-09-04 06:10:10',
                'provider_id' => NULL,
                'serviceman_id' => 1,
            ),
            17 => 
            array (
                'id' => 18,
                'f_name' => 'Jhon',
                'l_name' => 'Doe',
                'phone' => '+8801747415555',
                'email' => 'nipon@gmail.com',
                'image' => NULL,
                'admin_id' => NULL,
                'user_id' => 2,
                'vendor_id' => NULL,
                'deliveryman_id' => NULL,
                'created_at' => '2025-09-04 08:51:46',
                'updated_at' => '2025-09-04 08:51:46',
                'provider_id' => NULL,
                'serviceman_id' => NULL,
            ),
            18 => 
            array (
                'id' => 19,
                'f_name' => 'Jhon',
                'l_name' => 'Ali',
                'phone' => '+8801747410000',
                'email' => 'nipon.6666@gmail.com',
                'image' => NULL,
                'admin_id' => NULL,
                'user_id' => 4,
                'vendor_id' => NULL,
                'deliveryman_id' => NULL,
                'created_at' => '2025-09-04 10:03:19',
                'updated_at' => '2025-09-04 10:03:19',
                'provider_id' => NULL,
                'serviceman_id' => NULL,
            ),
            19 => 
            array (
                'id' => 20,
                'f_name' => 'Client1',
                'l_name' => '',
                'phone' => '+8801345678910',
                'email' => 'client1@gmail.com',
                'image' => '2025-09-04-68b96d5b0236c.png',
                'admin_id' => NULL,
                'user_id' => 29,
                'vendor_id' => NULL,
                'deliveryman_id' => NULL,
                'created_at' => '2025-09-04 10:40:41',
                'updated_at' => '2025-09-04 10:43:39',
                'provider_id' => NULL,
                'serviceman_id' => NULL,
            ),
            20 => 
            array (
                'id' => 21,
                'f_name' => 'Marjahan',
                'l_name' => 'Sultana',
                'phone' => '+8801700000000',
                'email' => 'mo*****@gmail.com',
                'image' => '2025-02-08-67a71eb3aef7d.png',
                'admin_id' => NULL,
                'user_id' => 8,
                'vendor_id' => NULL,
                'deliveryman_id' => NULL,
                'created_at' => '2025-09-07 06:29:43',
                'updated_at' => '2025-09-07 06:29:43',
                'provider_id' => NULL,
                'serviceman_id' => NULL,
            ),
            21 => 
            array (
                'id' => 22,
                'f_name' => 'Tomas',
                'l_name' => 'Porter',
                'phone' => '+8801700000098',
                'email' => 'tomas@gmail.com',
                'image' => NULL,
                'admin_id' => NULL,
                'user_id' => 10,
                'vendor_id' => NULL,
                'deliveryman_id' => NULL,
                'created_at' => '2025-09-08 08:56:57',
                'updated_at' => '2025-09-08 08:56:57',
                'provider_id' => NULL,
                'serviceman_id' => NULL,
            ),
            22 => 
            array (
                'id' => 23,
                'f_name' => 'Kyla',
                'l_name' => 'Velazquez',
                'phone' => '+8801700000020',
                'email' => 'provider@provider.com',
                'image' => '2025-09-09-68bfb1cf811f2.png',
                'admin_id' => NULL,
                'user_id' => NULL,
                'vendor_id' => NULL,
                'deliveryman_id' => NULL,
                'created_at' => '2025-09-09 10:49:35',
                'updated_at' => '2025-09-09 10:49:35',
                'provider_id' => 7,
                'serviceman_id' => NULL,
            ),
            23 => 
            array (
                'id' => 24,
                'f_name' => 'Olivia',
                'l_name' => 'Turner',
                'phone' => '+819012345678',
                'email' => 'provider3@provider.com',
                'image' => '2025-09-04-68b9274c52d47.png',
                'admin_id' => NULL,
                'user_id' => NULL,
                'vendor_id' => NULL,
                'deliveryman_id' => NULL,
                'created_at' => '2025-09-09 11:32:21',
                'updated_at' => '2025-09-09 11:32:21',
                'provider_id' => 3,
                'serviceman_id' => NULL,
            ),
            24 => 
            array (
                'id' => 25,
                'f_name' => 'MS',
                'l_name' => '123',
                'phone' => '+8801600000000',
                'email' => 'ms@gmail.com',
                'image' => '2025-02-06-67a49beef3c71.png',
                'admin_id' => NULL,
                'user_id' => 21,
                'vendor_id' => NULL,
                'deliveryman_id' => NULL,
                'created_at' => '2025-09-09 11:59:37',
                'updated_at' => '2025-09-09 11:59:37',
                'provider_id' => NULL,
                'serviceman_id' => NULL,
            ),
            25 => 
            array (
                'id' => 26,
                'f_name' => 'Jhon',
                'l_name' => 'Doe',
                'phone' => '+8801722334455',
                'email' => 'serviceman@serviceman.com',
                'image' => NULL,
                'admin_id' => NULL,
                'user_id' => NULL,
                'vendor_id' => NULL,
                'deliveryman_id' => NULL,
                'created_at' => '2025-09-09 13:14:45',
                'updated_at' => '2025-09-09 13:14:45',
                'provider_id' => NULL,
                'serviceman_id' => 3,
            ),
            26 => 
            array (
                'id' => 27,
                'f_name' => 'test',
                'l_name' => 'driver',
                'phone' => '+8801500000000',
                'email' => 'test.d@mail.com',
                'image' => '2025-09-11-68c2693771f0a.png',
                'admin_id' => NULL,
                'user_id' => NULL,
                'vendor_id' => NULL,
                'deliveryman_id' => 11,
                'created_at' => '2025-09-11 13:07:14',
                'updated_at' => '2025-09-11 13:07:14',
                'provider_id' => NULL,
                'serviceman_id' => NULL,
            ),
            27 => 
            array (
                'id' => 28,
                'f_name' => 'Munam',
                'l_name' => 'ShahariEr',
                'phone' => '+8801769911110',
                'email' => 'shaharier@gmail.com',
                'image' => '2023-01-17-63c6881feb599.png',
                'admin_id' => NULL,
                'user_id' => 14,
                'vendor_id' => NULL,
                'deliveryman_id' => NULL,
                'created_at' => '2025-09-17 12:20:28',
                'updated_at' => '2025-09-17 12:20:28',
                'provider_id' => NULL,
                'serviceman_id' => NULL,
            ),
            28 => 
            array (
                'id' => 29,
                'f_name' => 'User123',
                'l_name' => '',
                'phone' => '+8801422332233',
                'email' => 'tr@g.com',
                'image' => '2025-09-21-68cfd47c7d08e.png',
                'admin_id' => NULL,
                'user_id' => 33,
                'vendor_id' => NULL,
                'deliveryman_id' => NULL,
                'created_at' => '2025-09-18 11:19:29',
                'updated_at' => '2025-09-21 16:33:32',
                'provider_id' => NULL,
                'serviceman_id' => NULL,
            ),
            29 => 
            array (
                'id' => 30,
                'f_name' => 'Rider',
                'l_name' => 'jak',
                'phone' => '+8801900000001',
                'email' => 'tr1@gmail.com',
                'image' => '2025-09-09-68bfb25f2c2db.png',
                'admin_id' => NULL,
                'user_id' => NULL,
                'vendor_id' => NULL,
                'deliveryman_id' => 9,
                'created_at' => '2025-09-18 11:19:29',
                'updated_at' => '2025-09-18 11:19:29',
                'provider_id' => NULL,
                'serviceman_id' => NULL,
            ),
            30 => 
            array (
                'id' => 31,
                'f_name' => 'Auto Mobile',
                'l_name' => '',
                'phone' => '+8801876543211',
                'email' => 'habib@habib.com',
                'image' => '2025-09-09-68bfbabfbd1f8.png',
                'admin_id' => NULL,
                'user_id' => NULL,
                'vendor_id' => NULL,
                'deliveryman_id' => NULL,
                'created_at' => '2025-09-21 15:06:14',
                'updated_at' => '2025-10-10 16:26:19',
                'provider_id' => 8,
                'serviceman_id' => NULL,
            ),
            31 => 
            array (
                'id' => 32,
                'f_name' => 'Emily',
                'l_name' => 'Wright',
                'phone' => '+442079460958',
                'email' => 'provider2@provider.com',
                'image' => '2025-09-04-68b9271f4773d.png',
                'admin_id' => NULL,
                'user_id' => NULL,
                'vendor_id' => NULL,
                'deliveryman_id' => NULL,
                'created_at' => '2025-09-22 11:23:47',
                'updated_at' => '2025-09-22 11:23:47',
                'provider_id' => 2,
                'serviceman_id' => NULL,
            ),
            32 => 
            array (
                'id' => 33,
                'f_name' => 'Tester',
                'l_name' => 'Serviceman',
                'phone' => '+8801700008526',
                'email' => 'service@gmail.com',
                'image' => NULL,
                'admin_id' => NULL,
                'user_id' => NULL,
                'vendor_id' => NULL,
                'deliveryman_id' => NULL,
                'created_at' => '2025-09-22 13:21:29',
                'updated_at' => '2025-09-22 13:21:29',
                'provider_id' => NULL,
                'serviceman_id' => 7,
            ),
            33 => 
            array (
                'id' => 34,
                'f_name' => 'Mostafizur',
                'l_name' => 'Rahman',
                'phone' => '+8801700000040',
                'email' => 'mostafizur@gmail.com',
                'image' => '2025-10-11-68ea3789a4b43.png',
                'admin_id' => NULL,
                'user_id' => 32,
                'vendor_id' => NULL,
                'deliveryman_id' => NULL,
                'created_at' => '2025-09-28 16:55:35',
                'updated_at' => '2025-10-11 16:55:05',
                'provider_id' => NULL,
                'serviceman_id' => NULL,
            ),
            34 => 
            array (
                'id' => 35,
                'f_name' => 'Laura',
                'l_name' => 'Bennett',
                'phone' => '+14165551234',
                'email' => 'provider4@provider.com',
                'image' => '2025-09-04-68b927872e032.png',
                'admin_id' => NULL,
                'user_id' => NULL,
                'vendor_id' => NULL,
                'deliveryman_id' => NULL,
                'created_at' => '2025-09-30 15:01:42',
                'updated_at' => '2025-09-30 15:01:42',
                'provider_id' => 4,
                'serviceman_id' => NULL,
            ),
            35 => 
            array (
                'id' => 36,
                'f_name' => 'Ethan',
                'l_name' => 'Walker',
                'phone' => '+919876543210',
                'email' => 'provider6@provider.com',
                'image' => '2025-09-04-68b926e5b8cf3.png',
                'admin_id' => NULL,
                'user_id' => NULL,
                'vendor_id' => NULL,
                'deliveryman_id' => NULL,
                'created_at' => '2025-09-30 15:02:24',
                'updated_at' => '2025-09-30 15:02:24',
                'provider_id' => 6,
                'serviceman_id' => NULL,
            ),
            36 => 
            array (
                'id' => 37,
                'f_name' => 'Tess',
                'l_name' => 'Ppp',
                'phone' => '+8801700002569',
                'email' => 'Cccc@gmail.com',
                'image' => NULL,
                'admin_id' => NULL,
                'user_id' => NULL,
                'vendor_id' => NULL,
                'deliveryman_id' => NULL,
                'created_at' => '2025-10-08 09:49:38',
                'updated_at' => '2025-10-08 09:49:38',
                'provider_id' => NULL,
                'serviceman_id' => 6,
            ),
            37 => 
            array (
                'id' => 38,
                'f_name' => 'Test 11',
                'l_name' => 'Rider',
                'phone' => '+8801798765432',
                'email' => 'test11rider@gmail.com',
                'image' => '2025-10-13-68ecaa94103ad.png',
                'admin_id' => NULL,
                'user_id' => NULL,
                'vendor_id' => NULL,
                'deliveryman_id' => 22,
                'created_at' => '2025-10-10 17:55:51',
                'updated_at' => '2025-10-13 13:30:28',
                'provider_id' => NULL,
                'serviceman_id' => NULL,
            ),
            38 => 
            array (
                'id' => 39,
                'f_name' => 'Jason',
                'l_name' => 'Standley',
                'phone' => '+8801778945612',
                'email' => 'testing12@gmail.com',
                'image' => '2025-10-11-68ea2c13d3d03.png',
                'admin_id' => NULL,
                'user_id' => NULL,
                'vendor_id' => NULL,
                'deliveryman_id' => 24,
                'created_at' => '2025-10-11 16:10:30',
                'updated_at' => '2025-10-11 16:10:30',
                'provider_id' => NULL,
                'serviceman_id' => NULL,
            ),
            39 => 
            array (
                'id' => 40,
                'f_name' => 'Tawfiq',
                'l_name' => 'Rafi',
                'phone' => '+8801521333333',
                'email' => 'rafi@mail.com',
                'image' => NULL,
                'admin_id' => NULL,
                'user_id' => 37,
                'vendor_id' => NULL,
                'deliveryman_id' => NULL,
                'created_at' => '2025-10-11 16:16:08',
                'updated_at' => '2025-10-11 16:16:08',
                'provider_id' => NULL,
                'serviceman_id' => NULL,
            ),
            40 => 
            array (
                'id' => 41,
                'f_name' => 'Robert',
                'l_name' => 'Patricia',
                'phone' => '+8801700000001',
                'email' => 'marjahan@6amtech.com',
                'image' => '2022-03-30-624403bd562f3.png',
                'admin_id' => NULL,
                'user_id' => NULL,
                'vendor_id' => NULL,
                'deliveryman_id' => 2,
                'created_at' => '2025-10-11 17:31:42',
                'updated_at' => '2025-10-11 17:31:42',
                'provider_id' => NULL,
                'serviceman_id' => NULL,
            ),
            41 => 
            array (
                'id' => 42,
                'f_name' => 'Gsg',
                'l_name' => 'Ywyw',
                'phone' => '+8801422558800',
                'email' => 'gsgs@g.com',
                'image' => '2025-10-13-68ecaafcbb311.png',
                'admin_id' => NULL,
                'user_id' => NULL,
                'vendor_id' => NULL,
                'deliveryman_id' => 20,
                'created_at' => '2025-10-13 15:46:10',
                'updated_at' => '2025-10-13 15:46:10',
                'provider_id' => NULL,
                'serviceman_id' => NULL,
            ),
        ));
        
        
    }
}