<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class UserLevelHistoriesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('user_level_histories')->delete();
        
        \DB::table('user_level_histories')->insert(array (
            0 => 
            array (
                'id' => 1,
                'user_level_id' => 1,
                'user_id' => 8,
                'user_type' => 'driver',
                'completed_ride' => 0,
                'ride_reward_status' => 0,
                'total_amount' => '0.00',
                'amount_reward_status' => 0,
                'cancellation_rate' => '0.00',
                'cancellation_reward_status' => 0,
                'reviews' => 0,
                'reviews_reward_status' => 0,
                'is_level_reward_granted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2025-09-08 09:13:00',
                'updated_at' => '2025-09-08 09:13:00',
            ),
            1 => 
            array (
                'id' => 2,
                'user_level_id' => 1,
                'user_id' => 9,
                'user_type' => 'driver',
                'completed_ride' => 0,
                'ride_reward_status' => 0,
                'total_amount' => '0.00',
                'amount_reward_status' => 0,
                'cancellation_rate' => '0.00',
                'cancellation_reward_status' => 0,
                'reviews' => 0,
                'reviews_reward_status' => 0,
                'is_level_reward_granted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2025-09-09 10:51:43',
                'updated_at' => '2025-09-09 10:51:43',
            ),
            2 => 
            array (
                'id' => 3,
                'user_level_id' => 1,
                'user_id' => 10,
                'user_type' => 'driver',
                'completed_ride' => 0,
                'ride_reward_status' => 0,
                'total_amount' => '0.00',
                'amount_reward_status' => 0,
                'cancellation_rate' => '0.00',
                'cancellation_reward_status' => 0,
                'reviews' => 0,
                'reviews_reward_status' => 0,
                'is_level_reward_granted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2025-09-09 12:46:57',
                'updated_at' => '2025-09-09 12:46:57',
            ),
            3 => 
            array (
                'id' => 4,
                'user_level_id' => 1,
                'user_id' => 11,
                'user_type' => 'driver',
                'completed_ride' => 0,
                'ride_reward_status' => 0,
                'total_amount' => '0.00',
                'amount_reward_status' => 0,
                'cancellation_rate' => '0.00',
                'cancellation_reward_status' => 0,
                'reviews' => 0,
                'reviews_reward_status' => 0,
                'is_level_reward_granted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2025-09-11 12:16:23',
                'updated_at' => '2025-09-11 12:16:23',
            ),
            4 => 
            array (
                'id' => 5,
                'user_level_id' => 1,
                'user_id' => 12,
                'user_type' => 'driver',
                'completed_ride' => 0,
                'ride_reward_status' => 0,
                'total_amount' => '0.00',
                'amount_reward_status' => 0,
                'cancellation_rate' => '0.00',
                'cancellation_reward_status' => 0,
                'reviews' => 0,
                'reviews_reward_status' => 0,
                'is_level_reward_granted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2025-09-15 15:28:09',
                'updated_at' => '2025-09-15 15:28:09',
            ),
            5 => 
            array (
                'id' => 6,
                'user_level_id' => 1,
                'user_id' => 13,
                'user_type' => 'driver',
                'completed_ride' => 0,
                'ride_reward_status' => 0,
                'total_amount' => '0.00',
                'amount_reward_status' => 0,
                'cancellation_rate' => '0.00',
                'cancellation_reward_status' => 0,
                'reviews' => 0,
                'reviews_reward_status' => 0,
                'is_level_reward_granted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2025-09-15 18:12:00',
                'updated_at' => '2025-09-15 18:12:00',
            ),
            6 => 
            array (
                'id' => 7,
                'user_level_id' => 2,
                'user_id' => 9,
                'user_type' => 'driver',
                'completed_ride' => 5,
                'ride_reward_status' => 1,
                'total_amount' => '0.00',
                'amount_reward_status' => 1,
                'cancellation_rate' => '0.00',
                'cancellation_reward_status' => 1,
                'reviews' => 0,
                'reviews_reward_status' => 1,
                'is_level_reward_granted' => 1,
                'deleted_at' => NULL,
                'created_at' => '2025-09-16 14:40:51',
                'updated_at' => '2025-09-16 14:40:51',
            ),
            7 => 
            array (
                'id' => 8,
                'user_level_id' => 1,
                'user_id' => 14,
                'user_type' => 'driver',
                'completed_ride' => 0,
                'ride_reward_status' => 0,
                'total_amount' => '0.00',
                'amount_reward_status' => 0,
                'cancellation_rate' => '0.00',
                'cancellation_reward_status' => 0,
                'reviews' => 0,
                'reviews_reward_status' => 0,
                'is_level_reward_granted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2025-09-16 15:03:24',
                'updated_at' => '2025-09-16 15:03:24',
            ),
            8 => 
            array (
                'id' => 9,
                'user_level_id' => 1,
                'user_id' => 15,
                'user_type' => 'driver',
                'completed_ride' => 0,
                'ride_reward_status' => 0,
                'total_amount' => '0.00',
                'amount_reward_status' => 0,
                'cancellation_rate' => '0.00',
                'cancellation_reward_status' => 0,
                'reviews' => 0,
                'reviews_reward_status' => 0,
                'is_level_reward_granted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2025-09-16 16:13:05',
                'updated_at' => '2025-09-16 16:13:05',
            ),
            9 => 
            array (
                'id' => 10,
                'user_level_id' => 1,
                'user_id' => 16,
                'user_type' => 'driver',
                'completed_ride' => 0,
                'ride_reward_status' => 0,
                'total_amount' => '0.00',
                'amount_reward_status' => 0,
                'cancellation_rate' => '0.00',
                'cancellation_reward_status' => 0,
                'reviews' => 0,
                'reviews_reward_status' => 0,
                'is_level_reward_granted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2025-09-25 17:25:21',
                'updated_at' => '2025-09-25 17:25:21',
            ),
            10 => 
            array (
                'id' => 11,
                'user_level_id' => 1,
                'user_id' => 17,
                'user_type' => 'driver',
                'completed_ride' => 0,
                'ride_reward_status' => 0,
                'total_amount' => '0.00',
                'amount_reward_status' => 0,
                'cancellation_rate' => '0.00',
                'cancellation_reward_status' => 0,
                'reviews' => 0,
                'reviews_reward_status' => 0,
                'is_level_reward_granted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2025-09-25 18:01:17',
                'updated_at' => '2025-09-25 18:01:17',
            ),
            11 => 
            array (
                'id' => 12,
                'user_level_id' => 1,
                'user_id' => 18,
                'user_type' => 'driver',
                'completed_ride' => 0,
                'ride_reward_status' => 0,
                'total_amount' => '0.00',
                'amount_reward_status' => 0,
                'cancellation_rate' => '0.00',
                'cancellation_reward_status' => 0,
                'reviews' => 0,
                'reviews_reward_status' => 0,
                'is_level_reward_granted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2025-09-25 18:04:16',
                'updated_at' => '2025-09-25 18:04:16',
            ),
            12 => 
            array (
                'id' => 13,
                'user_level_id' => 1,
                'user_id' => 19,
                'user_type' => 'driver',
                'completed_ride' => 0,
                'ride_reward_status' => 0,
                'total_amount' => '0.00',
                'amount_reward_status' => 0,
                'cancellation_rate' => '0.00',
                'cancellation_reward_status' => 0,
                'reviews' => 0,
                'reviews_reward_status' => 0,
                'is_level_reward_granted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2025-10-05 17:53:22',
                'updated_at' => '2025-10-05 17:53:22',
            ),
            13 => 
            array (
                'id' => 14,
                'user_level_id' => 1,
                'user_id' => 20,
                'user_type' => 'driver',
                'completed_ride' => 0,
                'ride_reward_status' => 0,
                'total_amount' => '0.00',
                'amount_reward_status' => 0,
                'cancellation_rate' => '0.00',
                'cancellation_reward_status' => 0,
                'reviews' => 0,
                'reviews_reward_status' => 0,
                'is_level_reward_granted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2025-10-08 16:01:26',
                'updated_at' => '2025-10-08 16:01:26',
            ),
            14 => 
            array (
                'id' => 15,
                'user_level_id' => 1,
                'user_id' => 21,
                'user_type' => 'driver',
                'completed_ride' => 1,
                'ride_reward_status' => 1,
                'total_amount' => '0.00',
                'amount_reward_status' => 1,
                'cancellation_rate' => '0.00',
                'cancellation_reward_status' => 1,
                'reviews' => 0,
                'reviews_reward_status' => 1,
                'is_level_reward_granted' => 1,
                'deleted_at' => NULL,
                'created_at' => '2025-10-09 17:50:47',
                'updated_at' => '2025-10-09 17:50:47',
            ),
            15 => 
            array (
                'id' => 16,
                'user_level_id' => 1,
                'user_id' => 2,
                'user_type' => 'driver',
                'completed_ride' => 1,
                'ride_reward_status' => 1,
                'total_amount' => '0.00',
                'amount_reward_status' => 1,
                'cancellation_rate' => '0.00',
                'cancellation_reward_status' => 1,
                'reviews' => 0,
                'reviews_reward_status' => 1,
                'is_level_reward_granted' => 1,
                'deleted_at' => NULL,
                'created_at' => '2025-10-11 13:03:42',
                'updated_at' => '2025-10-11 13:03:42',
            ),
            16 => 
            array (
                'id' => 17,
                'user_level_id' => 1,
                'user_id' => 24,
                'user_type' => 'driver',
                'completed_ride' => 1,
                'ride_reward_status' => 1,
                'total_amount' => '0.00',
                'amount_reward_status' => 1,
                'cancellation_rate' => '0.00',
                'cancellation_reward_status' => 1,
                'reviews' => 0,
                'reviews_reward_status' => 1,
                'is_level_reward_granted' => 1,
                'deleted_at' => NULL,
                'created_at' => '2025-10-11 16:17:16',
                'updated_at' => '2025-10-11 16:17:16',
            ),
            17 => 
            array (
                'id' => 18,
                'user_level_id' => 1,
                'user_id' => 25,
                'user_type' => 'driver',
                'completed_ride' => 1,
                'ride_reward_status' => 1,
                'total_amount' => '0.00',
                'amount_reward_status' => 1,
                'cancellation_rate' => '0.00',
                'cancellation_reward_status' => 1,
                'reviews' => 0,
                'reviews_reward_status' => 1,
                'is_level_reward_granted' => 1,
                'deleted_at' => NULL,
                'created_at' => '2025-10-12 11:14:39',
                'updated_at' => '2025-10-12 11:14:39',
            ),
            18 => 
            array (
                'id' => 19,
                'user_level_id' => 2,
                'user_id' => 24,
                'user_type' => 'driver',
                'completed_ride' => 5,
                'ride_reward_status' => 1,
                'total_amount' => '0.00',
                'amount_reward_status' => 1,
                'cancellation_rate' => '0.00',
                'cancellation_reward_status' => 1,
                'reviews' => 0,
                'reviews_reward_status' => 1,
                'is_level_reward_granted' => 1,
                'deleted_at' => NULL,
                'created_at' => '2025-10-12 17:47:02',
                'updated_at' => '2025-10-12 17:47:02',
            ),
            19 => 
            array (
                'id' => 20,
                'user_level_id' => 2,
                'user_id' => 2,
                'user_type' => 'driver',
                'completed_ride' => 5,
                'ride_reward_status' => 1,
                'total_amount' => '0.00',
                'amount_reward_status' => 1,
                'cancellation_rate' => '0.00',
                'cancellation_reward_status' => 1,
                'reviews' => 0,
                'reviews_reward_status' => 1,
                'is_level_reward_granted' => 1,
                'deleted_at' => NULL,
                'created_at' => '2025-10-12 19:16:38',
                'updated_at' => '2025-10-12 19:16:38',
            ),
        ));
        
        
    }
}