<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class VendorsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('vendors')->delete();
        
        \DB::table('vendors')->insert(array (
            0 => 
            array (
                'id' => 1,
                'f_name' => 'John',
                'l_name' => 'Doe G',
                'phone' => '01000000000',
                'email' => 'grocery.store1@demo.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$OYtbJjGdkonSEcIb3PaSAOCy9bvXKZfp0LHsO8cxjtBGbd3BvIitm',
                'remember_token' => 'FR9riMdXGSiclLlz49wGgPl2bnkxJS3unpn4j4FaaIlr3D9eYiMwwIsLm9gd',
                'created_at' => '2022-03-16 14:28:06',
                'updated_at' => '2024-04-20 15:09:25',
                'bank_name' => NULL,
                'branch' => NULL,
                'holder_name' => NULL,
                'account_no' => NULL,
                'image' => NULL,
                'status' => 1,
                'firebase_token' => NULL,
                'auth_token' => NULL,
            ),
            1 => 
            array (
                'id' => 2,
                'f_name' => 'Jon',
                'l_name' => 'Doe P',
                'phone' => '+101747410000',
                'email' => 'pharmacy.store1@demo.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$CVbJL7OMD/WjgbD2Yj9RRujNDt4PHjiNJR17S4vlRfy/0twyT8cjG',
                'remember_token' => NULL,
                'created_at' => '2022-03-16 17:10:37',
                'updated_at' => '2024-04-20 15:18:34',
                'bank_name' => NULL,
                'branch' => NULL,
                'holder_name' => NULL,
                'account_no' => NULL,
                'image' => NULL,
                'status' => 1,
                'firebase_token' => 'dmDZ83WBQXi30dGjFVkJF3:APA91bF5KiO3mEABf06dhYxDRHy2_EOvkE0faYSyeoOmC-aiGF7vy11-zMG12akuGo_MbfpHL_tyNVmE7k06c3NB6ZbtHJ6OqHOTHC-MtCpS2R8MRJ16yQkBT9bfzRcys7sxDpvYVKkU',
                'auth_token' => 'Tu0oYx4l78bhUJ3Ec88vrDppPdEP7WI0rHLCZHRWmWgFsdzNUHjNW2BNptBJFsjuW91UxLCh3PTcm9kWGiVuZGMFIox2SkAzcQLo6v8uSdWVkuVwqnxCjGgZ',
            ),
            2 => 
            array (
                'id' => 3,
                'f_name' => 'John',
                'l_name' => 'Doe G1',
                'phone' => '02000000002',
                'email' => 'grocery.store2@demo.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$iIPUzX7AgsnbOmJARgrjp.tUgga546SbxZnFNRUL/ToP3YD6sxkOm',
                'remember_token' => NULL,
                'created_at' => '2022-03-22 11:19:28',
                'updated_at' => '2022-09-29 15:13:17',
                'bank_name' => 'International Bank',
                'branch' => 'USA',
                'holder_name' => 'John',
                'account_no' => '65149784',
                'image' => NULL,
                'status' => 1,
                'firebase_token' => 'fVka7nIFTqe6rPjYL-2ew7:APA91bFcBNVIl2LjaR5pxz-ce7Dal8cOZIddl0gp70EyRFIwpaeFSmmGV7xFApepl2rV6Rhhb_EQGDUF8vUc0P9qgMi1CiJY90amUb5W0eMUOTqw09scrcEyZIlD9qi4lUhYdb-eAZjD',
                'auth_token' => '5egOQXTcoET2cme9B50b53Niydy0SoyH0zj0PpFzvtCJoelWL8EcBKdISOzwEajk9FHROacFFeuWtqHdEgLQmCKKfq5AcbH4HoTECFieQXcSipOtvTyGs7gY',
            ),
            3 => 
            array (
                'id' => 4,
                'f_name' => 'Jon',
                'l_name' => 'Doe P',
                'phone' => '01000000002',
                'email' => 'pharmacy.store2@demo.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$M2TesnjGi4dGUaF85FPcbOT.hiuBRnKUahoDucFGyYfCijEheiO0.',
                'remember_token' => NULL,
                'created_at' => '2022-03-22 11:21:08',
                'updated_at' => '2022-03-22 11:21:08',
                'bank_name' => NULL,
                'branch' => NULL,
                'holder_name' => NULL,
                'account_no' => NULL,
                'image' => NULL,
                'status' => 1,
                'firebase_token' => NULL,
                'auth_token' => NULL,
            ),
            4 => 
            array (
                'id' => 5,
                'f_name' => 'John',
                'l_name' => 'Doe G3',
                'phone' => '02000000003',
                'email' => 'grocery.store3@demo.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$C84JNuIb3wt8MWyOFLLLO.IwoQzT//Rl5tEOaou2Z8TnQTsM1Phfe',
                'remember_token' => NULL,
                'created_at' => '2022-03-22 11:23:03',
                'updated_at' => '2022-03-22 11:23:59',
                'bank_name' => NULL,
                'branch' => NULL,
                'holder_name' => NULL,
                'account_no' => NULL,
                'image' => NULL,
                'status' => 1,
                'firebase_token' => NULL,
                'auth_token' => NULL,
            ),
            5 => 
            array (
                'id' => 6,
                'f_name' => 'Jon',
                'l_name' => 'Doe P',
                'phone' => '01000000003',
                'email' => 'pharmacy.store3@demo.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$vUUfsg.3iD6bqAUlnt7cIOwDXguVzOa9xSBKMYBbvqfGIb6hfzvTa',
                'remember_token' => 'TwOUHKookHrWJeTRfccdOCexU21d5LkMYGLUaR7gBM7HMVHFX9icucTUW3qh',
                'created_at' => '2022-03-22 11:25:06',
                'updated_at' => '2024-04-20 15:15:56',
                'bank_name' => NULL,
                'branch' => NULL,
                'holder_name' => NULL,
                'account_no' => NULL,
                'image' => NULL,
                'status' => 1,
                'firebase_token' => 'dI1esSiDTU6a66-FFL8w2Y:APA91bFWeJjURzh3Vxqiq1eQHPZz46oUJ1bnakgKtlruTzAoNqpvUdYn6joB86fYBskDA_eUkJloIaGTaSk9vS14lCM4DkNmQHo3phonDoBMzF9jJ6wzCDUvEtyFrc3KmuMx11gTAM7Q',
                'auth_token' => '6bPO16T9bwznausyIBOql3IsiVmW1ch7wuTbsnzwUNmtNi4kGJA8OqTiiBDh6Wyxyv9h8KXSi0rJUpgqIy609QkBQA73URjZzQbsS8YoSOllJxBwAWUXzd2C',
            ),
            6 => 
            array (
                'id' => 7,
                'f_name' => 'John',
                'l_name' => 'Doe G4',
                'phone' => '02000000004',
                'email' => 'grocery.store4@demo.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$Hihhj20ve7HBWcfDh1NzCO3y/.NToXuQ1rPj.d/EyzfJdT0oOqzVy',
                'remember_token' => NULL,
                'created_at' => '2022-03-22 11:28:20',
                'updated_at' => '2022-03-22 11:28:20',
                'bank_name' => NULL,
                'branch' => NULL,
                'holder_name' => NULL,
                'account_no' => NULL,
                'image' => NULL,
                'status' => 1,
                'firebase_token' => NULL,
                'auth_token' => NULL,
            ),
            7 => 
            array (
                'id' => 8,
                'f_name' => 'Jon',
                'l_name' => 'Doe P',
                'phone' => '01000000004',
                'email' => 'pharmacy.store4@demo.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$DI8MOByEVK1aMkMbxbJug.KB493sgWjHGnOwIzeFl7GORx2W9SrW6',
                'remember_token' => NULL,
                'created_at' => '2022-03-22 11:29:44',
                'updated_at' => '2022-03-22 11:29:44',
                'bank_name' => NULL,
                'branch' => NULL,
                'holder_name' => NULL,
                'account_no' => NULL,
                'image' => NULL,
                'status' => 1,
                'firebase_token' => NULL,
                'auth_token' => NULL,
            ),
            8 => 
            array (
                'id' => 9,
                'f_name' => 'John',
                'l_name' => 'Doe G5',
                'phone' => '02000000005',
                'email' => 'grocery.store5@demo.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$TRChhYT6zaw8TctU4GLn2.lmf4UpoCTjY5BHvy1Xt590r6b4m0z7C',
                'remember_token' => NULL,
                'created_at' => '2022-03-22 11:33:14',
                'updated_at' => '2022-03-22 11:33:14',
                'bank_name' => NULL,
                'branch' => NULL,
                'holder_name' => NULL,
                'account_no' => NULL,
                'image' => NULL,
                'status' => 1,
                'firebase_token' => NULL,
                'auth_token' => NULL,
            ),
            9 => 
            array (
                'id' => 10,
                'f_name' => 'Jon',
                'l_name' => 'Doe P',
                'phone' => '01000000005',
                'email' => 'pharmacy.store5@demo.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$0/oGxXk00nuez1PcQXXb4e.KU4jKOo98MZsy.LhgcoU/GHZruLOfK',
                'remember_token' => NULL,
                'created_at' => '2022-03-22 11:33:26',
                'updated_at' => '2022-03-22 11:33:26',
                'bank_name' => NULL,
                'branch' => NULL,
                'holder_name' => NULL,
                'account_no' => NULL,
                'image' => NULL,
                'status' => 1,
                'firebase_token' => NULL,
                'auth_token' => NULL,
            ),
            10 => 
            array (
                'id' => 11,
                'f_name' => 'John',
                'l_name' => 'Doe G6',
                'phone' => '02000000006',
                'email' => 'grocery.store6@demo.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$ZU8DFDGw2x8j9SxRrA4DqO7VnM8T1yig437gL.SxvKLqzkJoAEZca',
                'remember_token' => NULL,
                'created_at' => '2022-03-22 11:36:10',
                'updated_at' => '2024-01-02 16:57:40',
                'bank_name' => NULL,
                'branch' => NULL,
                'holder_name' => NULL,
                'account_no' => NULL,
                'image' => NULL,
                'status' => 1,
                'firebase_token' => 'cLSF3cTHSqSpsg4nklI6hQ:APA91bHfFfpqDIOV-IIc79oWXDTJ55yhqkqMFyJuMjv8sCmjlp5AWQVwMHhCoCOx8X1j83xDzqMAgEdK6aTfV4dYIU68yQrl1vPLfDzT33_9L4I-3wDYt4wcGbQXHIRaRbe-OtSvUGm3',
                'auth_token' => 'BbJYmEbu7kEBnY0rJaDzH5gqXp8MXbijuvjojvXux6Btc9MROBKcpsosLbOiBJbHd8UY5y0P1rxnmsj8YOq1dzYlb9zp3mND4s1gv7wi3aVH8hGQsYHe8c2x',
            ),
            11 => 
            array (
                'id' => 12,
                'f_name' => 'John',
                'l_name' => 'Doe G7',
                'phone' => '02000000007',
                'email' => 'grocery.store7@demo.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$fO2CmTonD98JxtVQx9Yu1emSuAr152tlkF4NVCEAUh/s.dRKW2asC',
                'remember_token' => NULL,
                'created_at' => '2022-03-22 11:39:51',
                'updated_at' => '2022-03-22 11:39:51',
                'bank_name' => NULL,
                'branch' => NULL,
                'holder_name' => NULL,
                'account_no' => NULL,
                'image' => NULL,
                'status' => 1,
                'firebase_token' => NULL,
                'auth_token' => NULL,
            ),
            12 => 
            array (
                'id' => 13,
                'f_name' => 'Jon',
                'l_name' => 'Doe P',
                'phone' => '01000000006',
                'email' => 'pharmacy.store6@demo.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$9vjcHlHb.c8sQqJAffwYAOYseHQX2rbFjVrnhcGnSfN3tJ8NAKxxy',
                'remember_token' => NULL,
                'created_at' => '2022-03-22 11:42:33',
                'updated_at' => '2022-03-22 11:42:33',
                'bank_name' => NULL,
                'branch' => NULL,
                'holder_name' => NULL,
                'account_no' => NULL,
                'image' => NULL,
                'status' => 1,
                'firebase_token' => NULL,
                'auth_token' => NULL,
            ),
            13 => 
            array (
                'id' => 14,
                'f_name' => 'John',
                'l_name' => 'Doe G8',
                'phone' => '02000000008',
                'email' => 'grocery.store8@demo.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$wSnMjZ3KTIA3OezpScrQUukdQPiHyVfmLPQxMamrDUjZGNLtbIidy',
                'remember_token' => NULL,
                'created_at' => '2022-03-22 11:42:49',
                'updated_at' => '2025-09-17 15:22:35',
                'bank_name' => NULL,
                'branch' => NULL,
                'holder_name' => NULL,
                'account_no' => NULL,
                'image' => NULL,
                'status' => 1,
                'firebase_token' => NULL,
                'auth_token' => NULL,
            ),
            14 => 
            array (
                'id' => 15,
                'f_name' => 'Jon',
                'l_name' => 'Doe P',
                'phone' => '01000000007',
                'email' => 'pharmacy.store7@demo.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$7tap2aconhisxn3rYCdUm.k4PBxnD7JJEH9gVp1AT2oaLmdPdDPvG',
                'remember_token' => 'EOs6IaRxAMptlFMKW6wsax2q5GKdHXxahLnreTUa0jpXIawepVBFzptyl2sO',
                'created_at' => '2022-03-22 11:45:46',
                'updated_at' => '2024-04-20 15:20:10',
                'bank_name' => NULL,
                'branch' => NULL,
                'holder_name' => NULL,
                'account_no' => NULL,
                'image' => NULL,
                'status' => 1,
                'firebase_token' => NULL,
                'auth_token' => NULL,
            ),
            15 => 
            array (
                'id' => 16,
                'f_name' => 'John',
                'l_name' => 'Doe G9',
                'phone' => '02000000009',
                'email' => 'grocery.store9@demo.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$VI2juah0Idow4GYy4gqQtOC.H48i7teI/77/7bxFHIuYsoDLgY2GS',
                'remember_token' => 'Gq4k2bBVdBSQfLkUZK1k6TL0LwB4YBByt1bqlHSi5nFyeJk055AZkH4bvW8r',
                'created_at' => '2022-03-22 11:46:40',
                'updated_at' => '2022-03-22 11:46:40',
                'bank_name' => NULL,
                'branch' => NULL,
                'holder_name' => NULL,
                'account_no' => NULL,
                'image' => NULL,
                'status' => 1,
                'firebase_token' => NULL,
                'auth_token' => NULL,
            ),
            16 => 
            array (
                'id' => 17,
                'f_name' => 'Jon',
                'l_name' => 'Doe P',
                'phone' => '01000000008',
                'email' => 'pharmacy.store8@demo.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$B/P9h3by3ZOtGClzHu/VN.CU1iH9aJBRUfBAXp7Yd07QCdmHeZMea',
                'remember_token' => NULL,
                'created_at' => '2022-03-22 11:49:20',
                'updated_at' => '2022-03-22 11:49:20',
                'bank_name' => NULL,
                'branch' => NULL,
                'holder_name' => NULL,
                'account_no' => NULL,
                'image' => NULL,
                'status' => 1,
                'firebase_token' => NULL,
                'auth_token' => NULL,
            ),
            17 => 
            array (
                'id' => 18,
                'f_name' => 'John',
                'l_name' => 'Doe G',
                'phone' => '0200000010',
                'email' => 'grocery.store10@demo.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$6CMEclWbpUD3SMOtGDFABOKe4HkNobaeoCY73Fuy9JlSdIjy88352',
                'remember_token' => '9NEVvRshcTTFLnyPsxZEQgE6ur8x0D4yocxLsAcmZNOOldBW36rGfvF69DkB',
                'created_at' => '2022-03-22 11:49:38',
                'updated_at' => '2024-04-20 15:13:57',
                'bank_name' => NULL,
                'branch' => NULL,
                'holder_name' => NULL,
                'account_no' => NULL,
                'image' => NULL,
                'status' => 1,
                'firebase_token' => NULL,
                'auth_token' => NULL,
            ),
            18 => 
            array (
                'id' => 19,
                'f_name' => 'Jon',
                'l_name' => 'Doe P',
                'phone' => '01000000009',
                'email' => 'pharmacy.store9@demo.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$nRtgfKlarrznkRm24ZNVIOW3dnNa7TRHoQgKKiHlEkUZ9OquuJ0TC',
                'remember_token' => NULL,
                'created_at' => '2022-03-22 11:52:58',
                'updated_at' => '2022-03-22 11:52:58',
                'bank_name' => NULL,
                'branch' => NULL,
                'holder_name' => NULL,
                'account_no' => NULL,
                'image' => NULL,
                'status' => 1,
                'firebase_token' => NULL,
                'auth_token' => NULL,
            ),
            19 => 
            array (
                'id' => 20,
                'f_name' => 'Jon',
                'l_name' => 'Doe P',
                'phone' => '010000000010',
                'email' => 'pharmacy.store10@demo.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$foaqZVRZSN.eGquG7PR/jubVBXJqSzEHAXIHKm8mBBDOOqOp5ZTxm',
                'remember_token' => NULL,
                'created_at' => '2022-03-22 11:55:50',
                'updated_at' => '2022-03-22 11:55:50',
                'bank_name' => NULL,
                'branch' => NULL,
                'holder_name' => NULL,
                'account_no' => NULL,
                'image' => NULL,
                'status' => 1,
                'firebase_token' => NULL,
                'auth_token' => NULL,
            ),
            20 => 
            array (
                'id' => 21,
                'f_name' => 'Jon',
                'l_name' => 'Doe E',
                'phone' => '010000000011',
                'email' => 'ecommerce.store6@demo.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$imELJNdypTj.Gbsbwbctlukso/jcT.MK2xHANGR8FJttSGnQETLLO',
                'remember_token' => NULL,
                'created_at' => '2022-03-22 12:03:20',
                'updated_at' => '2022-03-23 22:03:29',
                'bank_name' => NULL,
                'branch' => NULL,
                'holder_name' => NULL,
                'account_no' => NULL,
                'image' => NULL,
                'status' => 1,
                'firebase_token' => '@',
                'auth_token' => 'mYjpHy5RYnWaapQ6FppPhUxr5SB89z7jbWQwy7AR8RQSG8OFTQ7jStZfXcvDWx6stdlfQQxmw1EJaSQIZBDtOn28xETbMYfvuF8P1I0JXs6yi1m8hiuVvt1s',
            ),
            21 => 
            array (
                'id' => 22,
                'f_name' => 'John',
                'l_name' => 'Doe E',
                'phone' => '030000000001',
                'email' => 'ecommerce.store1@demo.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$s9mLUTXQsOg/tCvfEvTPuey.1yNZzlHqeMK2zx1ddVQctS/di5hK6',
                'remember_token' => NULL,
                'created_at' => '2022-03-22 12:03:36',
                'updated_at' => '2022-03-22 12:03:36',
                'bank_name' => NULL,
                'branch' => NULL,
                'holder_name' => NULL,
                'account_no' => NULL,
                'image' => NULL,
                'status' => 1,
                'firebase_token' => NULL,
                'auth_token' => NULL,
            ),
            22 => 
            array (
                'id' => 23,
                'f_name' => 'John',
                'l_name' => 'Doe E',
                'phone' => '03000000002',
                'email' => 'ecommerce.store3@demo.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$.7tnttskH7Mr2OP2Fp7wkOuaDRj2o0UVL3yjV7R.2u5aHCnxEzn5O',
                'remember_token' => NULL,
                'created_at' => '2022-03-22 12:05:30',
                'updated_at' => '2022-03-22 12:05:30',
                'bank_name' => NULL,
                'branch' => NULL,
                'holder_name' => NULL,
                'account_no' => NULL,
                'image' => NULL,
                'status' => 1,
                'firebase_token' => NULL,
                'auth_token' => NULL,
            ),
            23 => 
            array (
                'id' => 24,
                'f_name' => 'Jon',
                'l_name' => 'Doe E',
                'phone' => '010000000012',
                'email' => 'ecommerce.store7@demo.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$jQZqxQd4M8tzn7ZOFaxiZuUsNLKwJrEluc23pr8DxDLtuB42W7ory',
                'remember_token' => NULL,
                'created_at' => '2022-03-22 12:05:54',
                'updated_at' => '2022-03-22 12:05:54',
                'bank_name' => NULL,
                'branch' => NULL,
                'holder_name' => NULL,
                'account_no' => NULL,
                'image' => NULL,
                'status' => 1,
                'firebase_token' => NULL,
                'auth_token' => NULL,
            ),
            24 => 
            array (
                'id' => 25,
                'f_name' => 'John',
                'l_name' => 'Doe E',
                'phone' => '03000000004',
                'email' => 'ecommerce.store4@demo.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$.KXpooKsYFg0Kl0wpkPms.sktnowDSzchE..qTCYMa7d7nY3GQpQi',
                'remember_token' => NULL,
                'created_at' => '2022-03-22 12:08:19',
                'updated_at' => '2022-03-22 12:08:19',
                'bank_name' => NULL,
                'branch' => NULL,
                'holder_name' => NULL,
                'account_no' => NULL,
                'image' => NULL,
                'status' => 1,
                'firebase_token' => NULL,
                'auth_token' => NULL,
            ),
            25 => 
            array (
                'id' => 26,
                'f_name' => 'Jon',
                'l_name' => 'Doe E',
                'phone' => '010000000013',
                'email' => 'ecommerce.store8@demo.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$2LjpfMjD8S.CA6Q4y5oGe.AMIvH52PFbaN.39ou/mtep5fLfwSCxK',
                'remember_token' => NULL,
                'created_at' => '2022-03-22 12:08:38',
                'updated_at' => '2022-03-22 12:08:38',
                'bank_name' => NULL,
                'branch' => NULL,
                'holder_name' => NULL,
                'account_no' => NULL,
                'image' => NULL,
                'status' => 1,
                'firebase_token' => NULL,
                'auth_token' => NULL,
            ),
            26 => 
            array (
                'id' => 27,
                'f_name' => 'John',
                'l_name' => 'Doe E',
                'phone' => '03000000005',
                'email' => 'ecommerce.store5@demo.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$.KzMOw.sxRUCm25BGqyZuu6LVUC0NyffnzIUGtQjprfZHON9x8Y0a',
                'remember_token' => 'UfdUkXrYeASs2Ap3OuHURj0qiKFbTYIcg1VHY0tpb6oLA73ZQNud3ZzrlRIu',
                'created_at' => '2022-03-22 12:12:03',
                'updated_at' => '2024-04-20 15:26:20',
                'bank_name' => NULL,
                'branch' => NULL,
                'holder_name' => NULL,
                'account_no' => NULL,
                'image' => NULL,
                'status' => 1,
                'firebase_token' => NULL,
                'auth_token' => NULL,
            ),
            27 => 
            array (
                'id' => 28,
                'f_name' => 'Jon',
                'l_name' => 'Doe E',
                'phone' => '010000000014',
                'email' => 'ecommerce.store9@demo.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$eCowEBq40hEcC1zPXpzStuhCvnYn8XIVfn1ID4VQuI6HwyuZ4PZLC',
                'remember_token' => NULL,
                'created_at' => '2022-03-22 12:12:35',
                'updated_at' => '2022-03-22 12:12:35',
                'bank_name' => NULL,
                'branch' => NULL,
                'holder_name' => NULL,
                'account_no' => NULL,
                'image' => NULL,
                'status' => 1,
                'firebase_token' => NULL,
                'auth_token' => NULL,
            ),
            28 => 
            array (
                'id' => 29,
                'f_name' => 'John',
                'l_name' => 'Doe E',
                'phone' => '030000000010',
                'email' => 'ecommerce.store10@demo.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$LpCKLAx1OLfIG68IYLq/Aes3f63A4whXpkYUNLEDWBzmCjzfeRoT.',
                'remember_token' => NULL,
                'created_at' => '2022-03-22 12:15:07',
                'updated_at' => '2022-03-22 12:15:07',
                'bank_name' => NULL,
                'branch' => NULL,
                'holder_name' => NULL,
                'account_no' => NULL,
                'image' => NULL,
                'status' => 1,
                'firebase_token' => NULL,
                'auth_token' => NULL,
            ),
            29 => 
            array (
                'id' => 30,
                'f_name' => 'John',
                'l_name' => 'Doe G',
                'phone' => '020000000011',
                'email' => 'grocery.store11@demo.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$o8QlXvQvTZoWLM6S2DX1UOpw5x2yBMB3PAfxNnCllxYLnAWxyPSFq',
                'remember_token' => NULL,
                'created_at' => '2022-03-23 10:07:13',
                'updated_at' => '2024-10-27 17:49:50',
                'bank_name' => NULL,
                'branch' => NULL,
                'holder_name' => NULL,
                'account_no' => NULL,
                'image' => NULL,
                'status' => 1,
                'firebase_token' => 'dM94nK5mYkzVjPSL_VcoMb:APA91bHKBXCKdRDLxyi2hXnDf3xbo2Q5M6-4sUA5sxVv_lSVA3yX1lEW78MzVMvJwDPvRpTRasHPsNDzjaJHGXgVya3UzfKMbbCD8Ltupo7EzWwimAZCdAu_5Brjb8_rrIfDtGVtqPsm',
                'auth_token' => '2PbxMwC37XR0kuVLPU1NFsusG1dIBD3IWgf4v37kZYdUwKhifohvxlujXP4sKnkQOL2aNZi4fcmfHu8yqqVcPPxFA1UpQ4V2NSseU0yLckMGH4RMmnpa3ft8',
            ),
            30 => 
            array (
                'id' => 31,
                'f_name' => 'John',
                'l_name' => 'Doe G',
                'phone' => '020000000012',
                'email' => 'grocery.store12@demo.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$sFi.Ft6XzzM5YAkbPK8B1uPJ4/J.I4jWe3zniHB3wn.ZzOJWCZVd6',
                'remember_token' => 'SaUzQgP2bAH2thURFGmEVgA49SU5h99mj5jQ8X15fIfOWxH2k2JGhbR2UHS9',
                'created_at' => '2022-03-23 10:13:54',
                'updated_at' => '2024-04-20 15:11:04',
                'bank_name' => NULL,
                'branch' => NULL,
                'holder_name' => NULL,
                'account_no' => NULL,
                'image' => NULL,
                'status' => 1,
                'firebase_token' => NULL,
                'auth_token' => NULL,
            ),
            31 => 
            array (
                'id' => 32,
                'f_name' => 'John',
                'l_name' => 'Doe G',
                'phone' => '020000000013',
                'email' => 'grocery.store13@demo.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$TxRVVZuRpL0G9r7U1P0TEuQ1YURpjSe2q6/cjtIWK4KqUYffFw70m',
                'remember_token' => 'sesQwFvOLxqM19vv7EovSiH2g836toRoezfrTi5YHOgCYRLNMVxJcQ4m0bN6',
                'created_at' => '2022-03-23 10:20:09',
                'updated_at' => '2022-03-23 10:20:09',
                'bank_name' => NULL,
                'branch' => NULL,
                'holder_name' => NULL,
                'account_no' => NULL,
                'image' => NULL,
                'status' => 1,
                'firebase_token' => NULL,
                'auth_token' => NULL,
            ),
            32 => 
            array (
                'id' => 33,
                'f_name' => 'John',
                'l_name' => 'DoeG12345678@',
                'phone' => '020000000014',
                'email' => 'grocery.store14@demo.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$awIi3AvwjWcA6An5ptE4TOd2J2LOLLYn.6nawYP8wO4fQkMHdqQfK',
                'remember_token' => NULL,
                'created_at' => '2022-03-23 10:23:49',
                'updated_at' => '2024-10-29 17:06:20',
                'bank_name' => NULL,
                'branch' => NULL,
                'holder_name' => NULL,
                'account_no' => NULL,
                'image' => NULL,
                'status' => 1,
                'firebase_token' => NULL,
                'auth_token' => NULL,
            ),
            33 => 
            array (
                'id' => 34,
                'f_name' => 'John',
                'l_name' => 'Doe G',
                'phone' => '020000000015',
                'email' => 'grocery.store15@demo.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$lIw0en59SyLIWD2RBpH09eKhHsgyak6O41Q/YEccMMQFcAK07Pzti',
                'remember_token' => NULL,
                'created_at' => '2022-03-23 10:26:58',
                'updated_at' => '2022-03-23 10:26:58',
                'bank_name' => NULL,
                'branch' => NULL,
                'holder_name' => NULL,
                'account_no' => NULL,
                'image' => NULL,
                'status' => 1,
                'firebase_token' => NULL,
                'auth_token' => NULL,
            ),
            34 => 
            array (
                'id' => 35,
                'f_name' => 'Jon',
                'l_name' => 'Doe E',
                'phone' => '01000000020',
                'email' => 'ecommerce.store20@demo.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$xS8BHcp4xq44dVnoQdUEV.gT3MPBr63JSsAVBmtWMLCenSa1UFKhy',
                'remember_token' => NULL,
                'created_at' => '2022-03-23 10:56:04',
                'updated_at' => '2022-03-23 10:56:04',
                'bank_name' => NULL,
                'branch' => NULL,
                'holder_name' => NULL,
                'account_no' => NULL,
                'image' => NULL,
                'status' => 1,
                'firebase_token' => NULL,
                'auth_token' => NULL,
            ),
            35 => 
            array (
                'id' => 36,
                'f_name' => 'Jon',
                'l_name' => 'Doe E',
                'phone' => '010000000021',
                'email' => 'ecommerce.store21@demo.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$64JP6pjmrAZ5kZOjo7kHsOrNlcCoSFnElQLDfIJax0SiE7ARJIRgW',
                'remember_token' => NULL,
                'created_at' => '2022-03-23 10:59:16',
                'updated_at' => '2022-03-23 10:59:16',
                'bank_name' => NULL,
                'branch' => NULL,
                'holder_name' => NULL,
                'account_no' => NULL,
                'image' => NULL,
                'status' => 1,
                'firebase_token' => NULL,
                'auth_token' => NULL,
            ),
            36 => 
            array (
                'id' => 37,
                'f_name' => 'Jon',
                'l_name' => 'Doe E',
                'phone' => '010000000022',
                'email' => 'ecommerce.store22@demo.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$yA.C7KlKG0my/qsIySO76uu3gvlWHKuN/Gx6vTFLopoLqu6klnJWi',
                'remember_token' => NULL,
                'created_at' => '2022-03-23 11:06:47',
                'updated_at' => '2022-03-23 11:06:47',
                'bank_name' => NULL,
                'branch' => NULL,
                'holder_name' => NULL,
                'account_no' => NULL,
                'image' => NULL,
                'status' => 1,
                'firebase_token' => NULL,
                'auth_token' => NULL,
            ),
            37 => 
            array (
                'id' => 38,
                'f_name' => 'Jon',
                'l_name' => 'Doe E',
                'phone' => '010000000023',
                'email' => 'ecommerce.store23@demo.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$mpbwK9bq4P9rU02/xyE4ouAL3RJTB8q.LaC1KlHE5uV4am8tla2Je',
                'remember_token' => 'SAtziEEtWHSECkJ3IV35Br3UMTWajI14VoWX2SteU9nltTrhPrXnTodKrAPW',
                'created_at' => '2022-03-23 11:10:13',
                'updated_at' => '2024-04-20 15:24:42',
                'bank_name' => NULL,
                'branch' => NULL,
                'holder_name' => NULL,
                'account_no' => NULL,
                'image' => NULL,
                'status' => 1,
                'firebase_token' => NULL,
                'auth_token' => NULL,
            ),
            38 => 
            array (
                'id' => 39,
                'f_name' => 'Jon',
                'l_name' => 'Doe E',
                'phone' => '010000000024',
                'email' => 'ecommerce.store24@demo.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$KnUyMJ8XOOlt.yjgYGqVEexzk4mYD1pV5OR7tHscMEsSeRBkZ/O3O',
                'remember_token' => 'BPomaMDCKdWAcF2QFDIe3TGqxI5ql2SataMrJceEipGyEWRrnVcpyyTRCees',
                'created_at' => '2022-03-23 11:12:27',
                'updated_at' => '2024-04-20 15:22:31',
                'bank_name' => NULL,
                'branch' => NULL,
                'holder_name' => NULL,
                'account_no' => NULL,
                'image' => NULL,
                'status' => 1,
                'firebase_token' => NULL,
                'auth_token' => NULL,
            ),
            39 => 
            array (
                'id' => 40,
                'f_name' => 'Jon',
                'l_name' => 'Doe P',
                'phone' => '010000000028',
                'email' => 'pharmacy.store28@demo.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$qdmTP/1xam37fhPSR2OrG.Ns41srhRYiCiVwQWwHR7uBFrq0RSSnC',
                'remember_token' => NULL,
                'created_at' => '2022-03-23 11:28:55',
                'updated_at' => '2022-03-23 11:28:55',
                'bank_name' => NULL,
                'branch' => NULL,
                'holder_name' => NULL,
                'account_no' => NULL,
                'image' => NULL,
                'status' => 1,
                'firebase_token' => NULL,
                'auth_token' => NULL,
            ),
            40 => 
            array (
                'id' => 41,
                'f_name' => 'Jon',
                'l_name' => 'Doe P',
                'phone' => '010000000030',
                'email' => 'pharmacy.store30@demo.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$bubvXxw7d83vUgM6fabr.eJyQn0CYd2caGv0wNpHAfaGnGW3IvN3.',
                'remember_token' => NULL,
                'created_at' => '2022-03-23 11:31:28',
                'updated_at' => '2022-03-23 11:31:28',
                'bank_name' => NULL,
                'branch' => NULL,
                'holder_name' => NULL,
                'account_no' => NULL,
                'image' => NULL,
                'status' => 1,
                'firebase_token' => NULL,
                'auth_token' => NULL,
            ),
            41 => 
            array (
                'id' => 42,
                'f_name' => 'Jon',
                'l_name' => 'Doe P',
                'phone' => '01000000031',
                'email' => 'pharmacy.store31@demo.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$Fe7KP574VDxLBmokktZ37.rGO/2n/bPJ2jHgxGvNfKQmVdzZLzSOW',
                'remember_token' => NULL,
                'created_at' => '2022-03-23 11:34:07',
                'updated_at' => '2022-03-23 11:34:07',
                'bank_name' => NULL,
                'branch' => NULL,
                'holder_name' => NULL,
                'account_no' => NULL,
                'image' => NULL,
                'status' => 1,
                'firebase_token' => NULL,
                'auth_token' => NULL,
            ),
            42 => 
            array (
                'id' => 43,
                'f_name' => 'Jon',
                'l_name' => 'Doe P',
                'phone' => '010000000032',
                'email' => 'pharmacy.store32@demo.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$36FMcIdmj.zIVHSVIm.gEOBA.zlTgOFvAQuwfa8DYpER8W0V.b8Qq',
                'remember_token' => NULL,
                'created_at' => '2022-03-23 11:36:28',
                'updated_at' => '2022-03-23 11:36:28',
                'bank_name' => NULL,
                'branch' => NULL,
                'holder_name' => NULL,
                'account_no' => NULL,
                'image' => NULL,
                'status' => 1,
                'firebase_token' => NULL,
                'auth_token' => NULL,
            ),
            43 => 
            array (
                'id' => 44,
                'f_name' => 'Jon',
                'l_name' => 'Doe P',
                'phone' => '01000000033',
                'email' => 'pharmacy.store33@demo.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$Z5pFIeQ32TfQZ8lqFNReleeFLxbp798GZvNgqdgBPnfhn45/Oy5Bq',
                'remember_token' => NULL,
                'created_at' => '2022-03-23 11:38:27',
                'updated_at' => '2022-03-23 21:59:24',
                'bank_name' => NULL,
                'branch' => NULL,
                'holder_name' => NULL,
                'account_no' => NULL,
                'image' => NULL,
                'status' => 1,
                'firebase_token' => '@',
                'auth_token' => 'uaJSCRT2uT5IKrNvOXDuNqjDudH7cFSe3ZrAmms0LRJnWzRrdQDjcwiNIwVUjKw1tvQJ29KmK6dyEq9bmdi5jKf4APosiY6koASVpnP3sgcRjzIYYvbRnuCJ',
            ),
            44 => 
            array (
                'id' => 45,
                'f_name' => 'Joshef',
                'l_name' => 'Doe',
                'phone' => '+910111111111',
                'email' => 'joshef.doe1025822@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$gbYs0SKC5rxaKUUa.izXbeOwVomWs3U3KFrfzq5vqC7Cl/mC4AKvW',
                'remember_token' => NULL,
                'created_at' => '2021-08-20 21:05:49',
                'updated_at' => '2024-06-06 12:48:15',
                'bank_name' => NULL,
                'branch' => NULL,
                'holder_name' => NULL,
                'account_no' => NULL,
                'image' => NULL,
                'status' => 1,
                'firebase_token' => NULL,
                'auth_token' => NULL,
            ),
            45 => 
            array (
                'id' => 46,
                'f_name' => 'Pichart',
                'l_name' => 'Anthony',
                'phone' => '+8801710000000',
                'email' => 'test.restaurant@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$GkV8QOoxu8hMGlRUiHqpP.DuT2M226k5g/99pT4.STuhGf5pNHPGG',
                'remember_token' => 's1kVLTX6nYesGycDbBE4FvzJDPlNbaOcJgdzuAvvZrLj3NdU9hmtWyzf7ysS',
                'created_at' => '2021-08-20 21:11:45',
                'updated_at' => '2025-09-17 12:17:48',
                'bank_name' => NULL,
                'branch' => NULL,
                'holder_name' => NULL,
                'account_no' => NULL,
                'image' => '2021-08-22-61214e5a0db7d.png',
                'status' => 1,
                'firebase_token' => 'fXZlKPXrTzOUFAO4IMg3wS:APA91bGGlqmmY3d9tOrJGw0UsOKZkwKK5OqJfu8IY0iV1iUbxL6o-sBXyWVpMBOnJmnjb_d34-DEx50PgHMArxgm27Q0GY3a3TQgQ6dcooG3wLNum-_nmtk',
                'auth_token' => 'iA5dOTfItdyd37XEC5YjPQYunlTs54d26CcUgvptConWPUjtnWrvnzEz9Z8t9KDM9E5JL2dY88INHRq2P7ipOAdD6RmY2XyN2D0lP8lsQgDbNWKiACK2g2FR',
            ),
            46 => 
            array (
                'id' => 47,
                'f_name' => 'Robert',
                'l_name' => 'roy',
                'phone' => '0166666666',
                'email' => 'robert@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$JwU.Z0eXrpIR6vjkJUKy3.lJ4Wj8a3hctJ0.4m9EcNyGDPjJMk4vC',
                'remember_token' => NULL,
                'created_at' => '2021-08-20 21:18:09',
                'updated_at' => '2022-09-29 11:07:58',
                'bank_name' => NULL,
                'branch' => NULL,
                'holder_name' => NULL,
                'account_no' => NULL,
                'image' => NULL,
                'status' => 1,
                'firebase_token' => NULL,
                'auth_token' => NULL,
            ),
            47 => 
            array (
                'id' => 48,
                'f_name' => 'Jakatta',
                'l_name' => 'Potin',
                'phone' => '+88525695888',
                'email' => 'test.restaurant1@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$KhQKyf4AOnEqHE3tWB51x.nOj.orejD2QpBrpnkn9QLOyt3jd.sam',
                'remember_token' => NULL,
                'created_at' => '2021-08-20 21:26:42',
                'updated_at' => '2021-10-17 15:57:14',
                'bank_name' => NULL,
                'branch' => NULL,
                'holder_name' => NULL,
                'account_no' => NULL,
                'image' => NULL,
                'status' => 1,
                'firebase_token' => 'e_w7Vuv9SmyyTfGHYwhMYP:APA91bEOc251yRiaSc116fUQHuVatD01wPqf0AvD4tFlVew2UN7Fq6U83Y999-brut0P5SBrRR3Ott1fwYymzXnp1dChdM5GueJKyiMga6Xp9syZBWmGTjzHBC_l_ks1FoPX6u_CMlfP',
                'auth_token' => 'lNsm7hDeqo120RwSGXy6SRxcGxXvpvd2cPRL60BmCdx6vshsbZ9DQ59Z2ykK4iP9x7SfPxblheGVWBlUMY4YeYo2zYpwarDQD3cMdmTCbmHYdzoCb1cPBgV4',
            ),
            48 => 
            array (
                'id' => 49,
                'f_name' => 'Rimison',
                'l_name' => 'Doe',
                'phone' => '+6024588888',
                'email' => 'test.restaurant2@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$oGyCkIDOYbC22hTgkkiA6OrLIQ3GGlu40nyQKxmLGvsOysvuKWjsy',
                'remember_token' => 'OkwNIp9a6Tm1nTDIi2QfLCDsHS7hRQeWgX6dYVEVhpEHE70ofrZjmTjhmDr9',
                'created_at' => '2021-08-20 21:28:59',
                'updated_at' => '2021-08-20 21:28:59',
                'bank_name' => NULL,
                'branch' => NULL,
                'holder_name' => NULL,
                'account_no' => NULL,
                'image' => NULL,
                'status' => 1,
                'firebase_token' => NULL,
                'auth_token' => NULL,
            ),
            49 => 
            array (
                'id' => 50,
                'f_name' => 'Yello',
                'l_name' => 'Thid',
                'phone' => '+8565222222',
                'email' => 'test.restaurant3@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$4n1iOICzuctagsDSrofS/usNmeITSmrJ5iEmLpKU7GfoxOkFDjwA6',
                'remember_token' => NULL,
                'created_at' => '2021-08-20 21:31:51',
                'updated_at' => '2021-08-20 21:31:51',
                'bank_name' => NULL,
                'branch' => NULL,
                'holder_name' => NULL,
                'account_no' => NULL,
                'image' => NULL,
                'status' => 1,
                'firebase_token' => NULL,
                'auth_token' => NULL,
            ),
            50 => 
            array (
                'id' => 51,
                'f_name' => 'Mirra',
                'l_name' => 'Roy',
                'phone' => '+12562458744',
                'email' => 'test.restaurant4@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$rOzu5Is.Xxs.Xr32RLyHuuqnVZ4scL3xRWP8S.enWB19duo.8Ed9S',
                'remember_token' => NULL,
                'created_at' => '2021-08-21 01:55:13',
                'updated_at' => '2021-10-17 16:02:08',
                'bank_name' => NULL,
                'branch' => NULL,
                'holder_name' => NULL,
                'account_no' => NULL,
                'image' => NULL,
                'status' => 1,
                'firebase_token' => 'e_w7Vuv9SmyyTfGHYwhMYP:APA91bEOc251yRiaSc116fUQHuVatD01wPqf0AvD4tFlVew2UN7Fq6U83Y999-brut0P5SBrRR3Ott1fwYymzXnp1dChdM5GueJKyiMga6Xp9syZBWmGTjzHBC_l_ks1FoPX6u_CMlfP',
                'auth_token' => '0LFDyXK2Gio6H0Oo9JEB55PhAv5IOp3THXF3Txzd1dP0OGdG15yJ6Cc0yBPj0t4EmiRi1agOSigdCCsSdE9uScsCGa5avNZd0MoRRd9A6MC21lmBno2O66kY',
            ),
            51 => 
            array (
                'id' => 52,
                'f_name' => 'Kutman',
                'l_name' => 'Beneti',
                'phone' => '+12584555555',
                'email' => 'test.restaurant5@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$pCGDs0eVCqjR4mRliFnZSOdIsMigqzOoJbXANQAQUYLk8GuKecG5y',
                'remember_token' => NULL,
                'created_at' => '2021-08-21 01:59:41',
                'updated_at' => '2021-08-21 01:59:41',
                'bank_name' => NULL,
                'branch' => NULL,
                'holder_name' => NULL,
                'account_no' => NULL,
                'image' => NULL,
                'status' => 1,
                'firebase_token' => NULL,
                'auth_token' => NULL,
            ),
            52 => 
            array (
                'id' => 53,
                'f_name' => 'Staven',
                'l_name' => 'Sultan',
                'phone' => '880100000000',
                'email' => 'test.restaurant6@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$tSDv3gvQEthGwH3ZaM2vau0vhWxV3.pZDtDPq06sKiP26Qi1UsNay',
                'remember_token' => NULL,
                'created_at' => '2021-08-21 02:03:27',
                'updated_at' => '2022-09-29 11:08:54',
                'bank_name' => NULL,
                'branch' => NULL,
                'holder_name' => NULL,
                'account_no' => NULL,
                'image' => NULL,
                'status' => 1,
                'firebase_token' => NULL,
                'auth_token' => NULL,
            ),
            53 => 
            array (
                'id' => 54,
                'f_name' => 'Sumitro',
                'l_name' => 'Das',
                'phone' => '+91025888888',
                'email' => 'test.restaurant7@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$bBaATHdS6quLOqItaqSvCek/N/oaMOZd3PW2eaLhI7qb5tLg0Djuq',
                'remember_token' => NULL,
                'created_at' => '2021-08-21 02:07:50',
                'updated_at' => '2022-01-20 18:07:10',
                'bank_name' => NULL,
                'branch' => NULL,
                'holder_name' => NULL,
                'account_no' => NULL,
                'image' => NULL,
                'status' => 1,
                'firebase_token' => NULL,
                'auth_token' => 'ViAVg0CTdVZcm6sLjVhQZrVk1VDI1i4gpXTYuoIo10jM0ddGeDox0xxLC4KnHbe1PFYwhayqpXZdRWJFXbszjkBe9DK3oZJGkNBhwgr3mpOBOWzip2YPiCZ8',
            ),
            54 => 
            array (
                'id' => 55,
                'f_name' => 'Pinku',
                'l_name' => 'Islam',
                'phone' => '+91025558884',
                'email' => 'test.restaurant8@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$hTb7ShXmMUXPrqSoD3iPbeWKkZOmrK1uI/jVW3Ta8I8jz9ToBkix.',
                'remember_token' => NULL,
                'created_at' => '2021-08-21 02:11:30',
                'updated_at' => '2021-10-17 00:39:08',
                'bank_name' => NULL,
                'branch' => NULL,
                'holder_name' => NULL,
                'account_no' => NULL,
                'image' => NULL,
                'status' => 1,
                'firebase_token' => 'dwwfnoM1ShqmZ23-yH9QN1:APA91bFRhIavLsVybuZnnTmtUMEOUx_z3QAMY78PR8dRmbVfMAS1jTQPHcEPh6NzoQjtEDntM_kF8GJLhC--afQ_UDtEBwkEUKXtaO5rxrevSJVzjIuFBGLptqyUN8SxUbP6_hP4H_ve',
                'auth_token' => 'stdm9vbdhsjdFYB7RqzK3iTkPJyJckROE2cz77dYNeZHd0YmKxAC1fsTc7Tkmtgs1gzvX5s5l8Vb5Yvbx33oKINbCQ5ldDEMIu5Y0c9MtLR7aUigdbOUO3Ht',
            ),
            55 => 
            array (
                'id' => 56,
                'f_name' => 'Punchuk',
                'l_name' => 'Yangru',
                'phone' => '+02541255888',
                'email' => 'test.restaurant10@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$5D88uGCkHKd3ipRQ2A5Kgu.yGW.LVVbkDQXp7orL8UhVbPdCFNOiK',
                'remember_token' => NULL,
                'created_at' => '2021-08-21 02:18:16',
                'updated_at' => '2021-08-21 02:18:16',
                'bank_name' => NULL,
                'branch' => NULL,
                'holder_name' => NULL,
                'account_no' => NULL,
                'image' => NULL,
                'status' => 1,
                'firebase_token' => NULL,
                'auth_token' => NULL,
            ),
            56 => 
            array (
                'id' => 57,
                'f_name' => 'Jhon',
                'l_name' => 'Chung',
                'phone' => '+212588888',
                'email' => 'test.restaurant13@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$rtWnuBXVSFrIumJB7eTnoe1CN7z8mVsdKqECMu0.Zdd69UT3ifH9u',
                'remember_token' => NULL,
                'created_at' => '2021-08-21 02:26:33',
                'updated_at' => '2025-10-01 00:24:52',
                'bank_name' => NULL,
                'branch' => NULL,
                'holder_name' => NULL,
                'account_no' => NULL,
                'image' => NULL,
                'status' => 1,
                'firebase_token' => 'ddOwSmTrQR-7Ts1zz5WdAB:APA91bH8PBReHfnfn8zBAG2ZV4fI7oASl3jgMHtZv00f8k1-nbRbfKV4rdOakyNIhL7cWd4XgM0dhEn7PH2_K7nARLZtsv0mfOYfSWZkbuM7kDVXv_NDhF4',
                'auth_token' => 'ZaAM6v1QjLGCAmycHg4IK1wsVkToRFiFwoHjqVqqB4xN5xXqJtzdToC1Nt1CcdN2Xxq6PHBCDORsgCIdKyfdTra1tqlrOineLcfYO8FN8aF0s7XYxdGH5ZfT',
            ),
            57 => 
            array (
                'id' => 58,
                'f_name' => 'Jibona',
                'l_name' => 'Posta',
                'phone' => '+91021100000',
                'email' => 'test.restaurant12@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$zXmODRQSE0ReLz14bklmb.7twdttzxQD1ibYoN8ST2nl68SX4dcGy',
                'remember_token' => NULL,
                'created_at' => '2021-08-21 02:29:16',
                'updated_at' => '2024-11-03 14:19:57',
                'bank_name' => NULL,
                'branch' => NULL,
                'holder_name' => NULL,
                'account_no' => NULL,
                'image' => NULL,
                'status' => 1,
                'firebase_token' => 'eqqG_NSBQJGfwwZ8s2Z5gk:APA91bFG8XLdQ0IE69UaFOztNl54OEWiinqI9Zu-AixOY8pW280UaWrhX6CvyC-203YUG4qg24FO6azyO3EzeWCel4SnrceYEXLJF6JjroblcR6lA67dz5lYJKcjf8cu27BC4evKjkFG',
                'auth_token' => '4Ja8QuWPYnO2BQmeibVNromnjtmdcocWYrfNA2O1JtuwLKIXP7CWhS8w3J1y2tBG2hZt3xwDx32yTFHIfcKFXQ0DcFeHsozeewmKg2OEwzk73lMogZ1LbVzC',
            ),
            58 => 
            array (
                'id' => 59,
                'f_name' => 'Marjhan',
                'l_name' => 'Sultana',
                'phone' => '01712251697',
                'email' => 'marjahan@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$OgY.DTVcv.0I88gQJVuq9u9ah1/Vl3YPijN1RwdZBHmj0TdZ74gj2',
                'remember_token' => NULL,
                'created_at' => '2021-10-17 00:29:09',
                'updated_at' => '2022-01-20 18:06:22',
                'bank_name' => NULL,
                'branch' => NULL,
                'holder_name' => NULL,
                'account_no' => NULL,
                'image' => NULL,
                'status' => 1,
                'firebase_token' => '@',
                'auth_token' => 'mBL9F2QOzPsU26D5nvRDpxSG29ym4k2hTemCm4flrpYxDfJb0WAwziqAtzSy64txaoAx8o051Dz4Ivw5cfJHC0lPcwMQKARsD56uke7rAPVOHEzij6paX5ii',
            ),
            59 => 
            array (
                'id' => 60,
                'f_name' => 'Akeem',
                'l_name' => 'Boyle',
                'phone' => '+1 959-252-4064',
                'email' => 'provider1@demo.com',
                'email_verified_at' => NULL,
                'password' => '$2a$12$NQBXTu9.U.jS0McEJPVEZuVcC2eAorHB8vQXCPlbcXuJM/mb9RpfO',
                'remember_token' => NULL,
                'created_at' => '2025-02-05 16:19:19',
                'updated_at' => '2025-02-05 16:19:19',
                'bank_name' => NULL,
                'branch' => NULL,
                'holder_name' => NULL,
                'account_no' => NULL,
                'image' => NULL,
                'status' => 1,
                'firebase_token' => NULL,
                'auth_token' => NULL,
            ),
            60 => 
            array (
                'id' => 61,
                'f_name' => 'Jhon',
                'l_name' => 'Ali',
                'phone' => '+8801655443322',
                'email' => 'provider2@demo.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$8HDVzeHywwUsKseBbsvGW.XyAngbK3YRwV4C09fwJkk3tNCeRDS4O',
                'remember_token' => NULL,
                'created_at' => '2025-02-05 16:24:29',
                'updated_at' => '2025-02-05 16:24:29',
                'bank_name' => NULL,
                'branch' => NULL,
                'holder_name' => NULL,
                'account_no' => NULL,
                'image' => NULL,
                'status' => 1,
                'firebase_token' => NULL,
                'auth_token' => NULL,
            ),
            61 => 
            array (
                'id' => 62,
                'f_name' => 'Martina',
                'l_name' => 'Blake',
                'phone' => '+8801899000000',
                'email' => 'provider3@demo.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$gJ9wX4c7vLTIcrEJFFAo9eGVYeIuM51W6vPZIFp.B7l/hk99iV0ka',
                'remember_token' => NULL,
                'created_at' => '2025-02-05 16:35:15',
                'updated_at' => '2025-02-05 16:35:15',
                'bank_name' => NULL,
                'branch' => NULL,
                'holder_name' => NULL,
                'account_no' => NULL,
                'image' => NULL,
                'status' => 1,
                'firebase_token' => NULL,
                'auth_token' => NULL,
            ),
            62 => 
            array (
                'id' => 63,
                'f_name' => 'Happy',
                'l_name' => 'Potato',
                'phone' => '+8801990000222',
                'email' => 'provider4@demo.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$GmWtSUrGa4cyTOWmVLYnj.6Cahgb2KmV6n5pSnkEm/y1fy3Yh8WOi',
                'remember_token' => NULL,
                'created_at' => '2025-02-05 16:40:52',
                'updated_at' => '2025-02-05 16:40:52',
                'bank_name' => NULL,
                'branch' => NULL,
                'holder_name' => NULL,
                'account_no' => NULL,
                'image' => NULL,
                'status' => 1,
                'firebase_token' => NULL,
                'auth_token' => NULL,
            ),
            63 => 
            array (
                'id' => 64,
                'f_name' => 'Jhon',
                'l_name' => 'Jack',
                'phone' => '+8801621720011',
                'email' => 'provider5.@demo.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$fO2OvxDaCDjStSIiY1t/A.M48t3gEf7tiSeTUT1VvZFXzoB.GNpsW',
                'remember_token' => 'iavWGkUYxhUawvfqKP8TXVRSNjDZgXo8l4eugOv9OXw7AcNsuiy4xEkqVSUu',
                'created_at' => '2025-02-05 17:10:08',
                'updated_at' => '2025-02-08 11:25:52',
                'bank_name' => NULL,
                'branch' => NULL,
                'holder_name' => NULL,
                'account_no' => NULL,
                'image' => NULL,
                'status' => 1,
                'firebase_token' => 'fw8M55CKTrWrUjudsEMWoX:APA91bEB0nxESHkmGO7pmIanZ1UhMfa7WuxtF6AAEmFaWLPPy5ASexKEDjJz7dh7nlQSKxnu-ErLoeLWIAJXtWCakMpYK8N94R5HHn_J8nGhty0y01VnpVQ',
                'auth_token' => 'HoTM4pagJFo4mUqToTAS223V46TQZmdj0XQ2jFTxFBqE8BwOxCLUBNTkzWq741tZbByxHr5XFMyTj0UAYFLyelaVMqE0DbRyg8ogYB3XjYZQAj9vr7pAgmIN',
            ),
            64 => 
            array (
                'id' => 65,
                'f_name' => 'Will',
                'l_name' => 'Smith',
                'phone' => '+8801621720012',
                'email' => 'provider6@demo.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$7/8ehTd5vviw7FLahCYZ8.m5Mprsa98YHM/S/G0S7Aod0UNuyRrD2',
                'remember_token' => NULL,
                'created_at' => '2025-02-05 17:22:34',
                'updated_at' => '2025-02-08 11:26:41',
                'bank_name' => NULL,
                'branch' => NULL,
                'holder_name' => NULL,
                'account_no' => NULL,
                'image' => NULL,
                'status' => 1,
                'firebase_token' => NULL,
                'auth_token' => NULL,
            ),
            65 => 
            array (
                'id' => 66,
                'f_name' => 'Jonson',
                'l_name' => 'blue',
                'phone' => '+8801621720023',
                'email' => 'provider7@demo.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$7/HiQcCmivd868GPAh1YCuo83/pkAhoUU7jbRRRHyqjmgNQHySEzC',
                'remember_token' => NULL,
                'created_at' => '2025-02-05 17:27:33',
                'updated_at' => '2025-02-08 11:46:13',
                'bank_name' => NULL,
                'branch' => NULL,
                'holder_name' => NULL,
                'account_no' => NULL,
                'image' => NULL,
                'status' => 1,
                'firebase_token' => 'dNNVWpS0SbmEw1xo3YD5eW:APA91bFhs5RRgCUf4gJz3uyQ2dgptk081eNtAbfK8UYsQjoySHL_CbUvkbIhtVadbzOTBswV73Er-En557affvj6oWYnNdIplz5eCpaoeyCA1WL60pFbzPY',
                'auth_token' => 'ctNPWi9Z893KbMkqvoI2dVnDmqoCKXwuDl7Wh8wQPkxNKQbe4MyLeTfoo9z79pMu7Idh76tW4NV7P0X2QYZ7qKa7zURKtllVWBqEP6Nx2fNFg259pocoF46w',
            ),
            66 => 
            array (
                'id' => 67,
                'f_name' => 'Ittu',
                'l_name' => 'Seleisa',
                'phone' => '+8801621720034',
                'email' => 'provider8@demo.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$kYAT4j3MGVu3Q6ZQNLuwf.s2w5mxUkZ5VKZnrtZbSs1vgZCEFESU6',
                'remember_token' => NULL,
                'created_at' => '2025-02-05 17:30:10',
                'updated_at' => '2025-02-08 11:29:17',
                'bank_name' => NULL,
                'branch' => NULL,
                'holder_name' => NULL,
                'account_no' => NULL,
                'image' => NULL,
                'status' => 1,
                'firebase_token' => NULL,
                'auth_token' => NULL,
            ),
            67 => 
            array (
                'id' => 68,
                'f_name' => 'Jhon',
                'l_name' => 'Pro',
                'phone' => '+8801700001458',
                'email' => 'provider99@provider.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$dUX8trSZqkWN4V6U/vqqceMVUs/yOVFZS65fCfl.l..xeJZkyNJKu',
                'remember_token' => NULL,
                'created_at' => '2025-09-16 12:45:58',
                'updated_at' => '2025-09-16 12:45:58',
                'bank_name' => NULL,
                'branch' => NULL,
                'holder_name' => NULL,
                'account_no' => NULL,
                'image' => NULL,
                'status' => NULL,
                'firebase_token' => NULL,
                'auth_token' => NULL,
            ),
            68 => 
            array (
                'id' => 69,
                'f_name' => 'Hchc',
                'l_name' => 'Ycuc',
                'phone' => '+11769911110',
                'email' => 'providergg@provider.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$rkDI8Xc0VymHlQY6DQsg8uYdQxz8ypq5KOG9ONNPn/6cxLvqetTnC',
                'remember_token' => NULL,
                'created_at' => '2025-09-16 13:00:49',
                'updated_at' => '2025-09-16 13:00:49',
                'bank_name' => NULL,
                'branch' => NULL,
                'holder_name' => NULL,
                'account_no' => NULL,
                'image' => NULL,
                'status' => NULL,
                'firebase_token' => NULL,
                'auth_token' => NULL,
            ),
            69 => 
            array (
                'id' => 70,
                'f_name' => 'Tester',
                'l_name' => 'Doe',
                'phone' => '+8801700004569',
                'email' => 'provider111@provider.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$ZC9fOEWuh2Bpg4M33.DPB.Ksq/1KwCZ1fTbVnOJ5WHiQ9eVi4zMJW',
                'remember_token' => NULL,
                'created_at' => '2025-09-16 13:00:58',
                'updated_at' => '2025-09-16 13:00:58',
                'bank_name' => NULL,
                'branch' => NULL,
                'holder_name' => NULL,
                'account_no' => NULL,
                'image' => NULL,
                'status' => NULL,
                'firebase_token' => NULL,
                'auth_token' => NULL,
            ),
            70 => 
            array (
                'id' => 71,
                'f_name' => 'Reagan',
                'l_name' => 'Bates',
                'phone' => '+11753776656',
                'email' => 'kusa@mailinator.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$zBrlm10INdkB7alEmys98u6gHD3lcbm0cNlwoktlgmBwRWcML5QbO',
                'remember_token' => NULL,
                'created_at' => '2025-09-25 14:45:46',
                'updated_at' => '2025-09-25 14:45:46',
                'bank_name' => NULL,
                'branch' => NULL,
                'holder_name' => NULL,
                'account_no' => NULL,
                'image' => NULL,
                'status' => NULL,
                'firebase_token' => NULL,
                'auth_token' => NULL,
            ),
        ));
        
        
    }
}